# Generated by Django 5.2.16 on 2026-08-15 13:40

import apps.core.cuid
import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.CharField(max_length=191, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("dead", "Dead letter"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=8)),
                ("next_attempt_at", models.DateTimeField(db_index=True)),
                ("locked_by", models.CharField(blank=True, default="", max_length=128)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("succeeded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "outbox_event",
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"], name="idx_outbox_due"
                    )
                ],
            },
        ),
    ]
