# Generated by Django 5.2.4 on 2026-07-12 22:05

import apps.core.cuid
import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_development', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDRoleAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=32)),
                ('fy', models.CharField(max_length=16)),
                ('country', models.CharField(default='Uganda', max_length=64)),
                ('currency', models.CharField(default='UGX', max_length=8)),
                ('annual_allocation_cents', models.BigIntegerField(default=0)),
                ('set_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'pd_role_allocation',
                'indexes': [models.Index(fields=['fy', 'country'], name='pd_role_all_fy_8f050f_idx')],
                'constraints': [models.UniqueConstraint(fields=('role', 'fy', 'country'), name='uniq_pd_role_allocation_role_fy_country')],
            },
        ),
    ]
