# Generated by Django 5.2.16 on 2026-07-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professional_development", "0002_pdroleallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionaldevelopmentcertificate",
            name="document_type",
            field=models.CharField(
                choices=[("certificate", "Certificate"), ("transcript", "Transcript")],
                default="certificate",
                max_length=16,
            ),
        ),
    ]
