# Generated by Django 5.2.17 on 2026-08-23 08:27

from django.db import migrations, models

# PD budgets are USD-denominated. The module launched with the platform-wide
# UGX default, so every row written before this migration is labelled UGX
# regardless of what the figure meant. The relabel below is safe because it
# was verified against the data before writing it: every existing PD row
# carries amount 0 (and production holds no operational PD data), so no real
# UGX figure can be mislabelled by it.

MODELS = (
    "pdroleallocation",
    "professionaldevelopmentallocation",
    "professionaldevelopmentfundrequest",
    "professionaldevelopmentrequest",
)


def relabel_ugx_to_usd(apps, schema_editor):
    for name in MODELS:
        model = apps.get_model("professional_development", name)
        model.objects.filter(currency="UGX").update(currency="USD")


def relabel_usd_to_ugx(apps, schema_editor):
    for name in MODELS:
        model = apps.get_model("professional_development", name)
        model.objects.filter(currency="USD").update(currency="UGX")


class Migration(migrations.Migration):

    dependencies = [
        ('professional_development', '0003_professionaldevelopmentcertificate_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdroleallocation',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AlterField(
            model_name='professionaldevelopmentallocation',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AlterField(
            model_name='professionaldevelopmentfundrequest',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AlterField(
            model_name='professionaldevelopmentrequest',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.RunPython(relabel_ugx_to_usd, relabel_usd_to_ugx),
    ]
