# Generated by Django 5.2.17 on 2026-09-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flags", "0002_leadershipescalation"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadershipescalation",
            name="addressed_role",
            field=models.CharField(
                choices=[
                    ("PL", "Programme Lead"),
                    ("CD", "Country Director"),
                    ("RVP", "Regional Vice President"),
                ],
                default="RVP",
                max_length=8,
            ),
        ),
        migrations.AddIndex(
            model_name="leadershipescalation",
            index=models.Index(
                fields=["addressed_role", "status"],
                name="leadership__address_4da202_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leadershipescalation",
            index=models.Index(
                fields=["assigned_to_user_id", "status"],
                name="leadership__assigne_ca38bb_idx",
            ),
        ),
    ]
