# Generated by Django 5.2.4 on 2026-06-26 22:25

import apps.core.cuid
import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TargetSetting",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fy", models.CharField(max_length=16)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("SCHOOL_REACH", "School Reach"),
                            ("STAFF_DIRECT_SUPPORT", "Staff Direct Support"),
                            ("PARTNER_SUPPORT", "Partner Support"),
                            ("TRAINING", "Training"),
                            ("SSA", "SSA"),
                            ("SCHOOL_VISIT", "School Visit"),
                            ("MSCS", "MSCS"),
                            ("EXAM_RESULTS", "Exam Results"),
                            ("CORE_PACKAGE", "Core Package"),
                            ("PROJECT_SUPPORT", "Project Support"),
                            ("IA_VERIFICATION", "IA Verification"),
                            ("ACCOUNTABILITY", "Accountability"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("country", "Country"),
                            ("region", "Region"),
                            ("district", "District"),
                            ("cluster", "Cluster"),
                            ("staff", "Staff"),
                            ("pl_team", "PL Team"),
                            ("partner", "Partner"),
                            ("project", "Project"),
                            ("school_type", "School Type"),
                        ],
                        max_length=16,
                    ),
                ),
                ("scope_id", models.CharField(blank=True, max_length=30, null=True)),
                ("target_value", models.FloatField(blank=True, null=True)),
                (
                    "target_unit",
                    models.CharField(
                        choices=[("count", "Count"), ("percentage", "Percentage")],
                        default="percentage",
                        max_length=16,
                    ),
                ),
                ("target_percentage", models.FloatField(blank=True, null=True)),
                ("quarter_distribution", models.JSONField(blank=True, null=True)),
                ("set_by_user_id", models.CharField(max_length=30)),
                ("set_by_role", models.CharField(max_length=64)),
                ("effective_from", models.DateTimeField(auto_now_add=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "target_setting",
                "indexes": [
                    models.Index(
                        fields=["fy", "target_type"], name="target_sett_fy_ed1565_idx"
                    ),
                    models.Index(
                        fields=["scope_type", "scope_id"],
                        name="target_sett_scope_t_dce157_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="target_sett_is_acti_8a4829_idx"
                    ),
                ],
            },
        ),
    ]
