# Generated by Django 5.2.4 on 2026-07-12 13:03

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_seed_target_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatchUpPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('pl_user_id', models.CharField(max_length=30)),
                ('staff_user_id', models.CharField(max_length=30)),
                ('fy', models.CharField(max_length=16)),
                ('month_of_fy', models.IntegerField()),
                ('activities_proposed', models.IntegerField(default=0)),
                ('school_ids', models.JSONField(blank=True, default=list)),
                ('planned_dates', models.JSONField(blank=True, default=list)),
                ('partner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('returned', 'Returned'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='submitted', max_length=16)),
                ('return_reason', models.CharField(blank=True, max_length=512, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=30, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_activity_ids', models.JSONField(blank=True, default=list)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catchup_plans', to='targets.targetarea')),
            ],
            options={
                'db_table': 'target_catchup_plan',
                'indexes': [models.Index(fields=['pl_user_id', 'status'], name='target_catc_pl_user_931332_idx'), models.Index(fields=['staff_user_id', 'fy', 'month_of_fy'], name='target_catc_staff_u_7a029a_idx')],
            },
        ),
    ]
