# Generated by Django 5.2.17 on 2026-09-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "targets",
            "0005_monthlypersonaltarget_monthly_personal_target_month_1_12_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mostsignificantchangestory",
            name="country",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="mostsignificantchangestory",
            name="intervention",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="mostsignificantchangestory",
            name="outcome_area",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
