# Generated by Django 5.2.17 on 2026-09-24 22:31
"""The dirty marks behind apps.targets.ledger_sync (F-D).

Until this release every leadership page rebuilt the whole roster's ledger,
so the ledger was only as fresh as the last such load. Every officer with a
ledger, and every active user for the operational year, starts marked: the
first leadership page after deploy rebuilds them all, exactly as before, and
later loads rebuild only what changed.
"""

from django.db import migrations, models
from django.utils import timezone


def mark_everyone(apps, schema_editor):
    from apps.core.fy import get_operational_fy

    Ledger = apps.get_model("targets", "TargetAchievementLedger")
    User = apps.get_model("accounts", "User")
    Dirty = apps.get_model("targets", "TargetLedgerDirty")
    pairs = set(Ledger.objects.values_list("user_id", "fy").distinct())
    fy = get_operational_fy()
    pairs |= {
        (uid, fy)
        for uid in User.objects.filter(
            status="active", deleted_at__isnull=True
        ).values_list("id", flat=True)
    }
    now = timezone.now()
    Dirty.objects.bulk_create(
        [Dirty(owner_id=u, fy=y, marked_at=now) for u, y in sorted(pairs)],
        batch_size=1000,
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("targets", "0006_mscs_outcome_tags"),
        ("accounts", "0031_staffprofile_google_drive_folder_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetLedgerDirty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_id", models.CharField(max_length=30)),
                ("fy", models.CharField(max_length=16)),
                ("marked_at", models.DateTimeField()),
            ],
            options={
                "db_table": "target_ledger_dirty",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_id", "fy"), name="uniq_target_ledger_dirty"
                    )
                ],
            },
        ),
        migrations.RunPython(mark_everyone, migrations.RunPython.noop),
    ]
