// Shared notification data — used by the header NotificationBell drawer.
//
// Schema upgrade (per the floating-drawer spec): notifications now carry
// category, priority, actionRequired, and optional context so the drawer
// can group/filter and the row UI can paint priority + category badges.
// Older callers that only read {title, body, href, unread, ago, Icon} are
// unaffected — those keys are preserved.

import {
  AlertTriangle,
  ClipboardCheck,
  ShieldCheck,
  Wallet,
  Trophy,
  CalendarRange,
  Mail,
  GraduationCap,
  Truck,
  Heart,
  CalendarClock,
  School,
  Network,
  Handshake,
  FileCheck2,
  Target,
  type LucideIcon,
} from "lucide-react";

export type NotificationCategory =
  | "Message"
  | "Approval"
  | "Evidence"
  | "Payment"
  | "Planning"
  | "Partner"
  | "Debrief"
  | "School"
  | "Cluster"
  | "SSA"
  | "Reschedule"
  | "HR"
  | "System";

export type NotificationPriority = "normal" | "important" | "urgent" | "critical";

export type Notification = {
  id: string;
  title: string;
  body: string;
  href: string;
  unread: boolean;
  ago: string;
  Icon: LucideIcon;
  iconBg: string;
  iconText: string;
  /** What kind of thing this notification is about. */
  category?: NotificationCategory;
  /** Visual prominence — drives the priority badge.  Default: normal. */
  priority?: NotificationPriority;
  /** True when the user has to ACT (review, approve, confirm, fix).
   *  False for FYI / informational items. */
  actionRequired?: boolean;
  /** Short label shown under the title for context — e.g.
   *  "Hope Primary · Attendance sheet". */
  contextLabel?: string;
  /** Label on the action button when actionRequired is true. */
  actionLabel?: string;
  /** When the underlying work is due — e.g. "Today", "Fri 13 Jun". */
  dueDate?: string;
  /** The one concrete next step the recipient should take. */
  recommendedAction?: string;
};

export const NOTIFICATIONS: Notification[] = [
  {
    id: "n-1",
    title: "12 plans awaiting your approval",
    body: "Submitted by 6 CCEOs across Kigun and Mbarara.",
    href: "/approvals",
    unread: true,
    ago: "12m",
    Icon: ClipboardCheck,
    iconBg: "bg-amber-100",
    iconText: "text-amber-700",
    category: "Approval",
    priority: "urgent",
    actionRequired: true,
    contextLabel: "Kigun · Mbarara",
    actionLabel: "Review Queue",
  },
  {
    id: "n-2",
    title: "3 staff members behind target",
    body: "Mid-year flag triggered — open the support-review checklist.",
    href: "/team-targets",
    unread: true,
    ago: "32m",
    Icon: AlertTriangle,
    iconBg: "bg-rose-100",
    iconText: "text-rose-700",
    category: "HR",
    priority: "important",
    actionRequired: true,
    contextLabel: "Mid-year review",
    actionLabel: "Open checklist",
  },
  {
    id: "n-3",
    title: "Daily Field Debrief is due",
    body: "You haven't submitted today's debrief yet.",
    href: "/debriefs/new",
    unread: true,
    ago: "1h",
    Icon: ShieldCheck,
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-700",
    category: "Debrief",
    priority: "important",
    actionRequired: true,
    actionLabel: "Submit Debrief",
  },
  {
    id: "n-4",
    title: "5 fund requests need disbursement",
    body: "Disbursement window closes Friday at 17:00.",
    href: "/disbursements",
    unread: false,
    ago: "3h",
    Icon: Wallet,
    iconBg: "bg-violet-100",
    iconText: "text-violet-700",
    category: "Payment",
    priority: "important",
    actionRequired: true,
    contextLabel: "Window closes Fri 17:00",
    actionLabel: "Open Queue",
  },
  {
    id: "n-5",
    title: "You moved to #2 on the verified leaderboard",
    body: "Sarah Okello overtook Daniel Mwangi this cycle.",
    href: "/team-targets",
    unread: false,
    ago: "Yesterday",
    Icon: Trophy,
    iconBg: "bg-yellow-100",
    iconText: "text-yellow-700",
    category: "System",
    priority: "normal",
    actionRequired: false,
  },
  {
    id: "n-6",
    title: "Public holiday on Friday",
    body: "Planning auto-blocked — your route runner skipped 2 stops.",
    href: "/leave",
    unread: false,
    ago: "2d",
    Icon: CalendarRange,
    iconBg: "bg-sky-100",
    iconText: "text-sky-700",
    category: "Planning",
    priority: "normal",
    actionRequired: false,
  },
  {
    id: "n-7",
    title: "Evidence correction needed",
    body: "Attendance sheet for the Jan 14 visit is missing signatures.",
    href: "/data-verification?filter=returned",
    unread: true,
    ago: "4h",
    Icon: AlertTriangle,
    iconBg: "bg-rose-100",
    iconText: "text-rose-700",
    category: "Evidence",
    priority: "urgent",
    actionRequired: true,
    contextLabel: "Hope Primary · Attendance",
    actionLabel: "Review evidence",
  },
  {
    id: "n-8",
    title: "New message from Mary",
    body: "Re: Sunrise Primary — let's reschedule the cluster meeting.",
    href: "/messages",
    unread: true,
    ago: "5h",
    Icon: Mail,
    iconBg: "bg-sky-100",
    iconText: "text-sky-700",
    category: "Message",
    priority: "normal",
    actionRequired: false,
    contextLabel: "Mary Akello · IA",
  },
  {
    id: "n-9",
    title: "Cluster meeting rescheduled to next Tuesday",
    body: "Kireka cluster moved from Thursday to Tuesday — 3 schools affected.",
    href: "/clusters",
    unread: false,
    ago: "Yesterday",
    Icon: Truck,
    iconBg: "bg-amber-100",
    iconText: "text-amber-700",
    category: "Reschedule",
    priority: "normal",
    actionRequired: false,
    contextLabel: "Kireka cluster",
  },
  {
    id: "n-10",
    title: "Training scheduled: Numeracy Foundations",
    body: "Cluster Faleha · May 5 · 14 participants. Materials ready.",
    href: "/trainings",
    unread: false,
    ago: "2d",
    Icon: GraduationCap,
    iconBg: "bg-violet-100",
    iconText: "text-violet-700",
    category: "Cluster",
    priority: "normal",
    actionRequired: false,
    contextLabel: "Faleha · May 5",
  },
  {
    id: "n-11",
    title: "Partner submitted SSA evidence",
    body: "Living Word School · Q1 SSA assessment uploaded for review.",
    href: "/ssa",
    unread: false,
    ago: "3d",
    Icon: Heart,
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-700",
    category: "SSA",
    priority: "normal",
    actionRequired: false,
    contextLabel: "Living Word School",
  },
];

// ─── CCEO notification catalogue (spec §20) ─────────────────────────
//
// The full set of events the CCEO bell + /notifications page surface.
// Every entry carries: WHY it fired (body = reason), WHEN it's due
// (dueDate), WHAT to do (recommendedAction + actionLabel) and exactly
// ONE action link (href). Wired into the canonical readNotificationsFor
// source (src/lib/actions/audit.ts) under the "CCEO" role token — this
// array is the copy catalogue, not a parallel store.

export const CCEO_NOTIFICATIONS: Notification[] = [
  {
    id: "cceo-1",
    title: "Visit due today: Hope Primary",
    body: "Coaching visit scheduled for today has not been started.",
    href: "/my-plan",
    unread: true,
    ago: "10m",
    Icon: CalendarClock,
    iconBg: "bg-sky-100",
    iconText: "text-sky-700",
    category: "Planning",
    priority: "important",
    actionRequired: true,
    contextLabel: "Hope Primary · Coaching visit",
    actionLabel: "Open My Plan",
    dueDate: "Today",
    recommendedAction: "Complete the visit and upload evidence today, or reschedule within the slip limit.",
  },
  {
    id: "cceo-2",
    title: "Activity overdue: Sunrise Primary training",
    body: "School Improvement Training was planned 4 days ago and is still not completed.",
    href: "/my-plan",
    unread: true,
    ago: "25m",
    Icon: AlertTriangle,
    iconBg: "bg-rose-100",
    iconText: "text-rose-700",
    category: "Planning",
    priority: "urgent",
    actionRequired: true,
    contextLabel: "Sunrise Primary · 4 days overdue",
    actionLabel: "Resolve overdue",
    dueDate: "4 days overdue",
    recommendedAction: "Complete, reschedule, or cancel the activity — overdue items block your weekly fund request.",
  },
  {
    id: "cceo-3",
    title: "Weekly fund request due",
    body: "Next week's planned activities need a submitted fund request before the cutoff.",
    href: "/fund-requests",
    unread: true,
    ago: "1h",
    Icon: Wallet,
    iconBg: "bg-violet-100",
    iconText: "text-violet-700",
    category: "Payment",
    priority: "important",
    actionRequired: true,
    contextLabel: "Cutoff Thu 17:00",
    actionLabel: "Submit request",
    dueDate: "Thu 17:00",
    recommendedAction: "Review the auto-generated request and submit it so funds clear before Monday.",
  },
  {
    id: "cceo-4",
    title: "Daily Field Debrief is due",
    body: "You haven't submitted today's debrief — your PL's evening rollup is waiting on it.",
    href: "/debriefs",
    unread: true,
    ago: "2h",
    Icon: ClipboardCheck,
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-700",
    category: "Debrief",
    priority: "important",
    actionRequired: true,
    actionLabel: "Submit debrief",
    dueDate: "Today 18:00",
    recommendedAction: "Submit a short debrief covering today's school work before 18:00.",
  },
  {
    id: "cceo-5",
    title: "School missing SSA: Bukoto Junior",
    body: "Planning is locked for this school until a first SSA is on record.",
    href: "/ssa",
    unread: true,
    ago: "3h",
    Icon: ShieldCheck,
    iconBg: "bg-sky-100",
    iconText: "text-sky-700",
    category: "SSA",
    priority: "important",
    actionRequired: true,
    contextLabel: "Bukoto Junior · planning locked",
    actionLabel: "Review SSA status",
    dueDate: "This week",
    recommendedAction: "Coordinate with your IA to get the SSA uploaded so planning unlocks.",
  },
  {
    id: "cceo-6",
    title: "School not in a cluster: St. Jude Primary",
    body: "Unclustered schools are excluded from cluster trainings and fellowship meetings.",
    href: "/clusters",
    unread: true,
    ago: "5h",
    Icon: Network,
    iconBg: "bg-indigo-100",
    iconText: "text-indigo-700",
    category: "Cluster",
    priority: "normal",
    actionRequired: true,
    contextLabel: "St. Jude Primary",
    actionLabel: "Open clusters",
    dueDate: "This week",
    recommendedAction: "Flag the school for cluster assignment so it joins the next cluster cycle.",
  },
  {
    id: "cceo-7",
    title: "Red alert: Living Word School",
    body: "SSA average declined two cycles in a row and the last visit found attendance issues.",
    href: "/core-schools",
    unread: true,
    ago: "6h",
    Icon: AlertTriangle,
    iconBg: "bg-rose-100",
    iconText: "text-rose-700",
    category: "School",
    priority: "critical",
    actionRequired: true,
    contextLabel: "Living Word School · declining SSA",
    actionLabel: "Open school",
    dueDate: "Within 48h",
    recommendedAction: "Schedule an intervention visit within 48 hours and record the support plan.",
  },
  {
    id: "cceo-8",
    title: "No visit or training in 30 days: Mukono Hill",
    body: "This portfolio school has had no qualifying activity this month.",
    href: "/my-plan",
    unread: true,
    ago: "Yesterday",
    Icon: CalendarRange,
    iconBg: "bg-amber-100",
    iconText: "text-amber-700",
    category: "Planning",
    priority: "important",
    actionRequired: true,
    contextLabel: "Mukono Hill · 30 days idle",
    actionLabel: "Schedule activity",
    dueDate: "This week",
    recommendedAction: "Add a visit or training to your plan so the school doesn't fall out of reach.",
  },
  {
    id: "cceo-9",
    title: "Core package gaps: 2 of 8 slots planned",
    body: "Grace Academy (Core) has 6 unplanned slots from its 4-visit + 4-training package.",
    href: "/core-schools",
    unread: true,
    ago: "Yesterday",
    Icon: School,
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-700",
    category: "School",
    priority: "important",
    actionRequired: true,
    contextLabel: "Grace Academy · Core 4+4",
    actionLabel: "Fill package slots",
    dueDate: "Before quarter end",
    recommendedAction: "Plan the remaining core visits and trainings before the quarter closes.",
  },
  {
    id: "cceo-10",
    title: "Partner work not scheduled: LTU",
    body: "2 schools delegated to Lift Them Up have no scheduled partner activity.",
    href: "/partners",
    unread: true,
    ago: "Yesterday",
    Icon: Handshake,
    iconBg: "bg-violet-100",
    iconText: "text-violet-700",
    category: "Partner",
    priority: "important",
    actionRequired: true,
    contextLabel: "Lift Them Up · 2 schools",
    actionLabel: "Review partner plan",
    dueDate: "This week",
    recommendedAction: "Follow up with the partner to schedule the delegated school work.",
  },
  {
    id: "cceo-11",
    title: "Partner evidence uploaded: Bright Future",
    body: "Q2 visit evidence for Kireka Primary is awaiting your review and confirmation.",
    href: "/partners",
    unread: true,
    ago: "2d",
    Icon: FileCheck2,
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-700",
    category: "Evidence",
    priority: "normal",
    actionRequired: true,
    contextLabel: "Bright Future · Kireka Primary",
    actionLabel: "Review evidence",
    dueDate: "Within 3 days",
    recommendedAction: "Confirm the partner's evidence so the activity can move to verification.",
  },
  {
    id: "cceo-12",
    title: "Partner activity overdue: Lift Them Up",
    body: "The delegated training at Seeta Junior passed its planned date with no completion.",
    href: "/partners",
    unread: false,
    ago: "2d",
    Icon: Truck,
    iconBg: "bg-rose-100",
    iconText: "text-rose-700",
    category: "Partner",
    priority: "urgent",
    actionRequired: true,
    contextLabel: "Seeta Junior · delegated training",
    actionLabel: "Chase partner",
    dueDate: "3 days overdue",
    recommendedAction: "Contact the partner; reschedule or take the activity back into your own plan.",
  },
  {
    id: "cceo-13",
    title: "Salesforce ID missing on 3 completed activities",
    body: "Evidence is complete but the activities fail the Salesforce completion gate.",
    href: "/data-verification",
    unread: true,
    ago: "2d",
    Icon: ShieldCheck,
    iconBg: "bg-amber-100",
    iconText: "text-amber-700",
    category: "SSA",
    priority: "important",
    actionRequired: true,
    contextLabel: "3 activities blocked",
    actionLabel: "Enter Salesforce IDs",
    dueDate: "Before Friday",
    recommendedAction: "Enter the SV-/TS- Salesforce IDs so the activities count as completed and unblock payment.",
  },
  {
    id: "cceo-14",
    title: "IA returned your evidence: Hope Primary visit",
    body: "Attendance sheet rejected — missing head-teacher signature on page 2.",
    href: "/data-verification?filter=returned",
    unread: true,
    ago: "3d",
    Icon: AlertTriangle,
    iconBg: "bg-rose-100",
    iconText: "text-rose-700",
    category: "Evidence",
    priority: "urgent",
    actionRequired: true,
    contextLabel: "Hope Primary · attendance sheet",
    actionLabel: "Fix and resubmit",
    dueDate: "Within 2 days",
    recommendedAction: "Re-upload the signed attendance sheet and resubmit for IA verification.",
  },
  {
    id: "cceo-15",
    title: "Payment issue: cluster meeting refreshments",
    body: "The accountant flagged a receipt mismatch on your Kireka cluster meeting claim.",
    href: "/fund-requests",
    unread: false,
    ago: "3d",
    Icon: Wallet,
    iconBg: "bg-rose-100",
    iconText: "text-rose-700",
    category: "Payment",
    priority: "important",
    actionRequired: true,
    contextLabel: "Kireka cluster · receipt mismatch",
    actionLabel: "Resolve payment",
    dueDate: "This week",
    recommendedAction: "Upload the corrected receipt so the payment can clear with the next batch.",
  },
  {
    id: "cceo-16",
    title: "You are 12 activities behind pace",
    body: "Cumulative completed activities trail the FY target pace for this point in the year.",
    href: "/my-targets",
    unread: true,
    ago: "4d",
    Icon: Target,
    iconBg: "bg-amber-100",
    iconText: "text-amber-700",
    category: "HR",
    priority: "important",
    actionRequired: true,
    contextLabel: "FY target · behind pace",
    actionLabel: "Review targets",
    dueDate: "This month",
    recommendedAction: "Front-load next week's plan with completable visits to close the pace gap.",
  },
  {
    id: "cceo-17",
    title: "Cluster meeting due: Kireka cluster",
    body: "The monthly cluster/parish fellowship meeting hasn't been scheduled for this cycle.",
    href: "/clusters",
    unread: false,
    ago: "4d",
    Icon: GraduationCap,
    iconBg: "bg-indigo-100",
    iconText: "text-indigo-700",
    category: "Cluster",
    priority: "normal",
    actionRequired: true,
    contextLabel: "Kireka cluster · monthly cycle",
    actionLabel: "Schedule meeting",
    dueDate: "By month end",
    recommendedAction: "Schedule the cluster meeting and notify member schools before month end.",
  },
];

export const unreadNotificationCount = NOTIFICATIONS.filter((n) => n.unread).length;
export const urgentNotificationCount = NOTIFICATIONS.filter((n) =>
  n.unread && (n.priority === "urgent" || n.priority === "critical")
).length;
export const actionRequiredCount = NOTIFICATIONS.filter((n) =>
  n.unread && n.actionRequired
).length;
