# Generated by Django 5.2.4 on 2026-07-12 16:44

import apps.core.cuid
import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monthly_work_plan", "0002_alter_adminbudgetline_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryAnnualBudget",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fy", models.CharField(max_length=16)),
                ("country_id", models.CharField(default="UG", max_length=64)),
                ("strategic_priorities", models.TextField(blank=True, null=True)),
                ("target_schools", models.IntegerField(default=0)),
                ("target_activities", models.IntegerField(default=0)),
                ("planned_staff_visits", models.IntegerField(default=0)),
                ("planned_partner_visits", models.IntegerField(default=0)),
                ("core_package_schools", models.IntegerField(default=0)),
                ("cluster_activities", models.IntegerField(default=0)),
                ("special_project_total", models.BigIntegerField(default=0)),
                ("admin_total", models.BigIntegerField(default=0)),
                ("program_total", models.BigIntegerField(default=0)),
                ("total_amount", models.BigIntegerField(default=0)),
                ("monthly_phasing", models.JSONField(blank=True, default=list)),
                ("quarterly_phasing", models.JSONField(blank=True, default=list)),
                ("prior_year_total", models.BigIntegerField(default=0)),
                ("expected_impact", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted_to_rvp", "Submitted to RVP"),
                            ("approved_by_rvp", "RVP Approved"),
                            ("returned_by_rvp", "Returned by RVP"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submitted_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("rvp_reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rvp_reviewed_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "rvp_review_note",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("baseline_locked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "country_annual_budget",
                "indexes": [
                    models.Index(
                        fields=["status"], name="country_ann_status_b958f3_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country_id", "fy"), name="uniq_country_annual_fy"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RVPApprovalDecision",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("decision_type", models.CharField(max_length=32)),
                ("subject_id", models.CharField(max_length=64)),
                ("subject_label", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=32)),
                ("reason", models.CharField(blank=True, max_length=512, null=True)),
                ("decided_by", models.CharField(max_length=30)),
                ("amount", models.BigIntegerField(default=0)),
                ("fy", models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                "db_table": "rvp_approval_decision",
                "indexes": [
                    models.Index(
                        fields=["decision_type", "subject_id"],
                        name="rvp_approva_decisio_06a1af_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StrategyNote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author_id", models.CharField(max_length=30)),
                ("priority_label", models.CharField(max_length=128)),
                ("scope", models.CharField(default="Regional", max_length=128)),
                ("instruction", models.TextField()),
                ("expected_outcome", models.TextField(blank=True, null=True)),
                (
                    "responsible_cd_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("review_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "rvp_strategy_note",
                "indexes": [
                    models.Index(
                        fields=["status", "responsible_cd_id"],
                        name="rvp_strateg_status_b59354_idx",
                    )
                ],
            },
        ),
    ]
