# Generated by Django 5.2.4 on 2026-07-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_work_plan', '0003_countryannualbudget_rvpapprovaldecision_strategynote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryannualbudget',
            name='country_id',
            field=models.CharField(default='Uganda', max_length=64),
        ),
    ]
