# Generated by Django 5.2.16 on 2026-07-27 00:03

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monthly_work_plan", "0005_backfill_country_id_uganda"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyworkplanbudget",
            name="submission_version",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="MonthlyBudgetSubmissionSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField()),
                ("fy", models.CharField(max_length=16)),
                ("month_key", models.CharField(max_length=16)),
                ("country_id", models.CharField(blank=True, max_length=64, null=True)),
                ("program_total", models.BigIntegerField(default=0)),
                ("admin_total", models.BigIntegerField(default=0)),
                ("total_amount", models.BigIntegerField(default=0)),
                ("activity_count", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submitted_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("staff_rows", models.JSONField(blank=True, default=list)),
                ("line_items", models.JSONField(blank=True, default=list)),
                ("admin_lines", models.JSONField(blank=True, default=list)),
                (
                    "monthly_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="monthly_work_plan.monthlyworkplanbudget",
                    ),
                ),
            ],
            options={
                "db_table": "monthly_budget_submission_snapshot",
                "ordering": ["-version"],
                "indexes": [
                    models.Index(
                        fields=["monthly_budget"], name="monthly_bud_monthly_bf203e_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("monthly_budget", "version"),
                        name="uniq_budget_submission_version",
                    )
                ],
            },
        ),
    ]
