# Generated by Django 5.2.17 on 2026-08-28 06:30

from django.db import migrations, models
from django.db.models import F


def mark_legacy_envelopes_unbenchmarked(apps, schema_editor):
    """Preserve old payable totals without inventing a regional benchmark."""
    Budget = apps.get_model("monthly_work_plan", "MonthlyWorkPlanBudget")
    Snapshot = apps.get_model("monthly_work_plan", "MonthlyBudgetSubmissionSnapshot")
    for model in (Budget, Snapshot):
        model.objects.update(
            operational_activity_requirement=F("program_total"),
            reference_configuration_missing_count=F("activity_count"),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("monthly_work_plan", "0006_monthlyworkplanbudget_submission_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlybudgetsubmissionsnapshot",
            name="country_funding_shortfall",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthlybudgetsubmissionsnapshot",
            name="deferred_amount",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthlybudgetsubmissionsnapshot",
            name="operational_activity_requirement",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthlybudgetsubmissionsnapshot",
            name="reference_configuration_missing_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthlybudgetsubmissionsnapshot",
            name="regional_standard_ceiling",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthlybudgetsubmissionsnapshot",
            name="strategic_reserve_requested",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthlyworkplanbudget",
            name="country_funding_shortfall",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthlyworkplanbudget",
            name="deferred_amount",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthlyworkplanbudget",
            name="operational_activity_requirement",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthlyworkplanbudget",
            name="reference_configuration_missing_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthlyworkplanbudget",
            name="regional_standard_ceiling",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthlyworkplanbudget",
            name="strategic_reserve_requested",
            field=models.BigIntegerField(default=0),
        ),
        migrations.RunPython(
            mark_legacy_envelopes_unbenchmarked,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="monthlyworkplanbudget",
            constraint=models.CheckConstraint(
                condition=models.Q(regional_standard_ceiling__gte=0)
                & models.Q(operational_activity_requirement__gte=0)
                & models.Q(strategic_reserve_requested__gte=0)
                & models.Q(deferred_amount__gte=0)
                & models.Q(country_funding_shortfall__gte=0),
                name="monthly_country_envelope_amounts_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlybudgetsubmissionsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(regional_standard_ceiling__gte=0)
                & models.Q(operational_activity_requirement__gte=0)
                & models.Q(strategic_reserve_requested__gte=0)
                & models.Q(deferred_amount__gte=0)
                & models.Q(country_funding_shortfall__gte=0),
                name="monthly_envelope_snapshot_amounts_non_negative",
            ),
        ),
    ]
