# Generated by Django 5.2.16 on 2026-07-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0008_partnerassignment_purpose_of_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="ssa_intervention",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
