# Generated by Django 5.2.16 on 2026-07-30 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_catalogue", "__first__"),
        ("partners", "0009_partner_ssa_intervention"),
        ("ssa", "0006_alter_ssascore_intervention"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerassignment",
            name="allowed_catalogue_items",
            field=models.ManyToManyField(
                blank=True,
                related_name="partner_choice_assignments",
                to="activity_catalogue.activitycatalogueitem",
            ),
        ),
        migrations.AddField(
            model_name="partnerassignment",
            name="assignment_mode",
            field=models.CharField(
                choices=[
                    ("specific_activity", "Specific Activity"),
                    ("intervention_choice", "Intervention-based choice"),
                ],
                default="specific_activity",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="partnerassignment",
            name="catalogue_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_assignments",
                to="activity_catalogue.activitycatalogueitem",
            ),
        ),
        migrations.AddField(
            model_name="partnerassignment",
            name="catalogue_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="partnerassignment",
            name="override_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="partnerassignment",
            name="recommendation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="partnerassignment",
            name="source_ssa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_assignments",
                to="ssa.ssarecord",
            ),
        ),
    ]
