# Generated by Django 5.2.16 on 2026-08-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0011_partner_assignment_catalogue_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerassignment",
            name="return_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partnerassignment",
            name="return_reason_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("schedule_conflict", "Schedule conflict"),
                    ("distance", "Distance or travel constraint"),
                    ("school_unavailable", "School unavailable"),
                    ("capacity", "Insufficient capacity"),
                    ("out_of_scope", "Assignment outside agreed scope"),
                    ("duplicate", "Duplicate assignment"),
                    ("incorrect_details", "Incorrect school or activity"),
                    ("safety", "Safety or access concern"),
                    ("other", "Other"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partnerassignment",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partnerassignment",
            name="returned_by",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
