# Generated by Django 5.2.16 on 2026-08-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0012_partnerassignment_return_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerassignment",
            name="monitoring_staff_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
