# Generated by Django 5.2.16 on 2026-08-06 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0035_cluster_participant_planning"),
        ("partners", "0013_partnerassignment_monitoring_staff_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerassignment",
            name="scheduled_activity",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="originating_partner_assignment",
                to="activities.activity",
            ),
        ),
    ]
