# Generated by Django 5.2.16 on 2026-08-07 06:55

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0035_cluster_participant_planning"),
        ("budget", "0008_consolidate_cost_setting_registry"),
        ("partners", "0014_partnerassignment_scheduled_activity"),
        ("schools", "0018_relink_school_geography"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerAssignmentWithdrawal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("requested_by", models.CharField(max_length=30)),
                ("requested_by_role", models.CharField(blank=True, max_length=48)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved_by", models.CharField(blank=True, max_length=30, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("effective_at", models.DateTimeField(blank=True, null=True)),
                (
                    "responsible_cceo_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "supervising_pl_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("withdraw_unscheduled", "Withdraw assignment"),
                            ("recall_scheduled", "Recall scheduled activity"),
                            ("suspend_in_progress", "Suspend delivery and review"),
                            ("quality_review", "Withdraw for quality review"),
                            ("payment_hold", "Place payment on hold"),
                            ("blocked", "Not available in this state"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("under_review", "Under PL review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("effective", "Effective"),
                            ("suspended", "Suspended pending review"),
                            ("reassigned", "Reassigned"),
                            ("returned_to_planning", "Returned to planning"),
                            ("cancelled", "Cancelled"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                        ],
                        default="requested",
                        max_length=32,
                    ),
                ),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("not_scheduled", "Partner has not scheduled"),
                            ("scheduling_delay", "Repeated scheduling delay"),
                            ("repeated_reschedule", "Repeated rescheduling"),
                            ("capacity", "Partner capacity constraint"),
                            ("partner_unavailable", "Partner unavailable"),
                            ("poor_quality", "Poor quality of work"),
                            ("poor_evidence", "Poor evidence quality"),
                            ("repeated_evidence_return", "Repeated evidence return"),
                            ("communication", "Communication breakdown"),
                            ("missed_deadline", "Missed activity deadline"),
                            ("conduct", "Conduct or integrity concern"),
                            ("safeguarding", "Safeguarding concern"),
                            ("partner_requested_release", "Partner requested release"),
                            ("school_unavailable", "School unavailable"),
                            ("school_complaint", "School complaint"),
                            ("school_requested_change", "School requested a change"),
                            ("out_of_scope", "Assignment outside partner scope"),
                            ("incorrect_assignment", "Incorrect school or activity"),
                            ("duplicate_assignment", "Duplicate assignment"),
                            ("support_not_required", "Support no longer required"),
                            ("programme_change", "Project or programme change"),
                            ("strategic_reallocation", "Strategic reallocation"),
                            ("distance", "Distance or travel constraint"),
                            ("safety", "Safety or access concern"),
                            ("other", "Other documented reason"),
                        ],
                        max_length=40,
                    ),
                ),
                ("partner_facing_reason", models.TextField()),
                ("internal_note", models.TextField(blank=True)),
                (
                    "attribution",
                    models.CharField(
                        choices=[
                            ("partner", "Partner-attributable"),
                            ("school", "School-attributable"),
                            ("edify", "Edify-attributable"),
                            ("external", "External circumstance"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("return_to_planning", "Return to CCEO Planning"),
                            ("reassign_partner", "Assign to another Partner"),
                            ("schedule_as_staff", "Schedule as staff"),
                            ("hold_for_review", "Hold for review"),
                            ("cancel_support", "Cancel support"),
                            ("escalate", "Escalate to Country Director"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "assignment_state_at_withdrawal",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "activity_state_at_withdrawal",
                    models.CharField(blank=True, max_length=48),
                ),
                (
                    "financial_state_at_withdrawal",
                    models.CharField(blank=True, max_length=48),
                ),
                ("original_planned_cost", models.BigIntegerField(default=0)),
                (
                    "eligible_partner_cost",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "partner_acknowledged_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("partner_response", models.TextField(blank=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="partners.partnerassignment",
                    ),
                ),
                (
                    "budget_amendment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_withdrawals",
                        to="budget.budgetamendment",
                    ),
                ),
                (
                    "linked_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_withdrawals",
                        to="activities.activity",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawals",
                        to="partners.partner",
                    ),
                ),
                (
                    "replacement_assignment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaced_withdrawal",
                        to="partners.partnerassignment",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_withdrawals",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "partner_assignment_withdrawal",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["assignment", "state"],
                        name="partner_ass_assignm_ce6c35_idx",
                    ),
                    models.Index(
                        fields=["partner", "attribution"],
                        name="partner_ass_partner_d399c9_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                ["requested", "under_review", "approved", "suspended"],
                            )
                        ),
                        fields=("assignment",),
                        name="one_open_withdrawal_per_assignment",
                    )
                ],
            },
        ),
    ]
