# Generated by Django 5.2.16 on 2026-08-07 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0015_partnerassignmentwithdrawal"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerassignment",
            name="reassignment_sequence",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnerassignment",
            name="replaces_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaced_by",
                to="partners.partnerassignment",
            ),
        ),
    ]
