# Generated by Django 5.2.16 on 2026-08-07 07:26

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0016_partnerassignment_reassignment_sequence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerHold",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("not_scheduled", "Partner has not scheduled"),
                            ("scheduling_delay", "Repeated scheduling delay"),
                            ("repeated_reschedule", "Repeated rescheduling"),
                            ("capacity", "Partner capacity constraint"),
                            ("partner_unavailable", "Partner unavailable"),
                            ("poor_quality", "Poor quality of work"),
                            ("poor_evidence", "Poor evidence quality"),
                            ("repeated_evidence_return", "Repeated evidence return"),
                            ("communication", "Communication breakdown"),
                            ("missed_deadline", "Missed activity deadline"),
                            ("conduct", "Conduct or integrity concern"),
                            ("safeguarding", "Safeguarding concern"),
                            ("partner_requested_release", "Partner requested release"),
                            ("school_unavailable", "School unavailable"),
                            ("school_complaint", "School complaint"),
                            ("school_requested_change", "School requested a change"),
                            ("out_of_scope", "Assignment outside partner scope"),
                            ("incorrect_assignment", "Incorrect school or activity"),
                            ("duplicate_assignment", "Duplicate assignment"),
                            ("support_not_required", "Support no longer required"),
                            ("programme_change", "Project or programme change"),
                            ("strategic_reallocation", "Strategic reallocation"),
                            ("distance", "Distance or travel constraint"),
                            ("safety", "Safety or access concern"),
                            ("other", "Other documented reason"),
                        ],
                        max_length=40,
                    ),
                ),
                ("reason", models.TextField()),
                ("internal_note", models.TextField(blank=True)),
                ("requested_by", models.CharField(max_length=30)),
                ("requested_by_role", models.CharField(blank=True, max_length=48)),
                ("effective_from", models.DateField()),
                ("review_on", models.DateField()),
                ("lifted_at", models.DateTimeField(blank=True, null=True)),
                ("lifted_by", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holds",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "db_table": "partner_hold",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("lifted_at__isnull", True)),
                        fields=("partner",),
                        name="one_live_hold_per_partner",
                    )
                ],
            },
        ),
    ]
