# Generated by Django 5.2.17 on 2026-09-13 09:38

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cce_leadership", "0001_initial"),
        ("partners", "0019_partnermember"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerEngagement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author_id", models.CharField(db_index=True, max_length=30)),
                (
                    "author_role",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("review_meeting", "Partner review meeting"),
                            (
                                "framework_orientation",
                                "Orientation on Edify's CCE framework",
                            ),
                            ("quality_follow_up", "Training quality follow-up"),
                            ("joint_planning", "Joint planning"),
                            ("capacity_building", "Capacity-building session"),
                        ],
                        max_length=32,
                    ),
                ),
                ("held_on", models.DateField()),
                ("fy", models.CharField(db_index=True, max_length=16)),
                ("country", models.CharField(blank=True, default="", max_length=64)),
                ("subject", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("agreed_improvements", models.TextField(blank=True, default="")),
                ("follow_up_due", models.DateField(blank=True, null=True)),
                ("follow_up_done_at", models.DateTimeField(blank=True, null=True)),
                ("follow_up_note", models.TextField(blank=True, default="")),
                ("shared_with_partner_at", models.DateTimeField(blank=True, null=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="partners.partner",
                    ),
                ),
                (
                    "source_engagement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_engagements",
                        to="cce_leadership.regionalengagement",
                    ),
                ),
            ],
            options={
                "db_table": "partner_engagement",
                "ordering": ["-held_on", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["partner", "held_on"],
                        name="idx_partner_engagement_partner",
                    ),
                    models.Index(
                        fields=["author_id", "held_on"],
                        name="idx_partner_engagement_author",
                    ),
                    models.Index(
                        fields=["country", "held_on"],
                        name="idx_partner_engagement_country",
                    ),
                ],
            },
        ),
    ]
