# Generated by Django 5.2.17 on 2026-09-15 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_catalogue", "0014_mapping_review"),
        ("partners", "0020_partnerengagement"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerassignment",
            name="training_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_course_assignments",
                to="activity_catalogue.activitycatalogueitem",
            ),
        ),
    ]
