# Generated by Django 5.2.17 on 2026-09-15 18:25

from django.db import migrations, models


def backfill_user_setup(apps, schema_editor):
    """An organisation that already has a linked login is configured; every
    other existing organisation is pending, which is what it has been all
    along. Nothing is inferred from the organisation's contact email."""
    Partner = apps.get_model("partners", "Partner")
    Partner.objects.filter(user__isnull=False).update(user_setup_status="configured")


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0021_partnerassignment_training_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="user_setup_status",
            field=models.CharField(
                choices=[
                    ("pending", "User setup pending"),
                    ("not_required", "No login required yet"),
                    ("configured", "Partner login configured"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="user_setup_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="user_setup_updated_by",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.RunPython(backfill_user_setup, migrations.RunPython.noop),
    ]
