# Generated by Django 5.2.17 on 2026-09-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0056_training_materials_pages"),
        ("activity_catalogue", "0014_mapping_review"),
        ("clusters", "0006_backfill_catchments_and_membership_history"),
        ("partners", "0023_partner_activity_codes_partner_ssa_interventions"),
        ("projects", "0013_project_school_enrollment_history"),
        ("schools", "0022_school_ownership_transfers"),
        ("ssa", "0009_ssa_record_source_and_return"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerassignment",
            name="resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reassigned", "Reassigned to another Partner"),
                    ("staff_delivery", "Staff will deliver the support"),
                    ("support_closed", "Support no longer required"),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="partnerassignment",
            name="resolution_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="partnerassignment",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partnerassignment",
            name="resolved_by",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name="partnerassignment",
            index=models.Index(
                fields=["school", "status"], name="idx_partner_assign_school_st"
            ),
        ),
        migrations.AddIndex(
            model_name="partnerassignment",
            index=models.Index(
                fields=["partner", "status"], name="idx_partner_assign_partner_st"
            ),
        ),
    ]
