# Generated by Django 5.2.17 on 2026-10-09 15:36

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0032_clear_handover_target_dates"),
        ("schools", "0024_settle_closed_schools"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerSchoolMember",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assigned_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schools",
                        to="partners.partnermember",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_members",
                        to="partners.partner",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_team_members",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "partner_school_member",
                "indexes": [
                    models.Index(
                        fields=["partner", "member"],
                        name="partner_sch_partner_bacf0c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("partner", "school"),
                        name="partner_school_one_team_member",
                    )
                ],
            },
        ),
    ]
