# Generated by Django 5.2.4 on 2026-06-26 22:49

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('intervention_specific', 'Intervention Specific'), ('pilot', 'Pilot'), ('selective_limited', 'Selective Limited')], max_length=32)),
                ('intervention', models.CharField(blank=True, choices=[('teaching_and_learning', 'Teaching & Learning'), ('financial_health', 'Financial Health'), ('christlike_behaviour', 'Christlike Behaviour'), ('exposure_to_word_of_god', 'Exposure to Word of God'), ('government_requirements', 'Government Requirements'), ('leadership', 'Leadership'), ('education_technology', 'Education Technology'), ('learning_environment', 'Learning Environment')], max_length=64, null=True)),
                ('manager_staff_id', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImpactSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('fy', models.CharField(max_length=16)),
                ('metrics_json', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_snapshots', to='projects.project')),
            ],
            options={
                'db_table': 'project_impact_snapshot',
            },
        ),
        migrations.CreateModel(
            name='ProjectPartnerAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='partners.partner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_assignments', to='projects.project')),
            ],
            options={
                'db_table': 'project_partner_assignment',
                'constraints': [models.UniqueConstraint(fields=('project', 'partner'), name='uniq_project_partner')],
            },
        ),
        migrations.CreateModel(
            name='ProjectSchoolAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_assignments', to='projects.project')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='schools.school')),
            ],
            options={
                'db_table': 'project_school_assignment',
                'constraints': [models.UniqueConstraint(fields=('project', 'school'), name='uniq_project_school')],
            },
        ),
    ]
