# Generated by Django 5.2.4 on 2026-07-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_projectschoolassignment_assigned_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="intervention",
            field=models.CharField(
                blank=True,
                choices=[
                    ("christlike_behaviour", "Christlike Behaviour"),
                    ("exposure_to_word_of_god", "Exposure to Word of God"),
                    ("financial_health", "Financial Health"),
                    ("leadership", "Leadership"),
                    ("learning_environment", "Learning Environment"),
                    ("government_requirement", "Government Requirement"),
                    ("teaching_environment", "Teaching Environment"),
                    ("enrolment", "Enrolment"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
