# Generated by Django 5.2.4 on 2026-07-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_intervention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='intervention',
            field=models.CharField(blank=True, choices=[('christlike_behaviour', 'Christlike Behaviour'), ('exposure_to_word_of_god', 'Exposure to the Word of God'), ('financial_health', 'Financial Health'), ('leadership', 'Leadership'), ('government_requirement', 'Government Requirements'), ('learning_environment', 'Learning Environment'), ('teaching_environment', "Teacher's Environment"), ('enrolment', 'Enrolment')], max_length=64, null=True),
        ),
    ]
