# Generated by Django 5.2.4 on 2026-07-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_project_intervention"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="measurement_end_fy",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="measurement_start_fy",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="target_interventions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="projectschoolassignment",
            name="assignment_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectschoolassignment",
            name="matched_intervention",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
