# Generated by Django 5.2.17 on 2026-08-22 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_staff_priority_upgrade'),
        ('ssa', '0008_ssarecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectschoolassignment',
            name='baseline_band',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='projectschoolassignment',
            name='baseline_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectschoolassignment',
            name='baseline_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectschoolassignment',
            name='baseline_ssa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_baselines', to='ssa.ssarecord'),
        ),
        migrations.AddField(
            model_name='projectschoolassignment',
            name='exception_approved_by',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='projectschoolassignment',
            name='exception_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectschoolassignment',
            name='exception_status',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='projectschoolassignment',
            name='follow_up_due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectschoolassignment',
            name='follow_up_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectschoolassignment',
            name='follow_up_ssa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_follow_ups', to='ssa.ssarecord'),
        ),
        migrations.AddField(
            model_name='projectschoolassignment',
            name='impact_classification',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='projectschoolassignment',
            name='mapping_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
