# Generated by Django 5.2.17 on 2026-09-13 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_catalogue", "0014_mapping_review"),
        ("projects", "0011_projectschoolassignment_baseline_band_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectschoolassignment",
            name="mapping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stamped_enrolments",
                to="activity_catalogue.activityinterventionmapping",
            ),
        ),
    ]
