# Generated by Django 5.2.17 on 2026-09-16 03:34

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_projectschoolassignment_mapping"),
        ("schools", "0022_school_ownership_transfers"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSchoolEnrollmentHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField()),
                ("added_by", models.CharField(blank=True, default="", max_length=30)),
                ("removed_by", models.CharField(blank=True, default="", max_length=30)),
                ("removal_reason", models.TextField(blank=True, default="")),
                (
                    "matched_intervention",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("assignment_reason", models.TextField(blank=True, default="")),
                ("baseline_score", models.FloatField(blank=True, null=True)),
                (
                    "baseline_band",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("activities_delivered", models.PositiveIntegerField(default=0)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_enrollment_history",
                        to="projects.project",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_enrollment_history",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "project_school_enrollment_history",
                "ordering": ["-removed_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-removed_at"],
                        name="project_sch_project_2d7bfe_idx",
                    )
                ],
            },
        ),
    ]
