# Generated by Django 5.2.17 on 2026-09-29 12:44

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


# The allocation is held by the database as well as by the service
# (brief, 2026-09-29: "Do NOT implement this only in the frontend ... direct
# database requests ... race conditions"). Enrolling a school locks the
# staff member's allocation row and counts what it already holds, so two
# enrolments racing for the last place are serialised and the second is
# refused; an allocation cannot be lowered below what it already holds.
CAPACITY_TRIGGERS_SQL = """
CREATE OR REPLACE FUNCTION project_school_capacity_guard() RETURNS trigger AS $$
DECLARE
    allowed integer;
    held integer;
BEGIN
    IF NEW.assigned_staff_id IS NULL THEN
        RETURN NEW;
    END IF;
    IF TG_OP = 'UPDATE'
       AND NEW.assigned_staff_id IS NOT DISTINCT FROM OLD.assigned_staff_id
       AND NEW.project_id = OLD.project_id THEN
        RETURN NEW;
    END IF;
    SELECT max_schools INTO allowed
      FROM project_staff_capacity
     WHERE project_id = NEW.project_id AND staff_id = NEW.assigned_staff_id
       FOR UPDATE;
    IF allowed IS NULL THEN
        RETURN NEW;
    END IF;
    SELECT count(*) INTO held
      FROM project_school_assignment
     WHERE project_id = NEW.project_id
       AND assigned_staff_id = NEW.assigned_staff_id
       AND id <> NEW.id;
    IF held >= allowed THEN
        RAISE EXCEPTION 'Project capacity reached: % of % schools already assigned.',
            held, allowed
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER project_school_capacity_guard
BEFORE INSERT OR UPDATE OF assigned_staff_id, project_id
ON project_school_assignment
FOR EACH ROW EXECUTE FUNCTION project_school_capacity_guard();

CREATE OR REPLACE FUNCTION project_staff_capacity_floor() RETURNS trigger AS $$
DECLARE
    held integer;
BEGIN
    SELECT count(*) INTO held
      FROM project_school_assignment
     WHERE project_id = NEW.project_id
       AND assigned_staff_id = NEW.staff_id;
    IF NEW.max_schools < held THEN
        RAISE EXCEPTION 'Capacity cannot be reduced below the current number of assigned schools. Current assignment: %.',
            held
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER project_staff_capacity_floor
BEFORE INSERT OR UPDATE OF max_schools, project_id, staff_id
ON project_staff_capacity
FOR EACH ROW EXECUTE FUNCTION project_staff_capacity_floor();
"""

DROP_CAPACITY_TRIGGERS_SQL = """
DROP TRIGGER IF EXISTS project_school_capacity_guard ON project_school_assignment;
DROP FUNCTION IF EXISTS project_school_capacity_guard();
DROP TRIGGER IF EXISTS project_staff_capacity_floor ON project_staff_capacity;
DROP FUNCTION IF EXISTS project_staff_capacity_floor();
"""

# Existing enrolments draw on the allocation of the CCEO or Programme Lead who
# added them, so a coordinator setting an allocation sees what that person
# already holds. Enrolments added by a coordinator or a country role draw on
# nobody's. ``assigned_by`` holds a user id (older rows: a staff profile id).
BACKFILL_ASSIGNED_STAFF_SQL = """
UPDATE project_school_assignment AS psa
   SET assigned_staff_id = sp.id
  FROM staff_profile AS sp
  JOIN "user" AS u ON u.id = sp.user_id
 WHERE psa.assigned_staff_id IS NULL
   AND (psa.assigned_by = sp.user_id OR psa.assigned_by = sp.id)
   AND u.roles && ARRAY['CCEO', 'Program Lead']::varchar[];
"""


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0034_sign_in_minutes_belong_to_the_dashboard"),
        ("projects", "0013_project_school_enrollment_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectschoolassignment",
            name="assigned_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_school_enrolments",
                to="accounts.staffprofile",
            ),
        ),
        migrations.AddField(
            model_name="projectschoolenrollmenthistory",
            name="assigned_staff_id",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.CreateModel(
            name="ProjectStaffCapacity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("max_schools", models.PositiveIntegerField()),
                ("set_by", models.CharField(blank=True, default="", max_length=30)),
                (
                    "set_by_role",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_capacities",
                        to="projects.project",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_capacities",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "project_staff_capacity",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "staff"), name="uniq_project_staff_capacity"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_schools__gt", 0)),
                        name="project_staff_capacity_positive",
                    ),
                ],
            },
        ),
        migrations.RunSQL(BACKFILL_ASSIGNED_STAFF_SQL, migrations.RunSQL.noop),
        migrations.RunSQL(CAPACITY_TRIGGERS_SQL, DROP_CAPACITY_TRIGGERS_SQL),
    ]
