# Generated by Django 5.2.4 on 2026-07-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssa', '0004_rename_ssa_interventions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssascore',
            name='intervention',
            field=models.CharField(choices=[('christlike_behaviour', 'Christlike Behaviour'), ('exposure_to_word_of_god', 'Exposure to the Word of God'), ('financial_health', 'Financial Health'), ('leadership', 'Leadership'), ('learning_environment', 'Learning Environment'), ('government_requirement', 'Government Requirement'), ('teaching_environment', 'Teaching Environment'), ('enrolment', 'Enrollment Score')], max_length=64),
        ),
    ]
