# Generated by Django 5.2.17 on 2026-08-21 14:39

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "activities",
            "0044_activity_driver_reason_activity_primary_driver_id_and_more",
        ),
        (
            "activity_catalogue",
            "0009_alter_activitycatalogueitem_activity_type_and_more",
        ),
        ("schools", "0020_dataqualityissue_condition_key_and_more"),
        ("ssa", "0007_ssarecord_ssa_record_collect_18c247_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="SsaRecommendation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("condition_key", models.CharField(db_index=True, max_length=255)),
                (
                    "intervention",
                    models.CharField(
                        choices=[
                            ("christlike_behaviour", "Christlike Behaviour"),
                            ("exposure_to_word_of_god", "Exposure to the Word of God"),
                            ("financial_health", "Financial Health"),
                            ("leadership", "Leadership"),
                            ("government_requirement", "Government Requirements"),
                            ("learning_environment", "Learning Environment"),
                            ("teaching_environment", "Teacher's Environment"),
                            ("enrolment", "Enrolment"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("fy", models.CharField(db_index=True, max_length=16)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("score_band", models.CharField(blank=True, default="", max_length=32)),
                ("rank", models.IntegerField(default=0)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "unmapped_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("accepted", "Accepted for planning"),
                            ("deferred", "Deferred"),
                            ("planned", "Planned"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                            ("delivered", "Delivered and verified"),
                        ],
                        db_index=True,
                        default="generated",
                        max_length=32,
                    ),
                ),
                (
                    "owner_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True
                    ),
                ),
                (
                    "decided_by_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True, default="")),
                ("expires_on", models.DateField(blank=True, null=True)),
                (
                    "engine_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "planned_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answered_ssa_recommendations",
                        to="activities.activity",
                    ),
                ),
                (
                    "recommended_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ssa_recommendations",
                        to="activity_catalogue.activitycatalogueitem",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssa_recommendations",
                        to="schools.school",
                    ),
                ),
                (
                    "ssa_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="ssa.ssarecord",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="ssa.ssarecommendation",
                    ),
                ),
            ],
            options={
                "db_table": "ssa_recommendation",
                "indexes": [
                    models.Index(
                        fields=["school", "state"], name="idx_ssarec_school_state"
                    ),
                    models.Index(fields=["fy", "state"], name="idx_ssarec_fy_state"),
                    models.Index(
                        fields=["owner_id", "state"], name="idx_ssarec_owner_state"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                ("generated", "accepted", "deferred", "planned"),
                            )
                        ),
                        fields=("condition_key",),
                        name="uniq_live_ssa_recommendation_per_need",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("state__in", ["deferred", "rejected"]), _negated=True
                            ),
                            models.Q(("decision_reason", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="ssa_recommendation_decline_needs_reason",
                    ),
                ],
            },
        ),
    ]
