# Generated by Django 5.2.17 on 2026-09-13 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0053_activity_ssa_alignment"),
        ("ssa", "0008_ssarecommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssarecord",
            name="return_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ssarecord",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ssarecord",
            name="returned_by_user_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="ssarecord",
            name="source_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collected_ssa_records",
                to="activities.activity",
            ),
        ),
    ]
