# Generated by Django 5.2.4 on 2026-06-26 22:03

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentAudit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                ("school_id", models.CharField(blank=True, max_length=30, null=True)),
                ("activity_id", models.CharField(blank=True, max_length=30, null=True)),
                ("assigner_id", models.CharField(max_length=30)),
                (
                    "assigner_role",
                    models.CharField(
                        choices=[
                            ("CCEO", "CCEO"),
                            ("CountryProgramLead", "CountryProgramLead"),
                            ("CountryDirector", "CountryDirector"),
                            ("RegionalVicePresident", "RegionalVicePresident"),
                            ("ImpactAssessment", "ImpactAssessment"),
                            ("ProgramAccountant", "ProgramAccountant"),
                            ("HumanResources", "HumanResources"),
                            ("ProjectCoordinator", "ProjectCoordinator"),
                            ("PartnerAdmin", "PartnerAdmin"),
                            ("PartnerFieldOfficer", "PartnerFieldOfficer"),
                            ("Admin", "Admin"),
                        ],
                        max_length=64,
                    ),
                ),
                ("assigned_to_type", models.CharField(max_length=16)),
                (
                    "assigned_staff_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "assigned_partner_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("allowed", models.BooleanField()),
                (
                    "blocked_reason",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("override_used", models.BooleanField(default=False)),
                (
                    "override_reason",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
            ],
            options={
                "db_table": "assignment_audit",
                "indexes": [
                    models.Index(
                        fields=["assigner_id"], name="assignment__assigne_5a09e8_idx"
                    ),
                    models.Index(
                        fields=["school_id"], name="assignment__school__1c4bba_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="assignment__created_b6a6f7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=64)),
                ("fy", models.CharField(max_length=16)),
                ("scope", models.CharField(default="country", max_length=64)),
                (
                    "created_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("summary_json", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "report",
                "indexes": [
                    models.Index(fields=["type"], name="report_type_9eba38_idx"),
                    models.Index(fields=["fy"], name="report_fy_a26323_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=64)),
                ("start_date", models.CharField(max_length=32)),
                ("end_date", models.CharField(max_length=32)),
                ("days", models.IntegerField()),
                ("status", models.CharField(default="pending", max_length=32)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "reviewed_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "leave",
                "indexes": [
                    models.Index(fields=["staff"], name="leave_staff_i_3b0697_idx"),
                    models.Index(fields=["status"], name="leave_status_69e783_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffSupportCapacity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fy", models.CharField(max_length=16)),
                ("max_direct_schools_supported", models.IntegerField()),
                ("set_by_user_id", models.CharField(max_length=30)),
                (
                    "set_by_role",
                    models.CharField(
                        choices=[
                            ("CCEO", "CCEO"),
                            ("CountryProgramLead", "CountryProgramLead"),
                            ("CountryDirector", "CountryDirector"),
                            ("RegionalVicePresident", "RegionalVicePresident"),
                            ("ImpactAssessment", "ImpactAssessment"),
                            ("ProgramAccountant", "ProgramAccountant"),
                            ("HumanResources", "HumanResources"),
                            ("ProjectCoordinator", "ProjectCoordinator"),
                            ("PartnerAdmin", "PartnerAdmin"),
                            ("PartnerFieldOfficer", "PartnerFieldOfficer"),
                            ("Admin", "Admin"),
                        ],
                        max_length=64,
                    ),
                ),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_capacities",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "staff_support_capacity",
                "indexes": [
                    models.Index(fields=["fy"], name="staff_suppo_fy_421ac5_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "fy"), name="uniq_staff_capacity_fy"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffTargetProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fy", models.CharField(max_length=16)),
                ("visits_target", models.IntegerField(default=0)),
                ("trainings_target", models.IntegerField(default=0)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_profiles",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "staff_target_profile",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "fy"), name="uniq_staff_target_fy"
                    )
                ],
            },
        ),
    ]
