# Data migration: rewrite stored role values to the new canonical names.
#
# EdifyRole values renamed in apps/core/rbac.py:
#   "ProgramAccountant"  -> "Accountant"
#   "CountryProgramLead" -> "Program Lead"
#
# These values are persisted across many role-bearing CharField columns (some
# with EdifyRole choices, most without) and across the user.roles Postgres
# ArrayField. This migration rewrites every existing row so it matches the new
# enum values.
#
# It is idempotent: running it twice is a no-op because REPLACE/array_replace
# only match the exact old strings, which no longer exist after the first run.
#
# Historical migration files are intentionally left untouched (they are frozen
# schema definitions). This migration layers the rename on top.
#
# NOTE: choices are not enforced at the DB level by Django, so the schema
# AlterField operations in 0006 only update Django's recorded state. The actual
# row data is rewritten here.
#
# The (table, column, is_array) list below was generated by introspecting the
# live model metadata (every field whose name contains "role" and is a
# CharField/ArrayField). `permission.roles` is a ForeignKey to Role, not a role
# string, and is intentionally excluded. `staff_setup_candidate.suggested_role`
# is free-text and not constrained; it's included because it may hold the old
# canonical value when inferred from a CCEO/PL assignment.

from django.db import migrations


# (table, column, is_array) for every role-bearing string column in the project.
_ROLE_COLUMNS = [
    ("user", "active_role", False),
    ("user", "roles", True),
    ("role_permission", "role", False),
    ("staff_support_capacity", "set_by_role", False),
    ("assignment_audit", "assigner_role", False),
    ("staff_setup_candidate", "suggested_role", False),
    ("activity_timeline_event", "actor_role", False),
    ("audit_log", "actor_role", False),
    ("activity_schedule_cost_line", "responsible_role", False),
    ("closure_blocker", "responsible_role", False),
    ("budget_intelligence_insight", "reviewed_by_role", False),
    ("budget_intelligence_financedecisionnote", "author_role", False),
    ("daily_debrief", "submitted_by_role", False),
    ("daily_debrief_recipient", "recipient_role", False),
    ("evidence_record", "uploader_role", False),
    ("finance_audit_log", "actor_role", False),
    ("fund_request", "submitted_by_role", False),
    ("weekly_fund_request", "responsible_role", False),
    ("leadership_decision_insight", "reviewed_by_role", False),
    ("leadership_decisionnote", "author_role", False),
    ("notification", "recipient_role", False),
    ("target_setting", "set_by_role", False),
]

# (old_value, new_value) — applied in order. Neither old string is a substring
# of the other, so REPLACE cannot double-apply.
_RENAMES = [
    ("ProgramAccountant", "Accountant"),
    ("CountryProgramLead", "Program Lead"),
]


def _apply(schema_editor, renames):
    """Run parameterized UPDATEs against each role column.

    Uses schema_editor so the SQL executes on the same connection as the
    migration. Raw SQL is required because many target tables belong to apps
    other than `accounts` and we deliberately do not import their models here
    (avoids coupling and stale-model risks during a data migration).
    """
    with schema_editor.connection.cursor() as cursor:
        for table, column, is_array in _ROLE_COLUMNS:
            for old, new in renames:
                if is_array:
                    # Postgres ArrayField: swap matching array elements.
                    sql = f'UPDATE "{table}" SET "{column}" = array_replace("{column}", %s, %s)'
                else:
                    sql = f'UPDATE "{table}" SET "{column}" = REPLACE("{column}", %s, %s)'
                cursor.execute(sql, [old, new])


def forward(apps, schema_editor):
    _apply(schema_editor, _RENAMES)


def reverse(apps, schema_editor):
    # Inverse mapping, reversed so the original order is restored.
    _apply(schema_editor, [(new, old) for old, new in reversed(_RENAMES)])


class Migration(migrations.Migration):

    dependencies = [
        # accounts 0006 has the new schema (AlterField choices). Data rewrite
        # must run after it so recorded state is consistent before rows change.
        ("accounts", "0006_alter_assignmentaudit_assigner_role_and_more"),
        # Every other app whose rows we rewrite must have its tables present.
        ("audit", "0002_alter_auditlog_actor_role"),
        ("activities", "0012_activityclosure_activity_cl_status_30186c_idx_and_more"),
        ("budget_intelligence", "0001_initial"),
        ("debriefs", "0002_dailydebrief_environment_dailydebrief_source"),
        ("evidence", "0001_initial"),
        ("fund_requests", "0006_accountabilityrecord_disbursement_financeauditlog_and_more"),
        ("leadership", "0001_initial"),
        ("notifications", "0001_initial"),
        ("targets", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
