# Generated by Django 5.2.4 on 2026-07-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_add_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="coverage_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
