# Generated by Django 5.2.4 on 2026-07-08 18:35

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_leave_coverage_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveTypePolicy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("leave_type", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=128)),
                ("annual_entitlement", models.IntegerField(default=21)),
                ("requires_attachment", models.BooleanField(default=False)),
                (
                    "approver_role",
                    models.CharField(default="Program Lead", max_length=64),
                ),
                ("weekends_count", models.BooleanField(default=False)),
                ("public_holidays_count", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "leave_type_policy",
            },
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField(unique=True)),
            ],
            options={
                "db_table": "public_holiday",
            },
        ),
        migrations.AddField(
            model_name="leave",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="leave_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="covering_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leaves_covered",
                to="accounts.staffprofile",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="days_charged",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leave",
            name="emergency_contact",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leave",
            name="handover_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leave",
            name="hours_covered",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leave",
            name="urgent_activities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TemporaryCoverageAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("scope", models.CharField(default="operational_work", max_length=255)),
                ("status", models.CharField(default="active", max_length=32)),
                (
                    "created_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "approved_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "covering_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverages_received",
                        to="accounts.staffprofile",
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_assignments",
                        to="accounts.leave",
                    ),
                ),
                (
                    "original_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverages_given",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "temporary_coverage_assignment",
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("leave_type", models.CharField(max_length=64)),
                ("year", models.IntegerField(default=2026)),
                ("entitlement", models.IntegerField(default=21)),
                ("used", models.IntegerField(default=0)),
                ("pending", models.IntegerField(default=0)),
                ("approved", models.IntegerField(default=0)),
                ("remaining", models.IntegerField(default=21)),
                ("expired", models.IntegerField(default=0)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "leave_balance",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "leave_type", "year"),
                        name="uniq_staff_leave_type_year",
                    )
                ],
            },
        ),
    ]
