# Generated by Django 5.2.4 on 2026-07-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_leave_coverage_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_login_streak_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_lockout_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="lockout_cycle_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="lockout_escalated",
            field=models.BooleanField(default=False),
        ),
    ]
