# Generated by Django 5.2.4 on 2026-07-18 07:27

import django.db.models.deletion
from django.db import migrations, models


def _backfill_family_id(apps, schema_editor):
    """Pre-existing tokens predate lineage tracking — each becomes the root
    of its own singleton family (its own id is already a unique identifier),
    rather than left with the placeholder empty string that would collide
    every such row into one "family" and over-revoke on the first reuse
    event any of them ever triggers."""
    RefreshToken = apps.get_model("accounts", "RefreshToken")
    for token in RefreshToken.objects.filter(family_id="").iterator():
        RefreshToken.objects.filter(pk=token.pk).update(family_id=token.id)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_migrate_legacy_permanent_locks"),
    ]

    operations = [
        migrations.AddField(
            model_name="refreshtoken",
            name="consumed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="family_id",
            field=models.CharField(db_index=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="accounts.refreshtoken",
            ),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="reuse_detected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["family_id"], name="refresh_tok_family__6ba358_idx"
            ),
        ),
        migrations.RunPython(_backfill_family_id, migrations.RunPython.noop),
    ]
