# Generated by Django 5.2.16 on 2026-08-16 03:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_admin_also_field_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentaudit',
            name='assigner_role',
            field=models.CharField(choices=[('CCEO', 'CCEO'), ('Program Lead', 'Program Lead'), ('CountryDirector', 'CountryDirector'), ('RegionalVicePresident', 'RegionalVicePresident'), ('ImpactAssessment', 'ImpactAssessment'), ('Accountant', 'Accountant'), ('HumanResources', 'HumanResources'), ('ProjectCoordinator', 'ProjectCoordinator'), ('PartnerAdmin', 'PartnerAdmin'), ('PartnerFieldOfficer', 'PartnerFieldOfficer'), ('BusinessTransformationOfficer', 'BusinessTransformationOfficer'), ('MfiPartnerAdmin', 'MfiPartnerAdmin'), ('MfiLoanOfficer', 'MfiLoanOfficer'), ('Admin', 'Admin')], max_length=64),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('CCEO', 'CCEO'), ('Program Lead', 'Program Lead'), ('CountryDirector', 'CountryDirector'), ('RegionalVicePresident', 'RegionalVicePresident'), ('ImpactAssessment', 'ImpactAssessment'), ('Accountant', 'Accountant'), ('HumanResources', 'HumanResources'), ('ProjectCoordinator', 'ProjectCoordinator'), ('PartnerAdmin', 'PartnerAdmin'), ('PartnerFieldOfficer', 'PartnerFieldOfficer'), ('BusinessTransformationOfficer', 'BusinessTransformationOfficer'), ('MfiPartnerAdmin', 'MfiPartnerAdmin'), ('MfiLoanOfficer', 'MfiLoanOfficer'), ('Admin', 'Admin')], max_length=64),
        ),
        migrations.AlterField(
            model_name='staffsupportcapacity',
            name='set_by_role',
            field=models.CharField(choices=[('CCEO', 'CCEO'), ('Program Lead', 'Program Lead'), ('CountryDirector', 'CountryDirector'), ('RegionalVicePresident', 'RegionalVicePresident'), ('ImpactAssessment', 'ImpactAssessment'), ('Accountant', 'Accountant'), ('HumanResources', 'HumanResources'), ('ProjectCoordinator', 'ProjectCoordinator'), ('PartnerAdmin', 'PartnerAdmin'), ('PartnerFieldOfficer', 'PartnerFieldOfficer'), ('BusinessTransformationOfficer', 'BusinessTransformationOfficer'), ('MfiPartnerAdmin', 'MfiPartnerAdmin'), ('MfiLoanOfficer', 'MfiLoanOfficer'), ('Admin', 'Admin')], max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_role',
            field=models.CharField(choices=[('CCEO', 'CCEO'), ('Program Lead', 'Program Lead'), ('CountryDirector', 'CountryDirector'), ('RegionalVicePresident', 'RegionalVicePresident'), ('ImpactAssessment', 'ImpactAssessment'), ('Accountant', 'Accountant'), ('HumanResources', 'HumanResources'), ('ProjectCoordinator', 'ProjectCoordinator'), ('PartnerAdmin', 'PartnerAdmin'), ('PartnerFieldOfficer', 'PartnerFieldOfficer'), ('BusinessTransformationOfficer', 'BusinessTransformationOfficer'), ('MfiPartnerAdmin', 'MfiPartnerAdmin'), ('MfiLoanOfficer', 'MfiLoanOfficer'), ('Admin', 'Admin')], default='CCEO', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CCEO', 'CCEO'), ('Program Lead', 'Program Lead'), ('CountryDirector', 'CountryDirector'), ('RegionalVicePresident', 'RegionalVicePresident'), ('ImpactAssessment', 'ImpactAssessment'), ('Accountant', 'Accountant'), ('HumanResources', 'HumanResources'), ('ProjectCoordinator', 'ProjectCoordinator'), ('PartnerAdmin', 'PartnerAdmin'), ('PartnerFieldOfficer', 'PartnerFieldOfficer'), ('BusinessTransformationOfficer', 'BusinessTransformationOfficer'), ('MfiPartnerAdmin', 'MfiPartnerAdmin'), ('MfiLoanOfficer', 'MfiLoanOfficer'), ('Admin', 'Admin')], max_length=64), default=list, size=None),
        ),
    ]
