# Generated by Django 5.2.17 on 2026-08-20 19:18

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_alter_assignmentaudit_assigner_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.accounts.models.private_upload_storage,
                upload_to=apps.accounts.models.leave_attachment_name,
            ),
        ),
    ]
