# Generated by Django 5.2.17 on 2026-09-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_login_events_and_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mfachallenge",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("app", "Authenticator app"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mfa_channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("app", "Authenticator app"),
                ],
                default="email",
                max_length=16,
            ),
        ),
    ]
