# Generated by Django 5.2.17 on 2026-09-28 14:34

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0031_staffprofile_google_drive_folder_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="PresenceTime",
            fields=[
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("day", models.DateField()),
                ("section", models.CharField(max_length=64)),
                ("working_on", models.CharField(max_length=128)),
                ("seconds", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence_times",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "presence_time",
                "indexes": [
                    models.Index(fields=["day", "user"], name="presence_time_day_user")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "day", "section", "working_on"),
                        name="uniq_presence_time_slot",
                    )
                ],
            },
        ),
    ]
