# Generated by Django 5.2.17 on 2026-09-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0034_sign_in_minutes_belong_to_the_dashboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginevent",
            name="active_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loginevent",
            name="device",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="loginevent",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loginevent",
            name="last_active_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_seen_login_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
