# Generated by Django 5.2.17 on 2026-10-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0037_user_admin_is_never_cceo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="acting_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
