# Generated by Django 5.2.16 on 2026-08-16 03:39

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activities", "0040_alter_activity_est_cost_cents"),
        ("schools", "0020_dataqualityissue_condition_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanPurpose",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("is_edtech", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "bt_loan_purpose",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="MfiOrganization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual_upload", "Manual Upload"),
                            ("admin_created", "Admin Created"),
                            ("api_import", "API Import"),
                            ("local_test_upload", "Local Test Upload"),
                            ("production_upload", "Production Upload"),
                        ],
                        db_index=True,
                        default="manual_upload",
                        max_length=32,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                        ],
                        db_index=True,
                        default="production",
                        max_length=16,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("active", models.BooleanField(default=True)),
                ("data_sharing_agreement_active", models.BooleanField(default=False)),
                (
                    "onboarded_by",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("onboarded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "bt_mfi_organization",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BusinessTransformationPolicy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country_code", models.CharField(default="UG", max_length=2)),
                ("fy", models.CharField(db_index=True, max_length=16)),
                (
                    "financial_health_max_score",
                    models.DecimalField(decimal_places=2, default=5.5, max_digits=4),
                ),
                (
                    "government_requirements_max_score",
                    models.DecimalField(decimal_places=2, default=5.5, max_digits=4),
                ),
                (
                    "loan_use_verification_days",
                    models.PositiveSmallIntegerField(default=60),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.CharField(blank=True, default="system", max_length=30),
                ),
            ],
            options={
                "db_table": "bt_policy",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country_code", "fy"), name="uniq_bt_policy_country_fy"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("financial_health_max_score__gte", 0),
                            ("financial_health_max_score__lte", 10),
                            ("government_requirements_max_score__gte", 0),
                            ("government_requirements_max_score__lte", 10),
                        ),
                        name="bt_policy_ssa_thresholds_0_10",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceRequirement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country_code", models.CharField(default="UG", max_length=2)),
                ("code", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("evidence_description", models.TextField(blank=True, default="")),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "bt_compliance_requirement",
                "ordering": ["label"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country_code", "code"),
                        name="uniq_bt_compliance_country_code",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("country_code", "UG")),
                        name="bt_compliance_uganda_only",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FinanceReferral",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual_upload", "Manual Upload"),
                            ("admin_created", "Admin Created"),
                            ("api_import", "API Import"),
                            ("local_test_upload", "Local Test Upload"),
                            ("production_upload", "Production Upload"),
                        ],
                        db_index=True,
                        default="manual_upload",
                        max_length=32,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                        ],
                        db_index=True,
                        default="production",
                        max_length=16,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                ("intended_use", models.TextField()),
                ("consent_recorded_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Received by MFI"),
                            ("under_assessment", "Under assessment"),
                            ("more_information", "Additional information required"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("referred_by", models.CharField(max_length=30)),
                ("referred_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mfi_decided_by",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("mfi_decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True, default="")),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="business_transformation.loanpurpose",
                    ),
                ),
                (
                    "mfi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="business_transformation.mfiorganization",
                    ),
                ),
            ],
            options={
                "db_table": "bt_finance_referral",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanVerificationRequirement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("needs_scheduling", "Needs scheduling"),
                            ("scheduled", "Scheduled"),
                            ("awaiting_verification", "Awaiting IA verification"),
                            ("verified", "Verified"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="needs_scheduling",
                        max_length=24,
                    ),
                ),
                ("assigned_by", models.CharField(blank=True, max_length=30, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activity",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_verification_requirement",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "bt_loan_verification_requirement",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="LoanUseResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "finding",
                    models.CharField(
                        choices=[
                            ("fully_approved", "Used fully as approved"),
                            ("partly_approved", "Used partly as approved"),
                            ("delayed", "Use delayed"),
                            ("purpose_changed", "Purpose changed with MFI approval"),
                            ("possible_diversion", "Possible diversion"),
                            ("asset_not_delivered", "Asset not yet delivered"),
                            (
                                "asset_not_operational",
                                "Asset delivered but not operational",
                            ),
                            ("insufficient_evidence", "Insufficient evidence"),
                            ("not_completed", "Verification could not be completed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "edtech_asset_operational",
                    models.BooleanField(blank=True, null=True),
                ),
                ("recorded_by", models.CharField(max_length=30)),
                (
                    "verification_status",
                    models.CharField(default="provisional", max_length=16),
                ),
                ("ia_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requirement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result",
                        to="business_transformation.loanverificationrequirement",
                    ),
                ),
            ],
            options={
                "db_table": "bt_loan_use_result",
            },
        ),
        migrations.CreateModel(
            name="MfiLoan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual_upload", "Manual Upload"),
                            ("admin_created", "Admin Created"),
                            ("api_import", "API Import"),
                            ("local_test_upload", "Local Test Upload"),
                            ("production_upload", "Production Upload"),
                        ],
                        db_index=True,
                        default="manual_upload",
                        max_length=32,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                        ],
                        db_index=True,
                        default="production",
                        max_length=16,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_loan_reference", models.CharField(max_length=128)),
                (
                    "assigned_officer_reference",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "disbursed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("disbursement_date", models.DateField(blank=True, null=True)),
                (
                    "disbursement_confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "term_months",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "repayment_frequency",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("maturity_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("approved", "Approved"),
                            ("disbursed", "Disbursed"),
                            ("active", "Active"),
                            ("arrears", "In arrears"),
                            ("restructured", "Restructured"),
                            ("repaid", "Repaid"),
                            ("defaulted", "Defaulted"),
                            ("written_off", "Written off"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("registered_by", models.CharField(max_length=30)),
                ("last_repayment_data_date", models.DateField(blank=True, null=True)),
                ("certified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="business_transformation.loanpurpose",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="business_transformation.financereferral",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mfi_loans",
                        to="schools.school",
                    ),
                ),
                (
                    "mfi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="business_transformation.mfiorganization",
                    ),
                ),
            ],
            options={
                "db_table": "bt_mfi_loan",
                "ordering": ["-disbursement_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="loanverificationrequirement",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verification_requirements",
                to="business_transformation.mfiloan",
            ),
        ),
        migrations.CreateModel(
            name="LoanAmendment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField()),
                ("previous_values", models.JSONField()),
                ("new_values", models.JSONField()),
                ("requested_by", models.CharField(max_length=30)),
                ("approved_by", models.CharField(blank=True, max_length=30, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="requested", max_length=16)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amendments",
                        to="business_transformation.mfiloan",
                    ),
                ),
            ],
            options={
                "db_table": "bt_loan_amendment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MfiMembership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "MFI Partner Administrator"),
                            ("loan_officer", "MFI Loan Officer"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "officer_reference",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfi_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mfi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="business_transformation.mfiorganization",
                    ),
                ),
            ],
            options={
                "db_table": "bt_mfi_membership",
            },
        ),
        migrations.CreateModel(
            name="PortfolioSubmission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reporting_month", models.DateField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("spreadsheet", "Spreadsheet"),
                            ("api", "API"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source_file_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "file_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("staged", "Staged"),
                            ("needs_correction", "Needs correction"),
                            ("imported", "Imported"),
                            ("certified", "Certified"),
                        ],
                        default="staged",
                        max_length=24,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("exception_rows", models.PositiveIntegerField(default=0)),
                ("submitted_by", models.CharField(max_length=30)),
                (
                    "certified_by",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("certified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mfi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_submissions",
                        to="business_transformation.mfiorganization",
                    ),
                ),
            ],
            options={
                "db_table": "bt_portfolio_submission",
                "ordering": ["-reporting_month", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioDataException",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row_number", models.PositiveIntegerField(blank=True, null=True)),
                ("code", models.CharField(max_length=64)),
                ("message", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="open", max_length=16)),
                ("resolved_by", models.CharField(blank=True, max_length=30, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="business_transformation.portfoliosubmission",
                    ),
                ),
            ],
            options={
                "db_table": "bt_portfolio_data_exception",
            },
        ),
        migrations.CreateModel(
            name="RepaymentSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("as_of_date", models.DateField()),
                (
                    "principal_repaid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "amount_currently_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "amount_overdue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("days_in_arrears", models.PositiveIntegerField(default=0)),
                ("next_payment_date", models.DateField(blank=True, null=True)),
                ("last_payment_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("watch", "Watch"),
                            ("arrears_1_30", "1-30 days in arrears"),
                            ("par_30", "Portfolio at risk 30+"),
                            ("par_90", "Portfolio at risk 90+"),
                            ("restructured", "Restructured"),
                            ("repaid", "Repaid"),
                            ("defaulted", "Defaulted"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "restructuring_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("submitted_by", models.CharField(max_length=30)),
                ("certified", models.BooleanField(default=False)),
                ("certified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repayment_snapshots",
                        to="business_transformation.mfiloan",
                    ),
                ),
            ],
            options={
                "db_table": "bt_repayment_snapshot",
                "ordering": ["-as_of_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransformationCase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual_upload", "Manual Upload"),
                            ("admin_created", "Admin Created"),
                            ("api_import", "API Import"),
                            ("local_test_upload", "Local Test Upload"),
                            ("production_upload", "Production Upload"),
                        ],
                        db_index=True,
                        default="manual_upload",
                        max_length=32,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                        ],
                        db_index=True,
                        default="production",
                        max_length=16,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recommended", "Recommended"),
                            ("triage", "In triage"),
                            ("active", "Active"),
                            ("monitoring", "Monitoring"),
                            ("deferred", "Deferred"),
                            ("closed", "Closed"),
                        ],
                        default="recommended",
                        max_length=20,
                    ),
                ),
                (
                    "owner_staff_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("opened_fy", models.CharField(db_index=True, max_length=16)),
                (
                    "triage_decision",
                    models.CharField(blank=True, default="", max_length=48),
                ),
                ("triage_reason", models.TextField(blank=True, default="")),
                ("triaged_by", models.CharField(blank=True, max_length=30, null=True)),
                ("triaged_at", models.DateTimeField(blank=True, null=True)),
                ("deferred_until", models.DateField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closure_reason", models.TextField(blank=True, default="")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_transformation_cases",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "bt_case",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mfiloan",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loans",
                to="business_transformation.transformationcase",
            ),
        ),
        migrations.AddField(
            model_name="financereferral",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referrals",
                to="business_transformation.transformationcase",
            ),
        ),
        migrations.CreateModel(
            name="CaseTrigger",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("verified_ssa", "Verified SSA"),
                            ("school_request", "School request"),
                            ("staff_referral", "Staff referral"),
                            ("mfi_loan_import", "MFI loan import"),
                            ("campaign", "Campaign"),
                            ("country_priority", "Uganda priority"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_id", models.CharField(max_length=64)),
                ("source_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "triggered_by",
                    models.CharField(blank=True, default="system", max_length=30),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="business_transformation.transformationcase",
                    ),
                ),
            ],
            options={
                "db_table": "bt_case_trigger",
            },
        ),
        migrations.CreateModel(
            name="CaseRecommendation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("financial_health_training", "Financial Health training"),
                            ("accountant_training", "School accountant training"),
                            ("compliance_support", "Government requirements support"),
                            ("loan_readiness", "Loan readiness assessment"),
                            ("loan_referral", "MFI referral"),
                            ("loan_use_verification", "Loan-use verification"),
                            ("loan_impact_assessment", "Loan impact assessment"),
                            ("follow_up_mentorship", "Follow-up mentorship"),
                            ("further_assessment", "Further assessment"),
                            ("no_immediate_intervention", "No immediate intervention"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("accepted", "Accepted"),
                            ("changed", "Changed"),
                            ("deferred", "Deferred"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "source_intervention",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "source_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("decided_by", models.CharField(blank=True, max_length=30, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "trigger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="business_transformation.casetrigger",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="business_transformation.transformationcase",
                    ),
                ),
            ],
            options={
                "db_table": "bt_case_recommendation",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="BusinessTransformationActivityLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("financial_health_training", "Financial Health training"),
                            ("accountant_training", "School accountant training"),
                            ("compliance_support", "Government requirements support"),
                            ("loan_readiness", "Loan readiness assessment"),
                            ("loan_referral", "MFI referral"),
                            ("loan_use_verification", "Loan-use verification"),
                            ("loan_impact_assessment", "Loan impact assessment"),
                            ("follow_up_mentorship", "Follow-up mentorship"),
                            ("further_assessment", "Further assessment"),
                            ("no_immediate_intervention", "No immediate intervention"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_transformation_link",
                        to="activities.activity",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_links",
                        to="business_transformation.mfiloan",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_links",
                        to="business_transformation.transformationcase",
                    ),
                ),
            ],
            options={
                "db_table": "bt_activity_link",
            },
        ),
        migrations.AddConstraint(
            model_name="loanverificationrequirement",
            constraint=models.UniqueConstraint(
                fields=("loan",), name="uniq_bt_initial_verification_per_loan"
            ),
        ),
        migrations.AddConstraint(
            model_name="mfimembership",
            constraint=models.UniqueConstraint(
                fields=("mfi", "user"), name="uniq_bt_mfi_user_membership"
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliosubmission",
            constraint=models.UniqueConstraint(
                fields=("mfi", "reporting_month", "file_sha256"),
                name="uniq_bt_portfolio_submission_file",
            ),
        ),
        migrations.AddIndex(
            model_name="portfoliodataexception",
            index=models.Index(
                fields=["submission", "status"], name="bt_portfoli_submiss_a31f64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repaymentsnapshot",
            index=models.Index(
                fields=["loan", "as_of_date"], name="bt_repaymen_loan_id_00465b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repaymentsnapshot",
            index=models.Index(
                fields=["status", "as_of_date"], name="bt_repaymen_status_31f713_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="repaymentsnapshot",
            constraint=models.UniqueConstraint(
                fields=("loan", "as_of_date"), name="uniq_bt_loan_repayment_as_of"
            ),
        ),
        migrations.AddConstraint(
            model_name="repaymentsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("principal_repaid__gte", 0),
                    ("outstanding_amount__gte", 0),
                    ("amount_currently_due__gte", 0),
                    ("amount_overdue__gte", 0),
                ),
                name="bt_repayment_amounts_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="transformationcase",
            index=models.Index(
                fields=["status", "opened_fy"], name="bt_case_status_777091_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transformationcase",
            index=models.Index(
                fields=["owner_staff_id", "status"], name="bt_case_owner_s_f31901_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transformationcase",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    (
                        "status__in",
                        ("recommended", "triage", "active", "monitoring", "deferred"),
                    ),
                ),
                fields=("school",),
                name="uniq_open_bt_case_per_school",
            ),
        ),
        migrations.AddIndex(
            model_name="mfiloan",
            index=models.Index(
                fields=["mfi", "status"], name="bt_mfi_loan_mfi_id_8195ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mfiloan",
            index=models.Index(
                fields=["school", "status"], name="bt_mfi_loan_school__bae88b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mfiloan",
            index=models.Index(
                fields=["disbursement_date"], name="bt_mfi_loan_disburs_94f6f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mfiloan",
            index=models.Index(
                fields=["last_repayment_data_date"],
                name="bt_mfi_loan_last_re_a6deb4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="mfiloan",
            constraint=models.UniqueConstraint(
                fields=("mfi", "external_loan_reference"),
                name="uniq_bt_mfi_external_loan_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="mfiloan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_amount__isnull", True),
                    ("approved_amount__gt", 0),
                    _connector="OR",
                ),
                name="bt_loan_approved_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="mfiloan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("disbursed_amount__isnull", True),
                    ("disbursed_amount__gt", 0),
                    _connector="OR",
                ),
                name="bt_loan_disbursed_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="mfiloan",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency", "UGX")), name="bt_loan_uganda_currency"
            ),
        ),
        migrations.AddConstraint(
            model_name="mfiloan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "status__in",
                            (
                                "disbursed",
                                "active",
                                "arrears",
                                "restructured",
                                "repaid",
                                "defaulted",
                                "written_off",
                            ),
                        ),
                        _negated=True,
                    ),
                    models.Q(
                        ("disbursed_amount__isnull", False),
                        ("disbursement_date__isnull", False),
                        ("disbursement_confirmed_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="bt_disbursed_loan_has_confirmation",
            ),
        ),
        migrations.AddIndex(
            model_name="financereferral",
            index=models.Index(
                fields=["mfi", "status"], name="bt_finance__mfi_id_12f204_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="financereferral",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("requested_amount__isnull", True),
                    ("requested_amount__gt", 0),
                    _connector="OR",
                ),
                name="bt_referral_requested_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="financereferral",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency", "UGX")),
                name="bt_referral_uganda_currency",
            ),
        ),
        migrations.AddConstraint(
            model_name="casetrigger",
            constraint=models.UniqueConstraint(
                fields=("trigger_type", "source_id"), name="uniq_bt_trigger_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="caserecommendation",
            constraint=models.UniqueConstraint(
                fields=("trigger", "kind"), name="uniq_bt_recommendation_trigger_kind"
            ),
        ),
    ]
