# Generated by Django 5.2.16 on 2026-08-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_transformation', '0004_mfiloan_salesforce_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfiloan',
            name='salesforce_loan_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
