# Generated by Django 5.2.16 on 2026-08-16 07:41

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


def migrate_independent_status_dimensions(apps, schema_editor):
    Loan = apps.get_model("business_transformation", "MfiLoan")
    Snapshot = apps.get_model("business_transformation", "RepaymentSnapshot")
    History = apps.get_model("business_transformation", "LoanStatusHistory")
    Requirement = apps.get_model("business_transformation", "ComplianceRequirement")

    lifecycle_map = {
        "registered": "processing",
        "approved": "processing",
        "arrears": "active",
        "restructured": "active",
        "written_off": "defaulted",
        "cancelled": "canceled",
    }
    for loan in Loan.objects.all().iterator():
        original = loan.status
        loan.status = lifecycle_map.get(original, original)
        loan.salesforce_status = "confirmed" if loan.salesforce_loan_id else "pending"
        loan.salesforce_entry_date = (
            loan.salesforce_confirmed_at.date() if loan.salesforce_confirmed_at else None
        )
        loan.submitted_by = loan.registered_by
        loan.submitted_at = loan.created_at
        loan.save(
            update_fields=[
                "status",
                "salesforce_status",
                "salesforce_entry_date",
                "submitted_by",
                "submitted_at",
            ]
        )
        History.objects.create(
            loan=loan,
            dimension="lifecycle",
            previous_value=original if original != loan.status else "",
            new_value=loan.status,
            reason="Backfilled from the governed loan ledger",
            changed_by=loan.registered_by or "system",
            effective_at=loan.updated_at,
        )
        History.objects.create(
            loan=loan,
            dimension="salesforce",
            previous_value="",
            new_value=loan.salesforce_status,
            reason="Backfilled from Salesforce Loan ID presence",
            changed_by=loan.salesforce_confirmed_by or "system",
            effective_at=loan.salesforce_confirmed_at or loan.updated_at,
        )

    repayment_map = {
        "watch": "due_soon",
        "arrears_1_30": "overdue_1_30",
        "par_30": "overdue_31_90",
        "par_90": "overdue_90_plus",
        "repaid": "current",
        "defaulted": "overdue_90_plus",
    }
    for snapshot in Snapshot.objects.all().iterator():
        snapshot.status = repayment_map.get(snapshot.status, snapshot.status)
        snapshot.reporting_month = snapshot.as_of_date.replace(day=1)
        snapshot.amount_due_during_period = snapshot.amount_currently_due
        snapshot.save(
            update_fields=[
                "status",
                "reporting_month",
                "amount_due_during_period",
            ]
        )

    configuration = {
        "SCHOOL_REGISTRATION": (
            "Ministry of Education and Sports",
            12,
        ),
        "URA_TAX": ("Uganda Revenue Authority", None),
        "NSSF": ("National Social Security Fund", None),
    }
    for code, (authority, renewal_months) in configuration.items():
        Requirement.objects.filter(country_code="UG", code=code).update(
            responsible_authority=authority,
            renewal_months=renewal_months,
        )


def reverse_independent_status_dimensions(apps, schema_editor):
    Loan = apps.get_model("business_transformation", "MfiLoan")
    Snapshot = apps.get_model("business_transformation", "RepaymentSnapshot")
    lifecycle_map = {
        "processing": "registered",
        "canceled": "cancelled",
    }
    repayment_map = {
        "due_soon": "watch",
        "overdue_1_30": "arrears_1_30",
        "overdue_31_90": "par_30",
        "overdue_90_plus": "par_90",
        "unknown": "watch",
        "not_started": "current",
    }
    for loan in Loan.objects.all().iterator():
        loan.status = lifecycle_map.get(loan.status, loan.status)
        loan.save(update_fields=["status"])
    for snapshot in Snapshot.objects.all().iterator():
        snapshot.status = repayment_map.get(snapshot.status, snapshot.status)
        snapshot.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ('business_transformation', '0005_alter_mfiloan_salesforce_loan_id'),
        ('schools', '0020_dataqualityissue_condition_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPracticeAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('assessed_on', models.DateField()),
                ('practices', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_by', models.CharField(max_length=30)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('returned', 'Returned')], default='pending', max_length=16)),
                ('verified_by', models.CharField(blank=True, max_length=30, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bt_financial_practice_assessment',
                'ordering': ['-assessed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanImpactAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('baseline_indicators', models.JSONField(blank=True, default=dict)),
                ('follow_up_indicators', models.JSONField(blank=True, default=dict)),
                ('classification', models.CharField(choices=[('not_due', 'Not Due'), ('baseline_required', 'Baseline Required'), ('due', 'Due'), ('under_review', 'Under Review'), ('strong_positive', 'Strong Positive Impact'), ('positive', 'Positive Impact'), ('early_progress', 'Early Progress'), ('mixed', 'Mixed Impact'), ('no_change', 'No Measurable Change'), ('negative', 'Negative Impact'), ('insufficient_evidence', 'Insufficient Evidence')], default='not_due', max_length=32)),
                ('narrative', models.TextField(blank=True, default='')),
                ('prepared_by', models.CharField(blank=True, max_length=30, null=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('ia_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('returned', 'Returned')], default='pending', max_length=16)),
                ('ia_verified_by', models.CharField(blank=True, max_length=30, null=True)),
                ('ia_verified_at', models.DateTimeField(blank=True, null=True)),
                ('ia_note', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'bt_loan_impact_assessment',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('lifecycle', 'Loan lifecycle'), ('salesforce', 'Salesforce confirmation'), ('ia_validation', 'IA validation'), ('repayment', 'Repayment health'), ('impact', 'Loan impact')], max_length=24)),
                ('previous_value', models.CharField(blank=True, default='', max_length=64)),
                ('new_value', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('changed_by', models.CharField(max_length=30)),
                ('effective_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'bt_loan_status_history',
                'ordering': ['-effective_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolComplianceAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_assessed', 'Not Assessed'), ('unknown', 'Unknown'), ('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('compliant', 'Compliant'), ('action_required', 'Action Required'), ('expired', 'Expired'), ('exempt', 'Exempt/Not Applicable'), ('under_review', 'Under Review')], default='not_assessed', max_length=24)),
                ('registration_number', models.CharField(blank=True, default='', max_length=128)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('evidence_reference', models.CharField(blank=True, default='', max_length=255)),
                ('follow_up_action', models.TextField(blank=True, default='')),
                ('responsible_person', models.CharField(blank=True, default='', max_length=255)),
                ('assessed_by', models.CharField(max_length=30)),
                ('assessed_at', models.DateTimeField()),
                ('ia_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('returned', 'Returned')], default='pending', max_length=16)),
                ('ia_verified_by', models.CharField(blank=True, max_length=30, null=True)),
                ('ia_verified_at', models.DateTimeField(blank=True, null=True)),
                ('ia_note', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'bt_school_compliance_assessment',
                'ordering': ['requirement__label', '-assessed_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='mfiloan',
            name='bt_disbursed_loan_has_confirmation',
        ),
        migrations.RemoveConstraint(
            model_name='repaymentsnapshot',
            name='uniq_bt_loan_repayment_as_of',
        ),
        migrations.RemoveConstraint(
            model_name='repaymentsnapshot',
            name='bt_repayment_amounts_nonnegative',
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='applicability_rule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='renewal_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='responsible_authority',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='school_type',
            field=models.CharField(blank=True, default='all', max_length=64),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='default_classified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='ia_return_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='ia_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='ia_validated_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='ia_validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('returned', 'Returned')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='impact_status',
            field=models.CharField(choices=[('not_due', 'Not Due'), ('baseline_required', 'Baseline Required'), ('due', 'Due'), ('under_review', 'Under Review'), ('strong_positive', 'Strong Positive Impact'), ('positive', 'Positive Impact'), ('early_progress', 'Early Progress'), ('mixed', 'Mixed Impact'), ('no_change', 'No Measurable Change'), ('negative', 'Negative Impact'), ('insufficient_evidence', 'Insufficient Evidence')], db_index=True, default='not_due', max_length=32),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='processing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='requested_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='salesforce_confirmation_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='salesforce_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='salesforce_return_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='salesforce_return_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='salesforce_returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='salesforce_returned_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='salesforce_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('returned', 'Returned')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mfiloan',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='repaymentsnapshot',
            name='amount_due_during_period',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='repaymentsnapshot',
            name='amount_paid_during_period',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='repaymentsnapshot',
            name='reporting_month',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mfiloan',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('repaid', 'Repaid'), ('defaulted', 'Defaulted'), ('canceled', 'Canceled')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='repaymentsnapshot',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('current', 'Current'), ('due_soon', 'Due Soon'), ('overdue_1_30', 'Overdue 1–30'), ('overdue_31_90', 'Overdue 31–90'), ('overdue_90_plus', 'Overdue 90+'), ('restructured', 'Restructured'), ('unknown', 'Unknown')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='mfiloan',
            constraint=models.CheckConstraint(condition=models.Q(('requested_amount__isnull', True), ('requested_amount__gt', 0), _connector='OR'), name='bt_loan_requested_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='mfiloan',
            constraint=models.CheckConstraint(condition=models.Q(('installment_amount__isnull', True), ('installment_amount__gt', 0), _connector='OR'), name='bt_loan_installment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='mfiloan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('disbursed', 'active', 'repaid', 'defaulted')), _negated=True), models.Q(('disbursed_amount__isnull', False), ('disbursement_date__isnull', False), ('disbursement_confirmed_at__isnull', False)), _connector='OR'), name='bt_disbursed_loan_has_confirmation'),
        ),
        migrations.AddField(
            model_name='financialpracticeassessment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_practice_assessments', to='business_transformation.transformationcase'),
        ),
        migrations.AddField(
            model_name='loanimpactassessment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impact_assessments', to='business_transformation.mfiloan'),
        ),
        migrations.AddField(
            model_name='loanstatushistory',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='business_transformation.mfiloan'),
        ),
        migrations.AddField(
            model_name='schoolcomplianceassessment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_assessments', to='business_transformation.transformationcase'),
        ),
        migrations.AddField(
            model_name='schoolcomplianceassessment',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_assessments', to='business_transformation.compliancerequirement'),
        ),
        migrations.RunPython(
            migrate_independent_status_dimensions,
            reverse_independent_status_dimensions,
        ),
        migrations.AddConstraint(
            model_name='financialpracticeassessment',
            constraint=models.UniqueConstraint(fields=('case', 'assessed_on'), name='uniq_bt_financial_practice_case_date'),
        ),
        migrations.AddConstraint(
            model_name='loanimpactassessment',
            constraint=models.UniqueConstraint(fields=('loan', 'due_date'), name='uniq_bt_loan_impact_due_date'),
        ),
        migrations.AddIndex(
            model_name='loanstatushistory',
            index=models.Index(fields=['loan', 'dimension', 'effective_at'], name='bt_loan_sta_loan_id_038dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='loanstatushistory',
            index=models.Index(fields=['dimension', 'new_value', 'effective_at'], name='bt_loan_sta_dimensi_487f88_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolcomplianceassessment',
            constraint=models.UniqueConstraint(fields=('case', 'requirement'), name='uniq_bt_school_compliance_requirement'),
        ),
    ]
