# Generated by Django 5.2.17 on 2026-08-20 17:03

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "business_transformation",
            "0008_repaymentsnapshot_uniq_bt_loan_repayment_as_of_and_more",
        ),
        ("schools", "0020_dataqualityissue_condition_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingFacility",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_reference", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                (
                    "country_code",
                    models.CharField(db_index=True, default="UG", max_length=2),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                (
                    "commitment_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("revolving", models.BooleanField(default=False)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "agreement_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_by", models.CharField(max_length=30)),
                ("approved_by", models.CharField(blank=True, max_length=30, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "bt_funding_facility",
                "ordering": ["-starts_on", "name"],
            },
        ),
        migrations.CreateModel(
            name="FundingFacilityAllocation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("consumed", "Consumed"),
                            ("released", "Released"),
                        ],
                        db_index=True,
                        default="reserved",
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("reserved_by", models.CharField(max_length=30)),
                ("reserved_at", models.DateTimeField()),
                ("released_by", models.CharField(blank=True, max_length=30, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("release_reason", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "bt_funding_facility_allocation",
            },
        ),
        migrations.CreateModel(
            name="FundingFacilityTranche",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_reference", models.CharField(max_length=128)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("received_on", models.DateField(db_index=True)),
                ("value_date", models.DateField()),
                ("evidence_reference", models.CharField(max_length=255)),
                ("confirmed_by", models.CharField(max_length=30)),
                ("confirmed_at", models.DateTimeField()),
            ],
            options={
                "db_table": "bt_funding_facility_tranche",
                "ordering": ["value_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="FundingFacilityTrancheReversal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("reason", models.TextField()),
                ("reversed_by", models.CharField(max_length=30)),
                ("reversed_at", models.DateTimeField()),
            ],
            options={
                "db_table": "bt_funding_facility_tranche_reversal",
            },
        ),
        migrations.CreateModel(
            name="LoanDisbursement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                ("external_reference", models.CharField(max_length=128)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("disbursed_on", models.DateField(db_index=True)),
                ("value_date", models.DateField()),
                ("bank_reference", models.CharField(max_length=255)),
                ("confirmed_by", models.CharField(max_length=30)),
                ("confirmed_at", models.DateTimeField()),
            ],
            options={
                "db_table": "bt_loan_disbursement",
                "ordering": ["loan", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="LoanDisbursementReversal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("reason", models.TextField()),
                ("reversed_by", models.CharField(max_length=30)),
                ("reversed_at", models.DateTimeField()),
            ],
            options={
                "db_table": "bt_loan_disbursement_reversal",
            },
        ),
        migrations.CreateModel(
            name="LoanRepaymentInstallment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("schedule_version", models.PositiveSmallIntegerField(default=1)),
                ("installment_number", models.PositiveIntegerField()),
                ("due_date", models.DateField(db_index=True)),
                ("principal_due", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "interest_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "fee_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("created_by", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "bt_loan_repayment_installment",
                "ordering": ["loan", "schedule_version", "installment_number"],
            },
        ),
        migrations.CreateModel(
            name="RepaymentAllocation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("principal", "Principal"),
                            ("interest", "Interest"),
                            ("fee", "Fee"),
                            ("penalty", "Penalty"),
                        ],
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                "db_table": "bt_repayment_allocation",
            },
        ),
        migrations.CreateModel(
            name="RepaymentTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("payment", "Payment"), ("reversal", "Reversal")],
                        default="payment",
                        max_length=12,
                    ),
                ),
                ("external_reference", models.CharField(max_length=128)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("received_on", models.DateField(db_index=True)),
                ("value_date", models.DateField()),
                ("evidence_reference", models.CharField(max_length=255)),
                ("posted_by", models.CharField(max_length=30)),
                ("posted_at", models.DateTimeField()),
                ("reason", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "bt_repayment_transaction",
                "ordering": ["value_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolLoan",
            fields=[],
            options={
                "verbose_name": "School loan",
                "verbose_name_plural": "School loans",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("business_transformation.mfiloan",),
        ),
        migrations.RemoveConstraint(
            model_name="financereferral",
            name="bt_referral_uganda_currency",
        ),
        migrations.RemoveConstraint(
            model_name="mfiloan",
            name="bt_loan_uganda_currency",
        ),
        migrations.AddField(
            model_name="mfiorganization",
            name="country_code",
            field=models.CharField(db_index=True, default="UG", max_length=2),
        ),
        migrations.AddField(
            model_name="fundingfacility",
            name="mfi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="funding_facilities",
                to="business_transformation.mfiorganization",
            ),
        ),
        migrations.AddField(
            model_name="mfiloan",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loans",
                to="business_transformation.fundingfacility",
            ),
        ),
        migrations.AddIndex(
            model_name="mfiloan",
            index=models.Index(
                fields=["facility", "status"], name="bt_mfi_loan_facilit_b244a0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mfiloan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_amount__isnull", True),
                    ("disbursed_amount__isnull", True),
                    ("approved_amount__gte", models.F("disbursed_amount")),
                    _connector="OR",
                ),
                name="bt_loan_approved_covers_legacy_disbursed",
            ),
        ),
        migrations.AddField(
            model_name="fundingfacilityallocation",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="business_transformation.fundingfacility",
            ),
        ),
        migrations.AddField(
            model_name="fundingfacilityallocation",
            name="loan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="facility_allocation",
                to="business_transformation.mfiloan",
            ),
        ),
        migrations.AddField(
            model_name="fundingfacilitytranche",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tranches",
                to="business_transformation.fundingfacility",
            ),
        ),
        migrations.AddField(
            model_name="fundingfacilitytranchereversal",
            name="tranche",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal",
                to="business_transformation.fundingfacilitytranche",
            ),
        ),
        migrations.AddField(
            model_name="loandisbursement",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="disbursements",
                to="business_transformation.fundingfacilityallocation",
            ),
        ),
        migrations.AddField(
            model_name="loandisbursement",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="disbursements",
                to="business_transformation.mfiloan",
            ),
        ),
        migrations.AddField(
            model_name="loandisbursementreversal",
            name="disbursement",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal",
                to="business_transformation.loandisbursement",
            ),
        ),
        migrations.AddField(
            model_name="loanrepaymentinstallment",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repayment_installments",
                to="business_transformation.mfiloan",
            ),
        ),
        migrations.AddField(
            model_name="repaymentallocation",
            name="installment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_allocations",
                to="business_transformation.loanrepaymentinstallment",
            ),
        ),
        migrations.AddField(
            model_name="repaymenttransaction",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repayment_transactions",
                to="business_transformation.mfiloan",
            ),
        ),
        migrations.AddField(
            model_name="repaymenttransaction",
            name="reversal_of",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal_entry",
                to="business_transformation.repaymenttransaction",
            ),
        ),
        migrations.AddField(
            model_name="repaymentallocation",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="business_transformation.repaymenttransaction",
            ),
        ),
        migrations.AddIndex(
            model_name="fundingfacility",
            index=models.Index(
                fields=["mfi", "status"], name="bt_funding__mfi_id_5654ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fundingfacility",
            index=models.Index(
                fields=["country_code", "currency", "status"],
                name="bt_funding__country_af98c5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundingfacility",
            constraint=models.UniqueConstraint(
                fields=("mfi", "external_reference"),
                name="uniq_bt_facility_mfi_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundingfacility",
            constraint=models.CheckConstraint(
                condition=models.Q(("commitment_amount__gt", 0)),
                name="bt_facility_commitment_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundingfacility",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_on__isnull", True),
                    ("ends_on__gte", models.F("starts_on")),
                    _connector="OR",
                ),
                name="bt_facility_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundingfacility",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["approved", "active", "suspended", "closed"]),
                        _negated=True,
                    ),
                    models.Q(
                        ("approved_by__isnull", False), ("approved_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="bt_facility_approved_state_has_actor",
            ),
        ),
        migrations.AddIndex(
            model_name="fundingfacilityallocation",
            index=models.Index(
                fields=["facility", "status"], name="bt_funding__facilit_f0f177_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fundingfacilityallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="bt_facility_allocation_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundingfacilityallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "released"), _negated=True),
                    models.Q(
                        ("released_by__isnull", False),
                        ("released_at__isnull", False),
                        models.Q(("release_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="bt_released_allocation_has_reason",
            ),
        ),
        migrations.AddIndex(
            model_name="fundingfacilitytranche",
            index=models.Index(
                fields=["facility", "value_date"], name="bt_funding__facilit_719254_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fundingfacilitytranche",
            constraint=models.UniqueConstraint(
                fields=("facility", "external_reference"),
                name="uniq_bt_facility_tranche_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundingfacilitytranche",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="bt_facility_tranche_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="loandisbursement",
            index=models.Index(
                fields=["loan", "value_date"], name="bt_loan_dis_loan_id_539134_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loandisbursement",
            index=models.Index(
                fields=["allocation", "value_date"],
                name="bt_loan_dis_allocat_f5867f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="loandisbursement",
            constraint=models.UniqueConstraint(
                fields=("loan", "sequence"), name="uniq_bt_loan_disbursement_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="loandisbursement",
            constraint=models.UniqueConstraint(
                fields=("allocation", "external_reference"),
                name="uniq_bt_allocation_disbursement_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="loandisbursement",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="bt_loan_disbursement_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="loanrepaymentinstallment",
            index=models.Index(
                fields=["loan", "schedule_version", "due_date"],
                name="bt_loan_rep_loan_id_832c18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loanrepaymentinstallment",
            index=models.Index(
                fields=["due_date"], name="bt_loan_rep_due_dat_8a0a68_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="loanrepaymentinstallment",
            constraint=models.UniqueConstraint(
                fields=("loan", "schedule_version", "installment_number"),
                name="uniq_bt_installment_version_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanrepaymentinstallment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("principal_due__gte", 0),
                    ("interest_due__gte", 0),
                    ("fee_due__gte", 0),
                    models.Q(
                        ("principal_due__gt", 0),
                        ("interest_due__gt", 0),
                        ("fee_due__gt", 0),
                        _connector="OR",
                    ),
                ),
                name="bt_installment_has_positive_due",
            ),
        ),
        migrations.AddIndex(
            model_name="repaymenttransaction",
            index=models.Index(
                fields=["loan", "value_date"], name="bt_repaymen_loan_id_84667a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repaymenttransaction",
            index=models.Index(
                fields=["loan", "kind", "received_on"],
                name="bt_repaymen_loan_id_fb1d51_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="repaymenttransaction",
            constraint=models.UniqueConstraint(
                fields=("loan", "external_reference"),
                name="uniq_bt_repayment_loan_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="repaymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="bt_repayment_transaction_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="repaymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "payment"), ("reversal_of__isnull", True)),
                    models.Q(
                        ("kind", "reversal"),
                        ("reversal_of__isnull", False),
                        models.Q(("reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="bt_repayment_reversal_shape",
            ),
        ),
        migrations.AddIndex(
            model_name="repaymentallocation",
            index=models.Index(
                fields=["transaction", "component"],
                name="bt_repaymen_transac_1d0617_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="repaymentallocation",
            index=models.Index(
                fields=["installment", "component"],
                name="bt_repaymen_install_9fa511_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="repaymentallocation",
            constraint=models.UniqueConstraint(
                fields=("transaction", "installment", "component"),
                name="uniq_bt_repayment_allocation_component",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="repaymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="bt_repayment_allocation_positive",
            ),
        ),
    ]
