# Generated by Django 5.2.17 on 2026-08-20 17:25

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_transformation", "0009_lending_financial_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanUseVerification",
            fields=[],
            options={
                "verbose_name": "Loan-use verification",
                "verbose_name_plural": "Loan-use verifications",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("business_transformation.loanverificationrequirement",),
        ),
        migrations.CreateModel(
            name="LoanPurposeAllocation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "planned_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "reported_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "verified_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("intended_output", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("reported", "Reported"),
                            ("verified", "Verified"),
                            ("returned", "Returned"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("recorded_by", models.CharField(max_length=30)),
                ("verified_by", models.CharField(blank=True, max_length=30, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_note", models.TextField(blank=True, default="")),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purpose_allocations",
                        to="business_transformation.mfiloan",
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_allocations",
                        to="business_transformation.loanpurpose",
                    ),
                ),
            ],
            options={
                "db_table": "bt_loan_purpose_allocation",
            },
        ),
        migrations.CreateModel(
            name="LoanPurposeProposal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("proposed_code", models.CharField(max_length=64)),
                ("proposed_label", models.CharField(max_length=255)),
                ("proposed_is_edtech", models.BooleanField(default=False)),
                ("rationale", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=12,
                    ),
                ),
                ("requested_by", models.CharField(max_length=30)),
                ("reviewed_by", models.CharField(blank=True, max_length=30, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True, default="")),
                (
                    "resulting_purpose",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_proposal",
                        to="business_transformation.loanpurpose",
                    ),
                ),
            ],
            options={
                "db_table": "bt_loan_purpose_proposal",
            },
        ),
        migrations.CreateModel(
            name="PurposeSpecificAssetOutput",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset_type", models.CharField(max_length=128)),
                ("planned_quantity", models.PositiveIntegerField()),
                (
                    "reported_quantity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "verified_quantity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "evidence_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("verified", "Verified"),
                            ("returned", "Returned"),
                        ],
                        default="reported",
                        max_length=12,
                    ),
                ),
                ("reported_by", models.CharField(max_length=30)),
                ("verified_by", models.CharField(blank=True, max_length=30, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_outputs",
                        to="business_transformation.loanpurposeallocation",
                    ),
                ),
            ],
            options={
                "db_table": "bt_purpose_asset_output",
            },
        ),
        migrations.CreateModel(
            name="SalesforceConfirmation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("returned", "Returned"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "salesforce_loan_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("payload_sha256", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("recorded_by", models.CharField(max_length=30)),
                ("recorded_at", models.DateTimeField()),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salesforce_confirmations",
                        to="business_transformation.mfiloan",
                    ),
                ),
            ],
            options={
                "db_table": "bt_salesforce_confirmation",
            },
        ),
        migrations.CreateModel(
            name="TeacherDegreeUpgradeBeneficiary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("anonymized_reference", models.CharField(max_length=128)),
                ("institution", models.CharField(max_length=255)),
                ("programme", models.CharField(max_length=255)),
                ("started_on", models.DateField()),
                ("completed_on", models.DateField(blank=True, null=True)),
                ("evidence_reference", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("verified", "Verified"),
                            ("returned", "Returned"),
                        ],
                        default="reported",
                        max_length=12,
                    ),
                ),
                ("reported_by", models.CharField(max_length=30)),
                ("verified_by", models.CharField(blank=True, max_length=30, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teacher_beneficiaries",
                        to="business_transformation.mfiloan",
                    ),
                ),
            ],
            options={
                "db_table": "bt_teacher_degree_beneficiary",
            },
        ),
        migrations.CreateModel(
            name="EnrolmentSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("baseline", "Baseline"), ("follow_up", "Follow-up")],
                        max_length=12,
                    ),
                ),
                ("as_of_date", models.DateField(db_index=True)),
                ("learner_count", models.PositiveIntegerField()),
                ("cohort_definition", models.TextField()),
                ("evidence_reference", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("verified", "Verified"),
                            ("returned", "Returned"),
                        ],
                        db_index=True,
                        default="reported",
                        max_length=12,
                    ),
                ),
                ("reported_by", models.CharField(max_length=30)),
                ("verified_by", models.CharField(blank=True, max_length=30, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrolment_snapshots",
                        to="business_transformation.mfiloan",
                    ),
                ),
            ],
            options={
                "db_table": "bt_enrolment_snapshot",
                "ordering": ["loan", "as_of_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("loan", "kind", "as_of_date"),
                        name="uniq_bt_enrolment_snapshot_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "verified"), _negated=True),
                            models.Q(
                                ("verified_by__isnull", False),
                                ("verified_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="bt_verified_enrolment_has_actor",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="loanpurposeallocation",
            index=models.Index(
                fields=["loan", "status"], name="bt_loan_pur_loan_id_5d47e7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="loanpurposeallocation",
            constraint=models.UniqueConstraint(
                fields=("loan", "purpose"), name="uniq_bt_loan_purpose_allocation"
            ),
        ),
        migrations.AddConstraint(
            model_name="loanpurposeallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("planned_amount__gt", 0),
                    models.Q(
                        ("reported_amount__isnull", True),
                        ("reported_amount__gte", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("verified_amount__isnull", True),
                        ("verified_amount__gte", 0),
                        _connector="OR",
                    ),
                ),
                name="bt_purpose_allocation_amounts_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanpurposeallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "verified"), _negated=True),
                    models.Q(
                        ("verified_amount__isnull", False),
                        ("verified_by__isnull", False),
                        ("verified_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="bt_verified_purpose_has_evidence_actor",
            ),
        ),
        migrations.AddConstraint(
            model_name="purposespecificassetoutput",
            constraint=models.UniqueConstraint(
                fields=("allocation", "asset_type"),
                name="uniq_bt_allocation_asset_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="purposespecificassetoutput",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unit_cost__isnull", True), ("unit_cost__gte", 0), _connector="OR"
                ),
                name="bt_asset_unit_cost_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="salesforceconfirmation",
            index=models.Index(
                fields=["loan", "recorded_at"], name="bt_salesfor_loan_id_94cca6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherdegreeupgradebeneficiary",
            constraint=models.UniqueConstraint(
                fields=("loan", "anonymized_reference"),
                name="uniq_bt_loan_teacher_beneficiary",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherdegreeupgradebeneficiary",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("completed_on__isnull", True),
                    ("completed_on__gte", models.F("started_on")),
                    _connector="OR",
                ),
                name="bt_teacher_beneficiary_dates_ordered",
            ),
        ),
    ]
