# Generated by Django 5.2.17 on 2026-08-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_transformation", "0010_lending_use_impact_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanpurpose",
            name="allows_multiple",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="loanpurpose",
            name="applicable_countries",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="loanpurpose",
            name="applicable_school_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="loanpurpose",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loanpurpose",
            name="follow_up_days",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="loanpurpose",
            name="impact_indicators",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="loanpurpose",
            name="measurement_profile_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loanpurpose",
            name="parent_category",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="loanpurpose",
            name="required_evidence",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="loanpurpose",
            name="requires_actual_output",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="loanpurpose",
            name="requires_baseline",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="loanpurpose",
            name="requires_planned_output",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="loanpurpose",
            name="unit_of_measure",
            field=models.CharField(default="count", max_length=64),
        ),
        migrations.AddField(
            model_name="loanpurpose",
            name="verification_method",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loanpurpose",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="loanpurposeproposal",
            name="bt_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanpurposeproposal",
            name="bt_reviewed_by",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="loanpurposeproposal",
            name="cd_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanpurposeproposal",
            name="cd_approved_by",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="loanpurposeproposal",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loanpurposeproposal",
            name="example_loan_reference",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="loanpurposeproposal",
            name="expected_impact",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loanpurposeproposal",
            name="expected_outputs",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loanpurposeproposal",
            name="ia_defined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanpurposeproposal",
            name="ia_defined_by",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="loanpurposeproposal",
            name="required_evidence",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="loanpurposeproposal",
            name="unit_of_measure",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="purposespecificassetoutput",
            name="area",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="purposespecificassetoutput",
            name="area_unit",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="purposespecificassetoutput",
            name="learner_capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purposespecificassetoutput",
            name="reported_completion_state",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="purposespecificassetoutput",
            name="reported_operational_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purposespecificassetoutput",
            name="unit",
            field=models.CharField(default="count", max_length=64),
        ),
        migrations.AddField(
            model_name="purposespecificassetoutput",
            name="verified_completion_state",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="purposespecificassetoutput",
            name="verified_operational_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacherdegreeupgradebeneficiary",
            name="expected_completion_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacherdegreeupgradebeneficiary",
            name="funding_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="teacherdegreeupgradebeneficiary",
            name="programme_status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("enrolled", "Enrolled"),
                    ("studying", "Currently studying"),
                    ("deferred", "Deferred"),
                    ("withdrawn", "Withdrawn"),
                    ("completed", "Completed"),
                    ("verification_pending", "Verification pending"),
                    ("verified_completed", "Verified completed"),
                ],
                db_index=True,
                default="planned",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="teacherdegreeupgradebeneficiary",
            name="qualification_before",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="purposespecificassetoutput",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("area__isnull", True), ("area__gte", 0), _connector="OR"
                ),
                name="bt_asset_area_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purposespecificassetoutput",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("reported_quantity__isnull", True),
                        ("reported_quantity__lte", models.F("planned_quantity")),
                        _connector="OR",
                    ),
                    models.Q(
                        ("verified_quantity__isnull", True),
                        models.Q(
                            ("reported_quantity__isnull", False),
                            ("verified_quantity__lte", models.F("reported_quantity")),
                        ),
                        _connector="OR",
                    ),
                    models.Q(
                        ("verified_operational_quantity__isnull", True),
                        models.Q(
                            ("verified_quantity__isnull", False),
                            (
                                "verified_operational_quantity__lte",
                                models.F("verified_quantity"),
                            ),
                        ),
                        _connector="OR",
                    ),
                ),
                name="bt_asset_output_quantity_funnel",
            ),
        ),
        migrations.AddConstraint(
            model_name="purposespecificassetoutput",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "verified"), _negated=True),
                    models.Q(
                        models.Q(("evidence_reference", ""), _negated=True),
                        ("verified_by__isnull", False),
                        ("verified_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="bt_asset_verified_has_evidence_actor",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherdegreeupgradebeneficiary",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("funding_amount__isnull", True),
                    ("funding_amount__gte", 0),
                    _connector="OR",
                ),
                name="bt_teacher_funding_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherdegreeupgradebeneficiary",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("programme_status", "verified_completed"), _negated=True),
                    models.Q(
                        ("completed_on__isnull", False),
                        models.Q(("evidence_reference", ""), _negated=True),
                        ("verified_by__isnull", False),
                        ("verified_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="bt_teacher_verified_completion_has_evidence",
            ),
        ),
    ]
