# Generated by Django 5.2.17 on 2026-08-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_transformation", "0011_enrich_lending_impact_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanpurposeproposal",
            name="impact_indicators",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="loanpurposeproposal",
            name="verification_method",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="loanpurposeproposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("bt_reviewed", "BT reviewed"),
                    ("ia_defined", "IA measurement defined"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="requested",
                max_length=12,
            ),
        ),
    ]
