# Generated by Django 5.2.17 on 2026-08-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_transformation", "0012_purpose_governance_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanimpactassessment",
            name="evidence_references",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="loanimpactassessment",
            name="follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanimpactassessment",
            name="limitations",
            field=models.TextField(blank=True, default=""),
        ),
    ]
