# Generated by Django 5.2.17 on 2026-08-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_transformation", "0013_impact_assessment_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanamendment",
            name="approval_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loanamendment",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
