# Generated by Django 5.2.17 on 2026-08-20 18:24

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_transformation", "0014_loan_amendment_idempotency"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioImportRow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("raw_data", models.JSONField(default=dict)),
                ("normalized_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("applied", "Applied"),
                        ],
                        default="valid",
                        max_length=12,
                    ),
                ),
                ("error_codes", models.JSONField(blank=True, default=list)),
                ("idempotency_key", models.CharField(max_length=191, unique=True)),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_rows",
                        to="business_transformation.mfiloan",
                    ),
                ),
                (
                    "repayment_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_row",
                        to="business_transformation.repaymenttransaction",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="business_transformation.portfoliosubmission",
                    ),
                ),
            ],
            options={
                "db_table": "bt_portfolio_import_row",
                "ordering": ["submission", "row_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("submission", "row_number"),
                        name="uniq_bt_portfolio_submission_row",
                    )
                ],
            },
        ),
    ]
