# Generated by Django 5.2.17 on 2026-08-20 18:37

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_transformation", "0015_portfolioimportrow"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingFacilityMovement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("authorized_deduction", "Authorized facility deduction"),
                            ("capital_return", "Capital returned to funder"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "capital_source",
                    models.CharField(
                        choices=[
                            ("original", "Original funder capital"),
                            ("recovered", "Recovered principal"),
                        ],
                        default="original",
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("external_reference", models.CharField(max_length=128)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("value_date", models.DateField(db_index=True)),
                ("evidence_reference", models.CharField(max_length=255)),
                ("posted_by", models.CharField(max_length=30)),
                ("posted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "bt_funding_facility_movement",
            },
        ),
        migrations.CreateModel(
            name="FundingFacilityMovementReversal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("reason", models.TextField()),
                ("reversed_by", models.CharField(max_length=30)),
                ("reversed_at", models.DateTimeField()),
            ],
            options={
                "db_table": "bt_funding_facility_movement_reversal",
            },
        ),
        migrations.AddField(
            model_name="fundingfacility",
            name="approved_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="fundingfacility",
            name="facility_type",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="fundingfacility",
            name="funding_source",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="fundingfacility",
            name="geographic_restrictions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="fundingfacility",
            name="interest_structure",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="fundingfacility",
            name="permitted_purpose_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="fundingfacility",
            name="reporting_conditions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="fundingfacility",
            name="school_eligibility_restrictions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="fundingfacilityallocation",
            name="capital_source",
            field=models.CharField(
                choices=[
                    ("original", "Original funder capital"),
                    ("recovered", "Recovered principal"),
                ],
                db_index=True,
                default="original",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="fundingfacilitytranche",
            name="currency",
            field=models.CharField(default="UGX", max_length=3),
        ),
        migrations.AddField(
            model_name="fundingfacilitytranche",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=8, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name="fundingfacilitytranche",
            name="payment_reference",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="fundingfacilitytranche",
            name="reconciliation_status",
            field=models.CharField(db_index=True, default="confirmed", max_length=24),
        ),
        migrations.AddField(
            model_name="fundingfacilitytranche",
            name="source_account",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="fundingfacilitytranche",
            name="tranche_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loandisbursement",
            name="capital_source",
            field=models.CharField(
                choices=[
                    ("original", "Original funder capital"),
                    ("recovered", "Recovered principal"),
                ],
                db_index=True,
                default="original",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="fundingfacility",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_amount__isnull", True),
                    ("approved_amount__gt", 0),
                    _connector="OR",
                ),
                name="bt_facility_approved_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundingfacility",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_amount__isnull", True),
                    ("approved_amount__gte", models.F("commitment_amount")),
                    _connector="OR",
                ),
                name="bt_facility_approval_covers_commitment",
            ),
        ),
        migrations.AddField(
            model_name="fundingfacilitymovement",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="business_transformation.fundingfacility",
            ),
        ),
        migrations.AddField(
            model_name="fundingfacilitymovementreversal",
            name="movement",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal",
                to="business_transformation.fundingfacilitymovement",
            ),
        ),
        migrations.AddIndex(
            model_name="fundingfacilitymovement",
            index=models.Index(
                fields=["facility", "capital_source", "value_date"],
                name="bt_funding__facilit_66f1dc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundingfacilitymovement",
            constraint=models.UniqueConstraint(
                fields=("facility", "external_reference"),
                name="uniq_bt_facility_movement_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundingfacilitymovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="bt_facility_movement_amount_positive",
            ),
        ),
    ]
