# Generated by Django 5.2.17 on 2026-08-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_transformation", "0016_fundingfacilitymovement_and_more"),
        ("schools", "0020_dataqualityissue_condition_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mfiloan",
            name="default_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddConstraint(
            model_name="mfiloan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "defaulted"), _negated=True),
                    models.Q(
                        ("default_classified_at__isnull", False),
                        models.Q(("default_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="bt_defaulted_loan_has_date_and_reason",
            ),
        ),
    ]
