# Generated by Django 5.2.17 on 2026-08-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_transformation", "0017_mfiloan_default_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanuseresult",
            name="concern_review_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loanuseresult",
            name="concern_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanuseresult",
            name="concern_reviewed_by",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
