# Generated by Django 5.2.17 on 2026-09-07 18:13

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_transformation', '0018_loanuseresult_concern_review_note_and_more'),
        ('schools', '0021_school_uniq_school_salesforce_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual_upload', 'Manual Upload'), ('admin_created', 'Admin Created'), ('api_import', 'API Import'), ('local_test_upload', 'Local Test Upload'), ('production_upload', 'Production Upload')], db_index=True, default='manual_upload', max_length=32)),
                ('environment', models.CharField(choices=[('local', 'Local'), ('staging', 'Staging'), ('production', 'Production')], db_index=True, default='production', max_length=16)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_role', models.CharField(max_length=128)),
                ('applicant_phone', models.CharField(max_length=64)),
                ('applicant_email', models.EmailField(blank=True, default='', max_length=254)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('intended_use', models.TextField()),
                ('requested_term_months', models.PositiveSmallIntegerField()),
                ('repayment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('termly', 'Termly')], max_length=16)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('referred', 'Referred to lender'), ('processing', 'Processing'), ('approved', 'Approved'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('converted', 'Converted to loan')], db_index=True, default='submitted', max_length=24)),
                ('next_follow_up_on', models.DateField(blank=True, db_index=True, null=True)),
                ('consent_recorded_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(db_index=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=30, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('linked_loan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_application', to='business_transformation.mfiloan')),
                ('preferred_mfi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='business_transformation.mfiorganization')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='business_transformation.loanpurpose')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='schools.school')),
            ],
            options={
                'db_table': 'bt_loan_application',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplicationFollowUp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, default='', max_length=24)),
                ('new_status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('referred', 'Referred to lender'), ('processing', 'Processing'), ('approved', 'Approved'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('converted', 'Converted to loan')], max_length=24)),
                ('note', models.TextField(blank=True, default='')),
                ('next_follow_up_on', models.DateField(blank=True, null=True)),
                ('recorded_by', models.CharField(max_length=30)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='business_transformation.loanapplication')),
            ],
            options={
                'db_table': 'bt_loan_application_follow_up',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanTrackingDeliveryLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('delivery_kind', models.CharField(max_length=32)),
                ('subject_id', models.CharField(max_length=64)),
                ('period_key', models.CharField(max_length=32)),
                ('recipient_id', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'bt_loan_tracking_delivery_log',
                'constraints': [models.UniqueConstraint(fields=('delivery_kind', 'subject_id', 'period_key', 'recipient_id'), name='uniq_bt_loan_tracking_delivery')],
            },
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['school', 'status'], name='bt_loan_app_school__933e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['submitted_at', 'status'], name='bt_loan_app_submitt_a3b0d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='loanapplication',
            constraint=models.CheckConstraint(condition=models.Q(('requested_amount__gt', 0)), name='bt_loan_application_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='loanapplication',
            constraint=models.CheckConstraint(condition=models.Q(('requested_term_months__gt', 0)), name='bt_loan_application_term_positive'),
        ),
        migrations.AddIndex(
            model_name='loanapplicationfollowup',
            index=models.Index(fields=['application', 'created_at'], name='bt_loan_app_applica_528a6e_idx'),
        ),
    ]
