# Generated by Django 5.2.17 on 2026-09-07 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "business_transformation",
            "0019_loanapplication_loanapplicationfollowup_and_more",
        ),
        ("schools", "0021_school_uniq_school_salesforce_account_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="loanapplication",
            name="bt_loan_application_term_positive",
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="linked_loan",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_application",
                to="business_transformation.mfiloan",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("requested_term_months__gt", 0),
                    ("requested_term_months__lte", 120),
                ),
                name="bt_loan_application_term_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("linked_loan__isnull", False), ("status", "converted")),
                    models.Q(
                        models.Q(("status", "converted"), _negated=True),
                        ("linked_loan__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="bt_loan_application_conversion_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("processed_at__isnull", False),
                        ("status__in", ("declined", "withdrawn", "converted")),
                    ),
                    models.Q(
                        (
                            "status__in",
                            (
                                "submitted",
                                "under_review",
                                "referred",
                                "processing",
                                "approved",
                            ),
                        ),
                        ("processed_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="bt_loan_application_processed_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    (
                        "status__in",
                        (
                            "submitted",
                            "under_review",
                            "referred",
                            "processing",
                            "approved",
                        ),
                    ),
                ),
                fields=("school",),
                name="uniq_bt_open_loan_application_school",
            ),
        ),
    ]
