# Generated by Django 5.2.4 on 2026-06-26 22:49

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MessageThread",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "context_type",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("context_id", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sender_id", models.CharField(max_length=30)),
                (
                    "recipient_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("body", models.TextField()),
                ("category", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "context_type",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("context_id", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "target_route",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=16,
                    ),
                ),
                ("action_required", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Unread"),
                            ("read", "Read"),
                            ("archived", "Archived"),
                        ],
                        default="unread",
                        max_length=16,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messaging.messagethread",
                    ),
                ),
            ],
            options={
                "db_table": "message",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_id", "status"],
                        name="message_recipie_a2b676_idx",
                    )
                ],
            },
        ),
    ]
