# Generated by Django 5.2.4 on 2026-07-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagethread",
            name="participant_a_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="messagethread",
            name="participant_b_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name="messagethread",
            index=models.Index(
                fields=["participant_a_id", "participant_b_id"],
                name="messaging_m_partici_f638a2_idx",
            ),
        ),
    ]
