# Generated by Django 5.2.4 on 2026-07-10 05:12

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0003_backfill_thread_participants"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="message_attachments/%Y/%m/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(blank=True, max_length=64, null=True)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("uploaded_by", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MessageDraft",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(max_length=30)),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("category", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "context_type",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("context_id", models.CharField(blank=True, max_length=64, null=True)),
                ("recipient_ids", models.JSONField(blank=True, default=list)),
                ("cc_ids", models.JSONField(blank=True, default=list)),
                ("body", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageParticipant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(max_length=30)),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[("to", "To"), ("cc", "Cc")], default="to", max_length=8
                    ),
                ),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("starred", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="is_system_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="messagethread",
            name="category",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="messagethread",
            name="context_label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="messagethread",
            name="created_by",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="messagethread",
            name="is_system_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="messagethread",
            name="last_reply_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messagethread",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("normal", "Normal"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="normal",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="context_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="messagethread",
            name="context_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="messagethread",
            index=models.Index(
                fields=["context_type", "context_id"],
                name="messaging_m_context_e6286d_idx",
            ),
        ),
        migrations.AddField(
            model_name="messageattachment",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="messaging.message",
            ),
        ),
        migrations.AddIndex(
            model_name="messagedraft",
            index=models.Index(
                fields=["user_id"], name="messaging_m_user_id_01ca07_idx"
            ),
        ),
        migrations.AddField(
            model_name="messageparticipant",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="messaging.messagethread",
            ),
        ),
        migrations.AddIndex(
            model_name="messageparticipant",
            index=models.Index(
                fields=["user_id", "archived_at"], name="messaging_m_user_id_68f20b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="messageparticipant",
            constraint=models.UniqueConstraint(
                fields=("thread", "user_id"), name="uniq_thread_participant"
            ),
        ),
    ]
