# Generated by Django 5.2.4 on 2026-07-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0005_backfill_participants_and_thread_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagethread",
            name="linked_items",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
