"""FIN-05 — the Accountant's "Returned" figure must reach the money it counts.

The Accountant's home dashboard carries a five-row card, "All Fund Types This
Month". Its second row is Returned, and the figure is real: it comes from
`month_overview_all_fund_types`, which aggregates the AdvanceRequest ledger on
`status="returned"` — the status `return_weekly_request` writes when an
Accountant sends a confirmed advance back for correction.

The row is a link. It goes to /accounts/returned/, and that page read a
different table: `FinanceReturn`, which nothing in this codebase writes. Not a
service, not a view, not a management command, not a test — the model has
readers and no writers at all, so the queue could never hold a row.

The empty state is what makes it a defect rather than a dead page. It does not
say "nothing here yet". It says:

    "All corrections resolved. No returned finance items."

So the Accountant reads UGX N of returned money on the dashboard, clicks the
figure to see which requests, and is told every correction is done. Both
statements are generated by the platform, on adjacent screens, from the same
click. One of them is false and it is always the reassuring one.

This is the same class as GOV-01 — a designed capability with readers and no
writers — but with the failure pointed at the Accountant's money surface, and
with a live figure advertising the way in.

The fix is not to unlink the row. The codebase's own precedent for a
permanently-empty queue (apps/core/navigation.py, on Reimbursements) is to
de-link it and say where the live path went, and that is right when the data
genuinely lives elsewhere under another shape. Here the data is the same data:
every column this page renders exists on the returned advance. So the page is
pointed at the ledger the figure already comes from, and `FinanceReturn`
becomes what it in fact is — a legacy table with no writers.
"""

from __future__ import annotations

import datetime

from django.test import TestCase
from django.utils import timezone

from apps.accounts.models import (
    StaffProfile,
    StaffSchoolAssignment,
    StaffSupervisorAssignment,
    User,
)
from apps.activities.models import Activity
from apps.budget.models import CostCatalogue, CostSetting
from apps.core.fy import get_operational_fy
from apps.fund_requests.models import AdvanceRequest, WeeklyFundRequest
from apps.geography.models import District, Region
from apps.schools.models import School

TRANSPORT = 50_000
RETURN_REASON = "Receipt total does not match the requested transport line."


def _confirmed_ssa(school, *, fy=None, score=6.0):
    from apps.core.enums import SsaIntervention
    from apps.ssa.models import SsaRecord, SsaScore

    record = SsaRecord.objects.create(
        school=school,
        fy=fy or get_operational_fy(),
        date_of_ssa=timezone.now(),
        average_score=score,
        verification_status="confirmed",
    )
    for intervention, _ in SsaIntervention.choices:
        SsaScore.objects.create(
            ssa_record=record, intervention=intervention, score=score
        )
    return record


def _schedulable_date() -> datetime.date:
    from apps.core.calendar_policy import SchedulingPolicyService

    day = timezone.localdate() + datetime.timedelta(days=7)
    for _ in range(21):
        if SchedulingPolicyService.check(None, day)["status"] != "blocked":
            return day
        day += datetime.timedelta(days=1)
    raise AssertionError("no schedulable date within three weeks")


def _at(day: datetime.date):
    return timezone.make_aware(datetime.datetime.combine(day, datetime.time(9, 0)))


class ReturnedQueueShowsTheReturnedMoneyTest(TestCase):
    """One returned advance, seen from the figure and from the page it links to."""

    @classmethod
    def setUpTestData(cls):
        cls.region = Region.objects.create(name="Returned Region")
        cls.district = District.objects.create(
            name="Returned District", region=cls.region, district_type="primary"
        )
        cls.school = School.objects.create(
            school_id="SCH-RET-1",
            name="Returned Primary",
            region=cls.region,
            district=cls.district,
            school_type="client",
        )
        _confirmed_ssa(cls.school)

        def _person(email, name, role):
            user = User.objects.create_user(
                email=email,
                name=name,
                roles=[role],
                active_role=role,
                password="x",
                is_active=True,
            )
            profile = StaffProfile.objects.create(
                user=user, staff_number=f"RT-{name[:6]}", country="Uganda", title=role
            )
            return user, profile

        cls.cceo, cls.cceo_sp = _person("rt-cceo@edify.org", "Rt CCEO", "CCEO")
        cls.pl, cls.pl_sp = _person("rt-pl@edify.org", "Rt PL", "Program Lead")
        cls.accountant, _ = _person("rt-acct@edify.org", "Rt Acct", "Accountant")

        StaffSupervisorAssignment.objects.create(
            supervisor=cls.pl_sp, supervisee=cls.cceo_sp
        )
        StaffSchoolAssignment.objects.create(staff=cls.cceo_sp, school_id=cls.school.id)

        cls.day = _schedulable_date()
        cls.fy = get_operational_fy(cls.day)
        cls.catalogue, _ = CostCatalogue.objects.get_or_create(
            country="Uganda", fy=cls.fy, is_active=True, defaults={"version": 1}
        )
        CostSetting.objects.update_or_create(
            key="primary_transport_per_day",
            defaults={
                "label": "Primary Transport Per Day",
                "unit_cost": TRANSPORT,
                "fy": cls.fy,
                "catalogue": cls.catalogue,
            },
        )

    def _returned_advance(self) -> AdvanceRequest:
        """A confirmed advance the Accountant sends back for correction.

        The real path, not a hand-written row: `return_weekly_request` is the
        only thing that writes AdvanceRequestStatus.RETURNED, and it is the
        same call the Disbursement Dashboard's Return action makes.
        """
        from apps.activity_catalogue.services import resolve_item_for_workflow_kind
        from apps.fund_requests.disbursement_dashboard_service import (
            return_weekly_request,
        )
        from apps.fund_requests.weekly_service import (
            approve_weekly_request,
            request_advance,
        )
        from apps.planning.services import schedule_school_visit

        item = resolve_item_for_workflow_kind("school_visit")
        schedule_school_visit(
            {
                "schoolId": self.school.school_id,
                "catalogueItemId": item.id,
                "scheduledDate": _at(self.day).isoformat(),
                "activityPurposeText": "FIN-05 proof",
            },
            self.cceo,
        )
        Activity.objects.get(school=self.school)

        wfr = WeeklyFundRequest.objects.get(responsible_user=self.cceo.id)
        request_advance(wfr.id, self.cceo)
        approve_weekly_request(wfr.id, self.pl)
        # `return_weekly_request` gates on the object it is handed, not on a
        # re-read — the view passes a freshly fetched row, so the fixture must
        # too or the guard sees the pre-approval status.
        wfr.refresh_from_db()
        return_weekly_request(self.accountant, wfr, RETURN_REASON)

        advance = AdvanceRequest.objects.filter(status="returned").first()
        self.assertIsNotNone(
            advance,
            "the fixture must actually produce a returned advance, or every "
            "assertion below passes by having nothing to find",
        )
        return advance

    def test_the_dashboard_figure_counts_the_returned_advance(self):
        """The premise: the number on the card is real and non-zero."""
        from apps.fund_requests.disbursement_dashboard_service import (
            month_overview_all_fund_types,
        )

        advance = self._returned_advance()
        overview = month_overview_all_fund_types(advance.fy, advance.month)
        self.assertEqual(
            overview["returned"],
            advance.amount,
            "month_overview_all_fund_types reads the AdvanceRequest ledger; "
            "the returned row must carry this advance's money",
        )

    def test_the_page_that_figure_links_to_shows_the_same_advance(self):
        """FIN-05 itself. The figure is a link; the link must reach the money."""
        advance = self._returned_advance()

        self.client.force_login(self.accountant)
        response = self.client.get("/accounts/returned/")
        self.assertEqual(response.status_code, 200)
        body = response.content.decode()

        self.assertIn(
            RETURN_REASON,
            body,
            "the Returned queue does not show the advance the Accountant "
            "returned — /accounts/returned/ reads FinanceReturn, which nothing "
            "in this codebase writes, while the figure linking to it reads the "
            "AdvanceRequest ledger (FIN-05)",
        )
        self.assertIn(advance.activity.id[:8], body)

        # The click started from a money figure, so the destination has to
        # account for money. The page carried no amount column at all.
        from apps.core.metrics import format_ugx_compact

        self.assertIn(
            format_ugx_compact(advance.amount),
            body,
            "the queue must state the returned amount, at the same precision "
            "as the figure that links here",
        )

    def test_it_does_not_claim_every_correction_is_resolved_while_one_is_open(self):
        """The half that turns a dead page into a false statement."""
        self._returned_advance()

        self.client.force_login(self.accountant)
        body = self.client.get("/accounts/returned/").content.decode()

        self.assertNotIn(
            "All corrections resolved",
            body,
            "the page asserts every correction is done while a returned "
            "advance is open — an empty queue must never be reported as a "
            "cleared one",
        )

    def test_an_empty_queue_is_still_allowed_to_say_so(self):
        """Guard the fix from over-correcting: with nothing returned, the
        reassurance is true and should still be shown."""
        self.client.force_login(self.accountant)
        body = self.client.get("/accounts/returned/").content.decode()
        self.assertIn("All corrections resolved", body)
