"""The governed 28-item Edify source catalogue.

Source wording is intentionally repeated verbatim here.  Stable codes are the
only keys used for upsert; display names are never identities.
"""

from apps.core.enums import ActivityType, SsaIntervention

from .models import (
    CatalogueActivityType as Type,
    DeliveryMethod as Delivery,
    MappingMode,
)


INTERVENTION = SsaIntervention


def _item(
    stable_code,
    source_name,
    activity_type,
    delivery_method,
    workflow_kind,
    *,
    intervention=None,
    mapping_mode=MappingMode.FIXED,
    target_audience="School staff",
    evidence_profile="TRAINING_ATTENDANCE",
    salesforce_record_type="TRAINING",
    salesforce_expected_prefix="TS-",
    costing_profile="CLUSTER_TRAINING",
    staff=True,
    partner=True,
    school=True,
    cluster=False,
    project=True,
    requires_ssa=True,
    requires_source=False,
    new_school_only=False,
    client_visit=False,
    client_training=False,
    core_slot_type="",
    support_objective="SSA_INTERVENTION_SUPPORT",
    non_school=True,
    multi_day=False,
    participant_counts=False,
    programme_category="",
):
    return {
        "stable_code": stable_code,
        "source_name": source_name,
        "display_name": source_name,
        "description": "",
        "activity_type": activity_type,
        "delivery_method": delivery_method,
        "workflow_kind": workflow_kind,
        "target_audience": target_audience,
        "staff_delivery_allowed": staff,
        "partner_delivery_allowed": partner,
        "individual_school_allowed": school,
        "cluster_delivery_allowed": cluster,
        "project_delivery_allowed": project,
        "requires_school": school and not cluster,
        "requires_cluster": cluster and not school,
        "requires_project": False,
        "requires_current_ssa": requires_ssa,
        "requires_source_activity": requires_source,
        "new_school_only": new_school_only,
        "counts_toward_client_visit": client_visit,
        "counts_toward_client_training": client_training,
        "core_slot_type": core_slot_type or None,
        "salesforce_record_type": salesforce_record_type,
        "salesforce_expected_prefix": salesforce_expected_prefix,
        "evidence_profile": evidence_profile,
        "costing_profile": costing_profile,
        "support_objective": support_objective,
        "follow_up_required": requires_source,
        "mapping_mode": mapping_mode,
        "intervention": intervention,
        # Every governed activity can also be entered as a dated central
        # programme-budget line. This is additive: the school/cluster flags
        # above still govern operational delivery, while this flag makes the
        # same approved title available in the non-school Work Plan drawer so
        # its date and catalogue cost enter the budget.
        "non_school_allowed": non_school,
        "multi_day_allowed": multi_day,
        "requires_participant_counts": participant_counts,
        "programme_category": programme_category,
    }


CATALOGUE_ITEMS = [
    _item(
        "EDTECH_FOUNDATIONS",
        "EdTech Foundations",
        Type.TRAINING,
        Delivery.IN_SCHOOL_TRAINING,
        ActivityType.IN_SCHOOL_TRAINING,
        intervention=INTERVENTION.LEARNING_ENVIRONMENT,
        costing_profile="IN_SCHOOL_TRAINING",
        client_training=True,
    ),
    _item(
        "EDTECH_INTEGRATION",
        "EdTech Integration",
        Type.TRAINING,
        Delivery.IN_SCHOOL_TRAINING,
        ActivityType.IN_SCHOOL_TRAINING,
        intervention=INTERVENTION.LEARNING_ENVIRONMENT,
        costing_profile="IN_SCHOOL_TRAINING",
        client_training=True,
    ),
    _item(
        "LEARNER_CENTERED_APPROACHES",
        "Learner-Centered Approaches",
        Type.TRAINING,
        Delivery.IN_SCHOOL_TRAINING,
        ActivityType.IN_SCHOOL_TRAINING,
        intervention=INTERVENTION.LEARNING_ENVIRONMENT,
        costing_profile="IN_SCHOOL_TRAINING",
        client_training=True,
    ),
    _item(
        "TECH_SKILLS_EMPLOYABLE_FUTURE",
        "Technology Skills for an Employable Future",
        Type.TRAINING,
        Delivery.IN_SCHOOL_TRAINING,
        ActivityType.IN_SCHOOL_TRAINING,
        intervention=INTERVENTION.LEARNING_ENVIRONMENT,
        costing_profile="IN_SCHOOL_TRAINING",
        client_training=True,
    ),
    _item(
        "POST_TRAINING_FOLLOWUP_MEETINGS",
        "Post Training Followup Meetings",
        Type.TRAINING,
        Delivery.CLUSTER_MEETING,
        ActivityType.CLUSTER_MEETING,
        mapping_mode=MappingMode.INHERIT_FROM_SOURCE_ACTIVITY,
        intervention=None,
        requires_source=True,
        cluster=True,
        school=False,
        costing_profile="CLUSTER_MEETING",
        evidence_profile="FOLLOW_UP_MEETING",
        support_objective="GENERAL_FOLLOW_UP",
    ),
    _item(
        "SCHOOL_LEADERSHIP",
        "School Leadership",
        Type.TRAINING,
        Delivery.CLUSTER_TRAINING,
        ActivityType.CLUSTER_TRAINING,
        intervention=INTERVENTION.LEADERSHIP,
        cluster=True,
        school=False,
    ),
    _item(
        "ACCOUNTING_FINANCIAL_MANAGEMENT",
        "Accounting and Financial Management",
        Type.TRAINING,
        Delivery.CLUSTER_TRAINING,
        ActivityType.CLUSTER_TRAINING,
        intervention=INTERVENTION.FINANCIAL_HEALTH,
        target_audience="School leaders and accountants",
        cluster=True,
        school=False,
    ),
    _item(
        "FEES_ENROLMENT_MARKETING",
        "Fees, Enrollment, and Marketing Management",
        Type.TRAINING,
        Delivery.CLUSTER_MEETING,
        ActivityType.CLUSTER_MEETING,
        intervention=INTERVENTION.ENROLMENT,
        target_audience="School leaders",
        cluster=True,
        school=False,
        costing_profile="CLUSTER_MEETING",
    ),
    _item(
        "GOVERNMENT_STATUTORY_REQUIREMENTS",
        "Government and Statutory Requirements",
        Type.TRAINING,
        Delivery.CLUSTER_TRAINING,
        ActivityType.CLUSTER_TRAINING,
        intervention=INTERVENTION.GOVERNMENT_REQUIREMENT,
        cluster=True,
        school=False,
        support_objective="STATUTORY_REQUIREMENT",
    ),
    _item(
        "LEARNING_ENVIRONMENT_TRAINING",
        "Learning Environment",
        Type.TRAINING,
        Delivery.CLUSTER_TRAINING,
        ActivityType.CLUSTER_TRAINING,
        intervention=INTERVENTION.LEARNING_ENVIRONMENT,
        cluster=True,
        school=False,
    ),
    _item(
        "BIBLICAL_INTEGRATION",
        "Biblical Integration",
        Type.TRAINING,
        Delivery.CLUSTER_TRAINING,
        ActivityType.CLUSTER_TRAINING,
        intervention=INTERVENTION.EXPOSURE_TO_WORD_OF_GOD,
        cluster=True,
        school=False,
    ),
    _item(
        "TAM_I",
        "Teaching as a Mission (TAM) I",
        Type.TRAINING,
        Delivery.CLUSTER_TRAINING,
        ActivityType.CLUSTER_TRAINING,
        intervention=INTERVENTION.TEACHING_ENVIRONMENT,
        target_audience="Teachers",
        cluster=True,
        school=False,
    ),
    _item(
        "DISCIPLESHIP_DYNAMICS",
        "Discipleship Dynamics",
        Type.TRAINING,
        Delivery.CLUSTER_TRAINING,
        ActivityType.CLUSTER_TRAINING,
        intervention=INTERVENTION.EXPOSURE_TO_WORD_OF_GOD,
        cluster=True,
        school=False,
    ),
    _item(
        "TAM_II",
        "Teaching as a Mission (TAM) II",
        Type.TRAINING,
        Delivery.CLUSTER_TRAINING,
        ActivityType.CLUSTER_TRAINING,
        intervention=INTERVENTION.TEACHING_ENVIRONMENT,
        target_audience="Teachers",
        cluster=True,
        school=False,
    ),
    _item(
        "CLA_CHARACTER_DEVELOPMENT",
        "CLA Character Development",
        Type.TRAINING,
        Delivery.CLUSTER_TRAINING,
        ActivityType.CLUSTER_TRAINING,
        intervention=INTERVENTION.CHRISTLIKE_BEHAVIOUR,
        cluster=True,
        school=False,
    ),
    _item(
        "LITERACY_NUMERACY_PROJECT",
        "Literacy/Numeracy Project",
        Type.TRAINING,
        Delivery.CLUSTER_TRAINING,
        ActivityType.CLUSTER_TRAINING,
        intervention=INTERVENTION.LEARNING_ENVIRONMENT,
        project=True,
        cluster=True,
        school=False,
        support_objective="PROJECT_REQUIREMENT",
    ),
    _item(
        "EARLY_CHILDHOOD_EDUCATION_PROJECT",
        "Early Childhood Education Project",
        Type.TRAINING,
        Delivery.ONLINE,
        ActivityType.TRAINING,
        intervention=INTERVENTION.TEACHING_ENVIRONMENT,
        target_audience="Early childhood teachers",
        costing_profile="ONLINE_TRAINING",
        support_objective="PROJECT_REQUIREMENT",
    ),
    _item(
        "CORE_SCHOOL_FOLLOWUP_VISIT",
        "Core School Visits/Meetings School visits",
        Type.SCHOOL_VISIT,
        Delivery.SCHOOL_VISIT,
        ActivityType.CORE_VISIT,
        mapping_mode=MappingMode.INHERIT_FROM_SOURCE_ACTIVITY,
        intervention=None,
        requires_source=True,
        evidence_profile="SCHOOL_VISIT_FORM",
        salesforce_record_type="VISIT",
        salesforce_expected_prefix="SVE-",
        costing_profile="STAFF_SCHOOL_VISIT",
        core_slot_type="VISIT",
        client_visit=False,
        support_objective="GENERAL_FOLLOW_UP",
    ),
    _item(
        "CLIENT_SCHOOL_FOLLOWUP_VISIT",
        "Client School Visits/Meetings School visits",
        Type.SCHOOL_VISIT,
        Delivery.SCHOOL_VISIT,
        ActivityType.FOLLOW_UP_VISIT,
        mapping_mode=MappingMode.INHERIT_FROM_SOURCE_ACTIVITY,
        intervention=None,
        requires_source=True,
        evidence_profile="SCHOOL_VISIT_FORM",
        salesforce_record_type="VISIT",
        salesforce_expected_prefix="SVE-",
        costing_profile="STAFF_SCHOOL_VISIT",
        client_visit=True,
        support_objective="GENERAL_FOLLOW_UP",
    ),
    _item(
        "NEW_SCHOOL_ORIENTATION",
        "New School Orientation",
        Type.TRAINING,
        Delivery.CLUSTER_TRAINING,
        ActivityType.CLUSTER_TRAINING,
        intervention=INTERVENTION.LEADERSHIP,
        new_school_only=True,
        cluster=True,
        school=False,
        support_objective="NEW_SCHOOL_ORIENTATION",
    ),
    _item(
        "PARTNER_MEETINGS_ADMIN",
        "Partner Meetings Admin budget",
        Type.ADMIN,
        Delivery.ADMIN,
        ActivityType.PARTNER_ACTIVITY,
        mapping_mode=MappingMode.ADMINISTRATIVE,
        intervention=None,
        target_audience="Partners and authorized staff",
        evidence_profile="ADMIN_NONE",
        salesforce_record_type="NONE",
        salesforce_expected_prefix="",
        costing_profile="ADMIN_PARTNER_MEETING",
        school=False,
        cluster=False,
        project=False,
        requires_ssa=False,
        support_objective="ADMIN_OPERATION",
    ),
    _item(
        "ASA_SSA_DATA_GATHERING",
        "Data Gathering - ASA/SSA Project",
        Type.TRAINING,
        Delivery.SCHOOL_VISIT,
        ActivityType.BASELINE_SSA_VISIT,
        mapping_mode=MappingMode.SSA_COMPLETION_PREREQUISITE,
        intervention=None,
        evidence_profile="SSA_DATA_GATHERING",
        salesforce_record_type="SSA_DATA_GATHERING",
        salesforce_expected_prefix="",
        costing_profile="SSA_DATA_GATHERING",
        requires_ssa=False,
        support_objective="SSA_COMPLETION",
    ),
    _item(
        "STUDENT_TRAINING_YOUTH_CAMPS",
        "Student Training - Youth camps",
        Type.YOUTH_CAMP,
        Delivery.GROUP,
        ActivityType.TRAINING,
        intervention=INTERVENTION.CHRISTLIKE_BEHAVIOUR,
        target_audience="Students",
        evidence_profile="YOUTH_CAMP_SAFEGUARDING",
        costing_profile="PROGRAMME_EVENT",
        non_school=True,
        multi_day=True,
        participant_counts=True,
        programme_category="Student Programmes",
    ),
    _item(
        "STUDENT_LEADERSHIP_CAMPS",
        "Student Leadership Training - Students Camps",
        Type.YOUTH_CAMP,
        Delivery.GROUP,
        ActivityType.TRAINING,
        intervention=INTERVENTION.CHRISTLIKE_BEHAVIOUR,
        target_audience="Student leaders",
        evidence_profile="YOUTH_CAMP_SAFEGUARDING",
        costing_profile="PROGRAMME_EVENT",
        non_school=True,
        multi_day=True,
        participant_counts=True,
        programme_category="Student Programmes",
    ),
    _item(
        "STUDENT_CONFERENCE_CAMPS",
        "Student Conference/Camps - Student camps",
        Type.YOUTH_CAMP,
        Delivery.GROUP,
        ActivityType.TRAINING,
        intervention=INTERVENTION.CHRISTLIKE_BEHAVIOUR,
        target_audience="Students",
        evidence_profile="YOUTH_CAMP_SAFEGUARDING",
        costing_profile="PROGRAMME_EVENT",
        non_school=True,
        multi_day=True,
        participant_counts=True,
        programme_category="Student Programmes",
    ),
    _item(
        "TEACHER_PEDAGOGY_PROFESSIONALISM",
        "Teacher Pedagogy/Professionalism",
        Type.TRAINING,
        Delivery.CLUSTER_TRAINING,
        ActivityType.CLUSTER_TRAINING,
        intervention=INTERVENTION.LEARNING_ENVIRONMENT,
        target_audience="Teachers",
        cluster=True,
        school=False,
    ),
    _item(
        "TEACHER_LEADERSHIP_CONFERENCE",
        "Teacher Leadership Conference/Camp/Retreat",
        Type.TRAINING,
        Delivery.GROUP,
        ActivityType.TRAINING,
        intervention=INTERVENTION.TEACHING_ENVIRONMENT,
        target_audience="Teachers and school leaders",
        costing_profile="PROGRAMME_EVENT",
        non_school=True,
        multi_day=True,
        participant_counts=True,
        programme_category="People Development",
    ),
    _item(
        "CC_SEL",
        "CC-SEL",
        Type.TRAINING,
        Delivery.IN_SCHOOL_TRAINING,
        ActivityType.IN_SCHOOL_TRAINING,
        intervention=INTERVENTION.CHRISTLIKE_BEHAVIOUR,
        costing_profile="IN_SCHOOL_TRAINING",
        support_objective="PROJECT_REQUIREMENT",
        client_training=True,
    ),
]


ALTERNATE_STABLE_CODES = {
    "TECHNOLOGY_SKILLS_EMPLOYABLE_FUTURE": "TECH_SKILLS_EMPLOYABLE_FUTURE",
    "FEES_ENROLMENT_MARKETING_MANAGEMENT": "FEES_ENROLMENT_MARKETING",
    "CORE_SCHOOL_VISIT_FOLLOWUP": "CORE_SCHOOL_FOLLOWUP_VISIT",
    "CLIENT_SCHOOL_VISIT_FOLLOWUP": "CLIENT_SCHOOL_FOLLOWUP_VISIT",
    "PARTNER_MEETING_ADMIN": "PARTNER_MEETINGS_ADMIN",
    "DATA_GATHERING_ASA_SSA": "ASA_SSA_DATA_GATHERING",
}


assert len(CATALOGUE_ITEMS) == 28
assert len({row["stable_code"] for row in CATALOGUE_ITEMS}) == 28
