# Generated by Django 5.2.16 on 2026-08-15 13:44

import apps.core.cuid
import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntegrationSync",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("salesforce", "Salesforce"),
                            ("netsuite", "NetSuite"),
                        ],
                        max_length=16,
                    ),
                ),
                ("context_type", models.CharField(max_length=32)),
                ("context_id", models.CharField(db_index=True, max_length=30)),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("reconciled_manual", "Reconciled (manual reference)"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "integration_sync",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "context_type", "context_id"),
                        name="uniq_integration_sync_context",
                    )
                ],
            },
        ),
    ]
