# Generated by Django 5.2.4 on 2026-06-26 22:36

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("visit_form", "Visit Form"),
                            ("school_stamp", "School Stamp"),
                            ("attendance_form", "Attendance Form"),
                            ("meeting_minutes", "Meeting Minutes"),
                            ("resolutions", "Resolutions"),
                            ("evaluation_form", "Evaluation Form"),
                            ("assessment_form", "Assessment Form"),
                            ("photo", "Photo"),
                            ("pdf", "PDF"),
                            ("project_report", "Project Report"),
                            ("coaching_notes", "Coaching Notes"),
                        ],
                        max_length=32,
                    ),
                ),
                ("uri", models.CharField(max_length=512)),
                (
                    "original_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("mime_type", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "file_extension",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("storage_provider", models.CharField(default="local", max_length=32)),
                ("notes", models.TextField(blank=True, null=True)),
                ("uploaded_by", models.CharField(max_length=30)),
                (
                    "uploader_role",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("uploaded", "Uploaded"),
                            ("accepted", "Accepted"),
                            ("returned", "Returned"),
                            ("rejected", "Rejected"),
                        ],
                        default="uploaded",
                        max_length=16,
                    ),
                ),
                ("reviewed_by", models.CharField(blank=True, max_length=30, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_note",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("scan_status", models.CharField(default="pending", max_length=16)),
                ("quarantined", models.BooleanField(default=False)),
                (
                    "preview_status",
                    models.CharField(default="not_required", max_length=16),
                ),
                (
                    "pdf_rendition_storage_key",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "pdf_rendition_status",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "pdf_rendition_error",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("pdf_rendition_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.IntegerField(default=0)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "evidence_record",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["activity"], name="evidence_re_activit_0e5953_idx"
                    ),
                    models.Index(
                        fields=["quarantined"], name="evidence_re_quarant_cb4f34_idx"
                    ),
                    models.Index(
                        fields=["preview_status"], name="evidence_re_preview_70c4e5_idx"
                    ),
                ],
            },
        ),
    ]
