from django.urls import path

from . import views


urlpatterns = [
    path("cases", views.CaseListView.as_view(), name="cases"),
    path("cases/<str:case_id>/triage", views.CaseTriageView.as_view(), name="triage"),
    path("mfis", views.MfiListCreateView.as_view(), name="mfis"),
    path("mfi-members", views.MfiMemberCreateView.as_view(), name="mfi-members"),
    path("referrals", views.ReferralCreateView.as_view(), name="referrals"),
    path("loan-purposes", views.LoanPurposeListView.as_view(), name="loan-purposes"),
    path(
        "referrals/<str:referral_id>/decision",
        views.ReferralDecisionView.as_view(),
        name="referral-decision",
    ),
    path("loans", views.LoanListCreateView.as_view(), name="loans"),
    path(
        "loans/<str:loan_id>/salesforce-confirmation",
        views.LoanSalesforceConfirmationView.as_view(),
        name="loan-salesforce-confirmation",
    ),
    path(
        "loans/<str:loan_id>/salesforce-return",
        views.LoanSalesforceReturnView.as_view(),
        name="loan-salesforce-return",
    ),
    path(
        "loans/<str:loan_id>/resubmit",
        views.LoanReturnedResubmitView.as_view(),
        name="loan-returned-resubmit",
    ),
    path(
        "loans/<str:loan_id>/amendments",
        views.LoanAmendmentRequestView.as_view(),
        name="loan-amendment-request",
    ),
    path(
        "loan-amendments/<str:amendment_id>/approve",
        views.LoanAmendmentApproveView.as_view(),
        name="loan-amendment-approve",
    ),
    path(
        "portfolio-imports",
        views.PortfolioImportStageView.as_view(),
        name="portfolio-import-stage",
    ),
    path(
        "portfolio-imports/<str:submission_id>/apply",
        views.PortfolioImportApplyView.as_view(),
        name="portfolio-import-apply",
    ),
    path(
        "portfolio-imports/<str:submission_id>/certify",
        views.PortfolioImportCertifyView.as_view(),
        name="portfolio-import-certify",
    ),
    path(
        "loans/<str:loan_id>/ia-validation",
        views.LoanIAValidationView.as_view(),
        name="loan-ia-validation",
    ),
    path(
        "loans/<str:loan_id>/repayment-snapshots",
        views.RepaymentSnapshotCreateView.as_view(),
        name="repayment-snapshots",
    ),
    path(
        "verification-requirements/<str:requirement_id>/activity",
        views.VerificationActivityLinkView.as_view(),
        name="verification-activity",
    ),
    path(
        "verification-requirements/<str:requirement_id>/result",
        views.LoanUseResultView.as_view(),
        name="loan-use-result",
    ),
    path(
        "loan-use-results/<str:result_id>/review-concern",
        views.LoanUseConcernReviewView.as_view(),
        name="loan-use-concern-review",
    ),
    path("metrics", views.PortfolioMetricsView.as_view(), name="metrics"),
    path(
        "facilities", views.FundingFacilityListCreateView.as_view(), name="facilities"
    ),
    path(
        "facilities/<str:facility_id>/approve",
        views.FundingFacilityApproveView.as_view(),
        name="facility-approve",
    ),
    path(
        "facility-tranches",
        views.FundingFacilityTrancheCreateView.as_view(),
        name="facility-tranches",
    ),
    path(
        "facility-tranches/<str:tranche_id>/reverse",
        views.FundingFacilityTrancheReverseView.as_view(),
        name="facility-tranche-reverse",
    ),
    path(
        "facility-movements",
        views.FundingFacilityMovementCreateView.as_view(),
        name="facility-movements",
    ),
    path(
        "facility-movements/<str:movement_id>/reverse",
        views.FundingFacilityMovementReverseView.as_view(),
        name="facility-movement-reverse",
    ),
    path(
        "facility-allocations",
        views.FundingFacilityAllocationCreateView.as_view(),
        name="facility-allocations",
    ),
    path(
        "facility-allocations/<str:allocation_id>/release",
        views.FundingFacilityAllocationReleaseView.as_view(),
        name="facility-allocation-release",
    ),
    path(
        "loan-disbursements",
        views.LoanDisbursementCreateView.as_view(),
        name="loan-disbursements",
    ),
    path(
        "loan-disbursements/<str:disbursement_id>/reverse",
        views.LoanDisbursementReverseView.as_view(),
        name="loan-disbursement-reverse",
    ),
    path(
        "loans/<str:loan_id>/repayment-schedule",
        views.LoanRepaymentScheduleCreateView.as_view(),
        name="loan-repayment-schedule",
    ),
    path(
        "repayment-transactions",
        views.RepaymentTransactionCreateView.as_view(),
        name="repayment-transactions",
    ),
    path(
        "repayment-transactions/<str:transaction_id>/reverse",
        views.RepaymentTransactionReverseView.as_view(),
        name="repayment-transaction-reverse",
    ),
    path(
        "loans/<str:loan_id>/purpose-allocations",
        views.LoanPurposeAllocationPlanView.as_view(),
        name="loan-purpose-allocations",
    ),
    path(
        "purpose-allocations/<str:allocation_id>/report",
        views.LoanPurposeUseReportView.as_view(),
        name="loan-purpose-use-report",
    ),
    path(
        "purpose-allocations/<str:allocation_id>/verify",
        views.LoanPurposeUseVerifyView.as_view(),
        name="loan-purpose-use-verify",
    ),
    path(
        "loans/<str:loan_id>/enrolment-snapshots",
        views.LoanEnrolmentSnapshotCreateView.as_view(),
        name="loan-enrolment-snapshots",
    ),
    path(
        "enrolment-snapshots/<str:snapshot_id>/verify",
        views.LoanEnrolmentSnapshotVerifyView.as_view(),
        name="loan-enrolment-snapshot-verify",
    ),
    path(
        "purpose-allocations/<str:allocation_id>/outputs",
        views.PurposeAssetOutputCreateView.as_view(),
        name="purpose-asset-output-create",
    ),
    path(
        "purpose-outputs/<str:output_id>/report",
        views.PurposeAssetOutputReportView.as_view(),
        name="purpose-asset-output-report",
    ),
    path(
        "purpose-outputs/<str:output_id>/verify",
        views.PurposeAssetOutputVerifyView.as_view(),
        name="purpose-asset-output-verify",
    ),
    path(
        "loans/<str:loan_id>/teacher-beneficiaries",
        views.TeacherBeneficiaryCreateView.as_view(),
        name="teacher-beneficiary-create",
    ),
    path(
        "teacher-beneficiaries/<str:beneficiary_id>/progress",
        views.TeacherBeneficiaryProgressView.as_view(),
        name="teacher-beneficiary-progress",
    ),
    path(
        "teacher-beneficiaries/<str:beneficiary_id>/verify",
        views.TeacherBeneficiaryVerifyView.as_view(),
        name="teacher-beneficiary-verify",
    ),
    path(
        "loan-purpose-proposals",
        views.LoanPurposeRequestView.as_view(),
        name="loan-purpose-request",
    ),
    path(
        "loan-purpose-proposals/<str:proposal_id>/review",
        views.LoanPurposeReviewView.as_view(),
        name="loan-purpose-review",
    ),
    path(
        "loan-purpose-proposals/<str:proposal_id>/define",
        views.LoanPurposeDefineView.as_view(),
        name="loan-purpose-define",
    ),
    path(
        "loan-purpose-proposals/<str:proposal_id>/approve",
        views.LoanPurposeApproveView.as_view(),
        name="loan-purpose-approve",
    ),
    path(
        "impact-summary",
        views.LendingImpactSummaryView.as_view(),
        name="impact-summary",
    ),
    path(
        "impact-assessments/<str:assessment_id>/verify",
        views.LoanImpactVerifyView.as_view(),
        name="loan-impact-verify",
    ),
    path(
        "geographic-equity",
        views.LendingGeographicEquityView.as_view(),
        name="geographic-equity",
    ),
]
