# Generated by Django 5.2.16 on 2026-08-15 13:50

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0021_admin_also_field_officer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposedPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_start", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("accepted", "Accepted"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("rationale", models.JSONField(blank=True, default=dict)),
                (
                    "accepted_by",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_plans",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "autopilot_proposed_plan",
            },
        ),
        migrations.CreateModel(
            name="ProposedActivity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("school_id", models.CharField(db_index=True, max_length=30)),
                (
                    "school_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("area", models.CharField(blank=True, default="", max_length=128)),
                ("proposed_date", models.DateField()),
                (
                    "activity_type",
                    models.CharField(default="school_visit", max_length=64),
                ),
                (
                    "catalogue_stable_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_activity_id",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="autopilot.proposedplan",
                    ),
                ),
            ],
            options={
                "db_table": "autopilot_proposed_activity",
                "ordering": ["proposed_date", "area", "school_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="proposedplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "proposed")),
                fields=("staff", "week_start"),
                name="uniq_live_proposed_plan",
            ),
        ),
    ]
