# Generated by Django 5.2.4 on 2026-06-26 22:25

import apps.core.cuid
import apps.core.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyDebrief",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fy", models.CharField(max_length=16)),
                ("date", models.DateTimeField()),
                ("submitted_by_user_id", models.CharField(max_length=30)),
                ("submitted_by_role", models.CharField(max_length=64)),
                ("staff_id", models.CharField(blank=True, max_length=30, null=True)),
                ("partner_id", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "debrief_type",
                    models.CharField(
                        choices=[
                            ("staff", "Staff"),
                            ("partner", "Partner"),
                            ("merged", "Merged"),
                        ],
                        default="staff",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("merged", "Merged"),
                            ("returned", "Returned"),
                            ("archived", "Archived"),
                        ],
                        default="submitted",
                        max_length=16,
                    ),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                ("what_happened", models.TextField(blank=True, null=True)),
                ("what_went_well", models.TextField(blank=True, null=True)),
                ("what_did_not_go_well", models.TextField(blank=True, null=True)),
                (
                    "blockers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "blocker_other",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("support_needed", models.TextField(blank=True, null=True)),
                ("recommendations", models.TextField(blank=True, null=True)),
                (
                    "next_action",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "linked_school_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "linked_cluster_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "linked_partner_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "linked_project_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "linked_activity_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "parent_debrief_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "merged_into_debrief_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "reviewed_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "daily_debrief",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["fy", "date"], name="daily_debri_fy_cfd057_idx"
                    ),
                    models.Index(
                        fields=["submitted_by_user_id"],
                        name="daily_debri_submitt_9102e8_idx",
                    ),
                    models.Index(
                        fields=["status"], name="daily_debri_status_ce24c3_idx"
                    ),
                    models.Index(
                        fields=["partner_id"], name="daily_debri_partner_c426ec_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyDebriefRecipient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_user_id", models.CharField(max_length=30)),
                ("recipient_role", models.CharField(max_length=64)),
                (
                    "routing_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("action_required", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "debrief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="debriefs.dailydebrief",
                    ),
                ),
            ],
            options={
                "db_table": "daily_debrief_recipient",
                "indexes": [
                    models.Index(
                        fields=["recipient_user_id", "read_at"],
                        name="daily_debri_recipie_dd709b_idx",
                    ),
                    models.Index(
                        fields=["debrief"], name="daily_debri_debrief_466a4c_idx"
                    ),
                ],
            },
        ),
    ]
