# Generated by Django 5.2.4 on 2026-07-13 00:15

import apps.core.cuid
import apps.core.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_activity_daily_visit_batch_and_more'),
        ('debriefs', '0002_dailydebrief_environment_dailydebrief_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDebriefAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('issue', models.TextField()),
                ('action', models.TextField()),
                ('owner_user_id', models.CharField(max_length=30)),
                ('owner_role', models.CharField(blank=True, max_length=64, null=True)),
                ('assigned_by_user_id', models.CharField(max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=8)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('waiting_on_another_role', 'Waiting on Another Role'), ('resolved', 'Resolved'), ('returned', 'Returned'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='open', max_length=24)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('resolved_by_user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_debrief_action',
            },
        ),
        migrations.CreateModel(
            name='DailyDebriefActivityLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('school_id', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'daily_debrief_activity_link',
            },
        ),
        migrations.CreateModel(
            name='DailyDebriefChallenge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('challenge_type', models.CharField(choices=[('leader_unavailable', 'School Leader Unavailable'), ('teachers_unavailable', 'Teachers Unavailable'), ('low_attendance', 'Low Attendance'), ('started_late', 'Activity Started Late'), ('transport_late', 'Transport Came Late'), ('no_transport', 'No Transport'), ('weather', 'Weather'), ('road_conditions', 'Road Conditions'), ('distance_route', 'Distance or Route Problem'), ('holiday_conflict', 'Public Holiday Conflict'), ('school_event_conflict', 'School Event Conflict'), ('funds_delayed', 'Funds Delayed'), ('funds_insufficient', 'Funds Insufficient'), ('partner_delayed', 'Partner Delayed'), ('materials_unavailable', 'Materials Unavailable'), ('technology_problem', 'Technology Problem'), ('data_quality', 'Data-Quality Problem'), ('ssa_form_issue', 'SSA Form Issue'), ('language_communication', 'Language or Communication Problem'), ('safety_concern', 'Safety Concern'), ('health_concern', 'Health Concern'), ('community_resistance', 'Community Resistance'), ('government_regulatory', 'Government or Regulatory Issue'), ('other', 'Other')], max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('immediate_response', models.TextField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('follow_up_owner_id', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'daily_debrief_challenge',
            },
        ),
        migrations.CreateModel(
            name='DailyDebriefCommitment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('party', models.CharField(choices=[('school', 'School'), ('staff', 'Edify Staff'), ('partner', 'Partner')], max_length=8)),
                ('commitment_text', models.TextField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=8)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_debrief_commitment',
            },
        ),
        migrations.CreateModel(
            name='DailyDebriefInsight',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('school', 'School'), ('cluster', 'Cluster'), ('district', 'District'), ('partner', 'Partner'), ('staff', 'Staff'), ('team', 'Team'), ('country', 'Country'), ('region', 'Region')], max_length=16)),
                ('scope_id', models.CharField(blank=True, max_length=30, null=True)),
                ('challenge_type', models.CharField(blank=True, max_length=32, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('occurrence_count', models.IntegerField(default=1)),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('debrief_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('escalation_level', models.CharField(choices=[('team', 'Team'), ('country', 'Country'), ('region', 'Region')], default='team', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('notified_user_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
            ],
            options={
                'db_table': 'daily_debrief_insight',
            },
        ),
        migrations.CreateModel(
            name='DailyDebriefPeerSolution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('author_user_id', models.CharField(max_length=30)),
                ('suggestion', models.TextField()),
                ('related_experience', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('under_discussion', 'Under Discussion'), ('endorsed', 'Endorsed'), ('adopted', 'Adopted'), ('piloting', 'Piloting'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='proposed', max_length=16)),
                ('endorsed_by_user_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('pl_classification', models.CharField(blank=True, choices=[('useful', 'Useful'), ('adopt_for_team', 'Adopt for Team'), ('pilot', 'Pilot'), ('needs_more_evidence', 'Needs More Evidence'), ('not_applicable', 'Not Applicable')], max_length=20, null=True)),
                ('pl_classified_by_user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('pl_classified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_debrief_peer_solution',
            },
        ),
        migrations.CreateModel(
            name='DailyDebriefSupportRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('requested_from_role', models.CharField(choices=[('Program Lead', 'Program Lead'), ('CountryDirector', 'Country Director'), ('ImpactAssessment', 'Impact Assessment'), ('HumanResources', 'HR'), ('Accountant', 'Accountant'), ('partner_manager', 'Partner Manager'), ('ProjectCoordinator', 'Project Coordinator'), ('RegionalVicePresident', 'RVP')], max_length=32)),
                ('support_type', models.CharField(choices=[('technical', 'Technical Support'), ('intervention_guidance', 'Intervention Guidance'), ('budget', 'Budget Support'), ('transport', 'Transport Support'), ('partner', 'Partner Support'), ('training_materials', 'Training Materials'), ('ssa_data', 'SSA/Data Support'), ('workload', 'Workload Support'), ('hr_support', 'HR Support'), ('leadership_decision', 'Leadership Decision'), ('policy_clarification', 'Policy Clarification')], max_length=32)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_user_id', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'daily_debrief_support_request',
            },
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='actual_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='actual_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='actual_route',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='actual_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='actual_travel_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='attendance_concerns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='completion_status',
            field=models.CharField(blank=True, choices=[('completed_as_planned', 'Completed as Planned'), ('partially_completed', 'Partially Completed'), ('unsuccessful', 'Unsuccessful'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='engagement_level',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('moderate', 'Moderate'), ('low', 'Low'), ('very_low', 'Very Low')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='estimated_travel_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='expected_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='follow_up_owner_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='immediate_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='incomplete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='innovation_observed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='intended_purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='intervention_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('christlike_behaviour', 'Christlike Behaviour'), ('exposure_to_word_of_god', 'Exposure to Word of God'), ('financial_health', 'Financial Health'), ('leadership', 'Leadership'), ('learning_environment', 'Learning Environment'), ('government_requirement', 'Government Requirement'), ('teaching_environment', 'Teaching Environment'), ('enrolment', 'Enrolment')], max_length=64), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='is_restricted_incident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='key_lesson_learned',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='key_success',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='kind',
            field=models.CharField(choices=[('activity', 'Activity Debrief'), ('daily', 'Daily Field Debrief'), ('partner', 'Partner Debrief'), ('supervision', 'Supervision Debrief'), ('incident', 'Incident Debrief'), ('weekly_summary', 'Weekly Field Summary')], default='activity', max_length=16),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='mscs_draft_story_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='other_participants_present',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='participants_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='planned_route',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='potential_champion_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='potential_champion_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='potential_mscs_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='potential_mscs_narrative',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='potential_mscs_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='potential_partner_success_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='practice_worth_repeating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='purpose_achieved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='recommendation_accepted_activity_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='recommendation_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='recommendation_reviewed_by_user_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='recommendation_status',
            field=models.CharField(choices=[('none', 'None'), ('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='recommended_intervention',
            field=models.CharField(blank=True, choices=[('christlike_behaviour', 'Christlike Behaviour'), ('exposure_to_word_of_god', 'Exposure to Word of God'), ('financial_health', 'Financial Health'), ('leadership', 'Leadership'), ('learning_environment', 'Learning Environment'), ('government_requirement', 'Government Requirement'), ('teaching_environment', 'Teaching Environment'), ('enrolment', 'Enrolment')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='recommended_next_activity_type',
            field=models.CharField(blank=True, choices=[('school_visit', 'School Visit'), ('follow_up_visit', 'Follow-Up Visit'), ('baseline_ssa', 'Baseline SSA'), ('ssa_refresh', 'SSA Refresh'), ('cluster_meeting', 'Cluster Meeting'), ('cluster_training', 'Cluster Training'), ('core_visit', 'Core Visit'), ('core_training', 'Core Training'), ('partner_coaching', 'Partner Coaching'), ('leadership_follow_up', 'Leadership Follow-Up'), ('finance_follow_up', 'Finance Follow-Up'), ('data_cleanup', 'Data Cleanup'), ('no_further_action', 'No Further Action')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='restricted_incident_category',
            field=models.CharField(blank=True, choices=[('safeguarding', 'Safeguarding'), ('fraud', 'Fraud or Misuse of Funds'), ('staff_safety', 'Serious Staff Safety Issue'), ('data_integrity', 'Serious Data Integrity Issue'), ('partner_misconduct', 'Major Partner Misconduct'), ('school_complaint', 'Severe School Complaint'), ('other', 'Other')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='risk_level',
            field=models.CharField(choices=[('none', 'No Escalation'), ('monitor', 'Monitor'), ('pl_attention', 'PL Attention'), ('cd_attention', 'CD Attention'), ('ia_attention', 'IA Attention'), ('hr_attention', 'HR Attention'), ('finance_attention', 'Finance Attention'), ('critical', 'Critical Leadership Attention')], default='none', max_length=24),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='route_quality',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='school_leaders_present',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='schools_planned_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='schools_reached_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='support_needed_next',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='teachers_present',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='transport_issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='travel_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='travel_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='what_improved',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='what_observed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='what_remains_weak',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='what_surprised',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydebrief',
            name='what_was_done',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailydebrief',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('clarification_requested', 'Clarification Requested'), ('updated', 'Updated'), ('leadership_review', 'Leadership Review'), ('action_required', 'Action Required'), ('escalated', 'Escalated'), ('action_in_progress', 'Action in Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('restricted_incident', 'Restricted Incident'), ('reviewed', 'Reviewed'), ('merged', 'Merged'), ('returned', 'Returned'), ('archived', 'Archived')], default='submitted', max_length=32),
        ),
        migrations.AddIndex(
            model_name='dailydebrief',
            index=models.Index(fields=['risk_level'], name='daily_debri_risk_le_91a22a_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydebrief',
            index=models.Index(fields=['is_restricted_incident'], name='daily_debri_is_rest_ef8a3d_idx'),
        ),
        migrations.AddField(
            model_name='dailydebriefaction',
            name='debrief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='debriefs.dailydebrief'),
        ),
        migrations.AddField(
            model_name='dailydebriefactivitylink',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debrief_links', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='dailydebriefactivitylink',
            name='debrief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_links', to='debriefs.dailydebrief'),
        ),
        migrations.AddField(
            model_name='dailydebriefchallenge',
            name='debrief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='debriefs.dailydebrief'),
        ),
        migrations.AddField(
            model_name='dailydebriefcommitment',
            name='debrief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='debriefs.dailydebrief'),
        ),
        migrations.AddIndex(
            model_name='dailydebriefinsight',
            index=models.Index(fields=['scope', 'scope_id'], name='daily_debri_scope_dd7193_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydebriefinsight',
            index=models.Index(fields=['status'], name='daily_debri_status_5c35b8_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydebriefinsight',
            index=models.Index(fields=['escalation_level'], name='daily_debri_escalat_abf269_idx'),
        ),
        migrations.AddField(
            model_name='dailydebriefpeersolution',
            name='debrief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_solutions', to='debriefs.dailydebrief'),
        ),
        migrations.AddField(
            model_name='dailydebriefsupportrequest',
            name='debrief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='debriefs.dailydebrief'),
        ),
        migrations.AddIndex(
            model_name='dailydebriefaction',
            index=models.Index(fields=['owner_user_id', 'status'], name='daily_debri_owner_u_a57f75_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydebriefaction',
            index=models.Index(fields=['debrief'], name='daily_debri_debrief_02ba64_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydebriefaction',
            index=models.Index(fields=['status', 'priority'], name='daily_debri_status_364f15_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydebriefactivitylink',
            index=models.Index(fields=['activity'], name='daily_debri_activit_741107_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydebriefactivitylink',
            index=models.Index(fields=['school_id'], name='daily_debri_school__7044cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailydebriefactivitylink',
            constraint=models.UniqueConstraint(fields=('debrief', 'activity'), name='uniq_debrief_activity_link'),
        ),
        migrations.AddIndex(
            model_name='dailydebriefchallenge',
            index=models.Index(fields=['challenge_type'], name='daily_debri_challen_d20219_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydebriefchallenge',
            index=models.Index(fields=['debrief'], name='daily_debri_debrief_e27fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydebriefcommitment',
            index=models.Index(fields=['debrief'], name='daily_debri_debrief_52a552_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydebriefcommitment',
            index=models.Index(fields=['status'], name='daily_debri_status_6663e1_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydebriefpeersolution',
            index=models.Index(fields=['debrief'], name='daily_debri_debrief_b3b508_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydebriefpeersolution',
            index=models.Index(fields=['author_user_id'], name='daily_debri_author__6ffcff_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydebriefsupportrequest',
            index=models.Index(fields=['requested_from_role', 'status'], name='daily_debri_request_6b2724_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydebriefsupportrequest',
            index=models.Index(fields=['debrief'], name='daily_debri_debrief_e516b0_idx'),
        ),
    ]
