# Generated by Django 5.2.16 on 2026-07-24 08:33

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debriefs', '0006_dailydebrief_challenges_faced_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyDebriefReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('fy', models.CharField(max_length=16)),
                ('scope_kind', models.CharField(choices=[('pl_team', 'Program Lead Team'), ('country', 'Country'), ('rvp', 'Regional (RVP)'), ('hr_people', 'HR People Intelligence')], max_length=16)),
                ('scope_id', models.CharField(max_length=64)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft Generated'), ('finalized', 'Finalized'), ('superseded', 'Superseded')], default='draft', max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('snapshot', models.JSONField(default=dict)),
                ('commentary', models.TextField(blank=True, null=True)),
                ('generated_by_user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('signed_by_user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weekly_debrief_report',
                'ordering': ['-week_start', '-version'],
                'indexes': [models.Index(fields=['scope_kind', 'scope_id', 'week_start'], name='weekly_debr_scope_k_3335cf_idx'), models.Index(fields=['status'], name='weekly_debr_status_924870_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope_kind', 'scope_id', 'week_start', 'version'), name='uniq_weekly_report_scope_week_version')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReportDistribution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('sent_by_user_id', models.CharField(max_length=30)),
                ('recipients', models.JSONField(default=list)),
                ('subject', models.CharField(max_length=255)),
                ('report_version', models.IntegerField()),
                ('succeeded', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='debriefs.weeklydebriefreport')),
            ],
            options={
                'db_table': 'weekly_debrief_report_distribution',
                'indexes': [models.Index(fields=['report'], name='weekly_debr_report__257043_idx')],
            },
        ),
    ]
