# Generated by Django 5.2.4 on 2026-06-26 22:25

import apps.core.cuid
import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdFlag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('raised_by_user_id', models.CharField(max_length=30)),
                ('raised_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_to_user_id', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=64)),
                ('scope_type', models.CharField(blank=True, max_length=32, null=True)),
                ('scope_id', models.CharField(blank=True, max_length=30, null=True)),
                ('scope_name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField()),
                ('recommended_action', models.CharField(blank=True, max_length=512, null=True)),
                ('priority', models.CharField(default='normal', max_length=16)),
                ('due_date', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cd_flag',
                'indexes': [models.Index(fields=['assigned_to_user_id', 'status'], name='cd_flag_assigne_fb2bae_idx'), models.Index(fields=['raised_by_user_id'], name='cd_flag_raised__095e07_idx')],
            },
        ),
    ]
