// Mock seed for the SSA-gated Planning Tool. Every gap is produced
// through the recommendation engine so the demo data exercises the
// same code path the real backend will hit.

import type { PlanningGap, SsaGateState, GapKind } from "./gap-types";
import { recommendForGap } from "./ssa-recommendation";
import { groupGapsForTabs, type PlanningGapTabs } from "./gap-engine";

// ────────── Helpers ──────────
//
// `seed` lets us declare each gap as a plain shape minus the
// `recommendation` field, then we pass it through recommendForGap so
// the seed proves the engine produces a valid recommendation for every
// state we render in the demo. Anything ad-hoc (a hand-rolled
// recommendation object) would defeat the point of this fixture.

type GapSeed = Omit<PlanningGap, "recommendation">;

function seed(s: GapSeed): PlanningGap {
  return { ...s, recommendation: recommendForGap(s as PlanningGap) };
}

// Stable CCEO + partner IDs that line up with the budget engine seed.
const CCEO = {
  PC: "STF-PC-001",
  MO: "STF-MO-002",
  JN: "STF-JN-003",
  AK: "STF-AK-004",
  DM: "STF-DM-005",
  DA: "STF-DA-011",
  AH: "STF-AH-012",
  NL: "STF-NL-013",
} as const;

const PARTNER = {
  LRV: "PRT-LRV", // Living River Ventures
  SDC: "PRT-SDC", // Sustainable Development Coalition
  AYM: "PRT-AYM", // Acholi Youth Mission
} as const;

// Intervention areas the SSA scores against. The recommendation engine
// reads `ssaWeakest.area` + score to phrase the "Focus on X because the
// school scored Y/10" sentence — keep the wording stable.
const AREA = {
  TL:   "Teaching & Learning",
  LE:   "Learning Environment",
  LD:   "Leadership",
  FH:   "Financial Health",
  CB:   "Christlike Behaviour",
  EW:   "Exposure to the Word of God",
  GR:   "Government Requirements & Compliance",
  ET:   "Education Technology",
  PE:   "Parent Engagement",
} as const;

// ────────── Seed ──────────

const RAW: GapSeed[] = [
  // ════════════════════════════════════════════════════════════════
  // CLIENT SCHOOLS — SSA gate: SIT_NOT_DONE (5+)
  // School Improvement Training has not happened yet for the cluster,
  // so SSA can't be administered. Only valid action: SCHEDULE_SIT.
  // ════════════════════════════════════════════════════════════════
  {
    id: "GAP-SCH-001",
    kind: "NO_SSA" as GapKind,
    entity: "school",
    schoolId: "SCH-001",
    schoolName: "Hope Primary School",
    district: "Kitgum",
    clusterId: "CLU-001",
    clusterName: "Kitgum North Cluster",
    assignedCceoId: CCEO.DA,
    ssaGate: "SIT_NOT_DONE" as SsaGateState,
    priority: "CRITICAL",
    daysSinceLastSupport: 91,
    summary: "SIT not yet delivered — SSA cannot be administered.",
  },
  {
    id: "GAP-SCH-002",
    kind: "NO_SSA" as GapKind,
    entity: "school",
    schoolId: "SCH-002",
    schoolName: "Pader Hill Primary",
    district: "Pader",
    clusterId: "CLU-001",
    clusterName: "Kitgum North Cluster",
    assignedCceoId: CCEO.DA,
    ssaGate: "SIT_NOT_DONE" as SsaGateState,
    priority: "CRITICAL",
    daysSinceLastSupport: 78,
    summary: "SIT not yet delivered — SSA cannot be administered.",
  },
  {
    id: "GAP-SCH-003",
    kind: "NO_SSA" as GapKind,
    entity: "school",
    schoolId: "SCH-003",
    schoolName: "Lamwo Mission School",
    district: "Lamwo",
    clusterId: "CLU-002",
    clusterName: "Lamwo Border Cluster",
    assignedCceoId: CCEO.AH,
    ssaGate: "SIT_NOT_DONE" as SsaGateState,
    priority: "HIGH",
    daysSinceLastSupport: 62,
    summary: "SIT not yet delivered — SSA cannot be administered.",
  },
  {
    id: "GAP-SCH-004",
    kind: "NO_SSA" as GapKind,
    entity: "school",
    schoolId: "SCH-004",
    schoolName: "Agago Foundation Primary",
    district: "Agago",
    clusterId: "CLU-002",
    clusterName: "Lamwo Border Cluster",
    assignedCceoId: CCEO.AH,
    ssaGate: "SIT_NOT_DONE" as SsaGateState,
    priority: "HIGH",
    daysSinceLastSupport: 55,
    summary: "SIT not yet delivered — SSA cannot be administered.",
  },
  {
    id: "GAP-SCH-005",
    kind: "NO_SSA" as GapKind,
    entity: "school",
    schoolId: "SCH-005",
    schoolName: "Gulu Christian Academy",
    district: "Gulu",
    clusterId: "CLU-003",
    clusterName: "Gulu Central Cluster",
    assignedCceoId: CCEO.NL,
    ssaGate: "SIT_NOT_DONE" as SsaGateState,
    priority: "HIGH",
    daysSinceLastSupport: 49,
    summary: "SIT not yet delivered — SSA cannot be administered.",
  },
  {
    id: "GAP-SCH-006",
    kind: "NO_SSA" as GapKind,
    entity: "school",
    schoolId: "SCH-006",
    schoolName: "Lira Junior School",
    district: "Lira",
    clusterId: "CLU-003",
    clusterName: "Gulu Central Cluster",
    assignedCceoId: CCEO.NL,
    ssaGate: "SIT_NOT_DONE" as SsaGateState,
    priority: "NORMAL",
    daysSinceLastSupport: 41,
    summary: "SIT not yet delivered — SSA cannot be administered.",
  },

  // ════════════════════════════════════════════════════════════════
  // CLIENT SCHOOLS — SSA gate: SIT_DONE_SSA_MISSING (4+)
  // SIT happened, but SSA hasn't been completed. Only valid action:
  // COMPLETE_SSA. All intervention-based planning is locked.
  // ════════════════════════════════════════════════════════════════
  {
    id: "GAP-SCH-007",
    kind: "NO_SSA" as GapKind,
    entity: "school",
    schoolId: "SCH-007",
    schoolName: "Arua Hill Primary School",
    district: "Arua",
    clusterId: "CLU-004",
    clusterName: "West Nile Cluster",
    assignedCceoId: CCEO.PC,
    ssaGate: "SIT_DONE_SSA_MISSING" as SsaGateState,
    priority: "CRITICAL",
    daysSinceLastSupport: 88,
    summary: "SIT delivered Feb 2026 — SSA still outstanding.",
  },
  {
    id: "GAP-SCH-008",
    kind: "NO_SSA" as GapKind,
    entity: "school",
    schoolId: "SCH-008",
    schoolName: "Nebbi Mission School",
    district: "Nebbi",
    clusterId: "CLU-004",
    clusterName: "West Nile Cluster",
    assignedCceoId: CCEO.PC,
    ssaGate: "SIT_DONE_SSA_MISSING" as SsaGateState,
    priority: "CRITICAL",
    daysSinceLastSupport: 73,
    summary: "SIT delivered Mar 2026 — SSA still outstanding.",
  },
  {
    id: "GAP-SCH-009",
    kind: "NO_SSA" as GapKind,
    entity: "school",
    schoolId: "SCH-009",
    schoolName: "Galiraaya Primary School",
    district: "Kampala",
    clusterId: "CLU-005",
    clusterName: "Kampala East Cluster",
    assignedCceoId: CCEO.MO,
    ssaGate: "SIT_DONE_SSA_MISSING" as SsaGateState,
    priority: "HIGH",
    daysSinceLastSupport: 60,
    summary: "SIT delivered Mar 2026 — SSA still outstanding.",
  },
  {
    id: "GAP-SCH-010",
    kind: "NO_SSA" as GapKind,
    entity: "school",
    schoolId: "SCH-010",
    schoolName: "Wakiso Foundation School",
    district: "Wakiso",
    clusterId: "CLU-005",
    clusterName: "Kampala East Cluster",
    assignedCceoId: CCEO.MO,
    ssaGate: "SIT_DONE_SSA_MISSING" as SsaGateState,
    priority: "HIGH",
    daysSinceLastSupport: 52,
    summary: "SIT delivered Apr 2026 — SSA still outstanding.",
  },
  {
    id: "GAP-SCH-011",
    kind: "NO_SSA" as GapKind,
    entity: "school",
    schoolId: "SCH-011",
    schoolName: "Mukono Hope Academy",
    district: "Mukono",
    clusterId: "CLU-006",
    clusterName: "Mukono Central Cluster",
    assignedCceoId: CCEO.JN,
    ssaGate: "SIT_DONE_SSA_MISSING" as SsaGateState,
    priority: "HIGH",
    daysSinceLastSupport: 47,
    summary: "SIT delivered Apr 2026 — SSA still outstanding.",
  },

  // ════════════════════════════════════════════════════════════════
  // CLIENT SCHOOLS — SSA gate: SSA_COMPLETE_NOT_PLANNED (8+)
  // SSA complete with a known weakest intervention. Planning is now
  // unlocked. Mix kinds: NO_VISIT / NO_TRAINING / SSA_COMPLETE_NOT_PLANNED.
  // ════════════════════════════════════════════════════════════════
  {
    id: "GAP-SCH-012",
    kind: "NO_VISIT" as GapKind,
    entity: "school",
    schoolId: "SCH-012",
    schoolName: "Mbale Christian Primary",
    district: "Mbale",
    clusterId: "CLU-007",
    clusterName: "Mbale East Cluster",
    assignedCceoId: CCEO.AK,
    ssaGate: "SSA_COMPLETE_NOT_PLANNED" as SsaGateState,
    ssaCompletedOn: "2026-03-12",
    ssaWeakest:       { area: AREA.TL, score: 3.4 },
    ssaSecondWeakest: { area: AREA.LD, score: 5.8 },
    priority: "HIGH",
    daysSinceLastSupport: 79,
    summary: "Teaching & Learning scored 3.4/10 — no support visit booked yet.",
  },
  {
    id: "GAP-SCH-013",
    kind: "NO_VISIT" as GapKind,
    entity: "school",
    schoolId: "SCH-013",
    schoolName: "Tororo Junior School",
    district: "Tororo",
    clusterId: "CLU-007",
    clusterName: "Mbale East Cluster",
    assignedCceoId: CCEO.AK,
    ssaGate: "SSA_COMPLETE_NOT_PLANNED" as SsaGateState,
    ssaCompletedOn: "2026-02-22",
    ssaWeakest:       { area: AREA.LE, score: 4.1 },
    ssaSecondWeakest: { area: AREA.FH, score: 6.0 },
    priority: "HIGH",
    daysSinceLastSupport: 65,
    summary: "Learning Environment scored 4.1/10 — no support visit booked yet.",
  },
  {
    id: "GAP-SCH-014",
    kind: "NO_TRAINING" as GapKind,
    entity: "school",
    schoolId: "SCH-014",
    schoolName: "Soroti Foundation School",
    district: "Soroti",
    clusterId: "CLU-008",
    clusterName: "Soroti West Cluster",
    assignedCceoId: CCEO.DM,
    ssaGate: "SSA_COMPLETE_NOT_PLANNED" as SsaGateState,
    ssaCompletedOn: "2026-01-19",
    ssaWeakest:       { area: AREA.LD, score: 3.8 },
    ssaSecondWeakest: { area: AREA.TL, score: 5.5 },
    priority: "HIGH",
    daysSinceLastSupport: 58,
    summary: "Leadership scored 3.8/10 — School Improvement Training not yet planned.",
  },
  {
    id: "GAP-SCH-015",
    kind: "NO_TRAINING" as GapKind,
    entity: "school",
    schoolId: "SCH-015",
    schoolName: "Jinja Hill Primary",
    district: "Jinja",
    clusterId: "CLU-009",
    clusterName: "Jinja South Cluster",
    assignedCceoId: CCEO.JN,
    ssaGate: "SSA_COMPLETE_NOT_PLANNED" as SsaGateState,
    ssaCompletedOn: "2026-02-04",
    ssaWeakest:       { area: AREA.FH, score: 4.6 },
    ssaSecondWeakest: { area: AREA.GR, score: 6.2 },
    priority: "NORMAL",
    daysSinceLastSupport: 44,
    summary: "Financial Health scored 4.6/10 — training topic identified, not yet scheduled.",
  },
  {
    id: "GAP-SCH-016",
    kind: "SSA_COMPLETE_NOT_PLANNED" as GapKind,
    entity: "school",
    schoolId: "SCH-016",
    schoolName: "Iganga Christian School",
    district: "Iganga",
    clusterId: "CLU-009",
    clusterName: "Jinja South Cluster",
    assignedCceoId: CCEO.JN,
    ssaGate: "SSA_COMPLETE_NOT_PLANNED" as SsaGateState,
    ssaCompletedOn: "2026-02-15",
    ssaWeakest:       { area: AREA.CB, score: 4.2 },
    ssaSecondWeakest: { area: AREA.EW, score: 5.9 },
    priority: "HIGH",
    daysSinceLastSupport: 51,
    summary: "Christlike Behaviour scored 4.2/10 — no plan yet.",
  },
  {
    id: "GAP-SCH-017",
    kind: "SSA_COMPLETE_NOT_PLANNED" as GapKind,
    entity: "school",
    schoolId: "SCH-017",
    schoolName: "Mbarara Christian Academy",
    district: "Mbarara",
    clusterId: "CLU-010",
    clusterName: "Mbarara West Cluster",
    assignedCceoId: CCEO.PC,
    ssaGate: "SSA_COMPLETE_NOT_PLANNED" as SsaGateState,
    ssaCompletedOn: "2026-03-04",
    ssaWeakest:       { area: AREA.EW, score: 3.9 },
    ssaSecondWeakest: { area: AREA.CB, score: 6.1 },
    priority: "HIGH",
    daysSinceLastSupport: 54,
    summary: "Exposure to the Word of God scored 3.9/10 — no plan yet.",
  },
  {
    id: "GAP-SCH-018",
    kind: "NO_VISIT" as GapKind,
    entity: "school",
    schoolId: "SCH-018",
    schoolName: "Bushenyi Foundation Primary",
    district: "Bushenyi",
    clusterId: "CLU-010",
    clusterName: "Mbarara West Cluster",
    assignedCceoId: CCEO.PC,
    ssaGate: "SSA_COMPLETE_NOT_PLANNED" as SsaGateState,
    ssaCompletedOn: "2026-03-08",
    ssaWeakest:       { area: AREA.GR, score: 4.4 },
    ssaSecondWeakest: { area: AREA.LD, score: 6.4 },
    priority: "NORMAL",
    daysSinceLastSupport: 48,
    summary: "Government Requirements scored 4.4/10 — no support visit yet.",
  },
  {
    id: "GAP-SCH-019",
    kind: "NO_TRAINING" as GapKind,
    entity: "school",
    schoolId: "SCH-019",
    schoolName: "Kabarole Hill School",
    district: "Kabarole",
    clusterId: "CLU-008",
    clusterName: "Soroti West Cluster",
    assignedCceoId: CCEO.DM,
    ssaGate: "SSA_COMPLETE_NOT_PLANNED" as SsaGateState,
    ssaCompletedOn: "2026-02-26",
    ssaWeakest:       { area: AREA.ET, score: 3.2 },
    ssaSecondWeakest: { area: AREA.TL, score: 5.7 },
    priority: "HIGH",
    daysSinceLastSupport: 56,
    summary: "Education Technology scored 3.2/10 — training not scheduled.",
  },
  {
    id: "GAP-SCH-020",
    kind: "SSA_COMPLETE_NOT_PLANNED" as GapKind,
    entity: "school",
    schoolId: "SCH-020",
    schoolName: "Hoima Junior Primary",
    district: "Hoima",
    clusterId: "CLU-006",
    clusterName: "Mukono Central Cluster",
    assignedCceoId: CCEO.JN,
    ssaGate: "SSA_COMPLETE_NOT_PLANNED" as SsaGateState,
    ssaCompletedOn: "2026-03-21",
    ssaWeakest:       { area: AREA.PE, score: 4.7 },
    ssaSecondWeakest: { area: AREA.LE, score: 6.5 },
    priority: "NORMAL",
    daysSinceLastSupport: 39,
    summary: "Parent Engagement scored 4.7/10 — no plan yet.",
  },

  // ════════════════════════════════════════════════════════════════
  // CLIENT SCHOOLS — TRAINING_DONE_NO_FOLLOWUP (3+)
  // Training delivered, follow-up coaching/support visit not yet booked.
  // ════════════════════════════════════════════════════════════════
  {
    id: "GAP-SCH-021",
    kind: "TRAINING_DONE_NO_FOLLOWUP" as GapKind,
    entity: "school",
    schoolId: "SCH-021",
    schoolName: "Kitgum Vision Primary",
    district: "Kitgum",
    clusterId: "CLU-001",
    clusterName: "Kitgum North Cluster",
    assignedCceoId: CCEO.DA,
    ssaGate: "IN_PROGRESS" as SsaGateState,
    ssaCompletedOn: "2026-01-12",
    ssaWeakest:       { area: AREA.TL, score: 4.0 },
    ssaSecondWeakest: { area: AREA.LD, score: 6.0 },
    lastTrainingOn: "2026-04-18",
    priority: "NORMAL",
    daysSinceLastSupport: 42,
    summary: "Teaching & Learning training delivered Apr 18 — follow-up not booked.",
  },
  {
    id: "GAP-SCH-022",
    kind: "TRAINING_DONE_NO_FOLLOWUP" as GapKind,
    entity: "school",
    schoolId: "SCH-022",
    schoolName: "Pader Foundation School",
    district: "Pader",
    clusterId: "CLU-001",
    clusterName: "Kitgum North Cluster",
    assignedCceoId: CCEO.DA,
    ssaGate: "IN_PROGRESS" as SsaGateState,
    ssaCompletedOn: "2026-01-20",
    ssaWeakest:       { area: AREA.LD, score: 4.2 },
    ssaSecondWeakest: { area: AREA.GR, score: 6.3 },
    lastTrainingOn: "2026-04-26",
    priority: "NORMAL",
    daysSinceLastSupport: 34,
    summary: "Leadership training delivered Apr 26 — follow-up not booked.",
  },
  {
    id: "GAP-SCH-023",
    kind: "TRAINING_DONE_NO_FOLLOWUP" as GapKind,
    entity: "school",
    schoolId: "SCH-023",
    schoolName: "Lamwo Hill Primary",
    district: "Lamwo",
    clusterId: "CLU-002",
    clusterName: "Lamwo Border Cluster",
    assignedCceoId: CCEO.AH,
    ssaGate: "IN_PROGRESS" as SsaGateState,
    ssaCompletedOn: "2026-02-02",
    ssaWeakest:       { area: AREA.LE, score: 4.5 },
    ssaSecondWeakest: { area: AREA.FH, score: 5.6 },
    lastTrainingOn: "2026-05-04",
    priority: "NORMAL",
    daysSinceLastSupport: 26,
    summary: "Learning Environment training delivered May 4 — follow-up not booked.",
  },
  {
    id: "GAP-SCH-024",
    kind: "TRAINING_DONE_NO_FOLLOWUP" as GapKind,
    entity: "school",
    schoolId: "SCH-024",
    schoolName: "Arua Christian Primary",
    district: "Arua",
    clusterId: "CLU-004",
    clusterName: "West Nile Cluster",
    assignedCceoId: CCEO.PC,
    ssaGate: "IN_PROGRESS" as SsaGateState,
    ssaCompletedOn: "2026-02-08",
    ssaWeakest:       { area: AREA.CB, score: 4.6 },
    ssaSecondWeakest: { area: AREA.EW, score: 6.0 },
    lastTrainingOn: "2026-05-12",
    priority: "NORMAL",
    daysSinceLastSupport: 18,
    summary: "Christlike Behaviour training delivered May 12 — follow-up not booked.",
  },

  // ════════════════════════════════════════════════════════════════
  // CLIENT SCHOOLS — NO_CLUSTER (2+)
  // School isn't part of a peer-learning cluster yet.
  // ════════════════════════════════════════════════════════════════
  {
    id: "GAP-SCH-025",
    kind: "NO_CLUSTER" as GapKind,
    entity: "school",
    schoolId: "SCH-025",
    schoolName: "Soroti Vision School",
    district: "Soroti",
    assignedCceoId: CCEO.DM,
    ssaGate: "SSA_COMPLETE_NOT_PLANNED" as SsaGateState,
    ssaCompletedOn: "2026-03-15",
    ssaWeakest:       { area: AREA.PE, score: 5.2 },
    ssaSecondWeakest: { area: AREA.LE, score: 6.8 },
    priority: "LOW",
    daysSinceLastSupport: 32,
    summary: "Not yet assigned to a peer-learning cluster.",
  },
  {
    id: "GAP-SCH-026",
    kind: "NO_CLUSTER" as GapKind,
    entity: "school",
    schoolId: "SCH-026",
    schoolName: "Hoima Foundation Primary",
    district: "Hoima",
    assignedCceoId: CCEO.JN,
    ssaGate: "SSA_COMPLETE_NOT_PLANNED" as SsaGateState,
    ssaCompletedOn: "2026-03-25",
    ssaWeakest:       { area: AREA.ET, score: 5.0 },
    ssaSecondWeakest: { area: AREA.TL, score: 7.1 },
    priority: "LOW",
    daysSinceLastSupport: 30,
    summary: "Not yet assigned to a peer-learning cluster.",
  },

  // ════════════════════════════════════════════════════════════════
  // CLUSTER GAPS (6+)
  // Cluster-level pipeline: SIT first, then 3 meetings in order.
  // ════════════════════════════════════════════════════════════════
  {
    id: "GAP-CLU-001",
    kind: "CLUSTER_NO_SIT" as GapKind,
    entity: "cluster",
    clusterId: "CLU-001",
    clusterName: "Kitgum North Cluster",
    district: "Kitgum",
    assignedCceoId: CCEO.DA,
    schoolsInCluster: 7,
    schoolsWithSsa: 0,
    ssaGate: "SIT_NOT_DONE" as SsaGateState,
    priority: "CRITICAL",
    summary: "SIT not delivered — none of the 7 cluster schools have SSAs.",
  },
  {
    id: "GAP-CLU-002",
    kind: "CLUSTER_SSA_MISSING" as GapKind,
    entity: "cluster",
    clusterId: "CLU-004",
    clusterName: "West Nile Cluster",
    district: "Arua",
    assignedCceoId: CCEO.PC,
    schoolsInCluster: 6,
    schoolsWithSsa: 0,
    ssaGate: "SIT_DONE_SSA_MISSING" as SsaGateState,
    priority: "CRITICAL",
    summary: "SIT delivered — 6 of 6 schools still need SSA completed.",
  },
  {
    id: "GAP-CLU-003",
    kind: "CLUSTER_NO_FIRST_MEETING" as GapKind,
    entity: "cluster",
    clusterId: "CLU-005",
    clusterName: "Kampala East Cluster",
    district: "Kampala",
    assignedCceoId: CCEO.MO,
    schoolsInCluster: 5,
    schoolsWithSsa: 3,
    ssaGate: "IN_PROGRESS" as SsaGateState,
    priority: "LOW",
    summary: "SIT complete — first cluster meeting not yet scheduled.",
  },
  {
    id: "GAP-CLU-004",
    kind: "CLUSTER_NO_SECOND_MEETING" as GapKind,
    entity: "cluster",
    clusterId: "CLU-006",
    clusterName: "Mukono Central Cluster",
    district: "Mukono",
    assignedCceoId: CCEO.JN,
    schoolsInCluster: 6,
    schoolsWithSsa: 5,
    ssaGate: "IN_PROGRESS" as SsaGateState,
    priority: "LOW",
    summary: "First meeting complete Apr 24 — second meeting outstanding.",
  },
  {
    id: "GAP-CLU-005",
    kind: "CLUSTER_NO_THIRD_MEETING" as GapKind,
    entity: "cluster",
    clusterId: "CLU-007",
    clusterName: "Mbale East Cluster",
    district: "Mbale",
    assignedCceoId: CCEO.AK,
    schoolsInCluster: 5,
    schoolsWithSsa: 5,
    ssaGate: "IN_PROGRESS" as SsaGateState,
    priority: "LOW",
    summary: "Meetings 1 + 2 complete — third meeting outstanding.",
  },
  {
    id: "GAP-CLU-006",
    kind: "CLUSTER_TRAINING_NEEDED" as GapKind,
    entity: "cluster",
    clusterId: "CLU-008",
    clusterName: "Soroti West Cluster",
    district: "Soroti",
    assignedCceoId: CCEO.DM,
    schoolsInCluster: 6,
    schoolsWithSsa: 4,
    ssaGate: "SSA_COMPLETE_NOT_PLANNED" as SsaGateState,
    ssaWeakest:       { area: AREA.ET, score: 3.6 },
    ssaSecondWeakest: { area: AREA.TL, score: 5.8 },
    priority: "HIGH",
    summary: "Cluster-wide weakest area: Education Technology (3.6/10). Training needed.",
  },
  {
    id: "GAP-CLU-007",
    kind: "CLUSTER_NO_FIRST_MEETING" as GapKind,
    entity: "cluster",
    clusterId: "CLU-002",
    clusterName: "Lamwo Border Cluster",
    district: "Lamwo",
    assignedCceoId: CCEO.AH,
    schoolsInCluster: 6,
    schoolsWithSsa: 0,
    ssaGate: "SIT_DONE_SSA_MISSING" as SsaGateState,
    priority: "NORMAL",
    summary: "SIT delivered — first meeting outstanding, SSAs still missing.",
  },

  // ════════════════════════════════════════════════════════════════
  // CORE SCHOOLS (8+)
  // The 4-visit + 2-training Core School support package.
  // ════════════════════════════════════════════════════════════════
  {
    id: "GAP-COR-001",
    kind: "CORE_NO_SSA" as GapKind,
    entity: "core_school",
    schoolId: "SCH-027",
    schoolName: "St. Agnes Core Primary",
    district: "Gulu",
    clusterId: "CLU-003",
    clusterName: "Gulu Central Cluster",
    assignedCceoId: CCEO.NL,
    ssaGate: "SIT_DONE_SSA_MISSING" as SsaGateState,
    priority: "CRITICAL",
    daysSinceLastSupport: 70,
    summary: "Core school — SSA not completed. Package cannot start.",
  },
  {
    id: "GAP-COR-002",
    kind: "CORE_MISSING_VISIT_1" as GapKind,
    entity: "core_school",
    schoolId: "SCH-028",
    schoolName: "Lira Core Academy",
    district: "Lira",
    clusterId: "CLU-003",
    clusterName: "Gulu Central Cluster",
    assignedCceoId: CCEO.NL,
    ssaGate: "SSA_COMPLETE_NOT_PLANNED" as SsaGateState,
    ssaCompletedOn: "2026-02-10",
    ssaWeakest:       { area: AREA.TL, score: 3.0 },
    ssaSecondWeakest: { area: AREA.LD, score: 5.5 },
    priority: "HIGH",
    daysSinceLastSupport: 80,
    summary: "Visit 1 of 4 not yet scheduled. Weakest area: Teaching & Learning (3.0/10).",
  },
  {
    id: "GAP-COR-003",
    kind: "CORE_MISSING_VISIT_2" as GapKind,
    entity: "core_school",
    schoolId: "SCH-029",
    schoolName: "Mbarara Core Mission",
    district: "Mbarara",
    clusterId: "CLU-010",
    clusterName: "Mbarara West Cluster",
    assignedCceoId: CCEO.PC,
    ssaGate: "IN_PROGRESS" as SsaGateState,
    ssaCompletedOn: "2026-01-22",
    ssaWeakest:       { area: AREA.LD, score: 3.5 },
    ssaSecondWeakest: { area: AREA.GR, score: 5.7 },
    priority: "HIGH",
    daysSinceLastSupport: 36,
    summary: "Visit 1 complete Apr 24 — Visit 2 of 4 not yet scheduled.",
  },
  {
    id: "GAP-COR-004",
    kind: "CORE_MISSING_VISIT_3" as GapKind,
    entity: "core_school",
    schoolId: "SCH-030",
    schoolName: "Kabarole Core Primary",
    district: "Kabarole",
    clusterId: "CLU-008",
    clusterName: "Soroti West Cluster",
    assignedCceoId: CCEO.DM,
    ssaGate: "IN_PROGRESS" as SsaGateState,
    ssaCompletedOn: "2026-01-08",
    ssaWeakest:       { area: AREA.LE, score: 3.7 },
    ssaSecondWeakest: { area: AREA.PE, score: 6.1 },
    priority: "HIGH",
    daysSinceLastSupport: 28,
    summary: "Visits 1 + 2 complete — Visit 3 of 4 not yet scheduled.",
  },
  {
    id: "GAP-COR-005",
    kind: "CORE_MISSING_VISIT_4" as GapKind,
    entity: "core_school",
    schoolId: "SCH-031",
    schoolName: "Iganga Core Christian",
    district: "Iganga",
    clusterId: "CLU-009",
    clusterName: "Jinja South Cluster",
    assignedCceoId: CCEO.JN,
    ssaGate: "IN_PROGRESS" as SsaGateState,
    ssaCompletedOn: "2026-01-15",
    ssaWeakest:       { area: AREA.CB, score: 4.0 },
    ssaSecondWeakest: { area: AREA.EW, score: 5.9 },
    priority: "NORMAL",
    daysSinceLastSupport: 22,
    summary: "Visits 1–3 complete — Visit 4 (closing) not yet scheduled.",
  },
  {
    id: "GAP-COR-006",
    kind: "CORE_MISSING_TRAINING_1" as GapKind,
    entity: "core_school",
    schoolId: "SCH-032",
    schoolName: "Tororo Core Foundation",
    district: "Tororo",
    clusterId: "CLU-007",
    clusterName: "Mbale East Cluster",
    assignedCceoId: CCEO.AK,
    ssaGate: "SSA_COMPLETE_NOT_PLANNED" as SsaGateState,
    ssaCompletedOn: "2026-02-19",
    ssaWeakest:       { area: AREA.FH, score: 3.3 },
    ssaSecondWeakest: { area: AREA.GR, score: 5.6 },
    priority: "HIGH",
    daysSinceLastSupport: 64,
    summary: "Training 1 of 2 not yet scheduled. Weakest area: Financial Health (3.3/10).",
  },
  {
    id: "GAP-COR-007",
    kind: "CORE_MISSING_TRAINING_2" as GapKind,
    entity: "core_school",
    schoolId: "SCH-033",
    schoolName: "Jinja Core Vision Primary",
    district: "Jinja",
    clusterId: "CLU-009",
    clusterName: "Jinja South Cluster",
    assignedCceoId: CCEO.JN,
    ssaGate: "IN_PROGRESS" as SsaGateState,
    ssaCompletedOn: "2026-01-29",
    ssaWeakest:       { area: AREA.GR, score: 3.9 },
    ssaSecondWeakest: { area: AREA.LD, score: 5.4 },
    priority: "HIGH",
    daysSinceLastSupport: 35,
    summary: "Training 1 complete — Training 2 of 2 not yet scheduled.",
  },
  {
    id: "GAP-COR-008",
    kind: "CORE_PACKAGE_INCOMPLETE" as GapKind,
    entity: "core_school",
    schoolId: "SCH-034",
    schoolName: "Mbale Core Christian",
    district: "Mbale",
    clusterId: "CLU-007",
    clusterName: "Mbale East Cluster",
    assignedCceoId: CCEO.AK,
    ssaGate: "IN_PROGRESS" as SsaGateState,
    ssaCompletedOn: "2026-02-01",
    ssaWeakest:       { area: AREA.PE, score: 4.2 },
    ssaSecondWeakest: { area: AREA.LE, score: 6.3 },
    priority: "NORMAL",
    daysSinceLastSupport: 31,
    summary: "Core package incomplete: 2 of 4 visits done, 1 of 2 trainings done.",
  },
  {
    id: "GAP-COR-009",
    kind: "CORE_CHAMPION_REVIEW" as GapKind,
    entity: "core_school",
    schoolId: "SCH-035",
    schoolName: "Bushenyi Core Academy",
    district: "Bushenyi",
    clusterId: "CLU-010",
    clusterName: "Mbarara West Cluster",
    assignedCceoId: CCEO.PC,
    ssaGate: "IN_PROGRESS" as SsaGateState,
    ssaCompletedOn: "2026-01-12",
    ssaWeakest:       { area: AREA.TL, score: 4.5 },
    ssaSecondWeakest: { area: AREA.LD, score: 6.0 },
    lastTrainingOn: "2026-04-30",
    priority: "NORMAL",
    daysSinceLastSupport: 30,
    summary: "Champion review due — full package delivered, post-package check-in outstanding.",
  },

  // ════════════════════════════════════════════════════════════════
  // PARTNER-DELIVERED GAPS (5+)
  // Activities a partner organisation owns. Edify tracks status only.
  // ════════════════════════════════════════════════════════════════
  {
    id: "GAP-PRT-001",
    kind: "PARTNER_ASSIGNED_NOT_SCHEDULED" as GapKind,
    entity: "school",
    schoolId: "SCH-036",
    schoolName: "Nebbi Vision Primary",
    district: "Nebbi",
    clusterId: "CLU-004",
    clusterName: "West Nile Cluster",
    assignedCceoId: CCEO.PC,
    partnerId: PARTNER.LRV,
    partnerName: "Living River Ventures",
    ssaGate: "SSA_COMPLETE_NOT_PLANNED" as SsaGateState,
    ssaCompletedOn: "2026-03-02",
    ssaWeakest:       { area: AREA.LE, score: 4.3 },
    ssaSecondWeakest: { area: AREA.FH, score: 6.2 },
    priority: "HIGH",
    daysSinceLastSupport: 50,
    summary: "Partner LRV assigned for WASH intervention — date not yet on calendar.",
  },
  {
    id: "GAP-PRT-002",
    kind: "PARTNER_SCHEDULED" as GapKind,
    entity: "school",
    schoolId: "SCH-037",
    schoolName: "Agago Christian Primary",
    district: "Agago",
    clusterId: "CLU-002",
    clusterName: "Lamwo Border Cluster",
    assignedCceoId: CCEO.AH,
    partnerId: PARTNER.SDC,
    partnerName: "Sustainable Development Coalition",
    ssaGate: "IN_PROGRESS" as SsaGateState,
    ssaCompletedOn: "2026-02-12",
    ssaWeakest:       { area: AREA.ET, score: 4.0 },
    ssaSecondWeakest: { area: AREA.TL, score: 5.9 },
    priority: "NORMAL",
    daysSinceLastSupport: 20,
    summary: "Partner SDC EdTech rollout scheduled Jun 18, 2026.",
  },
  {
    id: "GAP-PRT-003",
    kind: "PARTNER_DELAYED" as GapKind,
    entity: "school",
    schoolId: "SCH-038",
    schoolName: "Gulu Vision Foundation",
    district: "Gulu",
    clusterId: "CLU-003",
    clusterName: "Gulu Central Cluster",
    assignedCceoId: CCEO.NL,
    partnerId: PARTNER.AYM,
    partnerName: "Acholi Youth Mission",
    ssaGate: "IN_PROGRESS" as SsaGateState,
    ssaCompletedOn: "2026-01-30",
    ssaWeakest:       { area: AREA.CB, score: 3.8 },
    ssaSecondWeakest: { area: AREA.EW, score: 5.5 },
    priority: "HIGH",
    daysSinceLastSupport: 73,
    summary: "Partner AYM Christian Behaviour workshop delayed — original date Apr 14, no new date proposed.",
  },
  {
    id: "GAP-PRT-004",
    kind: "PARTNER_RESCHEDULED" as GapKind,
    entity: "school",
    schoolId: "SCH-039",
    schoolName: "Kampala Vision Primary",
    district: "Kampala",
    clusterId: "CLU-005",
    clusterName: "Kampala East Cluster",
    assignedCceoId: CCEO.MO,
    partnerId: PARTNER.LRV,
    partnerName: "Living River Ventures",
    ssaGate: "IN_PROGRESS" as SsaGateState,
    ssaCompletedOn: "2026-02-18",
    ssaWeakest:       { area: AREA.LE, score: 4.1 },
    ssaSecondWeakest: { area: AREA.PE, score: 6.0 },
    priority: "NORMAL",
    daysSinceLastSupport: 41,
    summary: "Partner LRV WASH visit rescheduled twice — currently Jul 2, 2026.",
  },
  {
    id: "GAP-PRT-005",
    kind: "PARTNER_EVIDENCE_PENDING" as GapKind,
    entity: "school",
    schoolId: "SCH-040",
    schoolName: "Wakiso Christian Primary",
    district: "Wakiso",
    clusterId: "CLU-005",
    clusterName: "Kampala East Cluster",
    assignedCceoId: CCEO.MO,
    partnerId: PARTNER.SDC,
    partnerName: "Sustainable Development Coalition",
    ssaGate: "IN_PROGRESS" as SsaGateState,
    ssaCompletedOn: "2026-02-25",
    ssaWeakest:       { area: AREA.ET, score: 4.4 },
    ssaSecondWeakest: { area: AREA.TL, score: 6.2 },
    lastTrainingOn: "2026-05-08",
    priority: "NORMAL",
    daysSinceLastSupport: 22,
    summary: "Partner SDC delivered EdTech training May 8 — completion evidence not yet uploaded.",
  },
];

// ────────── Exports ──────────

export const PLANNING_GAPS: PlanningGap[] = RAW.map(seed);

export const planningTabs: PlanningGapTabs = groupGapsForTabs(PLANNING_GAPS);

export function gapsForCceo(cceoId: string): PlanningGap[] {
  return PLANNING_GAPS.filter((g) => g.assignedCceoId === cceoId);
}
