# Generated by Django 5.2.4 on 2026-06-26 21:38

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('school_visit', 'School Visit'), ('follow_up_visit', 'Follow-up Visit'), ('coaching_visit', 'Coaching Visit'), ('in_school_support', 'In-school Support'), ('training', 'Training'), ('school_improvement_training', 'School Improvement Training'), ('cluster_meeting', 'Cluster Meeting'), ('cluster_training', 'Cluster Training'), ('ssa_activity', 'SSA Activity'), ('project_activity', 'Project Activity'), ('partner_activity', 'Partner Activity'), ('core_visit', 'Core Visit'), ('core_training', 'Core Training')], max_length=48)),
                ('project_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fy', models.CharField(max_length=16)),
                ('quarter', models.CharField(max_length=8)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('planned_month', models.IntegerField(blank=True, null=True)),
                ('planned_week', models.IntegerField(blank=True, null=True)),
                ('responsible_staff_id', models.CharField(blank=True, max_length=30, null=True)),
                ('monitored_by_staff_id', models.CharField(blank=True, max_length=30, null=True)),
                ('assigned_partner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('delivery_type', models.CharField(choices=[('staff', 'Staff'), ('partner', 'Partner')], default='staff', max_length=16)),
                ('cluster_slot', models.CharField(blank=True, choices=[('sit', 'SIT'), ('first_meeting', 'First Meeting'), ('second_meeting', 'Second Meeting'), ('third_meeting', 'Third Meeting')], max_length=16, null=True)),
                ('purpose_intervention', models.CharField(blank=True, choices=[('teaching_and_learning', 'Teaching & Learning'), ('financial_health', 'Financial Health'), ('christlike_behaviour', 'Christlike Behaviour'), ('exposure_to_word_of_god', 'Exposure to Word of God'), ('government_requirements', 'Government Requirements'), ('leadership', 'Leadership'), ('education_technology', 'Education Technology'), ('learning_environment', 'Learning Environment')], max_length=64, null=True)),
                ('status', models.CharField(choices=[('not_planned', 'Not Planned'), ('planned', 'Planned'), ('scheduled', 'Scheduled'), ('assigned_to_partner', 'Assigned to Partner'), ('partner_scheduled', 'Partner Scheduled'), ('in_progress', 'In Progress'), ('completion_started', 'Completion Started'), ('evidence_uploaded', 'Evidence Uploaded'), ('evidence_accepted', 'Evidence Accepted'), ('salesforce_id_required', 'Salesforce ID Required'), ('submitted_to_pl', 'Submitted to PL'), ('returned_by_pl', 'Returned by PL'), ('awaiting_ia_verification', 'Awaiting IA Verification'), ('ia_verified', 'IA Verified'), ('accountant_confirmed', 'Accountant Confirmed'), ('completed', 'Completed'), ('returned', 'Returned'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('deferred', 'Deferred')], default='not_planned', max_length=32)),
                ('evidence_status', models.CharField(choices=[('none', 'None'), ('uploaded', 'Uploaded'), ('accepted', 'Accepted'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='none', max_length=16)),
                ('salesforce_activity_id', models.CharField(blank=True, max_length=128, null=True)),
                ('salesforce_activity_type', models.CharField(blank=True, max_length=16, null=True)),
                ('ia_verification_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('returned', 'Returned'), ('flagged', 'Flagged')], default='pending', max_length=16)),
                ('ia_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('ia_confirmed_by', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_status', models.CharField(choices=[('none', 'None'), ('pending_ia', 'Pending IA'), ('ia_confirmed', 'IA Confirmed'), ('pl_approval_required', 'PL Approval Required'), ('pl_approved', 'PL Approved'), ('accountant_cleared', 'Accountant Cleared'), ('paid', 'Paid'), ('netsuite_accountability', 'Netsuite Accountability'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='none', max_length=32)),
                ('reschedule_count', models.IntegerField(default=0)),
                ('last_reason', models.CharField(blank=True, max_length=512, null=True)),
                ('est_cost_cents', models.IntegerField(default=0)),
                ('cost_missing', models.BooleanField(default=False)),
                ('pl_review_note', models.CharField(blank=True, max_length=512, null=True)),
                ('pl_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('pl_reviewed_by', models.CharField(blank=True, max_length=30, null=True)),
                ('teachers_attended', models.IntegerField(blank=True, null=True)),
                ('leaders_attended', models.IntegerField(blank=True, null=True)),
                ('other_participants', models.IntegerField(blank=True, null=True)),
                ('next_meeting_date', models.DateTimeField(blank=True, null=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='clusters.cluster')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='schools.school')),
            ],
            options={
                'db_table': 'activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityCompletionVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('salesforce_id', models.CharField(max_length=128)),
                ('entered_by', models.CharField(max_length=30)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('returned', 'Returned'), ('flagged', 'Flagged')], default='pending', max_length=16)),
                ('ia_actor_id', models.CharField(blank=True, max_length=30, null=True)),
                ('ia_action_at', models.DateTimeField(blank=True, null=True)),
                ('ia_note', models.CharField(blank=True, max_length=512, null=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='activities.activity')),
            ],
            options={
                'db_table': 'activity_completion_verification',
            },
        ),
        migrations.CreateModel(
            name='ActivityScheduleCostLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('cost_setting_key', models.CharField(max_length=128)),
                ('label', models.CharField(max_length=255)),
                ('unit_cost', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.IntegerField()),
                ('cost_setting_version', models.IntegerField(default=1)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_cost_lines', to='activities.activity')),
            ],
            options={
                'db_table': 'activity_schedule_cost_line',
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['school'], name='activity_school__03d4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['cluster'], name='activity_cluster_1af84f_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['fy', 'quarter'], name='activity_fy_8be759_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['responsible_staff_id'], name='activity_respons_711310_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status'], name='activity_status_ebaa20_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['scheduled_date'], name='activity_schedul_398a42_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['assigned_partner_id'], name='activity_assigne_f20ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['ia_verification_status', 'payment_status'], name='activity_ia_veri_4001c9_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['evidence_status'], name='activity_evidenc_78c12a_idx'),
        ),
        migrations.AddIndex(
            model_name='activityschedulecostline',
            index=models.Index(fields=['activity'], name='activity_sc_activit_1991a7_idx'),
        ),
    ]
