// Database adapter — Prisma singleton.
//
// Two modes:
//
//   • `mock` — no client; the action layer reads/writes the
//     in-memory entity store in `src/lib/actions/store.ts`. Default.
//
//   • `prisma` — Prisma client, singleton per process. Connection
//     pool sized for serverless (1 connection / function instance).
//     Activated when DATABASE_URL is set.
//
// The client is intentionally `unknown` to the type system in this
// file — pulling `@prisma/client` here would force the type into
// every page that imports `infra`. Instead each consumer who actually
// needs the client imports the runtime-generated `@prisma/client`
// type alongside this adapter.

import "server-only";

export type DbAdapter = {
  label: string;
  mode: "mock" | "prisma";
  /**
   * Returns the live PrismaClient instance when `mode === "prisma"`.
   * Returns null in mock mode. Lazy — the client is constructed on
   * first call.
   */
  prisma(): unknown | null;
  /** Disconnects in prisma mode. No-op otherwise. */
  disconnect(): Promise<void>;
};

// ────────── mock impl ──────────────────────────────────────────────

const mockAdapter: DbAdapter = {
  label: "mock",
  mode: "mock",
  prisma() { return null; },
  async disconnect() { /* no-op */ },
};

// ────────── prisma impl ────────────────────────────────────────────
//
// Lazy import — the client is generated by `prisma generate` from the
// schema; if the generator hasn't run yet (or the project is in mock
// mode), we must not crash at import time.

function makePrismaAdapter(): DbAdapter {
  // Reuse the same instance across HMR by stashing on globalThis.
  // Same pattern Vercel recommends to avoid connection-pool exhaustion.
  const GLOBAL_KEY = "__edify_prisma_client__";
  let client: unknown | null = null;

  function getClient(): unknown {
    if (client) return client;
    const g = globalThis as { [k: string]: unknown };
    if (g[GLOBAL_KEY]) {
      client = g[GLOBAL_KEY];
      return client;
    }
    // Lazy import — the @prisma/client package must be installed and
    // generated before this runs. If it's not, throw a clean error
    // rather than crashing on a cryptic require. (0, eval)('require')
    // keeps the bundler from trying to statically resolve.
    let PrismaClient: unknown;
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const dynamicRequire: any = (0, eval)("require");
      PrismaClient = (dynamicRequire("@prisma/client") as { PrismaClient: unknown }).PrismaClient;
    } catch (err) {
      throw new Error(
        "DATABASE_URL is set but @prisma/client is not generated. " +
        "Run `npx prisma generate` then `npx prisma migrate deploy`. " +
        `Underlying error: ${String(err)}`,
      );
    }
    // PrismaClient constructor — typed as any here because we don't
    // want to pull the generated type into the adapter contract.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    client = new (PrismaClient as any)({
      log: process.env.PRISMA_LOG === "1" ? ["query", "info", "warn", "error"] : ["error"],
    });
    if (process.env.NODE_ENV !== "production") {
      g[GLOBAL_KEY] = client;
    }
    return client;
  }

  return {
    label: "prisma",
    mode: "prisma",
    prisma() { return getClient(); },
    async disconnect() {
      const c = client as { $disconnect?: () => Promise<void> } | null;
      if (c?.$disconnect) await c.$disconnect();
      client = null;
    },
  };
}

// ────────── resolver ────────────────────────────────────────────────

export function resolveDb(): DbAdapter {
  if (process.env.DATABASE_URL && process.env.EDIFY_USE_PRISMA !== "0") {
    try { return makePrismaAdapter(); }
    catch (err) {
      // eslint-disable-next-line no-console
      console.warn("[edify-infra] db: Prisma init failed; using mock. Reason:", String(err));
    }
  }
  return mockAdapter;
}
