# Generated by Django 5.2.17 on 2026-09-29 08:38

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffUsageFollowUp",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("manager_to_staff", "Manager to staff member"),
                            ("director_to_manager", "Country Director to manager"),
                        ],
                        default="manager_to_staff",
                        max_length=24,
                    ),
                ),
                ("period_key", models.CharField(default="day", max_length=16)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("no_login", "No login"),
                            ("low_engagement", "Low platform engagement"),
                            ("planning_not_done", "Required planning not completed"),
                            ("evidence_not_done", "Evidence work not completed"),
                            ("repeated_errors", "Repeated system errors"),
                            ("workflow_support", "Workflow support required"),
                            (
                                "excessive_time",
                                "Excessive time / possible usability problem",
                            ),
                            ("training", "Training required"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("note", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        max_length=8,
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("acknowledged", "Acknowledged"),
                            ("support_scheduled", "Support scheduled"),
                            ("waiting_for_staff", "Waiting for staff"),
                            ("resolved_by_activity", "Resolved by activity"),
                            ("resolved_by_manager", "Resolved by manager"),
                            ("returned", "Returned for clarification"),
                            ("escalated", "Escalated"),
                            ("closed", "Closed"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="sent",
                        max_length=24,
                    ),
                ),
                ("resolution", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("history", models.JSONField(blank=True, default=list)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_follow_ups_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_follow_ups_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_follow_ups_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_follow_ups_about",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "staff_usage_follow_up",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["assignee", "status"], name="usage_fu_assignee_status"
                    ),
                    models.Index(
                        fields=["subject", "status"], name="usage_fu_subject_status"
                    ),
                    models.Index(
                        fields=["created_by", "status"], name="usage_fu_creator_status"
                    ),
                ],
            },
        ),
    ]
