# Generated by Django 5.2.4 on 2026-06-26 23:00

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FundRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fy", models.CharField(max_length=16)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        max_length=16,
                    ),
                ),
                ("period_key", models.CharField(max_length=32)),
                ("scope", models.CharField(max_length=16)),
                ("submitted_by_user_id", models.CharField(max_length=30)),
                ("submitted_by_role", models.CharField(max_length=64)),
                ("total_amount", models.FloatField()),
                ("activity_count", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("returned", "Returned"),
                            ("rejected", "Rejected"),
                            ("disbursed", "Disbursed"),
                            ("draft", "Draft"),
                            ("submitted_to_pl", "Submitted to PL"),
                            ("approved_by_pl", "Approved by PL"),
                            ("submitted_to_cd", "Submitted to CD"),
                            ("approved_by_cd", "Approved by CD"),
                            ("submitted_to_rvp", "Submitted to RVP"),
                            ("approved_by_rvp", "Approved by RVP"),
                            ("sent_to_accountant", "Sent to Accountant"),
                            ("closed", "Closed"),
                            ("returned_by_pl", "Returned by PL"),
                            ("returned_by_cd", "Returned by CD"),
                            ("returned_by_rvp", "Returned by RVP"),
                            ("returned_by_accountant", "Returned by Accountant"),
                        ],
                        default="submitted",
                        max_length=32,
                    ),
                ),
                (
                    "reviewed_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_note",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("disbursed_amount", models.FloatField(blank=True, null=True)),
                ("disbursed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "disbursed_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "disburse_method",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "disburse_reference",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("accounted_amount", models.FloatField(blank=True, null=True)),
                ("returned_amount", models.FloatField(blank=True, null=True)),
                (
                    "accountability_status",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "accountability_netsuite_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "accountability_submitted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "accountability_reviewed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "fund_request",
                "indexes": [
                    models.Index(
                        fields=["status"], name="fund_reques_status_9abf3b_idx"
                    ),
                    models.Index(
                        fields=["fy", "period"], name="fund_reques_fy_245341_idx"
                    ),
                    models.Index(
                        fields=["submitted_by_user_id"],
                        name="fund_reques_submitt_b19958_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("submitted_by_user_id", "period", "period_key"),
                        name="uniq_request_period_owner",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FundRequestItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("activity_id", models.CharField(max_length=30)),
                ("activity_schedule_cost_line_id", models.CharField(max_length=30)),
                ("amount", models.FloatField()),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        max_length=16,
                    ),
                ),
                ("period_key", models.CharField(max_length=32)),
                ("added_after_generation", models.BooleanField(default=False)),
                (
                    "fund_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fund_requests.fundrequest",
                    ),
                ),
            ],
            options={
                "db_table": "fund_request_item",
                "indexes": [
                    models.Index(
                        fields=["activity_id"], name="fund_reques_activit_c76a4a_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fund_request", "activity_schedule_cost_line_id"),
                        name="uniq_request_costline",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "activity_schedule_cost_line_id",
                            "period",
                            "period_key",
                        ),
                        name="uniq_costline_period",
                    ),
                ],
            },
        ),
    ]
