# Generated by Django 5.2.4 on 2026-07-03 01:29

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0010_alter_activity_status_duplicateactivity_and_more"),
        ("fund_requests", "0005_weeklyfundrequest_weeklyfundrequestline"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountabilityRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("staff_id", models.CharField(max_length=30)),
                ("amount_disbursed", models.BigIntegerField()),
                ("actual_spend", models.BigIntegerField()),
                ("variance", models.BigIntegerField()),
                ("variance_reason", models.TextField(blank=True, null=True)),
                (
                    "netsuite_expense_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("status", models.CharField(default="pending", max_length=32)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=30, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accountability_records",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "accountability_record",
            },
        ),
        migrations.CreateModel(
            name="Disbursement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_disbursed", models.BigIntegerField()),
                (
                    "disbursed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("disbursed_by", models.CharField(max_length=30)),
                ("payment_method", models.CharField(max_length=64)),
                ("payment_reference", models.CharField(max_length=128)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disbursements",
                        to="activities.activity",
                    ),
                ),
                (
                    "fund_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fund_requests.fundrequest",
                    ),
                ),
            ],
            options={
                "db_table": "disbursement",
            },
        ),
        migrations.CreateModel(
            name="FinanceAuditLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("actor_id", models.CharField(max_length=30)),
                ("actor_role", models.CharField(max_length=64)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_audit_logs",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "finance_audit_log",
            },
        ),
        migrations.CreateModel(
            name="FinanceReturn",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("returned_to", models.CharField(max_length=30)),
                ("returned_by", models.CharField(max_length=30)),
                ("reason", models.TextField()),
                (
                    "returned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("status", models.CharField(default="pending", max_length=32)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_returns",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "finance_return",
            },
        ),
        migrations.CreateModel(
            name="NetSuiteExpenseRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("netsuite_expense_id", models.CharField(max_length=128, unique=True)),
                ("expense_date", models.DateField()),
                ("amount_entered", models.BigIntegerField()),
                ("entered_by", models.CharField(max_length=30)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netsuite_expenses",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "netsuite_expense_record",
            },
        ),
        migrations.CreateModel(
            name="PartnerPayment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("partner_name", models.CharField(max_length=255)),
                ("amount_paid", models.BigIntegerField()),
                ("payment_method", models.CharField(max_length=64)),
                ("payment_reference", models.CharField(max_length=128)),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("paid_by", models.CharField(max_length=30)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_payments",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "partner_payment",
            },
        ),
        migrations.CreateModel(
            name="ReimbursementClaim",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("staff_id", models.CharField(max_length=30)),
                ("approved_budget", models.BigIntegerField()),
                ("amount_advanced", models.BigIntegerField(default=0)),
                ("actual_spend", models.BigIntegerField()),
                ("reimbursement_amount", models.BigIntegerField()),
                ("status", models.CharField(default="pending", max_length=32)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("paid_by", models.CharField(blank=True, max_length=30, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reimbursement_claims",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "reimbursement_claim",
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("uri", models.CharField(max_length=512)),
                ("file_size", models.BigIntegerField()),
                ("mime_type", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "accountability_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="fund_requests.accountabilityrecord",
                    ),
                ),
                (
                    "reimbursement_claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="fund_requests.reimbursementclaim",
                    ),
                ),
            ],
            options={
                "db_table": "finance_receipt",
            },
        ),
        migrations.CreateModel(
            name="VarianceReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("budgeted_amount", models.BigIntegerField()),
                ("disbursed_amount", models.BigIntegerField()),
                ("actual_spend", models.BigIntegerField()),
                ("variance", models.BigIntegerField()),
                ("reason", models.TextField()),
                ("status", models.CharField(default="pending", max_length=32)),
                ("reviewed_by", models.CharField(blank=True, max_length=30, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variance_reviews",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "variance_review",
            },
        ),
    ]
