# Generated by Django 5.2.4 on 2026-07-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0021_activitysalesforcereference"),
        ("fund_requests", "0008_advancerequest_reimburse_method_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="partnerpayment",
            constraint=models.UniqueConstraint(
                fields=("activity",), name="uniq_partner_payment_per_activity"
            ),
        ),
    ]
