# Generated by Django 5.2.16 on 2026-08-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_requests', '0010_monthly_team_request_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyfundrequest',
            name='receipt_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
