# Generated by Django 5.2.16 on 2026-08-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0040_alter_activity_est_cost_cents"),
        ("fund_requests", "0012_advancerequest_accountability_pl_approved_at_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="partnerpayment",
            name="uniq_partner_payment_per_activity",
        ),
        migrations.AddField(
            model_name="partnerpayment",
            name="payment_type",
            field=models.CharField(
                choices=[("advance", "50% MOU Advance"), ("clearance", "Clearance")],
                default="clearance",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerpayment",
            constraint=models.UniqueConstraint(
                fields=("activity", "payment_type"),
                name="uniq_partner_payment_per_activity_type",
            ),
        ),
    ]
