# Generated by Django 5.2.16 on 2026-08-19 07:11

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "daily_visit_batches",
            "0002_dailyvisitbatch_actual_field_cost_per_school_and_more",
        ),
        (
            "fund_requests",
            "0013_remove_partnerpayment_uniq_partner_payment_per_activity_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportPayment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_name", models.CharField(max_length=255)),
                ("amount", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "netsuite_expense_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("paid_by", models.CharField(blank=True, max_length=30, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_payment",
                        to="daily_visit_batches.dailyvisitbatch",
                    ),
                ),
            ],
            options={
                "db_table": "transport_payment",
            },
        ),
    ]
