# Generated by Django 5.2.16 on 2026-08-19 08:45

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0042_activityschedulecostline_vendor_paid"),
        ("fund_requests", "0014_transportpayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerInvoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("partner_id", models.CharField(db_index=True, max_length=30)),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("advance", "50% Advance Invoice"),
                            ("clearance", "Clearance Invoice"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "period_kind",
                    models.CharField(
                        choices=[
                            ("week", "Week"),
                            ("month", "Month"),
                            ("quarter", "Quarter"),
                        ],
                        max_length=12,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("system_total", models.BigIntegerField()),
                ("entered_total", models.BigIntegerField()),
                ("payable_amount", models.BigIntegerField()),
                ("stored_name", models.CharField(max_length=255)),
                ("original_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, default="", max_length=128)),
                ("file_size", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted_to_pl", "With Program Lead"),
                            ("confirmed_by_pl", "PL-confirmed — awaiting payment"),
                            ("returned_by_pl", "Returned by Program Lead"),
                            ("paid", "Paid"),
                        ],
                        default="submitted_to_pl",
                        max_length=24,
                    ),
                ),
                ("submitted_by", models.CharField(max_length=30)),
                (
                    "pl_confirmed_by",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("pl_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("pl_note", models.CharField(blank=True, default="", max_length=512)),
            ],
            options={
                "db_table": "partner_invoice",
            },
        ),
        migrations.CreateModel(
            name="PartnerInvoiceItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "instalment",
                    models.CharField(
                        choices=[
                            ("advance", "50% Advance Invoice"),
                            ("clearance", "Clearance Invoice"),
                        ],
                        max_length=16,
                    ),
                ),
                ("planned_amount", models.BigIntegerField()),
                ("payable_amount", models.BigIntegerField()),
                ("category", models.CharField(max_length=64)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_invoice_items",
                        to="activities.activity",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fund_requests.partnerinvoice",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_item",
                        to="fund_requests.partnerpayment",
                    ),
                ),
            ],
            options={
                "db_table": "partner_invoice_item",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("activity", "instalment"),
                        name="uniq_partner_invoice_item_activity_instalment",
                    )
                ],
            },
        ),
    ]
