# Generated by Django 5.2.17 on 2026-08-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fund_requests",
            "0016_advancerequest_advance_request_amount_non_negative_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyfundrequest",
            name="return_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="weeklyfundrequest",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weeklyfundrequest",
            name="returned_by_user_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
