# Generated by Django 5.2.17 on 2026-08-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fund_requests", "0017_weekly_return_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyfundrequest",
            name="funding_source",
            field=models.CharField(
                choices=[("advance", "Advance"), ("self_fund", "Self Fund")],
                default="advance",
                max_length=16,
            ),
        ),
    ]
