# Generated by Django 5.2.17 on 2026-10-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fund_requests", "0018_weekly_funding_source"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fundrequestitem",
            index=models.Index(
                fields=["activity_schedule_cost_line_id"],
                name="fund_reques_activit_e9dd17_idx",
            ),
        ),
    ]
