# Generated by Django 5.2.17 on 2026-10-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fund_requests", "0019_index_item_cost_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerinvoice",
            name="program_lead_staff_id",
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="partnerinvoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("advance", "50% Advance Invoice"),
                    ("clearance", "Completed Work Invoice"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="partnerinvoice",
            name="original_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="partnerinvoice",
            name="stored_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="partnerinvoiceitem",
            name="instalment",
            field=models.CharField(
                choices=[
                    ("advance", "50% Advance Invoice"),
                    ("clearance", "Completed Work Invoice"),
                ],
                max_length=16,
            ),
        ),
    ]
