# Generated by Django 5.2.16 on 2026-07-28 13:10

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaintenanceTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("support", "User Support"),
                            ("incident", "System Incident"),
                            ("security", "Security"),
                            ("preventive_maintenance", "Preventive Maintenance"),
                            ("corrective_maintenance", "Corrective Maintenance"),
                            ("performance", "Performance"),
                            ("data_repair", "Data Repair"),
                            ("configuration", "Configuration"),
                            ("integration", "Integration"),
                            ("job_failure", "Background Job"),
                            ("frontend_defect", "Frontend Defect"),
                            ("backend_defect", "Backend Defect"),
                            ("route_defect", "Route Defect"),
                            ("accessibility", "Accessibility"),
                            ("feature", "Feature Development"),
                            ("release", "Release / Deployment"),
                            ("monitoring", "Post-Release Monitoring"),
                            ("backup", "Backup and Restore"),
                            ("audit_integrity", "Audit Integrity"),
                        ],
                        default="preventive_maintenance",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("frequency_days", models.PositiveIntegerField()),
                ("next_due_date", models.DateField(db_index=True)),
                ("owner_id", models.CharField(blank=True, max_length=30, null=True)),
                ("estimated_minutes", models.PositiveIntegerField(default=60)),
                ("steps", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "admin_maintenance_template",
                "ordering": ["next_due_date"],
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cannot_log_in", "Cannot Log In"),
                            ("forgot_password", "Forgot Password"),
                            ("account_locked", "Account Locked"),
                            ("cannot_access_page", "Cannot Access Page"),
                            ("incorrect_permission", "Incorrect Permission"),
                            ("missing_data", "Missing School / Activity / Budget"),
                            ("upload_problem", "Upload Problem"),
                            ("dead_button", "Dead Button"),
                            ("broken_link", "Broken Link"),
                            ("slow_page", "Slow Page"),
                            ("frozen_screen", "Frozen Screen"),
                            ("incorrect_data", "Incorrect Data or Status"),
                            ("notification_problem", "Notification Problem"),
                            ("message_problem", "Message Problem"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("triaged", "Triaged"),
                            ("more_info", "More Information Required"),
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("waiting_on_user", "Waiting on User"),
                            ("fix_ready", "Fix Ready"),
                            ("verification", "Verification"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("duplicate", "Duplicate"),
                            ("invalid", "Rejected as Invalid"),
                            ("cancelled", "Cancelled"),
                            ("reopened", "Reopened"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=24,
                    ),
                ),
                ("reporter_id", models.CharField(db_index=True, max_length=30)),
                (
                    "reporter_role",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("owner_id", models.CharField(blank=True, max_length=30, null=True)),
                ("route", models.CharField(blank=True, default="", max_length=255)),
                (
                    "page_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "object_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("object_id", models.CharField(blank=True, default="", max_length=64)),
                ("browser", models.CharField(blank=True, default="", max_length=255)),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                ("resolution", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "admin_support_ticket",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemIncident",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(max_length=20, unique=True)),
                (
                    "signature",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("support", "User Support"),
                            ("incident", "System Incident"),
                            ("security", "Security"),
                            ("preventive_maintenance", "Preventive Maintenance"),
                            ("corrective_maintenance", "Corrective Maintenance"),
                            ("performance", "Performance"),
                            ("data_repair", "Data Repair"),
                            ("configuration", "Configuration"),
                            ("integration", "Integration"),
                            ("job_failure", "Background Job"),
                            ("frontend_defect", "Frontend Defect"),
                            ("backend_defect", "Backend Defect"),
                            ("route_defect", "Route Defect"),
                            ("accessibility", "Accessibility"),
                            ("feature", "Feature Development"),
                            ("release", "Release / Deployment"),
                            ("monitoring", "Post-Release Monitoring"),
                            ("backup", "Backup and Restore"),
                            ("audit_integrity", "Audit Integrity"),
                        ],
                        default="incident",
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="high",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("mitigated", "Mitigated"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "affected_route",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "affected_component",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("affected_roles", models.JSONField(blank=True, default=list)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("samples", models.JSONField(blank=True, default=list)),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("first_detected_at", models.DateTimeField()),
                ("last_detected_at", models.DateTimeField()),
                ("reopened_count", models.PositiveIntegerField(default=0)),
                ("owner_id", models.CharField(blank=True, max_length=30, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "admin_system_incident",
                "ordering": ["-last_detected_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminOperationsWorkItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("support", "User Support"),
                            ("incident", "System Incident"),
                            ("security", "Security"),
                            ("preventive_maintenance", "Preventive Maintenance"),
                            ("corrective_maintenance", "Corrective Maintenance"),
                            ("performance", "Performance"),
                            ("data_repair", "Data Repair"),
                            ("configuration", "Configuration"),
                            ("integration", "Integration"),
                            ("job_failure", "Background Job"),
                            ("frontend_defect", "Frontend Defect"),
                            ("backend_defect", "Backend Defect"),
                            ("route_defect", "Route Defect"),
                            ("accessibility", "Accessibility"),
                            ("feature", "Feature Development"),
                            ("release", "Release / Deployment"),
                            ("monitoring", "Post-Release Monitoring"),
                            ("backup", "Backup and Restore"),
                            ("audit_integrity", "Audit Integrity"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "Backlog"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("waiting", "Waiting"),
                            ("monitoring", "Monitoring"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="backlog",
                        max_length=16,
                    ),
                ),
                (
                    "owner_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "scheduled_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "next_action",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("resolution_criteria", models.TextField(blank=True, default="")),
                ("verification_note", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "affected_module",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "affected_route",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_items",
                        to="admin_ops.supportticket",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_items",
                        to="admin_ops.systemincident",
                    ),
                ),
            ],
            options={
                "db_table": "admin_ops_work_item",
                "ordering": ["-created_at"],
            },
        ),
    ]
