# Generated by Django 5.2.4 on 2026-07-11 20:34

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("daily_visit_batches", "0001_initial"),
        ("geography", "0002_secondarydistrictgroup_district_district_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyVisitRouteBatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("responsible_user", models.CharField(max_length=30)),
                ("visit_date", models.DateField()),
                (
                    "district_type",
                    models.CharField(
                        blank=True,
                        choices=[("primary", "Primary"), ("secondary", "Secondary")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("school_ids", models.JSONField(default=list)),
                ("school_count", models.IntegerField(default=0)),
                ("area_labels", models.JSONField(default=list)),
                ("sub_county_ids", models.JSONField(default=list)),
                ("coords_used", models.IntegerField(default=0)),
                ("est_distance_km", models.FloatField(blank=True, null=True)),
                ("est_travel_minutes", models.IntegerField(default=0)),
                ("visit_minutes", models.IntegerField(default=0)),
                ("buffer_minutes", models.IntegerField(default=0)),
                ("day_load_minutes", models.IntegerField(default=0)),
                ("available_minutes", models.IntegerField(default=0)),
                ("feasible", models.BooleanField(default=True)),
                ("quality_score", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("risky", "Risky"),
                            ("not_feasible", "Not Feasible"),
                            ("blocked", "Blocked"),
                        ],
                        default="good",
                        max_length=16,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High confidence"),
                            ("medium", "Medium confidence"),
                            ("low", "Low confidence"),
                            ("needs_cleanup", "Needs location cleanup"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                ("warnings", models.JSONField(default=list)),
                ("target_snapshot", models.IntegerField(blank=True, null=True)),
                (
                    "cost_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="route_batches",
                        to="daily_visit_batches.dailyvisitbatch",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="route_batches",
                        to="geography.district",
                    ),
                ),
                (
                    "secondary_district_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="route_batches",
                        to="geography.secondarydistrictgroup",
                    ),
                ),
            ],
            options={
                "db_table": "daily_visit_route_batch",
            },
        ),
        migrations.CreateModel(
            name="RouteRecommendation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                ("message", models.CharField(max_length=512)),
                ("school_ids", models.JSONField(default=list)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="routes.dailyvisitroutebatch",
                    ),
                ),
            ],
            options={
                "db_table": "route_recommendation",
            },
        ),
        migrations.CreateModel(
            name="RouteValidationIssue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("severity", models.CharField(default="warning", max_length=16)),
                ("message", models.CharField(max_length=512)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="routes.dailyvisitroutebatch",
                    ),
                ),
            ],
            options={
                "db_table": "route_validation_issue",
            },
        ),
        migrations.CreateModel(
            name="SchoolGeoPoint",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("school_id", models.CharField(max_length=30, unique=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("source", models.CharField(default="manual", max_length=32)),
                ("captured_by", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "school_geo_point",
                "indexes": [
                    models.Index(
                        fields=["school_id"], name="school_geo__school__b04f00_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SchoolLocationConfidence",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("school_id", models.CharField(max_length=30, unique=True)),
                (
                    "source_used",
                    models.CharField(
                        choices=[
                            ("coordinates", "Coordinates"),
                            ("district_subcounty", "District + Sub-county"),
                            ("district_parish", "District + Parish"),
                            ("address_text", "Shipping Address Parsing"),
                            ("none", "Manual Review Needed"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High confidence"),
                            ("medium", "Medium confidence"),
                            ("low", "Low confidence"),
                            ("needs_cleanup", "Needs location cleanup"),
                        ],
                        default="needs_cleanup",
                        max_length=16,
                    ),
                ),
                ("tokens", models.JSONField(default=list)),
                ("area_label", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "school_location_confidence",
                "indexes": [
                    models.Index(
                        fields=["confidence"], name="school_loca_confide_64e3e7_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="dailyvisitroutebatch",
            index=models.Index(
                fields=["visit_date"], name="daily_visit_visit_d_1db2ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyvisitroutebatch",
            index=models.Index(
                fields=["responsible_user"], name="daily_visit_respons_4a86cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyvisitroutebatch",
            index=models.Index(fields=["status"], name="daily_visit_status_c30b72_idx"),
        ),
        migrations.AddConstraint(
            model_name="dailyvisitroutebatch",
            constraint=models.UniqueConstraint(
                fields=("responsible_user", "visit_date"),
                name="uniq_daily_visit_route_batch_user_date",
            ),
        ),
        migrations.AddIndex(
            model_name="routevalidationissue",
            index=models.Index(fields=["code"], name="route_valid_code_bfaa61_idx"),
        ),
    ]
