# Generated by Django 5.2.16 on 2026-07-28 17:19

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("help_center", "0007_expand_guides_for_learning"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAsset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Shown in the Help Center and on the agreement page."
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("policy", "Organisational Policy"),
                            ("manual", "Organisational Manual"),
                            ("training_manual", "Training Manual"),
                            ("training_presentation", "Training Presentation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("category", models.CharField(blank=True, default="", max_length=96)),
                (
                    "owner_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True
                    ),
                ),
                ("country", models.CharField(blank=True, default="", max_length=96)),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("internal", "Public within Edify"),
                            ("role_restricted", "Role Restricted"),
                            ("country_restricted", "Country Restricted"),
                            ("team_restricted", "Team Restricted"),
                            ("partner_restricted", "Partner Restricted"),
                            ("confidential", "Confidential"),
                            ("highly_restricted", "Highly Restricted"),
                        ],
                        default="role_restricted",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("effective", "Effective"),
                            ("superseded", "Superseded"),
                            ("archived", "Archived"),
                            ("returned", "Returned for Correction"),
                            ("blocked", "Publication Blocked"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("acknowledgement_required", models.BooleanField(default=False)),
                ("agreement_required", models.BooleanField(default=False)),
                ("comment_required", models.BooleanField(default=False)),
                ("agreement_statement", models.TextField(blank=True, default="")),
                (
                    "acknowledgement_reason",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("blocks_application_access", models.BooleanField(default=False)),
                (
                    "require_reacknowledgement_on_new_version",
                    models.BooleanField(default=True),
                ),
                (
                    "acknowledgement_due_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("download_allowed", models.BooleanField(default=True)),
                ("print_allowed", models.BooleanField(default=True)),
                ("help_visible", models.BooleanField(default=True)),
                (
                    "help_category",
                    models.CharField(blank=True, default="", max_length=96),
                ),
                ("help_keywords", models.JSONField(blank=True, default=list)),
                ("created_by", models.CharField(blank=True, max_length=30, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "help_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_assets",
                        to="help_center.helparticle",
                    ),
                ),
            ],
            options={
                "db_table": "document_asset",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAcknowledgement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=30)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("agreed", "Agreed"),
                            ("disagreed", "Disagreed"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        blank=True,
                        choices=[("agree", "I Agree"), ("disagree", "I Disagree")],
                        default="",
                        max_length=16,
                    ),
                ),
                ("statement", models.TextField(blank=True, default="")),
                ("comment", models.TextField(blank=True, default="")),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "role_at_acknowledgement",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "country_at_acknowledgement",
                    models.CharField(blank=True, default="", max_length=96),
                ),
                ("active_reading_seconds", models.PositiveIntegerField(default=0)),
                ("session_count", models.PositiveIntegerField(default=0)),
                (
                    "last_page_reached",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("viewer_completed", models.BooleanField(default=False)),
                ("download_initiated", models.BooleanField(default=False)),
                ("print_initiated", models.BooleanField(default=False)),
                ("offline_attestation", models.BooleanField(default=False)),
                (
                    "offline_attestation_note",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "typed_full_name",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("reminder_count", models.PositiveIntegerField(default=0)),
                ("last_reminded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements",
                        to="documents.documentasset",
                    ),
                ),
            ],
            options={
                "db_table": "document_acknowledgement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAudienceRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(blank=True, default="", max_length=64)),
                ("country", models.CharField(blank=True, default="", max_length=96)),
                ("region_id", models.CharField(blank=True, default="", max_length=30)),
                (
                    "team_lead_staff_id",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("partner_id", models.CharField(blank=True, default="", max_length=30)),
                ("project_id", models.CharField(blank=True, default="", max_length=30)),
                ("user_id", models.CharField(blank=True, default="", max_length=30)),
                ("effective_from", models.DateField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audience_rules",
                        to="documents.documentasset",
                    ),
                ),
            ],
            options={
                "db_table": "document_audience_rule",
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("uri", models.CharField(max_length=512)),
                ("original_filename", models.CharField(max_length=512)),
                ("mime_type", models.CharField(blank=True, default="", max_length=128)),
                (
                    "file_extension",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("file_size", models.BigIntegerField(default=0)),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("review_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("change_summary", models.TextField(blank=True, default="")),
                ("material_change", models.BooleanField(default=True)),
                ("uploaded_by", models.CharField(blank=True, max_length=30, null=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=30, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_decision",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                (
                    "review_note",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "published_by",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "preview_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not Required"),
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("not_supported", "Preview Unavailable"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "preview_uri",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "preview_error",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("preview_generated_at", models.DateTimeField(blank=True, null=True)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("scan_status", models.CharField(default="pending", max_length=16)),
                (
                    "scan_detail",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.documentasset",
                    ),
                ),
            ],
            options={
                "db_table": "document_version",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="DocumentEngagementSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=30)),
                ("started_at", models.DateTimeField()),
                ("last_heartbeat_at", models.DateTimeField()),
                ("active_seconds", models.PositiveIntegerField(default=0)),
                ("pages_viewed", models.JSONField(blank=True, default=list)),
                ("last_page", models.PositiveIntegerField(blank=True, null=True)),
                ("finalised", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_sessions",
                        to="documents.documentasset",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_sessions",
                        to="documents.documentversion",
                    ),
                ),
            ],
            options={
                "db_table": "document_engagement_session",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentComment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author_id", models.CharField(db_index=True, max_length=30)),
                (
                    "author_role",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "author_country",
                    models.CharField(blank=True, default="", max_length=96),
                ),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("under_review", "Under Review"),
                            ("response_required", "Response Required"),
                            ("responded", "Responded"),
                            ("resolved", "Resolved"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=24,
                    ),
                ),
                ("owner_id", models.CharField(blank=True, max_length=30, null=True)),
                ("response", models.TextField(blank=True, default="")),
                (
                    "responded_by",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledgement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_records",
                        to="documents.documentacknowledgement",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="documents.documentasset",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="documents.documentversion",
                    ),
                ),
            ],
            options={
                "db_table": "document_comment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="documentasset",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for",
                to="documents.documentversion",
            ),
        ),
        migrations.AddField(
            model_name="documentacknowledgement",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acknowledgements",
                to="documents.documentversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "version_number"),
                name="uniq_document_version_number",
            ),
        ),
        migrations.AddIndex(
            model_name="documentengagementsession",
            index=models.Index(
                fields=["user_id", "version"], name="document_en_user_id_3853b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentcomment",
            index=models.Index(
                fields=["status", "document"], name="document_co_status_f450ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentasset",
            index=models.Index(
                fields=["document_type", "status"],
                name="document_as_documen_da8805_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentasset",
            index=models.Index(
                fields=["acknowledgement_required", "status"],
                name="document_as_acknowl_307301_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentacknowledgement",
            index=models.Index(
                fields=["user_id", "state"], name="document_ac_user_id_c77df7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentacknowledgement",
            index=models.Index(
                fields=["document", "state"], name="document_ac_documen_1c4e35_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentacknowledgement",
            constraint=models.UniqueConstraint(
                fields=("version", "user_id"), name="uniq_ack_per_user_version"
            ),
        ),
    ]
