# Generated by Django 5.2.17 on 2026-09-14 06:20

import apps.core.cuid
import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("command_center", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodayActionRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=30)),
                ("todo_id", models.CharField(max_length=128)),
                ("kind", models.CharField(max_length=64)),
                ("operation", models.CharField(max_length=32)),
                ("record_id", models.CharField(max_length=64)),
                ("reason", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "command_center_today_action",
                "indexes": [
                    models.Index(
                        fields=["user_id", "created_at"],
                        name="command_cen_user_id_db19ad_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TodoSnooze",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(max_length=30)),
                ("todo_id", models.CharField(max_length=128)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("until", models.DateField()),
            ],
            options={
                "db_table": "command_center_todo_snooze",
                "indexes": [
                    models.Index(
                        fields=["user_id", "until"],
                        name="command_cen_user_id_67b91f_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "todo_id"), name="todo_snooze_one_per_item"
                    )
                ],
            },
        ),
    ]
