"use client";

// Monthly Fund Request — status banner + role-aware approval actions.
//
// The banner reads as a workflow tracker: where the request is in the
// chain, how much has been requested, what the next step is. The
// action bar shows the moves available to the viewer's role:
//
//   • PL: Submit to CD / Mark Under Review / Return draft
//   • CD: Approve / Return to PL / Submit to RVP
//   • RVP: Approve / Return to CD / Hold
//
// Each action is gated by status. Disabled actions explain why via
// title attribute.

import {
  ArrowRight,
  CheckCircle2,
  CircleAlert,
  Download,
  PauseCircle,
  RotateCcw,
} from "lucide-react";
import {
  CD_ACTION_STATUSES,
  MFR_STATUS_LABEL,
  PL_ACTION_STATUSES,
  POST_CD_APPROVAL_STATUSES,
  RVP_ACTION_STATUSES,
  type MonthlyFundRequest,
  type MonthlyFundRequestStatus,
} from "@/lib/funds/monthly-fund-request-types";
import { cn } from "@/lib/utils";

export type MfrViewerRole = "PL" | "CD" | "RVP" | "Accountant";

// Map each status onto the system-wide .status-indicator tone class.
// The dot + text pattern replaces the saturated pill fills used
// previously — calmer, more "Mercury / Stripe" than "consumer app".
const STATUS_TONE: Record<string, string> = {
  AUTO_GENERATED:        "status-neutral",
  UNDER_PL_REVIEW:       "status-info",
  SUBMITTED_TO_CD:       "status-pending",
  UNDER_CD_REVIEW:       "status-pending",
  RETURNED_TO_PL:        "status-returned",
  CD_APPROVED:           "status-approved",
  SUBMITTED_TO_RVP:      "status-approved",
  UNDER_RVP_REVIEW:      "status-pending",
  RVP_APPROVED:          "status-approved",
  RETURNED_TO_CD:        "status-returned",
  ON_HOLD:               "status-hold",
  SENT_TO_FINANCE:       "status-approved",
  DISBURSEMENT_PREPARED: "status-approved",
  CLOSED:                "status-neutral",
};

export function MonthlyFundRequestHeader({
  mfr,
  viewerRole,
  onAction,
}: {
  mfr: MonthlyFundRequest;
  viewerRole: MfrViewerRole;
  onAction?: (next: MonthlyFundRequestStatus, note?: string) => void;
}) {
  // Legacy STATUS_TONE_OLD kept for any other callers that look up the
  // string. Removed from this file's render path — the .status-indicator
  // primitive takes over. Define empty placeholder to satisfy the
  // closure structure below.
  const STATUS_TONE_OLD: Record<string, string> = {
    AUTO_GENERATED:        "",
    UNDER_PL_REVIEW:       "",
    SUBMITTED_TO_CD:       "",
    UNDER_CD_REVIEW:       "",
    RETURNED_TO_PL:        "",
    CD_APPROVED:           "",
    SUBMITTED_TO_RVP:      "",
    UNDER_RVP_REVIEW:      "",
    RVP_APPROVED:          "",
    RETURNED_TO_CD:        "",
    ON_HOLD:               "",
    SENT_TO_FINANCE:       "",
    DISBURSEMENT_PREPARED: "",
    CLOSED:                "",
  };
  void STATUS_TONE_OLD;

  const stepIndex = stepIndexFor(mfr.status);
  const nextStep = STEPS[stepIndex + 1];

  // Compute which buttons are available to the viewer
  const canPLAct  = viewerRole === "PL"  && PL_ACTION_STATUSES.has(mfr.status);
  const canCDAct  = viewerRole === "CD"  && CD_ACTION_STATUSES.has(mfr.status);
  const canRVPAct = viewerRole === "RVP" && RVP_ACTION_STATUSES.has(mfr.status);

  return (
    <section className="card p-4 lg:p-5 flex flex-col gap-3">
      <div className="flex items-start justify-between gap-3 flex-wrap">
        <div className="min-w-0">
          <div className="text-[10.5px] muted font-bold uppercase tracking-wide">
            Monthly Fund Request
          </div>
          <h1 className="text-[20px] font-extrabold tracking-tight text-slate-900">
            Funds Allocation for {mfr.monthLabel}
          </h1>
          <p className="text-[12px] muted mt-0.5 leading-snug">
            Auto-generated from approved monthly plans · cost rates from <span className="font-bold">{mfr.costSettings.versionId}</span> · generated by {mfr.generatedByName}
          </p>
        </div>

        <div className="flex flex-col items-end gap-3 shrink-0 min-w-[260px]">
          {/* Status — dot + text, no fill */}
          <span className={cn("status-indicator", STATUS_TONE[mfr.status] ?? "status-neutral")}>
            {MFR_STATUS_LABEL[mfr.status]}
          </span>

          {/* Currency hero — UGX label + giant tabular figure */}
          {viewerRole === "PL" ? (
            <div className="flex flex-col items-end gap-1">
              <div className="text-[10px] font-bold uppercase tracking-[0.1em] text-[var(--text-muted)]">
                Program Total
              </div>
              <div className="currency-display currency-hero">
                <span className="currency-unit">UGX</span>
                <span className="currency-value">{mfr.totalProgramCost.amount.toLocaleString()}</span>
              </div>
              <div className="text-[10.5px] text-[var(--text-muted)] font-medium">
                Admin items added by CD after PL approval
              </div>
            </div>
          ) : (
            <div className="flex flex-col items-end gap-1">
              <div className="text-[10px] font-bold uppercase tracking-[0.1em] text-[var(--text-muted)]">
                Grand Total
              </div>
              <div className="currency-display currency-hero">
                <span className="currency-unit">UGX</span>
                <span className="currency-value">{mfr.grandTotal.amount.toLocaleString()}</span>
              </div>
              <div className="text-[10.5px] text-[var(--text-muted)] font-medium tabular">
                Program {(mfr.totalProgramCost.amount / 1_000_000).toFixed(1)}M
                <span className="opacity-40 mx-1.5">·</span>
                Admin {(mfr.totalAdminCost.amount / 1_000_000).toFixed(1)}M
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Workflow stepper — connector line + nodes, replaces the chip row */}
      <div className="workflow-stepper" role="list" aria-label="Approval workflow">
        {STEPS.map((s, i) => {
          const state = i < stepIndex ? "done" : i === stepIndex ? "current" : "future";
          return (
            <div
              key={s.key}
              role="listitem"
              className={cn(
                "workflow-step",
                state === "done"    && "is-done",
                state === "current" && "is-current",
              )}
            >
              <span className="workflow-step-node" aria-hidden />
              <span className="workflow-step-label">{s.label}</span>
            </div>
          );
        })}
      </div>

      {/* Legacy stepper block kept inert below — removed via false guard */}
      {false && (
      <ol className="flex items-center gap-1 overflow-x-auto pb-1 -mx-1 px-1">
        {STEPS.map((s, i) => {
          const state = i < stepIndex ? "done" : i === stepIndex ? "current" : "future";
          return (
            <li key={s.key} className="flex items-center gap-1 shrink-0">
              <div className={cn(
                "inline-flex items-center gap-1.5 h-7 px-2.5 rounded-full text-[10.5px] font-extrabold",
                state === "done"    && "bg-emerald-100 text-emerald-700",
                state === "current" && "bg-amber-100 text-amber-700 ring-2 ring-amber-200",
                state === "future"  && "bg-slate-100  text-slate-500",
              )}>
                {state === "done"    && <CheckCircle2 size={10} />}
                {s.label}
              </div>
            </li>
          );
        })}
      </ol>
      )}

      {/* Action row */}
      <footer className="flex items-center justify-between gap-3 flex-wrap pt-2 border-t border-dashed border-[var(--color-edify-border)]">
        <div className="flex items-center gap-2 text-[11.5px] muted">
          {nextStep ? (
            <>
              <ArrowRight size={11} className="text-emerald-600" />
              <span>Next step: <span className="font-bold text-slate-800">{nextStep.label}</span></span>
            </>
          ) : (
            <span className="font-bold text-emerald-700">Workflow complete</span>
          )}
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button
            type="button"
            className="inline-flex items-center gap-1.5 h-9 px-3 rounded-lg border border-[var(--color-edify-border)] bg-white hover:bg-slate-50 text-[12px] font-semibold text-slate-700"
            title="Export this request"
          >
            <Download size={12} />
            Export
          </button>

          {canPLAct && (
            <>
              <Button
                tone="rose"
                icon={<RotateCcw size={12} />}
                label="Return to draft"
                onClick={() => onAction?.("AUTO_GENERATED")}
              />
              <Button
                tone="primary"
                icon={<CheckCircle2 size={12} />}
                label="Approve program & send to CD"
                onClick={() => onAction?.("SUBMITTED_TO_CD")}
              />
            </>
          )}

          {canCDAct && (
            <>
              <Button
                tone="rose"
                icon={<RotateCcw size={12} />}
                label="Return to PL"
                onClick={() => onAction?.("RETURNED_TO_PL")}
              />
              <Button
                tone="primary"
                icon={<CheckCircle2 size={12} />}
                label="Add admin & submit to RVP"
                onClick={() => onAction?.("SUBMITTED_TO_RVP")}
              />
            </>
          )}

          {canRVPAct && (
            <>
              <Button
                tone="amber"
                icon={<PauseCircle size={12} />}
                label="Hold"
                onClick={() => onAction?.("ON_HOLD")}
              />
              <Button
                tone="rose"
                icon={<RotateCcw size={12} />}
                label="Return to CD"
                onClick={() => onAction?.("RETURNED_TO_CD")}
              />
              <Button
                tone="primary"
                icon={<CheckCircle2 size={12} />}
                label="Approve & release to Accountant"
                onClick={() => onAction?.("RVP_APPROVED")}
              />
            </>
          )}

          {!canPLAct && !canCDAct && !canRVPAct && (
            <div className="inline-flex items-center gap-1.5 text-[11.5px] muted">
              <CircleAlert size={12} />
              {viewerRole === "RVP" && !POST_CD_APPROVAL_STATUSES.has(mfr.status)
                ? "Visible after CD approval."
                : "No actions for your role at this stage."}
            </div>
          )}
        </div>
      </footer>
    </section>
  );
}

function Button({
  tone,
  icon,
  label,
  onClick,
}: {
  tone: "primary" | "rose" | "amber";
  icon: React.ReactNode;
  label: string;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        "inline-flex items-center gap-1.5 h-9 px-3 rounded-lg text-[12px] font-extrabold transition-colors",
        tone === "primary" && "bg-emerald-600 hover:bg-emerald-700 text-white shadow-[0_10px_28px_-12px_rgba(5,150,105,0.45)]",
        tone === "rose"    && "bg-white border border-rose-200 text-rose-700 hover:bg-rose-50",
        tone === "amber"   && "bg-white border border-amber-200 text-amber-700 hover:bg-amber-50",
      )}
    >
      {icon}
      {label}
    </button>
  );
}

// Workflow stepper config
// Workflow stages — note that PL reviews the program plan only, CD
// layers the admin budget on top after PL approval, RVP reviews the
// combined request, and the RVP-approved package routes directly to
// the Accountant for disbursement + accountability tracking.
const STEPS: { key: string; label: string; statuses: ReadonlyArray<MonthlyFundRequestStatus> }[] = [
  { key: "draft",        label: "Auto-generated",         statuses: ["AUTO_GENERATED"] },
  { key: "pl",           label: "PL Review (Program)",    statuses: ["UNDER_PL_REVIEW", "RETURNED_TO_PL"] },
  { key: "cd",           label: "CD Review + Admin",      statuses: ["SUBMITTED_TO_CD", "UNDER_CD_REVIEW", "RETURNED_TO_CD"] },
  { key: "cd_approved",  label: "CD Approved",            statuses: ["CD_APPROVED"] },
  { key: "rvp",          label: "RVP Review",             statuses: ["SUBMITTED_TO_RVP", "UNDER_RVP_REVIEW", "ON_HOLD"] },
  { key: "rvp_approved", label: "RVP Approved",           statuses: ["RVP_APPROVED"] },
  { key: "accountant",   label: "Accountant — Disburse",  statuses: ["SENT_TO_FINANCE", "DISBURSEMENT_PREPARED", "CLOSED"] },
];

function stepIndexFor(status: MonthlyFundRequestStatus): number {
  return STEPS.findIndex((s) => s.statuses.includes(status));
}
