# Generated by Django 5.2.4 on 2026-07-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coreactivityslot",
            name="netsuite_status",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="coreplan",
            name="assessment_completed",
            field=models.IntegerField(default=0),
        ),
    ]
