# Generated by Django 5.2.4 on 2026-07-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_schools", "0003_backfill_core_assessment_slots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coreplan",
            name="school_id",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="coreplan",
            constraint=models.UniqueConstraint(
                fields=("school_id", "fy"), name="uniq_core_plan_per_school_fy"
            ),
        ),
    ]
