# Generated by Django 5.2.17 on 2026-10-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_schools", "0010_in_school_training_visit_in_the_package"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="coreactivityslot",
            index=models.Index(
                fields=["activity_id"], name="core_activi_activit_6a7dc0_idx"
            ),
        ),
    ]
