# Generated by Django 5.2.17 on 2026-10-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    # Written as 0011 on the performance branch. Main gained its own 0011 before
    # that branch merged (the universal-training refile), so this one follows it:
    # an index does not care what order it is built in, and a data migration
    # that has already run on production must not find a new one in front of it.
    dependencies = [
        ("core_schools", "0011_universal_training_on_top_of_the_package"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="coreactivityslot",
            index=models.Index(
                fields=["activity_id"], name="core_activi_activit_6a7dc0_idx"
            ),
        ),
    ]
