"""Hold the committed traceability matrix to reality, and prove the tracer looks.

Two different failures are possible here and they need different guards.

The first is drift: the matrix is generated by a command nobody runs on every
commit, so the committed artefact can fall behind the journeys it claims to
describe. ``ManifestMatchesTheJourneysTest`` compares it against
``apps.core.tests.release_journeys`` -- the same manifest the journey census
holds -- so a renamed test or a newly covered journey turns the artefact stale
loudly rather than quietly.

The second is worse, and it is the one this audit has hit four times already: a
tool built to find defects producing one of its own. A tracer that records
nothing produces a matrix full of honest-looking zeroes, and a zero reads
exactly like "the platform does not do this". So ``TracerControlsTest`` runs the
tracer against known-answer tests in this very module -- one that makes an HTTP
request, one that writes a model, one that checks a permission, one that fails
on purpose -- and asserts it saw each. If the tracer stops seeing, these go red
before any conclusion is drawn from a zero.

The zero that matters is pinned separately, in ``TheJourneysNeverKnockTest``.
"""

from __future__ import annotations

import json
import unittest
from pathlib import Path

from django.conf import settings
from django.test import SimpleTestCase, TestCase

from apps.core.tests.release_journeys import JOURNEYS
from apps.system_health.traceability import (
    Instrumentation,
    Recording,
    TestPointerError,
    _metrics_for,
    normalise_route,
    split_service_path,
    trace_test,
)

MATRIX_PATH = Path(settings.BASE_DIR) / "docs" / "platform-traceability-matrix.json"

#: Requirements traced by executing their own test. Matches COVERED_COUNT in
#: apps/core/tests/test_release_journey_census.py -- deliberately restated
#: rather than imported, so that adding a journey test forces a look at both
#: the census and this artefact instead of one silently satisfying the other.
TRACED_COUNT = 20

#: Requirements with no test to trace: the two journeys blocked on capability
#: that was never built.
UNTRACED_COUNT = 2

_CONTROL = "apps.system_health.test_traceability_matrix:TracerFixtures."


def load_matrix() -> dict:
    return json.loads(MATRIX_PATH.read_text(encoding="utf-8"))


# ─────────────────────────────────────────────────────────────────────────────
# Known-answer fixtures. These are real tests -- the suite runs them like any
# other -- and TracerControlsTest also runs them through the tracer and checks
# that what they did shows up.
# ─────────────────────────────────────────────────────────────────────────────


class TracerFixtures(TestCase):
    """Each of these does exactly one traceable thing, and says what."""

    def test_fixture_makes_one_http_request(self):
        # A 404 still goes through the handler, so this needs no real route and
        # cannot break when routing changes.
        response = self.client.get("/__traceability_control__")
        self.assertEqual(response.status_code, 404)

    def test_fixture_writes_one_model(self):
        from apps.audit.models import AuditLog
        from apps.audit.services import log as audit_log

        audit_log(
            action="traceability.control",
            subject_kind="Control",
            subject_id="tracer",
        )
        # log() is best-effort and swallows its own failures, so the fixture
        # has to check. Without this a swallowed write would reach the control
        # as "the tracer saw nothing", and the control would blame the tracer.
        self.assertEqual(
            AuditLog.objects.filter(action="traceability.control").count(),
            1,
            "the control's own write did not land, so it can prove nothing "
            "about the tracer",
        )

    def test_fixture_checks_one_permission(self):
        from apps.core.permissions import has_permission

        class _Nobody:
            active_role = None
            is_authenticated = True

        self.assertFalse(has_permission(_Nobody(), "traceability.controlPermission"))

    def test_fixture_fails_on_purpose(self):
        self.fail("this fixture exists to prove a red test is never traced")


# ─────────────────────────────────────────────────────────────────────────────
# The controls
# ─────────────────────────────────────────────────────────────────────────────


class TracerControlsTest(SimpleTestCase):
    """A SimpleTestCase on purpose.

    The tracer runs a real ``django.test.TestCase``, and that class closes every
    connection in ``tearDownClass``. Nested inside another ``TestCase`` it takes
    the outer test's transaction down with it -- "the connection is closed",
    every control red, and the tracer blamed for it. A ``SimpleTestCase`` opens
    no transaction of its own, so the fixture's own rollback is the only
    cleanup needed and there is nothing for it to break.
    """

    databases = "__all__"

    def test_it_sees_an_http_route(self):
        recording = trace_test(_CONTROL + "test_fixture_makes_one_http_request")
        self.assertIn("GET /__traceability_control__", recording.routes)

    def test_it_sees_a_model_write(self):
        recording = trace_test(_CONTROL + "test_fixture_writes_one_model")
        self.assertIn("audit.AuditLog", recording.models_written)

    def test_it_sees_the_audit_action_that_write_recorded(self):
        recording = trace_test(_CONTROL + "test_fixture_writes_one_model")
        self.assertIn("traceability.control", recording.audit_actions)

    def test_it_sees_a_permission_check(self):
        recording = trace_test(_CONTROL + "test_fixture_checks_one_permission")
        self.assertIn("traceability.controlPermission", recording.permissions)

    def test_it_sees_the_service_file_that_ran(self):
        recording = trace_test(_CONTROL + "test_fixture_writes_one_model")
        self.assertIn("apps/audit/services.py", recording.services)

    def test_it_never_traces_a_failing_test(self):
        with self.assertRaises(TestPointerError):
            trace_test(_CONTROL + "test_fixture_fails_on_purpose")

    def test_it_refuses_a_pointer_that_names_nothing(self):
        with self.assertRaises(TestPointerError):
            trace_test(
                "apps.system_health.test_traceability_matrix:TracerFixtures."
                "test_no_such_fixture"
            )

    def test_it_leaves_no_trace_hook_behind(self):
        import sys

        before = sys.gettrace()
        trace_test(_CONTROL + "test_fixture_checks_one_permission")
        self.assertIs(sys.gettrace(), before)

    def test_it_ignores_the_test_that_drives_it(self):
        """The harness must not appear in the evidence it collects."""
        recording = trace_test(_CONTROL + "test_fixture_writes_one_model")
        self.assertNotIn(
            "apps/system_health/test_traceability_matrix.py", recording.services
        )
        self.assertNotIn("apps/system_health/traceability.py", recording.services)


class InstrumentationIsReversibleTest(SimpleTestCase):
    def test_signals_are_disconnected_afterwards(self):
        from django.db.models.signals import post_save

        before = len(post_save.receivers)
        with Instrumentation():
            during = len(post_save.receivers)
        self.assertGreater(during, before)
        self.assertEqual(len(post_save.receivers), before)


class ServicePathResolutionTest(SimpleTestCase):
    def test_it_splits_a_dotted_service_into_module_and_function(self):
        self.assertEqual(
            split_service_path("apps.core.permissions.has_permission"),
            ("apps/core/permissions.py", "has_permission"),
        )

    def test_it_keeps_the_leaf_of_a_class_method_path(self):
        self.assertEqual(
            split_service_path(
                "apps.core.permissions.RolePermissionService.can_view_page"
            ),
            ("apps/core/permissions.py", "can_view_page"),
        )

    def test_it_returns_nothing_for_a_path_that_does_not_exist(self):
        self.assertIsNone(split_service_path("apps.no_such_app.services.fn"))

    def test_every_registered_metric_still_names_a_real_module(self):
        from apps.core.metrics.registry import all_metrics

        unresolved = [
            spec.key
            for spec in all_metrics()
            if split_service_path(spec.service) is None
        ]
        self.assertEqual(unresolved, [], "a metric names a service module that is gone")


class RouteNormalisationTest(SimpleTestCase):
    """Opaque ids out, route words kept.

    Both halves matter. Leaving fixture ids in makes the committed artefact
    differ from itself on every rebuild, and a matrix that churns without the
    platform changing teaches its readers to skip its diffs. Normalising too
    eagerly is worse the other way: two genuinely different routes would
    collapse into one and the door coverage would be overstated.
    """

    def test_it_replaces_a_cuid(self):
        self.assertEqual(
            normalise_route("/schools/cmt9slehb0050amdjhi8o/edit-drawer"),
            "/schools/{id}/edit-drawer",
        )

    def test_it_replaces_a_uuid(self):
        self.assertEqual(
            normalise_route("/apps/8f8682cd-1111-2222-3333-444455556666/spec"),
            "/apps/{id}/spec",
        )

    def test_it_replaces_a_bare_integer(self):
        self.assertEqual(normalise_route("/reports/2026/"), "/reports/{id}/")

    def test_it_keeps_route_words(self):
        for path in (
            "/disbursements",
            "/fund-requests/weekly/xr-no-such-request/disburse",
            "/core-schools/schedule-visit/action",
            "/accounts/partner-payments/xr-no-such-activity/pay",
        ):
            with self.subTest(path=path):
                self.assertEqual(normalise_route(path), path)

    def test_it_is_stable_under_repetition(self):
        once = normalise_route("/schools/cmt9slehb0050amdjhi8o/edit-drawer")
        self.assertEqual(normalise_route(once), once)


class MetricAttributionTest(SimpleTestCase):
    """Prove the metric join before reading anything into an empty metric cell.

    The matrix credits no journey with computing a registered metric. That is
    either a real property of the journey evidence or a broken join, and the
    two are indistinguishable from the artefact alone. These three tests
    separate them: the tracer records functions and not merely files, a metric
    whose own computing function ran is credited, and a metric whose module ran
    without it is not. The last is the regression pin for the first version of
    this module, which matched on the file and credited one journey with twelve
    analytics metrics it had never computed.
    """

    databases = "__all__"

    def _first_spec(self):
        from apps.core.metrics.registry import all_metrics

        return sorted(all_metrics(), key=lambda spec: spec.key)[0]

    def test_the_tracer_records_functions_not_just_files(self):
        recording = trace_test(_CONTROL + "test_fixture_writes_one_model")
        self.assertIn("apps/audit/services.py::log", recording.functions)

    def test_a_metric_is_credited_when_its_own_function_ran(self):
        spec = self._first_spec()
        module_file, function_name = split_service_path(spec.service)
        recording = Recording(functions={f"{module_file}::{function_name}"})
        computed, _ = _metrics_for(recording)
        self.assertIn(spec.key, computed)

    def test_a_metric_is_not_credited_when_only_its_module_ran(self):
        spec = self._first_spec()
        module_file, function_name = split_service_path(spec.service)
        recording = Recording(
            services={module_file},
            functions={f"{module_file}::some_other_function_entirely"},
        )
        computed, _ = _metrics_for(recording)
        self.assertNotIn(spec.key, computed)

    def test_a_metric_is_affected_when_a_source_model_is_written(self):
        from apps.core.metrics.registry import all_metrics

        spec = next(spec for spec in all_metrics() if spec.source_models)
        recording = Recording(models_written={spec.source_models[0]})
        _, affected = _metrics_for(recording)
        self.assertIn(spec.key, affected)


# ─────────────────────────────────────────────────────────────────────────────
# The committed artefact
# ─────────────────────────────────────────────────────────────────────────────


class ManifestMatchesTheJourneysTest(unittest.TestCase):
    def setUp(self):
        self.matrix = load_matrix()
        self.rows = self.matrix["requirements"]

    def test_it_covers_every_mandated_journey_in_order(self):
        self.assertEqual(
            [row["requirement"] for row in self.rows],
            [f"journey-{j.number:02d}" for j in JOURNEYS],
        )

    def test_each_row_carries_the_journey_title_and_steps(self):
        for row, journey in zip(self.rows, JOURNEYS):
            with self.subTest(requirement=row["requirement"]):
                self.assertEqual(row["title"], journey.title)
                self.assertEqual(row["steps"], list(journey.steps))

    def test_each_row_names_the_test_the_census_names(self):
        for row, journey in zip(self.rows, JOURNEYS):
            with self.subTest(requirement=row["requirement"]):
                expected = journey.covered_by[0] if journey.covered_by else ""
                self.assertEqual(
                    row["test"],
                    expected,
                    "the matrix was generated against a different manifest; "
                    "re-run `python manage.py build_traceability_matrix`",
                )

    def test_the_counts_are_what_this_suite_declares(self):
        summary = self.matrix["summary"]
        self.assertEqual(summary["requirements"], len(JOURNEYS))
        self.assertEqual(summary["traced"], TRACED_COUNT)
        self.assertEqual(summary["untraced"], UNTRACED_COUNT)

    def test_a_traced_row_is_never_empty(self):
        """An empty trace is a tracer failure wearing a coverage result."""
        for row in self.rows:
            if row["untracedBecause"]:
                continue
            with self.subTest(requirement=row["requirement"]):
                self.assertTrue(row["services"], "no service file executed")
                self.assertTrue(row["modelsWritten"], "no model written")

    def test_an_untraced_row_claims_nothing_and_says_why(self):
        for row in self.rows:
            if not row["untracedBecause"]:
                continue
            with self.subTest(requirement=row["requirement"]):
                self.assertEqual(row["test"], "")
                for column in ("routes", "services", "modelsWritten", "roles"):
                    self.assertEqual(row[column], [])
                self.assertGreater(len(row["untracedBecause"]), 40)

    def test_every_role_named_is_a_real_role(self):
        from apps.core.rbac import EdifyRole

        known = {role.value for role in EdifyRole}
        for row in self.rows:
            with self.subTest(requirement=row["requirement"]):
                self.assertLessEqual(set(row["roles"]), known)

    def test_it_declares_the_requirement_sets_it_does_not_cover(self):
        sets = self.matrix["untracedRequirementSets"]
        self.assertGreaterEqual(len(sets), 3)
        for entry in sets:
            with self.subTest(entry=entry["set"]):
                self.assertGreater(
                    len(entry["reason"]),
                    80,
                    "an uncovered requirement set needs a reason, not a label",
                )
        self.assertIn(
            "GAP-01..GAP-16",
            " ".join(entry["set"] for entry in sets),
            "the approved-extensions list is the one requirement set that is "
            "still prose only; the matrix must keep saying so",
        )


#: Journeys whose covering test drives the platform through its own routes.
#: JRN-01 was the finding that this set was EMPTY — all twenty walked journeys
#: proved the domain and none of them ever knocked on the door, leaving the
#: platform's 810 route-level authority gates exercised by no mandated journey
#: at all. Journey 19 is the first converted, and it was chosen because its
#: whole subject is unauthorized access, so proving it only below the door was
#: the least defensible instance of the gap.
#:
#: Add to this set as journeys are converted, and update §4b of
#: docs/release-readiness-2026-08-25.md in the same commit. It is pinned rather
#: than derived so that neither growing nor losing door coverage can happen
#: without somebody saying so.
JOURNEYS_THAT_KNOCK = {"journey-19"}


class WhichJourneysReachTheDoorTest(unittest.TestCase):
    """Exactly which journeys are proven at the request path, and no other.

    This holds JRN-01 in both directions. A journey that stops driving the
    platform over HTTP fails it, which is the regression. A journey that starts
    also fails it, which is the improvement — and the failure is how the
    assessment gets updated in the same commit instead of the gain going
    unrecorded.

    The gap it describes is real and mostly still open: for the nineteen
    journeys not listed above, nothing exercises URL routing,
    ``require_page_permission``, ``RequirePermissions``, view-level scoping,
    serializers or templates. A defect living between the door and the service
    — an ungated route, a view handing a service the wrong principal, a
    serializer widening a field — is invisible to all of them. SEC-01 was
    exactly that defect, and journey 19's route sweep now reproduces it: delete
    ``assert_may_write_school`` from the school edit drawer and the sweep
    reports the Programme Lead's takeover with a 200.
    """

    def _journey_numbers_by_module(self) -> dict[str, set[str]]:
        by_module: dict[str, set[str]] = {}
        for journey in JOURNEYS:
            if not journey.covered_by:
                continue
            module_path = journey.covered_by[0].split(":", 1)[0]
            by_module.setdefault(module_path, set()).add(
                f"journey-{journey.number:02d}"
            )
        return by_module

    def test_the_matrix_records_routes_for_exactly_these_journeys(self):
        rows = load_matrix()["requirements"]
        with_routes = {row["requirement"] for row in rows if row["routes"]}
        self.assertEqual(
            with_routes,
            JOURNEYS_THAT_KNOCK,
            "door coverage changed. If a journey was converted, re-run "
            "`manage.py build_traceability_matrix`, add it to "
            "JOURNEYS_THAT_KNOCK and update the assessment's §4b in the same "
            "commit. If coverage was lost, that is the regression.",
        )

    def test_the_journey_modules_agree_without_reading_the_artefact(self):
        """The same question by a second method that does not read the matrix.

        The pin above reads the committed matrix, so on its own it only
        notices a change once somebody also regenerates the matrix — and the
        regeneration is a command nobody runs per commit. This one reads the
        journey tests themselves, so a converted journey and a stale artefact
        disagree immediately rather than quietly agreeing.

        It matches ``self.client`` rather than ``self.client.get(`` and the
        other four verbs, and the difference is not cosmetic. The first
        version of this check looked for the literal method calls, and journey
        19's route sweep — which dispatches with ``getattr(self.client,
        method)`` so one table can drive GETs and POSTs alike — went straight
        past it. It reported the journey as not knocking while the matrix,
        which records what actually ran, reported four routes. The two methods
        disagreeing is what surfaced it; a narrower pattern here would have
        meant a second method that agrees with the first only by accident.
        """
        import re

        knocking: set[str] = set()
        for module_path, numbers in self._journey_numbers_by_module().items():
            source = Path(module_path.replace(".", "/") + ".py").read_text(
                encoding="utf-8"
            )
            if re.search(r"self\.client\b", source):
                knocking |= numbers
        self.assertEqual(
            knocking,
            JOURNEYS_THAT_KNOCK,
            "the journey tests and JOURNEYS_THAT_KNOCK disagree. Re-run "
            "`manage.py build_traceability_matrix` and update this set and "
            "the assessment's §4b together.",
        )

    def test_no_traced_journey_computes_a_registered_metric(self):
        """The same gap, one layer higher, and the more surprising half.

        The journeys move the data that 75 registered metrics are computed
        from, but not one of them ever calls a metric's own computing
        function. So no mandated journey verifies a number a user is actually
        shown — they verify the domain state those numbers are derived from,
        and the derivation is left to the metric suite to check separately.
        That is the same seam as the route gap: the join between what the
        platform knows and what it displays is proven by nothing end to end.

        ``MetricAttributionTest`` proves this zero is a reading and not a
        broken join, which is the only reason it is safe to state.
        """
        rows = load_matrix()["requirements"]
        computing = {
            row["requirement"]: row["metricsComputed"]
            for row in rows
            if row["metricsComputed"]
        }
        self.assertEqual(
            computing,
            {},
            "a journey now computes a registered metric — good. Update this "
            "test and the assessment's §4b together.",
        )


def _flatten(suite):
    for item in suite:
        if isinstance(item, unittest.TestSuite):
            yield from _flatten(item)
        else:
            yield item


def load_tests(loader, standard_tests, pattern):
    """Keep the tracer fixtures out of the normal suite.

    ``TracerFixtures.test_fixture_fails_on_purpose`` must genuinely fail — that
    failure is how ``test_it_never_traces_a_failing_test`` proves the tracer
    refuses to record evidence from a red test. Discovered normally it would
    turn the build red for the wrong reason, so discovery skips the whole
    fixture class; ``TracerControlsTest`` runs each fixture itself, through the
    tracer, which is where their result actually means something.
    """
    kept = unittest.TestSuite()
    for test in _flatten(standard_tests):
        if isinstance(test, TracerFixtures):
            continue
        kept.addTest(test)
    return kept
