# Generated by Django 5.2.4 on 2026-07-18 18:18

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=96, unique=True)),
                ("slug", models.SlugField(max_length=96, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=32)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Help categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HelpArticle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("summary", models.TextField()),
                ("content", models.JSONField(default=list)),
                ("search_document", models.TextField(blank=True)),
                ("feature", models.CharField(blank=True, max_length=96)),
                ("workflow", models.CharField(blank=True, max_length=96)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("source_paths", models.JSONField(blank=True, default=list)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("technical_review", "Technical review"),
                            ("product_review", "Product review"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("review_due", "Review due"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("reviewer_name", models.CharField(blank=True, max_length=160)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_due_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "estimated_reading_minutes",
                    models.PositiveSmallIntegerField(default=3),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="help_articles_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_articles",
                    models.ManyToManyField(blank=True, to="help_center.helparticle"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="help_articles_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="help_center.helpcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="HelpArticleFeedback",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_role", models.CharField(blank=True, max_length=64)),
                ("page_context", models.CharField(blank=True, max_length=255)),
                ("helpful", models.BooleanField(blank=True, null=True)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("helpful", "Helpful"),
                            ("outdated", "Report outdated information"),
                            ("missing", "Report missing instructions"),
                        ],
                        default="helpful",
                        max_length=32,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="help_center.helparticle",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_help_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HelpGlossaryTerm",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("term", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("definition", models.TextField()),
                ("used_in", models.CharField(blank=True, max_length=255)),
                ("related_terms", models.JSONField(blank=True, default=list)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="glossary_terms",
                        to="help_center.helparticle",
                    ),
                ),
            ],
            options={
                "ordering": ["term"],
            },
        ),
        migrations.CreateModel(
            name="HelpReleaseNote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("version_label", models.CharField(max_length=48)),
                ("summary", models.TextField()),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "related_articles",
                    models.ManyToManyField(blank=True, to="help_center.helparticle"),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="HelpSearchKeyword",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("term", models.CharField(max_length=120)),
                ("synonym_for", models.CharField(blank=True, max_length=120)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_keywords",
                        to="help_center.helparticle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HelpWalkthrough",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("route_pattern", models.CharField(max_length=255)),
                ("steps", models.JSONField(default=list)),
                ("roles", models.JSONField(default=list)),
                ("active", models.BooleanField(default=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walkthroughs",
                        to="help_center.helparticle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HelpArticleRoleAccess",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CCEO", "CCEO"),
                            ("Program Lead", "Program Lead"),
                            ("CountryDirector", "CountryDirector"),
                            ("RegionalVicePresident", "RegionalVicePresident"),
                            ("ImpactAssessment", "ImpactAssessment"),
                            ("Accountant", "Accountant"),
                            ("HumanResources", "HumanResources"),
                            ("ProjectCoordinator", "ProjectCoordinator"),
                            ("PartnerAdmin", "PartnerAdmin"),
                            ("PartnerFieldOfficer", "PartnerFieldOfficer"),
                            ("Admin", "Admin"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_accesses",
                        to="help_center.helparticle",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "role"), name="unique_help_article_role"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HelpArticleRouteContext",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("route_pattern", models.CharField(db_index=True, max_length=255)),
                ("route_name", models.CharField(blank=True, max_length=128)),
                ("workflow_status", models.CharField(blank=True, max_length=96)),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_contexts",
                        to="help_center.helparticle",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "route_pattern", "workflow_status"),
                        name="unique_help_route_context",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HelpArticleVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("technical_review", "Technical review"),
                            ("product_review", "Product review"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("review_due", "Review due"),
                            ("archived", "Archived"),
                        ],
                        max_length=32,
                    ),
                ),
                ("snapshot", models.JSONField(default=dict)),
                ("change_summary", models.CharField(blank=True, max_length=512)),
                ("reviewer_name", models.CharField(blank=True, max_length=160)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="help_center.helparticle",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="help_article_versions_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="help_article_versions_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "version"),
                        name="unique_help_article_version",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="helparticle",
            index=models.Index(
                fields=["state", "category"], name="help_center_state_a261f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helparticle",
            index=models.Index(
                fields=["state", "slug"], name="help_center_state_81d2ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helparticle",
            index=models.Index(
                fields=["feature"], name="help_center_feature_e84216_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helparticle",
            index=models.Index(
                fields=["workflow"], name="help_center_workflo_b55556_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helpsearchkeyword",
            index=models.Index(fields=["term"], name="help_center_term_c6d36e_idx"),
        ),
        migrations.AddConstraint(
            model_name="helpsearchkeyword",
            constraint=models.UniqueConstraint(
                fields=("article", "term"), name="unique_help_search_keyword"
            ),
        ),
    ]
