// AUTO-GENERATED from "Statistics Subcounties.pdf" (Uganda General Elections 2015-2016
// sub-county register). District -> sub-counties, the canonical mapping used by
// the geography layer. Do not hand-edit; regenerate from the source if it changes.

export const SUBCOUNTY_NAMES_BY_DISTRICT: Record<string, string[]> = {
  "Abim": ["Abim", "Abim Town Council", "Alerek", "Lotukei", "Morulem", "Nyakwae"],
  "Adjumani": ["Adropi", "Arinyapi", "Ciforo", "Dzaipi", "Itirikwa", "Ofua", "Pachara", "Pakele", "Ukusijoni"],
  "Agago": ["Adilang", "Agago Town Council", "Arum", "Kalongo Town Council", "Kotomor", "Lamiyo", "Lapono", "Lira-Palwo", "Lokole", "Omiya Pacwa", "Omot", "Paimol", "Parabongo", "Patongo", "Patongo Town Council", "Wol"],
  "Alebtong": ["Abako", "Abia", "Akura", "Aloi", "Amugu", "Apala", "Awei", "Omoro"],
  "Amolatar": ["Agikdak", "Agwingiri", "Akwon", "Aputi", "Arwotcek", "Awello", "Etam", "Muntu", "Namasale"],
  "Amudat": ["Amudat", "Amudat Town Council", "Karita", "Loroo"],
  "Amuria": ["Abarilela", "Acowa", "Akeriau", "Akoromit", "Amuria Town Council", "Apeduru", "Asamuk", "Kapelebyong", "Kuju", "Morungatuny", "Obalanga", "Ogolai", "Okungur", "Orungo", "Wera", "Willa"],
  "Amuru": ["Amuru", "Amuru Town Council", "Atiak", "Lamogi", "Pabbo"],
  "Apac": ["Abongomola", "Aduku", "Aduku Town Council", "Akokoro", "Apac", "Apac Town Council", "Cawente", "Chegere", "Ibuje", "Inomo", "Nambieso"],
  "Arua": ["Adumi", "Aii-Vu/Ajivu", "Ajia", "Anyiribu", "Arivu", "Aroi", "Arua Hill", "Ayivuni", "Beleafe", "Dadamu", "Ewanga", "Katrini", "Logiri", "Manibe", "Odupi", "Offaka", "Ogoko", "Okollo", "Oli River", "Oluko", "Omugo", "Pajulu", "Pawor", "Rhino Camp", "Rigbo", "Uleppi", "Uriama", "Vurra"],
  "Budaka": ["Budaka", "Budaka Town Council", "Iki-Iki", "Kachomo", "Kaderuna", "Kakule", "Kameruka", "Kamonkoli", "Katira", "Lyama", "Mugiti", "Naboa", "Nansanga"],
  "Bududa": ["Bubiita", "Bududa", "Bududa Town Council", "Bukalasi", "Bukibokolo", "Bukigai", "Bulucheke", "Bumasheti", "Bumayoka", "Bushika", "Bushiribo", "Bushiyi", "Buwali", "Nabweya", "Nakatsi", "Nalwanza"],
  "Bugiri": ["Budhaya", "Bugiri Town Council", "Bulesa", "Bulidha", "Buluguyi", "Buwunga", "Iwemba", "Kapyanga", "Muterere", "Nabukalu", "Nankoma"],
  "Buhweju": ["Bihanga", "Bitsya", "Burere", "Engaju", "Karungu", "Nsiika Town Council", "Nyakishana", "Rwengwe"],
  "Buikwe": ["Buikwe", "Buikwe Town Council", "Central Division", "Kawolo Division", "Najja", "Najjembe Division", "Ngogwe", "Njeru Town Council", "Nyenga", "Ssi", "Wakisi"],
  "Bukedea": ["Bukedea", "Bukedea Town Council", "Kachumbala Council", "Kidongole", "Kolir", "Malera"],
  "Bukwo": ["Bukwa", "Bukwo Town Council", "Chepkwasta", "Chesower", "Kabei", "Kamet", "Kaptererwo", "Kortek", "Riwo", "Senendet", "Suam", "Tulel"],
  "Bulambuli": ["Buginyanya", "Bukhalu", "Bulago", "Bulegeni", "Bulegeni Town Council", "Buluganya", "Bumasobo", "Bumugibole", "Bunambutye", "Bwikhonge", "Kamu", "Lusha", "Masira", "Muyembe", "Nabbongo", "Namisuni", "Simu", "Sisiyi"],
  "Buliisa": ["Biiso", "Buliisa", "Buliisa Town Council", "Butiaba", "Kigwera", "Kihungya", "Ngwedo"],
  "Bundibugyo": ["Bubandi", "Bubukwanga", "Bukonzo", "Busaru", "Harugali", "Kasitu", "Kirumya", "Kisubba", "Mirambi", "Ndugutu", "Ngamba", "Ntotoro", "Nyahuka Town Council", "Sindila"],
  "Bushenyi": ["Bitooma", "Bumbaire", "Central Division", "Ibaare", "Ishaka Division", "Kakanju", "Kyabugimbi", "Kyamuhunga", "Kyeizooba", "Nyabubare", "Nyakabirizi Division", "Ruhumuro"],
  "Busia": ["Buhehe", "Bulumbi", "Busime", "Busitema", "Buteba", "Buyanga", "Dabani", "Eastern Division", "Lumino", "Lunyo", "Majanji", "Masaba", "Masafu", "Masinya", "Sikuda", "Western Division"],
  "Butaleja": ["Budumba", "Busaba", "Busabi", "Busolwe", "Busolwe Town Council", "Butaleja", "Butaleja Town Council", "Himutu", "Kachonga", "Mazimasa", "Nawanjofu", "Naweyo"],
  "Butambala": ["Budde", "Bulo", "Gombe Town Council", "Kalamba", "Kibibi", "Ngando"],
  "Buvuma": ["Bugaya", "Busamuzi", "Buvuma Town Council", "Buwooya", "Bweema", "Lubya", "Lwaje", "Lyabaana", "Nairambi"],
  "Buyende": ["Bugaya", "Buyende", "Buyende Town Council", "Kagulu", "Kidera", "Nkondo"],
  "Dokolo": ["Adeknino", "Adok", "Agwatta", "Amwoma", "Batta", "Dokolo", "Dokolo Town Council", "Kangai", "Kwera", "Okwalongwen", "Okwongodul"],
  "Gomba": ["Kabulasoke", "Kanoni Town Council", "Kyegonza", "Maddu", "Mpenja"],
  "Gulu": ["Awach", "Bar-Dege", "Bobi", "Bungatira", "Koro", "Lakwana", "Lalogi", "Laroo", "Layibi", "Odek", "Ongako", "Paicho", "Palaro", "Patiko", "Pece", "Unyama"],
  "Hoima": ["Bugambe", "Buhanika", "Buhimba", "Bujumbura Division", "Buseruka", "Busiisi Division", "Kabwoya", "Kahoora Division", "Kigorobya", "Kitoba", "Kiziranfumbi", "Kyabigambire", "Kyangwali", "Mparo Division"],
  "Ibanda": ["Bisheshe", "Ibanda Town Council", "Igorora Town Council", "Ishongororo", "Kashangura", "Keihangara", "Kicuzi", "Kijongo", "Kikyenkye", "Nsasi", "Nyabuhikye", "Nyamarebe", "Rukiri"],
  "Iganga": ["Bulamagi", "Buyanga", "Central Division", "Ibulanku", "Igombe", "Makuutu", "Nabitende", "Nakalama", "Nakigo", "Namalemba", "Nambale", "Namungalwe", "Nawandala", "Nawanyingi", "Northern Division"],
  "Isingiro": ["Birere", "Endinzi", "Isingiro Town Council", "Kabingo", "Kabuyanda", "Kashumba", "Kikagate", "Masha", "Mbaare", "Ngarama", "Nyakitunda", "Nyamuyanja", "Ruborogota", "Rugaaga", "Rushasha"],
  "Jinja": ["Budondo", "Bugembe Town Council", "Busedde", "Butagaya", "Buwenge", "Buwenge Town Council", "Buyengo", "Jinja Central", "Kakira Town Council", "Kimaka /Mpumudde", "Mafubira", "Walukuba/Masese"],
  "Kaabong": ["Kaabong East", "Kaabong Town Council", "Kaabong West", "Kalapata", "Kamion", "Kapedo", "Karenga(Napore)", "Kathile", "Kawalakol", "Lobalangit", "Lodiko", "Lolelia", "Loyoro", "Sidok (Kopoth)"],
  "Kabale": ["Bubare", "Bufundi", "Buhara", "Bukinda", "Butanda", "Hamurwa", "Ikumba", "Kabale Central", "Kabale Northern", "Kabale Southern", "Kaharo", "Kamuganguzi", "Kamwezi", "Kashambya", "Katuna Town Council", "Kitumba", "Kyanamira", "Maziba", "Muko", "Nyamweeru", "Rubaya", "Ruhija", "Rwamucucu"],
  "Kabarole": ["Buheesi", "Bukuuku", "Busoro", "Eastern Division", "Hakibale", "Harugongo", "Kabende", "Kabonero", "Karago Town Council", "Karambi", "Karangura", "Kasenda", "Kateebwa", "Kibiito", "Kibiito Town Council", "Kicwamba", "Kijura Town Council", "Kiko Town Council", "Kisomoro", "Kiyombya", "Mugusu", "Rubona Town Council", "Ruteete", "Rwimi", "Rwimi Town Council", "Southern Division", "Western Division Council"],
  "Kalangala": ["Bubeke", "Bufumira", "Bujumba", "Kyamuswa", "Mazinga", "Mugoye"],
  "Kaliro": ["Bumanya", "Gadumire", "Kaliro Town Council", "Namugongo", "Namwiwa", "Nawaikoke"],
  "Kalungu": ["Bukulula", "Kalungu", "Kalungu Town Council", "Kyamulibwa", "Lukaya Town Council", "Lwabenge"],
  "Kampala": ["Kampala Central", "Kawempe Division", "Makerere University", "Makindye Division", "Nakawa", "Rubaga Division"],
  "Kamuli": ["Balawoli", "Bugulumbya", "Bulopa", "Butansi", "Kisozi", "Kitayunjwa", "Mbulamuti", "Nabwigulu", "Namasagali", "Namwendwa", "Nawanyago", "Northern Division", "Southern Division", "Wankole"],
  "Kamwenge": ["Biguli", "Bihanga", "Buhanda", "Busiriba", "Bwizi", "Kabambiro", "Kahunge", "Kamwenge", "Kanara", "Kicheche", "Mahyoro", "Nkoma", "Ntara", "Nyabbani"],
  "Kanungu": ["Kambuga", "Kambuga Town Council", "Kanungu Town Council", "Kanyantorogo", "Katete", "Kayonza", "Kihiihi", "Kihiihi Town Council", "Kinaaba", "Kirima", "Mpungu", "Nyakinoni", "Nyamirama", "Nyanga", "Rugyeyo", "Rutenga"],
  "Kapchorwa": ["Amukol", "Central Division", "Chema", "Chepterech", "East Division", "Gamogo", "Kabeywa", "Kapsinda", "Kaptanya", "Kaserem", "Kawowo", "Munarya", "Sipi", "West Division"],
  "Kasese": ["Bugoye", "Buhuhira", "Bulembia Division", "Bwera", "Bwesumbu", "Central Division", "Hima Town Council", "Ihandiro", "Isango", "Karambi", "Karusandara", "Kilembe", "Kisinga", "Kitholu", "Kitswamba", "Kyabarungira", "Kyarumba", "Kyondo", "Lake Katwe", "Mahango", "Maliba", "Muhokya", "Munkunyu", "Nyakatonzi", "Nyakiyumbu", "Nyamwamba Division", "Rukoki", "Town Council"],
  "Katakwi": ["Kapujan", "Katakwi", "Katakwi Town Council", "Magoro", "Ngariam", "Omodoi", "Ongongoja", "Palam", "Toroma", "Usuk"],
  "Kayunga": ["Bbaale", "Busaana", "Galiraya", "Kangulumira", "Kayonza", "Kayunga", "Kayunga Town Council", "Kitimbwa", "Nazigo"],
  "Kibaale": ["Birembo", "Bubango", "Burora", "Bwamiramira", "Bwanswa", "Bwikara", "Kabamba", "Kagadi", "Kagadi Town Council", "Kakindo", "Kasambya", "Kibaale Town Council", "Kiryanga", "Kisiita", "Kyakabadiima", "Kyanaisoke", "Kyaterekera", "Kyebando", "Kyenzige", "Mabaale", "Matale", "Mpasaana", "Mpeefu", "Mugarama", "Muhorro", "Narweyo", "Ndaiga", "Nkooko", "Nyamarunda", "Nyamarwa", "Pachwa", "Rugashari", "Ruteete"],
  "Kiboga": ["Bukomero", "Ddwaniro", "Kapeke", "Kibiga", "Kiboga Town Council", "Lwamata", "Muwanga"],
  "Kibuku": ["Bulangira", "Buseta", "Kabweri", "Kadama", "Kagumu", "Kasasira", "Kibuku", "Kibuku Town Council", "Kirika", "Tirinyi"],
  "Kiruhura": ["Buremba", "Burunga", "Engari", "Kanoni", "Kanyaryeru", "Kashongi", "Kazo", "Kazo Town Council", "Kenshunga", "Kikatsi", "Kinoni", "Kiruhura Town Council", "Kitura", "Nkungu", "Nyakashashara", "Rwemikoma", "Sanga", "Sanga Town Council"],
  "Kisoro": ["Bukimbiri", "Busanza", "Central Division", "Chahi", "Kanaba", "Kirundo", "Muramba", "Murora", "North Division", "Nyabwishenya", "Nyakabande", "Nyakinama", "Nyarubuye", "Nyarusiza", "Nyundo", "South Division"],
  "Kitgum": ["Akwang", "Central Division", "Kitgum Matidi", "Labongo-Amida", "Labongo-Layamo", "Lagoro", "Muchwini", "Nam-Okora", "Omiya-Anyima", "Orom", "Pager Division", "Pandwong Division"],
  "Koboko": ["Abuku", "Dranya", "Kuluba", "Lobule", "Ludara", "Midia", "North Division", "South Division", "Western Division"],
  "Kole": ["Aboke", "Akalo", "Alito", "Ayer", "Balla", "Kole Town Council"],
  "Kotido": ["Kacheri", "Kotido", "Kotido Town Council", "Nakapelimoru", "Panyangara", "Rengen"],
  "Kumi": ["Atutur", "Kanyum", "Kumi", "Mukongoro", "North Division", "Nyero", "Ongino", "South Division"],
  "Kween": ["Benet", "Binyiny", "Binyiny Town Council", "Greek River", "Kaproron", "Kaptoyoy", "Kaptum", "Kitawoi", "Kwanyiy", "Kwosir", "Moyok", "Ngenge"],
  "Kyankwanzi": ["Bananywa", "Butemba", "Butemba Town Council", "Gayaza", "Kitabona", "Kyankwanzi", "Mulagi", "Nkandwa", "Nsambya", "Wattuba"],
  "Kyegegwa": ["Hapuuyo", "Kakabara", "Kasule", "Kigambo", "Kyegegwa", "Mpara", "Ruyonza", "Rwentuha"],
  "Kyenjojo": ["Bufunjo", "Bugaaki", "Butiiti", "Butunduzi", "Katooke", "Katooke Town Council", "Kigaraale", "Kihuura", "Kisojo", "Kyarusozi", "Kyembogo", "Kyenjojo Town Council", "Nyabuharwa", "Nyankwanzi", "Nyantungo"],
  "Lamwo": ["Agoro", "Lamwo Town Council", "Lokung", "Madi-Opei", "Ogili", "Padibe East", "Padibe Town Council", "Padibe West", "Palabek-Gem", "Palabek-Kal", "Paloga"],
  "Lira": ["Adekokwok", "Adyel", "Agali", "Agweng", "Amach", "Aromo", "Barr", "Lira", "Lira Central", "Ngetta", "Ogur", "Ojwina", "Railways"],
  "Luuka": ["Bukanga", "Bukooma", "Bulongo", "Ikumbya", "Irongo", "Luuka Town Council", "Nawampiti", "Waibuga"],
  "Luweero": ["Bamunanika", "Bombo Town Council", "Butuntumula", "Kalagala", "Kamira", "Katikamu", "Kikyusa", "Luweero Town Council", "Luwero", "Makulubita", "Nyimbwa", "Zirobwe"],
  "Lwengo": ["Kingo", "Kisekka", "Kyazanga", "Lwengo", "Lwengo Town Council", "Malongo", "Ndagwe"],
  "Lyantonde": ["Kaliiro", "Kasagama", "Kinuuka", "Lyakajura", "Lyantonde", "Mpumudde"],
  "Manafwa": ["Bubutu", "Bugobero", "Bukhabusi", "Bukhaweka", "Bukhofu", "Bukiabi", "Bukoho", "Bukusu", "Bumbo", "Bumwoni", "Bunabwana", "Bupoto", "Busukuya", "Butiru", "Butta", "Buwabwala", "Buwagogo", "Kaato", "Khabutoola", "Magale", "Mukoto", "Nalondo", "Namabya", "Namboko", "Sibanga", "Sisuni", "Tsekululu", "Weswa"],
  "Maracha": ["Kijomoro", "Maracha Town Council", "Nyadri", "Oleba", "Olufe", "Oluvu", "Tara", "Yivu"],
  "Masaka": ["Bukakata", "Buwunga", "Kabonera", "Katwe/Butego", "Kimaanya/Kyabakuza", "Kyanamukaka", "Kyesiiga", "Mukungwe", "Nyendo/Senyange"],
  "Masindi": ["Budongo", "Bwijanga", "Central Division", "Karujubu Division", "Kigulya Division", "Kimengo", "Miirya", "Nyangahya Division", "Pakanyi"],
  "Mayuge": ["Baitambogwe", "Bukabooli", "Bukatube", "Busakira", "Buwaaya", "Imanyiro", "Jaguzi", "Kigandalo", "Kityerera", "Malongo", "Mayuge Town Council", "Mpungwe", "Wairasa"],
  "Mbale": ["Bubyangu", "Budwale", "Bufumbo", "Bukasakya", "Bukhiende", "Bukonde", "Bumasikye", "Bumbobi", "Bungokho", "Busano", "Busiu", "Busoba", "Industrial Borough", "Lukhonge", "Lwasso", "Nakaloke", "Namanyonyi", "Nambale", "Northern Borough", "Nyondo", "Wanale", "Wanale Borough"],
  "Mbarara": ["Biharwe", "Bubaare", "Bugamba", "Bukiiro", "Kagongi", "Kakiika", "Kakoba", "Kamukuzi", "Kashare", "Mwizi", "Ndeija", "Nyakayojo", "Nyamitanga", "Rubaya", "Rubindi", "Rugando", "Rwanyamahembe"],
  "Mitooma": ["Bitereko", "Kabira", "Kanyabwanga", "Kashenshero", "Katenga", "Kiyanga", "Mayanga", "Mitooma", "Mitooma Town Council", "Mutara", "Rurehe"],
  "Mityana": ["Bbanda", "Bulera", "Busimbi Division", "Butayunja", "Central Division", "Kakindu", "Kalangaalo", "Kikandwa", "Maanyi", "Malangala", "Namungo", "Ssekanyonyi", "Ttamu Division"],
  "Moroto": ["Katikekile", "Nadunget", "North Division", "Rupa", "South Division", "Tapac"],
  "Moyo": ["Aliba", "Dufile", "Gimara", "Itula", "Laropi", "Lefori", "Metu", "Moyo", "Moyo Town Council"],
  "Mpigi": ["Buwama", "Kammengo", "Kiringente", "Kituntu", "Mpigi Town Council", "Muduma", "Nkozi"],
  "Mubende": ["Bagezza", "Bukuya", "Butoloogo", "East Division", "Kalwana", "Kasambya", "Kassanda", "Kibalinga", "Kiganda", "Kigando", "Kitenga", "Kitumbi", "Kiyuni", "Madudu", "Makokoto", "Manyogaseka", "Myanzi", "Nabingoola", "Nalutuntu", "South Division", "West Division"],
  "Mukono": ["Goma Division", "Kasawo", "Kimenyedde", "Koome Islands", "Kyampisi", "Mpatta", "Mpunge", "Mukono Division", "Nabbale", "Nagojje", "Nakisunga", "Nama", "Namuganga", "Ntenjeru", "Ntunda Council"],
  "Nakaseke": ["Kaasangombe", "Kapeeka", "Kikamulo", "Kinoni", "Kinyogoga", "Kitto", "Kiwoko Town Council", "Nakaseke", "Nakaseke Town Council", "Ngoma", "Ngoma Town Council", "Semuto", "Semuto Town Council", "Wakyato"],
  "Namayingo": ["Banda", "Buhemba", "Bukana", "Buswale", "Buyinja", "Lolwe", "Mutumba", "Sigulu Islands"],
  "Napak": ["Iriiri", "Lokopo", "Lopei", "Lorengecora", "Lotome", "Matany", "Napak Town Council", "Ngoleriet"],
  "Nebbi": ["Akworo", "Alwi", "Atego", "Erussi", "Kucwiny", "Ndhew", "Nebbi", "Nebbi Town Council", "Nyaravur", "Pakwach", "Pakwach Town Council", "Panyango", "Panyimur", "Parombo", "Wadelai"],
  "Ngora": ["Kapir", "Kobwin", "Mukura", "Ngora", "Ngora Town Council"],
  "Ntoroko": ["Butungama", "Bweramule", "Kanara", "Kanara Town Council", "Karugutu", "Kibuuku Town Council", "Nombe", "Rwebisengo"],
  "Ntungamo": ["Bwongyera", "Central Division", "Eastern Division", "Ihunga", "Itojo", "Kayonza", "Kibatsi", "Kitwe Town Council", "Ngoma", "Ntungamo", "Nyabihoko", "Nyakyera", "Rubaare", "Rubaare Town Council", "Rugarama", "Ruhaama", "Rukoni East", "Rukoni West", "Rweikiniro", "Western Division"],
  "Nwoya": ["Alero", "Anaka (Payira)", "Got Apwoyo", "Koch-Goma", "Lii", "Lungulu", "Nwoya Town Council", "Purongo"],
  "Otuke": ["Adwari", "Ogor", "Okwang", "Olilim", "Orum", "Otuke Town Council"],
  "Oyam": ["Aber", "Abok", "Achaba", "Aleka", "Icheme", "Kamdini", "Loro", "Minakulu", "Myene", "Ngai", "Otwal", "Oyam Town Council"],
  "Pader": ["Acholi-Bur", "Angagura", "Atanga", "Awere", "Laguti", "Lapul", "Latanya", "Ogom", "Pader", "Pader Town Council", "Pajule", "Puranga"],
  "Pallisa": ["Agule", "Akisim", "Apopong", "Butebo", "Chelekura", "Gogonyo", "Kabwangasi", "Kakoro", "Kameke", "Kamuge", "Kanginima", "Kasodo", "Kibale", "Olok", "Opwateta", "Pallisa", "Pallisa Town Council", "Petete", "Puti-Puti"],
  "Rakai": ["Byakabanda", "Ddwaniro", "Kabira", "Kacheera", "Kagamba (Buyamba)", "Kakuuto", "Kalisizo", "Kalisizo Town Council", "Kasaali", "Kasasa", "Kibanda", "Kifamba", "Kirumba", "Kiziba", "Kyalulangira", "Kyebe", "Kyotera Town Council", "Lwamaggwa", "Lwanda", "Lwankoni", "Nabigasa", "Rakai Town Council"],
  "Rubirizi": ["Katanda", "Katerera", "Katerera Town Council", "Katunguru", "Kichwamba", "Kirugu", "Kyabakara", "Magambo", "Rubirizi Town Council", "Rutoto", "Ryeru"],
  "Rukungiri": ["Bugangari", "Buhunga", "Buyanja", "Bwambara", "Eastern Division", "Kebisoni", "Nyakagyeme", "Nyakishenyi", "Nyarushanje", "Ruhinda", "Southern Division", "Western Division"],
  "Serere": ["Atiira", "Bugondo", "Kadungulu", "Kasilo Town Council", "Kateta", "Kyere", "Labor", "Pingire", "Serere Town Council", "Serere/Olio"],
  "Sheema": ["Bugongi Town Council", "Kagango", "Kasaana", "Kashozi", "Kigarama", "Kitagata", "Kyangyenyi", "Masheruka", "Rugarama", "Sheema Town Council", "Shuuku", "Town Council"],
  "Sironko": ["Budadiri Town Council", "Bugitimwa", "Buhugu", "Bukhulo", "Bukiise", "Bukiyi", "Bukyabo", "Bukyambi", "Bumalimba", "Bumasifwa", "Bunyafwa", "Busulani", "Butandiga", "Buteza", "Buwalasi", "Buwasa", "Buyobo", "Masaba", "Nalusala", "Sironko Town Council", "Zesui"],
  "Soroti": ["Arapai", "Asuret", "Eastern", "Gweri", "Kamuda", "Katine", "Northern", "Soroti", "Tubur", "Western"],
  "Ssembabule": ["Lugusulu", "Lwebitakuli", "Lwemiyaga", "Mateete", "Mateete Town Council", "Mijwala", "Ntuusi"],
  "Tororo": ["Iyolwa", "Kirewa", "Kisoko", "Kwapa", "Magola", "Malaba Town Council", "Mella", "Merikit", "Molo", "Mukuju", "Mulanda", "Nabuyoga", "Nagongera", "Osukuru", "Paya", "Petta", "Rubongi", "Sopsop", "Tororo Eastern", "Tororo Western"],
  "Wakiso": ["Bunamwaya Division", "Bussi", "Busukuma Division", "Bweyogerere Division", "Division A", "Division B", "Gombe Division", "Kakiri", "Kakiri Town Council", "Kasanje", "Katabi", "Kira Division", "Kiziba(Masuliita)", "Masajja Division", "Mende", "Nabweru Division", "Namayumba", "Namugongo Division", "Nangabo", "Nansana Division", "Ndejje Division", "Nsangi", "Ssisa", "Wakiso", "Wakiso Town Council"],
  "Yumbe": ["Apo", "Ariwa", "Drajini/Arajim", "Kei", "Kerwa", "Kochi", "Kululu", "Kuru", "Lodonga", "Midingo", "Odravu", "Romogi", "Yumbe Town Council"],
  "Zombo": ["Abanga", "Atyak", "Jangokoro", "Kango", "Nyapea", "Paidha", "Paidha Town Council", "Warr", "Zeu", "Zombo Town Council"],
};
