# Generated by Django 5.2.4 on 2026-07-08 22:26

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecondaryDistrictGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("inactive", "Inactive"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("approved_by", models.CharField(blank=True, max_length=30, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                "db_table": "secondary_district_group",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="district",
            name="district_type",
            field=models.CharField(
                blank=True,
                choices=[("primary", "Primary"), ("secondary", "Secondary")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SecondaryDistrictGroupMember",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_group_memberships",
                        to="geography.district",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="geography.secondarydistrictgroup",
                    ),
                ),
            ],
            options={
                "db_table": "secondary_district_group_member",
                "indexes": [
                    models.Index(
                        fields=["district"], name="secondary_d_distric_b793ba_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "district"),
                        name="uniq_secondary_group_district",
                    )
                ],
            },
        ),
    ]
