# Generated by Django 5.2.4 on 2026-07-12 18:29

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0012_stafftargetprofile_new_core_schools_target_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=64, null=True)),
                ("skills", models.TextField(blank=True, null=True)),
                ("talent_pool_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hr_candidate",
            },
        ),
        migrations.CreateModel(
            name="ComplianceRequirement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_mandatory", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "hr_compliance_requirement",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("category", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "db_table": "hr_skill",
            },
        ),
        migrations.CreateModel(
            name="CompensationRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("salary_band", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "base_salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "allowances",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "benefits_tier",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("status", models.CharField(default="HR Review", max_length=32)),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensation_details",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "hr_compensation",
            },
        ),
        migrations.CreateModel(
            name="CPDAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=64)),
                ("status", models.CharField(default="Assigned", max_length=32)),
                (
                    "evidence_url",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpd_assignments",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "hr_cpd_assignment",
            },
        ),
        migrations.CreateModel(
            name="EmployeeRelationsCase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("case_type", models.CharField(db_index=True, max_length=64)),
                ("severity", models.CharField(default="medium", max_length=32)),
                ("status", models.CharField(default="Submitted", max_length=32)),
                ("description", models.TextField()),
                ("findings", models.TextField(blank=True, null=True)),
                ("is_confidential", models.BooleanField(default=True)),
                (
                    "case_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relations_cases_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_relations_case",
            },
        ),
        migrations.CreateModel(
            name="OffboardingPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="Initiated", max_length=32)),
                ("last_working_day", models.DateField(blank=True, null=True)),
                ("clearance_completed", models.BooleanField(default=False)),
                (
                    "handover_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_handovers",
                        to="accounts.staffprofile",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offboarding_details",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "hr_offboarding",
            },
        ),
        migrations.CreateModel(
            name="OnboardingPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="Not Started", max_length=32)),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_plan",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "hr_onboarding_plan",
            },
        ),
        migrations.CreateModel(
            name="OnboardingTask",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="hr.onboardingplan",
                    ),
                ),
            ],
            options={
                "db_table": "hr_onboarding_task",
            },
        ),
        migrations.CreateModel(
            name="PerformanceImprovementPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="Draft", max_length=32)),
                ("cause", models.CharField(max_length=128)),
                ("action_plan", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pip_plans",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "hr_pip_plan",
            },
        ),
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period", models.CharField(db_index=True, max_length=32)),
                (
                    "review_type",
                    models.CharField(default="Quarterly Review", max_length=64),
                ),
                ("status", models.CharField(default="Not Started", max_length=32)),
                ("due_date", models.DateField()),
                ("rating", models.CharField(blank=True, max_length=32, null=True)),
                ("score", models.FloatField(default=0.0)),
                ("manager_feedback", models.TextField(blank=True, null=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "hr_performance_review",
            },
        ),
        migrations.CreateModel(
            name="SuccessionCandidate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position_name", models.CharField(db_index=True, max_length=255)),
                (
                    "readiness",
                    models.CharField(default="Development Required", max_length=64),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "staff_successor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="succession_nominations",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "hr_succession_candidate",
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country", models.CharField(db_index=True, max_length=64)),
                ("department", models.CharField(db_index=True, max_length=64)),
                ("role", models.CharField(db_index=True, max_length=64)),
                (
                    "employment_type",
                    models.CharField(default="Full-time", max_length=64),
                ),
                ("reason_for_vacancy", models.TextField(blank=True, null=True)),
                (
                    "replacement_or_new_role",
                    models.CharField(
                        choices=[
                            ("replacement", "Replacement"),
                            ("new_role", "New Role"),
                        ],
                        default="new_role",
                        max_length=32,
                    ),
                ),
                ("required_skills", models.TextField(blank=True, null=True)),
                ("target_start_date", models.DateField(blank=True, null=True)),
                (
                    "approved_salary_band",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "budget_source",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("status", models.CharField(default="Draft", max_length=32)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_vacancies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_vacancies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_vacancy",
            },
        ),
        migrations.CreateModel(
            name="EmployeeComplianceRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="Missing", max_length=32)),
                (
                    "document_url",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.compliancerequirement",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_records",
                        to="accounts.staffprofile",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_compliance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_employee_compliance_record",
                "unique_together": {("staff", "requirement")},
            },
        ),
        migrations.CreateModel(
            name="HRAuditEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=255)),
                ("record_id", models.CharField(max_length=64)),
                ("details", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_audit_event",
                "indexes": [
                    models.Index(
                        fields=["record_id"], name="hr_audit_ev_record__5d0990_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="hr_audit_ev_created_f0d002_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollReadinessRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payroll_period", models.CharField(db_index=True, max_length=32)),
                ("has_exceptions", models.BooleanField(default=False)),
                ("exception_notes", models.TextField(blank=True, null=True)),
                ("is_payroll_ready", models.BooleanField(default=False)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_checks",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "hr_payroll_readiness",
                "unique_together": {("staff", "payroll_period")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeSkill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("level", models.IntegerField(default=1)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills_matrix",
                        to="accounts.staffprofile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hr.skill"
                    ),
                ),
            ],
            options={
                "db_table": "hr_employee_skill",
                "unique_together": {("staff", "skill")},
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stage", models.CharField(default="Applied", max_length=64)),
                ("status_notes", models.TextField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="hr.candidate",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="hr.vacancy",
                    ),
                ),
            ],
            options={
                "db_table": "hr_application",
                "unique_together": {("vacancy", "candidate")},
            },
        ),
    ]
