# Generated by Django 5.2.4 on 2026-07-21 19:07

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_exited_state'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformancePriority',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('outcome_statement', models.TextField()),
                ('strategic_alignment', models.CharField(blank=True, max_length=255, null=True)),
                ('measures_of_success', models.TextField(blank=True, null=True)),
                ('baseline', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.PositiveSmallIntegerField(default=20)),
                ('support_needed', models.TextField(blank=True, null=True)),
                ('current_result', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('on_track', 'On track'), ('at_risk', 'At risk'), ('off_track', 'Off track'), ('achieved', 'Achieved'), ('not_assessed', 'Not assessed')], default='not_assessed', max_length=32)),
                ('system_evidence', models.JSONField(blank=True, null=True)),
                ('employee_reflection', models.TextField(blank=True, null=True)),
                ('manager_assessment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_performance_priority',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='PerformancePriorityMilestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=512)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_url', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'hr_performance_priority_milestone',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCheckIn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('held_on', models.DateField()),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'hr_recovery_check_in',
                'ordering': ['-held_on'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryMilestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=512)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_recovery_milestone',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='assessment_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='decision_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_panel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='provisioned_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='reference_check_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retention_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerelationscase',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerelationscase',
            name='appeal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerelationscase',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerelationscase',
            name='country',
            field=models.CharField(db_index=True, default='Uganda', max_length=64),
        ),
        migrations.AddField(
            model_name='employeerelationscase',
            name='investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations_cases_investigating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeerelationscase',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerelationscase',
            name='raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations_cases_raised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeerelationscase',
            name='retention_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerelationscase',
            name='subject_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations_cases_about', to='accounts.staffprofile'),
        ),
        migrations.AddField(
            model_name='onboardingplan',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingplan',
            name='probation_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingplan',
            name='source_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_plans', to='hr.application'),
        ),
        migrations.AddField(
            model_name='onboardingplan',
            name='supervisor_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingplan',
            name='target_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='category',
            field=models.CharField(default='general', max_length=64),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_onboarding_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='owner_role',
            field=models.CharField(default='employee', max_length=64),
        ),
        migrations.AddField(
            model_name='performanceimprovementplan',
            name='cause_evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceimprovementplan',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceimprovementplan',
            name='escalated_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_recovery_plans', to='hr.employeerelationscase'),
        ),
        migrations.AddField(
            model_name='performanceimprovementplan',
            name='outcome',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='performanceimprovementplan',
            name='outcome_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceimprovementplan',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_plans_owned', to='accounts.staffprofile'),
        ),
        migrations.AddField(
            model_name='performanceimprovementplan',
            name='plan_type',
            field=models.CharField(choices=[('informal', 'Informal recovery plan'), ('formal', 'Formal performance improvement plan')], default='informal', max_length=16),
        ),
        migrations.AddField(
            model_name='performanceimprovementplan',
            name='support_offered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='calibrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='calibrated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrated_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='calibration_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='calibration_result',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='employee_reflection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='employee_reflection_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='fy',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_managed', to='accounts.staffprofile'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='manager_assessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='manager_rating',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='stage',
            field=models.CharField(choices=[('not_started', 'Not started'), ('priorities_draft', 'Employee drafting priorities'), ('priorities_manager_review', 'Manager reviewing priorities'), ('priorities_agreed', 'Priorities agreed'), ('employee_reflection', 'Employee reflection'), ('manager_assessment', 'Manager assessment'), ('calibration', 'Calibration'), ('awaiting_acknowledgement', 'Awaiting employee acknowledgement'), ('closed', 'Closed')], default='not_started', max_length=40),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='system_evidence',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='system_evidence_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='system_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='decision_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_vacancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('assessment', 'Assessment'), ('reference_check', 'Reference check'), ('offer', 'Offer'), ('accepted', 'Offer accepted'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=64),
        ),
        migrations.AlterField(
            model_name='employeerelationscase',
            name='case_type',
            field=models.CharField(choices=[('grievance', 'Grievance'), ('conflict', 'Conflict'), ('harassment', 'Harassment concern'), ('conduct', 'Conduct concern'), ('whistleblowing', 'Whistleblowing'), ('safeguarding', 'Safeguarding referral')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='employeerelationscase',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('triage', 'Restricted triage'), ('investigation', 'Investigation'), ('findings', 'Findings recorded'), ('action', 'Action decided'), ('appeal', 'Under appeal'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='submitted', max_length=32),
        ),
        migrations.AlterField(
            model_name='onboardingplan',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('supervisor_review', 'Awaiting supervisor confirmation'), ('ready_for_activation', 'Ready for activation'), ('closed', 'Closed')], default='not_started', max_length=32),
        ),
        migrations.AlterField(
            model_name='performanceimprovementplan',
            name='cause',
            field=models.CharField(choices=[('capacity', 'Capacity — portfolio beyond capacity'), ('workload', 'Workload — competing demands'), ('skill', 'Skill gap'), ('availability', 'Availability — leave or absence'), ('data_quality', 'Data quality — work done but not credited'), ('manager_support', 'Manager support'), ('conduct', 'Conduct'), ('other', 'Other')], default='other', max_length=128),
        ),
        migrations.AlterField(
            model_name='performanceimprovementplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('progress_review', 'Progress review'), ('completed', 'Successfully completed'), ('extended', 'Extended'), ('escalated', 'Escalated to a conduct case'), ('closed', 'Closed')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='review_type',
            field=models.CharField(choices=[('annual_priorities', 'Annual priorities'), ('mid_year', 'Mid-year review'), ('year_end', 'Year-end review'), ('quarterly', 'Quarterly review'), ('probation', 'Probation review')], default='annual_priorities', max_length=64),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
        migrations.AddIndex(
            model_name='employeerelationscase',
            index=models.Index(fields=['country', 'status'], name='hr_relation_country_92d152_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['staff', 'fy'], name='hr_performa_staff_i_472064_idx'),
        ),
        migrations.AddField(
            model_name='performancepriority',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='hr.performancereview'),
        ),
        migrations.AddField(
            model_name='performanceprioritymilestone',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='hr.performancepriority'),
        ),
        migrations.AddField(
            model_name='recoverycheckin',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='hr.performanceimprovementplan'),
        ),
        migrations.AddField(
            model_name='recoverycheckin',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recoverymilestone',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='hr.performanceimprovementplan'),
        ),
        migrations.AlterUniqueTogether(
            name='performancepriority',
            unique_together={('review', 'sequence')},
        ),
    ]
