# Generated by Django 5.2.4 on 2026-07-22 05:28

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_people_workflows"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePriorityTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(db_index=True, max_length=64)),
                ("priority_layer", models.CharField(default="role", max_length=16)),
                ("outcome_statement", models.TextField()),
                ("metric_key", models.CharField(blank=True, max_length=64, null=True)),
                ("default_weight", models.PositiveSmallIntegerField(default=20)),
                ("sequence", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "db_table": "hr_role_priority_template",
                "ordering": ["role", "sequence"],
            },
        ),
        migrations.AddField(
            model_name="performancepriority",
            name="denominator_note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="performancepriority",
            name="metric_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="performancepriority",
            name="priority_layer",
            field=models.CharField(
                choices=[
                    ("org", "Organization"),
                    ("role", "Role"),
                    ("project", "Project"),
                    ("personal", "Personal / Values"),
                ],
                default="role",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="performancepriority",
            name="target_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DevelopmentPlanItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=512)),
                ("expected_impact", models.TextField(blank=True, null=True)),
                ("progress_note", models.TextField(blank=True, null=True)),
                ("reflection", models.TextField(blank=True, null=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="development_items",
                        to="hr.performancereview",
                    ),
                ),
            ],
            options={
                "db_table": "hr_development_plan_item",
            },
        ),
        migrations.CreateModel(
            name="PerformanceCycle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fy", models.CharField(max_length=16, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("locked", "Locked"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_performance_cycle",
            },
        ),
        migrations.CreateModel(
            name="PriorityAmendment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "changed_target",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("changed_target_number", models.IntegerField(blank=True, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="hr.performancepriority",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_priority_amendment",
            },
        ),
        migrations.CreateModel(
            name="ValueCommitment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value_name", models.CharField(max_length=128)),
                ("agreed_behaviour", models.TextField(blank=True, null=True)),
                ("employee_reflection", models.TextField(blank=True, null=True)),
                ("manager_evidence", models.TextField(blank=True, null=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_commitments",
                        to="hr.performancereview",
                    ),
                ),
            ],
            options={
                "db_table": "hr_value_commitment",
            },
        ),
    ]
