# Generated by Django 5.2.4 on 2026-07-22 06:24

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0003_performance_engine"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="performancecycle",
            name="active_window",
            field=models.CharField(
                choices=[
                    ("none", "No window open"),
                    ("priority_setting", "FY priority setting"),
                    ("q1", "Q1 conversation"),
                    ("mid_year", "Mid-year review (Q2)"),
                    ("q3", "Q3 conversation"),
                    ("year_end", "End-of-year review (Q4)"),
                ],
                default="none",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="performancecycle",
            name="window_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="performancecycle",
            name="window_opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="performancepriority",
            name="agreed_action",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="performancepriority",
            name="employee_rating",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="performancepriority",
            name="functional_manager_rating",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="performancepriority",
            name="manager_rating",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name="PerformanceSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("window", models.CharField(max_length=32)),
                ("data", models.JSONField()),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
                ("signed_off_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="hr.performancereview",
                    ),
                ),
                (
                    "signed_off_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_performance_snapshot",
                "unique_together": {("review", "window")},
            },
        ),
    ]
