# Generated by Django 5.2.4 on 2026-07-22 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0004_conversation_windows"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="performancereview",
            name="functional_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="functionally_managed_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="valuecommitment",
            name="functional_manager_observation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="valuecommitment",
            name="kind",
            field=models.CharField(
                choices=[
                    ("value", "Edify Value"),
                    ("spiritual", "Spiritual Formation"),
                ],
                default="value",
                max_length=16,
            ),
        ),
    ]
