# Generated by Django 5.2.16 on 2026-07-23 03:44

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_exited_state'),
        ('hr', '0005_form_taxonomy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceimprovementplan',
            name='authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceimprovementplan',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pips_authorized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performanceimprovementplan',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pips_recommended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='stage',
            field=models.CharField(choices=[('not_started', 'Not started'), ('priorities_draft', 'Employee drafting priorities'), ('priorities_manager_review', 'Manager reviewing priorities'), ('priorities_agreed', 'Priorities agreed'), ('employee_reflection', 'Employee reflection'), ('manager_assessment', 'Manager assessment'), ('calibration', 'Calibration'), ('awaiting_acknowledgement', 'Awaiting employee acknowledgement'), ('closed', 'Closed'), ('manager_review_complete', 'Manager review complete'), ('functional_manager_complete', 'Functional manager complete'), ('hr_quality_review', 'HR quality review'), ('ready_for_slt_calibration', 'Ready for SLT calibration'), ('slt_calibrated', 'SLT calibrated'), ('final_rating_confirmed', 'Final rating confirmed'), ('employee_acknowledged', 'Employee acknowledged'), ('signed_and_archived', 'Signed and archived')], default='not_started', max_length=40),
        ),
        migrations.CreateModel(
            name='SeparationConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('country', models.CharField(db_index=True, default='Uganda', max_length=64)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('awaiting_employee_response', 'Awaiting employee response'), ('hr_review', 'HR review'), ('awaiting_leadership_approval', 'Awaiting leadership approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=40)),
                ('reason', models.TextField()),
                ('evidence', models.TextField(blank=True, null=True)),
                ('policy_basis', models.TextField(blank=True, null=True)),
                ('employee_response', models.TextField(blank=True, null=True)),
                ('employee_responded_at', models.DateTimeField(blank=True, null=True)),
                ('manager_recommendation', models.TextField(blank=True, null=True)),
                ('hr_review_note', models.TextField(blank=True, null=True)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_note', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separations_approved', to=settings.AUTH_USER_MODEL)),
                ('hr_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separations_reviewed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separations_opened', to=settings.AUTH_USER_MODEL)),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separations_recommended', to=settings.AUTH_USER_MODEL)),
                ('subject_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separation_conversations', to='accounts.staffprofile')),
            ],
            options={
                'db_table': 'hr_separation_conversation',
                'ordering': ['-created_at'],
            },
        ),
    ]
