# Generated by Django 5.2.16 on 2026-07-27 03:14

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_performanceimprovementplan_authorized_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performancepriority',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StrategicPriority',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('fy', models.CharField(db_index=True, max_length=16)),
                ('level', models.CharField(choices=[('regional', 'Regional (RVP)'), ('country', 'Country (CD)')], max_length=16)),
                ('country_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('title', models.CharField(max_length=255)),
                ('strategic_purpose', models.TextField()),
                ('expected_result', models.TextField(blank=True, null=True)),
                ('minimum_standard', models.CharField(blank=True, max_length=255, null=True)),
                ('target_guidance', models.CharField(blank=True, max_length=255, null=True)),
                ('quality_standard', models.TextField(blank=True, null=True)),
                ('evidence_source', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_notes', models.TextField(blank=True, null=True)),
                ('weight_min', models.PositiveSmallIntegerField(default=5)),
                ('weight_max', models.PositiveSmallIntegerField(default=40)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author_id', models.CharField(blank=True, max_length=30, null=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('parent', models.ForeignKey(blank=True, help_text='The regional priority this country priority translates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='hr.strategicpriority')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_strategic_priority',
                'ordering': ['level', 'sequence', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StrategicPriorityRoleRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('role', models.CharField(db_index=True, max_length=64)),
                ('accountability', models.CharField(choices=[('execute', 'Execute'), ('supervise', 'Supervise'), ('verify', 'Verify'), ('finance', 'Finance'), ('not_applicable', 'Not applicable')], default='execute', max_length=16)),
                ('metric_key', models.CharField(blank=True, max_length=64, null=True)),
                ('outcome_statement', models.TextField(help_text='Role-appropriate wording — what THIS role commits to.')),
                ('target_guidance', models.CharField(blank=True, max_length=255, null=True)),
                ('default_weight', models.PositiveSmallIntegerField(default=20)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_rules', to='hr.strategicpriority')),
            ],
            options={
                'db_table': 'hr_strategic_priority_role_rule',
                'ordering': ['priority', 'sequence', 'role'],
            },
        ),
        migrations.AddField(
            model_name='performancepriority',
            name='source_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_priorities', to='hr.strategicpriorityrolerule'),
        ),
        migrations.AddIndex(
            model_name='strategicpriority',
            index=models.Index(fields=['fy', 'level', 'status'], name='hr_strategi_fy_523549_idx'),
        ),
        migrations.AddConstraint(
            model_name='strategicpriority',
            constraint=models.CheckConstraint(condition=models.Q(('weight_max__gte', models.F('weight_min'))), name='strategic_priority_weight_range_ordered'),
        ),
        migrations.AddConstraint(
            model_name='strategicpriorityrolerule',
            constraint=models.UniqueConstraint(fields=('priority', 'role'), name='uniq_priority_role_rule'),
        ),
    ]
