# Generated by Django 5.2.16 on 2026-07-30 07:55

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_user_mfa_channel_mfachallenge"),
        ("activities", "0027_activity_closed_activity_must_have_sf_id"),
        ("activity_catalogue", "0001_initial"),
        ("hr", "0007_performancepriority_is_mandatory_strategicpriority_and_more"),
        ("projects", "0008_project_budget_ceiling_ugx_project_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MilestoneMetricDefinition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_key", models.CharField(max_length=128, unique=True)),
                ("canonical_label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("source_models", models.JSONField(blank=True, default=list)),
                ("canonical_service", models.CharField(blank=True, max_length=255)),
                ("numerator_definition", models.TextField(blank=True)),
                ("denominator_definition", models.TextField(blank=True)),
                ("included_states", models.JSONField(blank=True, default=list)),
                ("excluded_states", models.JSONField(blank=True, default=list)),
                ("date_basis", models.CharField(blank=True, max_length=64)),
                ("financial_year_basis", models.CharField(blank=True, max_length=64)),
                ("counting_basis", models.CharField(blank=True, max_length=64)),
                ("quality_gate", models.CharField(blank=True, max_length=128)),
                ("rounding_rule", models.CharField(blank=True, max_length=128)),
                ("null_behavior", models.CharField(blank=True, max_length=128)),
                ("provisional_behavior", models.CharField(blank=True, max_length=128)),
                ("verified_behavior", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "db_table": "hr_milestone_metric_definition",
            },
        ),
        migrations.AddField(
            model_name="strategicpriority",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=96, null=True),
        ),
        migrations.AddField(
            model_name="strategicpriority",
            name="source_document",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="strategicpriority",
            name="source_reference",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="strategicpriority",
            name="source_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="strategicpriority",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="MilestoneAllocation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("allocated_to_type", models.CharField(max_length=32)),
                ("country_id", models.CharField(blank=True, max_length=64, null=True)),
                ("team_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "allocated_target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "denominator",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("allocation_reason", models.TextField()),
                ("allocated_by", models.CharField(max_length=30)),
                ("approved_by", models.CharField(blank=True, max_length=30, null=True)),
                ("effective_date", models.DateField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="milestone_allocations",
                        to="accounts.staffprofile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="milestone_allocations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "hr_milestone_allocation",
            },
        ),
        migrations.CreateModel(
            name="PriorityMilestone",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=255)),
                ("source_text", models.TextField()),
                ("description", models.TextField(blank=True)),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("outcome", "Outcome"),
                            ("output", "Output"),
                            ("activity", "Activity"),
                            ("quality", "Quality"),
                            ("deadline", "Deadline"),
                            ("compliance", "Compliance"),
                            ("development", "Development"),
                            ("behaviour", "Behaviour"),
                            ("narrative", "Narrative"),
                            ("composite", "Composite"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "measurement_type",
                    models.CharField(
                        choices=[
                            ("count", "Count"),
                            ("percentage", "Percentage"),
                            ("currency", "Currency"),
                            ("date", "Date"),
                            ("boolean", "Boolean"),
                            ("ratio", "Ratio"),
                            ("score", "Score"),
                            ("composite", "Composite"),
                            ("manual_assessment", "Manual assessment"),
                        ],
                        max_length=24,
                    ),
                ),
                ("progress_source", models.CharField(max_length=64)),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("target_unit", models.CharField(blank=True, max_length=64)),
                ("target_source_text", models.CharField(blank=True, max_length=255)),
                ("denominator_definition", models.TextField(blank=True)),
                ("quality_gate", models.CharField(blank=True, max_length=128)),
                ("role_applicability", models.JSONField(blank=True, default=list)),
                ("country_applicability", models.JSONField(blank=True, default=list)),
                ("project_applicability", models.JSONField(blank=True, default=list)),
                (
                    "activity_catalogue_rules",
                    models.JSONField(blank=True, default=list),
                ),
                ("requires_definition", models.BooleanField(default=False)),
                (
                    "definition_status",
                    models.CharField(
                        choices=[
                            ("needs_definition", "Needs Definition"),
                            ("draft", "Draft"),
                            ("defined", "Defined"),
                            ("approved", "Approved"),
                        ],
                        default="needs_definition",
                        max_length=24,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("source_order", models.PositiveIntegerField(default=1)),
                (
                    "metric_definition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="milestones",
                        to="hr.milestonemetricdefinition",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="hr.strategicpriority",
                    ),
                ),
            ],
            options={
                "db_table": "hr_priority_milestone",
                "ordering": ["priority", "source_order"],
            },
        ),
        migrations.CreateModel(
            name="MilestonePeriodTarget",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scope", models.CharField(max_length=32)),
                ("country_id", models.CharField(blank=True, max_length=64, null=True)),
                ("team_id", models.CharField(blank=True, max_length=64, null=True)),
                ("period_type", models.CharField(max_length=16)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("planned_value", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "actual_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("actual_source", models.CharField(blank=True, max_length=128)),
                (
                    "achievement_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("status", models.CharField(default="not_started", max_length=24)),
                ("snapshot_at", models.DateTimeField(blank=True, null=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="period_targets",
                        to="hr.milestoneallocation",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="milestone_period_targets",
                        to="accounts.staffprofile",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="period_targets",
                        to="hr.prioritymilestone",
                    ),
                ),
            ],
            options={
                "db_table": "hr_milestone_period_target",
            },
        ),
        migrations.AddField(
            model_name="milestoneallocation",
            name="milestone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="hr.prioritymilestone",
            ),
        ),
        migrations.CreateModel(
            name="MilestoneActivityRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("counting_basis", models.CharField(max_length=64)),
                (
                    "required_delivery_method",
                    models.CharField(blank=True, max_length=32),
                ),
                ("required_executor_type", models.CharField(blank=True, max_length=16)),
                ("school_type", models.CharField(blank=True, max_length=32)),
                ("school_level", models.CharField(blank=True, max_length=64)),
                ("target_intervention", models.CharField(blank=True, max_length=64)),
                (
                    "minimum_completion_state",
                    models.CharField(default="ia_verified", max_length=32),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "catalogue_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="milestone_rules",
                        to="activity_catalogue.activitycatalogueitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.project",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_rules",
                        to="hr.prioritymilestone",
                    ),
                ),
            ],
            options={
                "db_table": "hr_milestone_activity_rule",
            },
        ),
        migrations.CreateModel(
            name="StrategicPriorityCycle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial_year", models.CharField(max_length=16, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("scope_type", models.CharField(default="regional", max_length=32)),
                ("region_id", models.CharField(blank=True, max_length=64, null=True)),
                ("country_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("rvp_review", "RVP Review"),
                            ("approved", "Approved"),
                            ("allocated", "Allocated"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_by", models.CharField(blank=True, max_length=30, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_strategic_priority_cycle",
            },
        ),
        migrations.AddField(
            model_name="performancecycle",
            name="strategic_priority_cycle",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="performance_cycle",
                to="hr.strategicprioritycycle",
            ),
        ),
        migrations.AddField(
            model_name="strategicpriority",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="priorities",
                to="hr.strategicprioritycycle",
            ),
        ),
        migrations.CreateModel(
            name="MilestoneProgressCredit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "credited_value",
                    models.DecimalField(decimal_places=2, default=1, max_digits=18),
                ),
                ("source_snapshot", models.JSONField(default=dict)),
                ("credited_at", models.DateTimeField()),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="milestone_credits",
                        to="activities.activity",
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progress_credits",
                        to="hr.milestoneallocation",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits",
                        to="hr.milestoneactivityrule",
                    ),
                ),
            ],
            options={
                "db_table": "hr_milestone_progress_credit",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rule", "activity"),
                        name="uniq_milestone_activity_credit",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="prioritymilestone",
            constraint=models.UniqueConstraint(
                fields=("priority", "code"), name="uniq_priority_milestone_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="prioritymilestone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("active", True), _negated=True),
                    models.Q(
                        ("definition_status", "approved"),
                        ("metric_definition__isnull", False),
                        ("requires_definition", False),
                    ),
                    _connector="OR",
                ),
                name="active_milestone_must_be_defined",
            ),
        ),
        migrations.AddConstraint(
            model_name="milestoneperiodtarget",
            constraint=models.UniqueConstraint(
                fields=("milestone", "allocation", "period_type", "period_start"),
                name="uniq_milestone_period_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="milestoneactivityrule",
            constraint=models.UniqueConstraint(
                fields=("milestone", "catalogue_item", "project"),
                name="uniq_milestone_catalogue_project_rule",
            ),
        ),
    ]
