# Generated by Django 5.2.16 on 2026-08-15 14:51

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0040_alter_activity_est_cost_cents"),
        ("hr", "0011_milestoneallocation_client_target_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriorityImportBatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fy", models.CharField(db_index=True, max_length=16)),
                (
                    "country_id",
                    models.CharField(db_index=True, default="Uganda", max_length=64),
                ),
                ("original_file_name", models.CharField(max_length=255)),
                ("file_sha256", models.CharField(max_length=64)),
                ("uploaded_by", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("validated", "Validated"),
                            ("needs_correction", "Needs correction"),
                            ("committed", "Committed"),
                            ("rejected", "Rejected"),
                        ],
                        default="validated",
                        max_length=24,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("invalid_rows", models.PositiveIntegerField(default=0)),
                ("duplicate_rows", models.PositiveIntegerField(default=0)),
                ("validation_summary", models.JSONField(blank=True, default=dict)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "committed_by",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
            options={
                "db_table": "hr_priority_import_batch",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fy", "country_id", "file_sha256"),
                        name="uniq_priority_import_file_per_scope",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityPriorityLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "planned_contribution",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("linked_by", models.CharField(max_length=30)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priority_links",
                        to="activities.activity",
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_links",
                        to="hr.milestoneallocation",
                    ),
                ),
            ],
            options={
                "db_table": "hr_activity_priority_link",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("activity", "allocation"),
                        name="uniq_activity_priority_allocation",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("activity",),
                        name="uniq_primary_priority_per_activity",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriorityImportRow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("group_code", models.CharField(max_length=96)),
                ("group_title", models.CharField(max_length=255)),
                ("priority_code", models.CharField(max_length=96)),
                ("priority_title", models.CharField(max_length=255)),
                ("milestone_code", models.CharField(max_length=128)),
                ("milestone_title", models.CharField(max_length=255)),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("target_unit", models.CharField(blank=True, max_length=64)),
                (
                    "core_target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "client_target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("measurement_type", models.CharField(blank=True, max_length=24)),
                ("metric_key", models.CharField(blank=True, max_length=128)),
                ("allocation_method", models.CharField(blank=True, max_length=24)),
                ("responsible_role", models.CharField(blank=True, max_length=64)),
                ("needs_confirmation", models.BooleanField(default=False)),
                ("confirmation_note", models.TextField(blank=True)),
                ("quality_gate", models.CharField(blank=True, max_length=128)),
                ("counting_basis", models.CharField(blank=True, max_length=64)),
                ("activity_codes", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("review", "Review required"),
                            ("blocked", "Blocked"),
                            ("imported", "Imported"),
                        ],
                        default="ready",
                        max_length=16,
                    ),
                ),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="hr.priorityimportbatch",
                    ),
                ),
                (
                    "imported_milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_rows",
                        to="hr.prioritymilestone",
                    ),
                ),
            ],
            options={
                "db_table": "hr_priority_import_row",
                "ordering": ["row_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "row_number"), name="uniq_priority_import_row"
                    )
                ],
            },
        ),
    ]
