# Generated by Django 5.2.16 on 2026-08-20 14:20

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_alter_assignmentaudit_assigner_role_and_more"),
        ("hr", "0012_priorityimportbatch_activityprioritylink_and_more"),
        ("projects", "0010_project_staff_priority_upgrade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MilestoneTargetComponent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=160)),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "target_unit",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("needs_confirmation", models.BooleanField(default=False)),
                ("confirmation_note", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "hr_milestone_target_component",
                "ordering": ("sequence",),
            },
        ),
        migrations.AddField(
            model_name="milestoneallocation",
            name="component_split",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="milestoneprogresscredit",
            name="reversed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="milestoneprogresscredit",
            name="reversed_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="prioritymilestone",
            name="recurrence_per_month",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="milestoneallocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("employee__isnull", False), ("status__in", ("draft", "approved"))
                ),
                fields=("milestone", "employee"),
                name="uniq_live_allocation_per_employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="milestoneallocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("draft", "approved")), ("team_id__isnull", False)
                ),
                fields=("milestone", "team_id"),
                name="uniq_live_allocation_per_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="milestoneallocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("project__isnull", False), ("status__in", ("draft", "approved"))
                ),
                fields=("milestone", "project"),
                name="uniq_live_allocation_per_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="strategicpriority",
            constraint=models.UniqueConstraint(
                fields=("fy", "level", "country_id", "code"),
                name="uniq_strategic_priority_per_scope",
                nulls_distinct=False,
            ),
        ),
        migrations.AddField(
            model_name="milestonetargetcomponent",
            name="milestone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="hr.prioritymilestone",
            ),
        ),
        migrations.AddConstraint(
            model_name="milestonetargetcomponent",
            constraint=models.UniqueConstraint(
                fields=("milestone", "code"), name="uniq_component_per_milestone"
            ),
        ),
    ]
