# Generated by Django 5.2.16 on 2026-08-20 16:09

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0013_priorities_audit_hardening"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraWorkScoringPolicy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fy", models.CharField(max_length=16, unique=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("additive", "Additive"), ("bonus", "Bonus")],
                        default="bonus",
                        max_length=16,
                    ),
                ),
                (
                    "max_contribution_points",
                    models.DecimalField(decimal_places=2, default=10, max_digits=6),
                ),
                (
                    "complexity_weights",
                    models.JSONField(
                        default=dict,
                        help_text='Points per verified task by complexity, e.g. {"low": 1, "medium": 2, "high": 4}.',
                    ),
                ),
                (
                    "overdue_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.5"), max_digits=4
                    ),
                ),
                ("can_offset_mandatory", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "hr_extra_work_scoring_policy",
            },
        ),
        migrations.CreateModel(
            name="ExtraAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fy", models.CharField(max_length=16)),
                ("title", models.CharField(max_length=200)),
                ("instruction", models.TextField()),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("priority_linked", "Priority-linked additional work"),
                            ("operational_support", "Operational support"),
                            ("strategic", "Strategic assignment"),
                            ("emergency", "Emergency assignment"),
                            ("cross_team", "Cross-team support"),
                            ("special_project", "Special project"),
                            ("leadership", "Leadership responsibility"),
                            ("non_scoreable_support", "Non-scoreable support task"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "linked_activity_id",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("assigner_id", models.CharField(db_index=True, max_length=30)),
                ("assigner_role", models.CharField(max_length=48)),
                ("assignee_id", models.CharField(db_index=True, max_length=30)),
                ("assignee_role", models.CharField(max_length=48)),
                (
                    "supervising_pl_id",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("country", models.CharField(default="Uganda", max_length=64)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField()),
                (
                    "expected_output",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "output_unit",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("evidence_required", models.BooleanField(default=True)),
                ("reviewer_id", models.CharField(db_index=True, max_length=30)),
                (
                    "complexity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=12,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("assigned", "Assigned"),
                            ("acknowledged", "Acknowledged"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("returned", "Returned for Correction"),
                            ("verified", "Completed & Verified"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="assigned",
                        max_length=16,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.TextField(blank=True, default="")),
                ("evidence_note", models.TextField(blank=True, default="")),
                (
                    "evidence_uri",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("return_reason", models.TextField(blank=True, default="")),
                ("return_count", models.PositiveIntegerField(default=0)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verified_by",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, default="")),
                (
                    "contribution_points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "linked_milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extra_assignments",
                        to="hr.prioritymilestone",
                    ),
                ),
                (
                    "linked_priority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extra_assignments",
                        to="hr.strategicpriority",
                    ),
                ),
                (
                    "scoring_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="hr.extraworkscoringpolicy",
                    ),
                ),
            ],
            options={
                "db_table": "hr_extra_assignment",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["assignee_id", "status"],
                        name="hr_extra_as_assigne_5129b8_idx",
                    ),
                    models.Index(
                        fields=["assigner_id", "status"],
                        name="hr_extra_as_assigne_ebd41b_idx",
                    ),
                    models.Index(
                        fields=["fy", "status"], name="hr_extra_as_fy_a6978c_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("assignee_id", models.F("assigner_id")), _negated=True
                        ),
                        name="extra_work_no_self_assignment",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reviewer_id", models.F("assignee_id")), _negated=True
                        ),
                        name="extra_work_no_self_review",
                    ),
                ],
            },
        ),
    ]
