# Generated by Django 5.2.17 on 2026-08-20 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0014_extra_assigned_work"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="strategicpriority",
            name="uniq_strategic_priority_per_scope",
        ),
        migrations.AddConstraint(
            model_name="strategicpriority",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("code", None), _negated=True),
                    models.Q(("code", ""), _negated=True),
                ),
                fields=("fy", "level", "country_id", "code"),
                name="uniq_strategic_priority_per_scope",
                nulls_distinct=False,
            ),
        ),
    ]
