# Generated by Django 5.2.17 on 2026-08-20 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0015_strategic_priority_code_scoped_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="performancecycle",
            name="reopened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="performancecycle",
            name="reopened_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reopened_performance_cycles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="performancecycle",
            name="reopening_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="performancecycle",
            name="window_closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
