# Generated by Django 5.2.17 on 2026-09-12 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_user_roles_regional_programme_lead'),
        ('hr', '0016_performance_cycle_close_reopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerelationscase',
            name='complainant_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations_cases_raised_by_them', to='accounts.staffprofile'),
        ),
        migrations.AddField(
            model_name='employeerelationscase',
            name='hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerelationscase',
            name='sanction',
            field=models.CharField(blank=True, choices=[('no_action', 'No further action'), ('counselling', 'Counselling'), ('verbal_warning', 'Verbal warning'), ('written_warning', 'Written warning'), ('final_warning', 'Final written warning'), ('suspension', 'Suspension'), ('dismissal', 'Dismissal')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='employeerelationscase',
            name='case_type',
            field=models.CharField(choices=[('disciplinary', 'Disciplinary matter'), ('grievance', 'Grievance'), ('dispute', 'Dispute between staff'), ('conflict', 'Conflict'), ('harassment', 'Harassment concern'), ('conduct', 'Conduct concern'), ('whistleblowing', 'Whistleblowing'), ('safeguarding', 'Safeguarding referral')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='employeerelationscase',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=32),
        ),
    ]
