# Generated by Django 5.2.17 on 2026-09-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0019_rewards_safety_recognition_pulse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeecompliancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("Compliant", "Compliant"),
                    ("Due Soon", "Due soon"),
                    ("Expired", "Expired"),
                    ("Missing", "Missing"),
                ],
                default="Missing",
                max_length=32,
            ),
        ),
    ]
