# Generated by Django 5.2.17 on 2026-09-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0020_compliance_status_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prioritymilestone",
            name="source_order",
            field=models.PositiveIntegerField(default=None),
        ),
    ]
