# Generated by Django 5.2.17 on 2026-10-07 09:22

import apps.acting.models
import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0038_user_acting_until"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActingAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role_key",
                    models.CharField(
                        choices=[
                            ("acting_pl", "Acting Program Lead"),
                            ("acting_cd", "Acting Country Director"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "acting_role",
                    models.CharField(
                        choices=[
                            ("CCEO", "CCEO"),
                            ("Program Lead", "Program Lead"),
                            ("CountryDirector", "CountryDirector"),
                            ("RegionalVicePresident", "RegionalVicePresident"),
                            ("RegionalProgramLead", "RegionalProgramLead"),
                            ("ImpactAssessment", "ImpactAssessment"),
                            ("Accountant", "Accountant"),
                            ("HumanResources", "HumanResources"),
                            ("ProjectCoordinator", "ProjectCoordinator"),
                            ("PartnerAdmin", "PartnerAdmin"),
                            ("PartnerFieldOfficer", "PartnerFieldOfficer"),
                            (
                                "BusinessTransformationOfficer",
                                "BusinessTransformationOfficer",
                            ),
                            ("MfiPartnerAdmin", "MfiPartnerAdmin"),
                            ("MfiLoanOfficer", "MfiLoanOfficer"),
                            ("Admin", "Admin"),
                        ],
                        max_length=64,
                    ),
                ),
                ("appointee_role", models.CharField(max_length=64)),
                ("appointed_by_role", models.CharField(max_length=64)),
                ("scope_type", models.CharField(max_length=32)),
                ("country", models.CharField(blank=True, default="", max_length=64)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancel_reason",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("reminded_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("in_capacity", models.BooleanField(default=True)),
                ("grant_snapshot", models.JSONField(blank=True, default=dict)),
                ("revisions", models.JSONField(blank=True, default=list)),
                (
                    "appointed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acting_appointments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "appointee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acting_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acting_assignments",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "acting_assignment",
                "ordering": ["-start_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["country", "start_date"],
                        name="acting_country_month_idx",
                    ),
                    models.Index(fields=["end_date"], name="acting_end_date_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="acting_window_ordered",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("start_date__day", 1)),
                        name="acting_window_starts_on_first",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "end_date",
                                apps.acting.models.LastDayOfMonth(
                                    models.F("start_date")
                                ),
                            )
                        ),
                        name="acting_window_is_one_month",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("appointee", models.F("appointed_by")), _negated=True
                        ),
                        name="acting_never_self_appointed",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("cancelled_at__isnull", True)),
                        fields=("seat", "role_key", "start_date"),
                        name="uniq_standing_acting_per_seat_month",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("cancelled_at__isnull", True)),
                        fields=("appointee", "start_date"),
                        name="uniq_standing_acting_per_person_month",
                    ),
                ],
            },
        ),
    ]
