# Generated by Django 5.2.17 on 2026-09-13 17:38

import apps.core.cuid
import apps.core.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activities", "0054_verification_sample_subjects"),
        (
            "business_transformation",
            "0020_remove_loanapplication_bt_loan_application_term_positive_and_more",
        ),
        ("projects", "0012_projectschoolassignment_mapping"),
        ("schools", "0021_school_uniq_school_salesforce_account_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpactFinding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_id", models.CharField(db_index=True, max_length=30)),
                (
                    "author_role",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_basis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("peer_ia", "Reviewed by a second IA officer"),
                            ("cd_fallback", "Acknowledged by the Country Director"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "programme",
                    models.CharField(
                        choices=[
                            ("training", "Christian training"),
                            ("lending", "Lending"),
                            ("edtech", "Educational technology"),
                            ("visits", "School visits"),
                            ("cross", "Across programmes"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "intervention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("christlike_behaviour", "Christlike Behaviour"),
                            ("exposure_to_word_of_god", "Exposure to the Word of God"),
                            ("financial_health", "Financial Health"),
                            ("leadership", "Leadership"),
                            ("government_requirement", "Government Requirements"),
                            ("learning_environment", "Learning Environment"),
                            ("teaching_environment", "Teacher's Environment"),
                            ("enrolment", "Enrolment"),
                        ],
                        default="",
                        max_length=64,
                    ),
                ),
                ("cohort_filters", models.JSONField(blank=True, default=dict)),
                ("metric_snapshot", models.JSONField(blank=True, default=dict)),
                ("statement", models.TextField()),
                ("contrary_evidence", models.TextField(blank=True, default="")),
                ("limitations", models.TextField(blank=True, default="")),
                ("recommendation", models.TextField(blank=True, default="")),
                (
                    "action_owner_role",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("follow_up_due", models.DateField(blank=True, null=True)),
                ("evidence_refs", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In review"),
                            ("returned", "Returned"),
                            ("approved", "Approved"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "impact_finding",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EdTechDeployment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual_upload", "Manual Upload"),
                            ("admin_created", "Admin Created"),
                            ("api_import", "API Import"),
                            ("local_test_upload", "Local Test Upload"),
                            ("production_upload", "Production Upload"),
                        ],
                        db_index=True,
                        default="manual_upload",
                        max_length=32,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                        ],
                        db_index=True,
                        default="production",
                        max_length=16,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("fy", models.CharField(db_index=True, max_length=16)),
                (
                    "evidence_reference",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("recorded_by_user_id", models.CharField(db_index=True, max_length=30)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending verification"),
                            ("confirmed", "Confirmed"),
                            ("returned", "Returned"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "verified_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("return_reason", models.TextField(blank=True, default="")),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablets"),
                            ("laptop", "Laptops"),
                            ("desktop", "Desktop computers"),
                            ("projector", "Projectors"),
                            ("digital_library", "Digital library / server"),
                            ("connectivity", "Connectivity"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("deployed_on", models.DateField()),
                (
                    "funding",
                    models.CharField(
                        choices=[
                            ("project", "Special project"),
                            ("loan", "School loan"),
                            ("grant", "Grant or donation"),
                            ("school", "School's own funds"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "teachers_trained",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "learners_with_access",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="business_transformation.mfiloan",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="schools.school",
                    ),
                ),
                (
                    "source_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "impact_edtech_deployment",
                "ordering": ["-deployed_on", "school_id"],
            },
        ),
        migrations.CreateModel(
            name="EdTechCheck",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual_upload", "Manual Upload"),
                            ("admin_created", "Admin Created"),
                            ("api_import", "API Import"),
                            ("local_test_upload", "Local Test Upload"),
                            ("production_upload", "Production Upload"),
                        ],
                        db_index=True,
                        default="manual_upload",
                        max_length=32,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                        ],
                        db_index=True,
                        default="production",
                        max_length=16,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("fy", models.CharField(db_index=True, max_length=16)),
                (
                    "evidence_reference",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("recorded_by_user_id", models.CharField(db_index=True, max_length=30)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending verification"),
                            ("confirmed", "Confirmed"),
                            ("returned", "Returned"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "verified_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("return_reason", models.TextField(blank=True, default="")),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checked_on", models.DateField()),
                ("units_functional", models.PositiveIntegerField()),
                ("teachers_using", models.PositiveIntegerField(blank=True, null=True)),
                ("learners_using", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "weekly_use_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("issues", models.TextField(blank=True, default="")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="schools.school",
                    ),
                ),
                (
                    "source_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="activities.activity",
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="impact.edtechdeployment",
                    ),
                ),
            ],
            options={
                "db_table": "impact_edtech_check",
                "ordering": ["-checked_on"],
            },
        ),
        migrations.CreateModel(
            name="ImpactReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_id", models.CharField(db_index=True, max_length=30)),
                (
                    "author_role",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_basis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("peer_ia", "Reviewed by a second IA officer"),
                            ("cd_fallback", "Acknowledged by the Country Director"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country", models.CharField(db_index=True, max_length=64)),
                ("fy", models.CharField(blank=True, default="", max_length=16)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "programme_areas",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("training", "Christian training"),
                                ("lending", "Lending"),
                                ("edtech", "Educational technology"),
                                ("visits", "School visits"),
                                ("cross", "Across programmes"),
                            ],
                            max_length=16,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted for review"),
                            ("returned", "Returned"),
                            ("reviewed", "Reviewed"),
                            ("released", "Released"),
                            ("withdrawn", "Withdrawn"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("methodology", models.TextField(blank=True, default="")),
                ("findings", models.TextField(blank=True, default="")),
                ("limitations", models.TextField(blank=True, default="")),
                ("evidence_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "snapshot_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="impact.impactreport",
                    ),
                ),
            ],
            options={
                "db_table": "impact_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImpactReportRecommendation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("owner_role", models.CharField(blank=True, default="", max_length=32)),
                (
                    "owner_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("deferred", "Deferred"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("response", models.TextField(blank=True, default="")),
                (
                    "responded_by_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "team_action_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="impact.impactreport",
                    ),
                ),
            ],
            options={
                "db_table": "impact_report_recommendation",
                "ordering": ["due_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImpactReportRelease",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("leadership", "Country leadership"),
                            ("school", "Partner school"),
                            ("donor", "Donors"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "redaction_profile",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("rendered_payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Awaiting approval"),
                            ("approved", "Approved"),
                            ("released", "Released"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending_approval",
                        max_length=20,
                    ),
                ),
                (
                    "requested_by_id",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "approved_by_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "released_by_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_reason", models.TextField(blank=True, default="")),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="impact.impactreport",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "impact_report_release",
                "ordering": ["audience", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningAssessmentResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual_upload", "Manual Upload"),
                            ("admin_created", "Admin Created"),
                            ("api_import", "API Import"),
                            ("local_test_upload", "Local Test Upload"),
                            ("production_upload", "Production Upload"),
                        ],
                        db_index=True,
                        default="manual_upload",
                        max_length=32,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                        ],
                        db_index=True,
                        default="production",
                        max_length=16,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("fy", models.CharField(db_index=True, max_length=16)),
                (
                    "evidence_reference",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("recorded_by_user_id", models.CharField(db_index=True, max_length=30)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending verification"),
                            ("confirmed", "Confirmed"),
                            ("returned", "Returned"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "verified_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("return_reason", models.TextField(blank=True, default="")),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("onetest", "OneTest"),
                            ("national_exam", "National examination"),
                            ("internal", "School internal assessment"),
                        ],
                        max_length=24,
                    ),
                ),
                ("assessed_on", models.DateField()),
                ("grade_level", models.CharField(max_length=32)),
                ("subject", models.CharField(max_length=64)),
                ("learners_tested", models.PositiveIntegerField()),
                (
                    "mean_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "learners_proficient",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="schools.school",
                    ),
                ),
                (
                    "source_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "impact_learning_result",
                "ordering": ["-assessed_on", "school_id"],
            },
        ),
        migrations.CreateModel(
            name="OutcomeArea",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_id", models.CharField(db_index=True, max_length=30)),
                (
                    "author_role",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_basis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("peer_ia", "Reviewed by a second IA officer"),
                            ("cd_fallback", "Acknowledged by the Country Director"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=120)),
                ("definition", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In review"),
                            ("returned", "Returned"),
                            ("approved", "Approved"),
                            ("superseded", "Superseded"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("change_reason", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "impact_outcome_area",
                "ordering": ["name", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "version"), name="uniq_outcome_area_version"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IndicatorDefinition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_id", models.CharField(db_index=True, max_length=30)),
                (
                    "author_role",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_basis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("peer_ia", "Reviewed by a second IA officer"),
                            ("cd_fallback", "Acknowledged by the Country Director"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=80)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=160)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("output", "Output"),
                            ("intermediate", "Intermediate outcome"),
                            ("outcome", "Outcome"),
                        ],
                        max_length=16,
                    ),
                ),
                ("unit", models.CharField(max_length=48)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ssa", "School Self-Assessment"),
                            ("learning_results", "Student learning results"),
                            ("discipleship", "Discipleship indicators"),
                            ("edtech", "EdTech deployments and checks"),
                            ("lending", "Lending impact evidence"),
                            ("activity", "Verified activity records"),
                            ("stories", "Most Significant Change stories"),
                        ],
                        max_length=24,
                    ),
                ),
                ("calculation", models.TextField()),
                ("population", models.TextField(blank=True, default="")),
                ("denominator", models.TextField(blank=True, default="")),
                ("baseline_rule", models.TextField(blank=True, default="")),
                ("frequency", models.CharField(blank=True, default="", max_length=64)),
                ("disaggregation", models.TextField(blank=True, default="")),
                ("limitations", models.TextField(blank=True, default="")),
                (
                    "data_owner_role",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("country", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In review"),
                            ("returned", "Returned"),
                            ("approved", "Approved"),
                            ("superseded", "Superseded"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("change_reason", models.TextField(blank=True, default="")),
                (
                    "outcome_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indicators",
                        to="impact.outcomearea",
                    ),
                ),
            ],
            options={
                "db_table": "impact_indicator_definition",
                "ordering": ["key", "-version"],
            },
        ),
        migrations.CreateModel(
            name="OutcomeAreaDomain",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "intervention",
                    models.CharField(
                        choices=[
                            ("christlike_behaviour", "Christlike Behaviour"),
                            ("exposure_to_word_of_god", "Exposure to the Word of God"),
                            ("financial_health", "Financial Health"),
                            ("leadership", "Leadership"),
                            ("government_requirement", "Government Requirements"),
                            ("learning_environment", "Learning Environment"),
                            ("teaching_environment", "Teacher's Environment"),
                            ("enrolment", "Enrolment"),
                        ],
                        max_length=64,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="impact.outcomearea",
                    ),
                ),
            ],
            options={
                "db_table": "impact_outcome_area_domain",
            },
        ),
        migrations.CreateModel(
            name="DiscipleshipIndicatorRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual_upload", "Manual Upload"),
                            ("admin_created", "Admin Created"),
                            ("api_import", "API Import"),
                            ("local_test_upload", "Local Test Upload"),
                            ("production_upload", "Production Upload"),
                        ],
                        db_index=True,
                        default="manual_upload",
                        max_length=32,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                        ],
                        db_index=True,
                        default="production",
                        max_length=16,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("fy", models.CharField(db_index=True, max_length=16)),
                (
                    "evidence_reference",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("recorded_by_user_id", models.CharField(db_index=True, max_length=30)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending verification"),
                            ("confirmed", "Confirmed"),
                            ("returned", "Returned"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "verified_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("return_reason", models.TextField(blank=True, default="")),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("observed_on", models.DateField()),
                (
                    "devotions_per_week",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "discipleship_groups_active",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "learners_in_groups",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "learners_enrolled",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "staff_in_devotions_pct",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("spiritual_lead_in_post", models.BooleanField(blank=True, null=True)),
                (
                    "bible_lessons_timetabled",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="schools.school",
                    ),
                ),
                (
                    "source_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "impact_discipleship_record",
                "ordering": ["-observed_on", "school_id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("staff_in_devotions_pct__isnull", True),
                            ("staff_in_devotions_pct__lte", 100),
                            _connector="OR",
                        ),
                        name="discipleship_staff_pct_within_100",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="impactreport",
            index=models.Index(
                fields=["country", "status"], name="idx_impact_report_country"
            ),
        ),
        migrations.AddConstraint(
            model_name="impactreportrelease",
            constraint=models.UniqueConstraint(
                fields=("report", "audience", "school"),
                name="uniq_impact_release_audience_school",
                nulls_distinct=False,
            ),
        ),
        migrations.AddIndex(
            model_name="learningassessmentresult",
            index=models.Index(
                fields=["school", "subject", "grade_level", "assessed_on"],
                name="idx_learning_result_school",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningassessmentresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("learners_proficient__isnull", True),
                    ("learners_proficient__lte", models.F("learners_tested")),
                    _connector="OR",
                ),
                name="learning_result_proficient_within_tested",
            ),
        ),
        migrations.AddConstraint(
            model_name="indicatordefinition",
            constraint=models.UniqueConstraint(
                fields=("key", "version"), name="uniq_indicator_key_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="outcomeareadomain",
            constraint=models.UniqueConstraint(
                fields=("area", "intervention"), name="uniq_outcome_area_domain"
            ),
        ),
    ]
