# Generated by Django 5.2.16 on 2026-07-30 07:50

import apps.core.cuid
import apps.core.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0008_project_budget_ceiling_ugx_project_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityCatalogueItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stable_code", models.CharField(max_length=96, unique=True)),
                ("source_name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("school_visit", "School Visit"),
                            ("youth_camp", "Youth Camp"),
                            ("admin", "Admin"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("in_school_training", "In-school Training"),
                            ("cluster_meeting", "Cluster Meeting"),
                            ("cluster_training", "Cluster Training"),
                            ("online", "Online"),
                            ("school_visit", "School Visit"),
                            ("group", "Group"),
                            ("admin", "Admin"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "workflow_kind",
                    models.CharField(
                        choices=[
                            ("school_visit", "School Visit"),
                            ("follow_up_visit", "Follow-up Visit"),
                            ("coaching_visit", "Coaching Visit"),
                            ("in_school_support", "In-school Support"),
                            ("donor_visit", "Donor Visit"),
                            ("story_gathering_visit", "Gathering Story"),
                            ("school_invitation", "School Invitation"),
                            ("social_visit", "Social Visit"),
                            ("training_follow_up_visit", "Training Follow-up Visit"),
                            ("in_school_coaching_visit", "In-school Coaching Visit"),
                            ("training", "Training"),
                            ("in_school_training", "In-school Training"),
                            (
                                "school_improvement_training",
                                "School Improvement Training",
                            ),
                            ("cluster_meeting", "Cluster Meeting"),
                            ("cluster_training", "Cluster Training"),
                            ("ssa_activity", "SSA Activity"),
                            ("project_activity", "Project Activity"),
                            ("partner_activity", "Partner Activity"),
                            ("core_visit", "Core Visit"),
                            ("core_training", "Core Training"),
                            ("baseline_ssa_visit", "SSA Visit"),
                            (
                                "school_visit_ssa_collection",
                                "School Visit + SSA Collection",
                            ),
                            (
                                "cluster_training_ssa_collection",
                                "Cluster Training + SSA Collection",
                            ),
                            (
                                "cluster_meeting_ssa_review",
                                "Cluster Meeting + SSA Review",
                            ),
                            ("partner_ssa_collection", "Partner SSA Collection"),
                            ("core_assessment_visit", "Core Assessment Visit"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(default="School staff", max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("staff_delivery_allowed", models.BooleanField(default=True)),
                ("partner_delivery_allowed", models.BooleanField(default=True)),
                ("individual_school_allowed", models.BooleanField(default=True)),
                ("cluster_delivery_allowed", models.BooleanField(default=False)),
                ("project_delivery_allowed", models.BooleanField(default=True)),
                ("requires_school", models.BooleanField(default=True)),
                ("requires_cluster", models.BooleanField(default=False)),
                ("requires_project", models.BooleanField(default=False)),
                ("requires_current_ssa", models.BooleanField(default=True)),
                ("requires_source_activity", models.BooleanField(default=False)),
                ("new_school_only", models.BooleanField(default=False)),
                ("counts_toward_client_visit", models.BooleanField(default=False)),
                ("counts_toward_client_training", models.BooleanField(default=False)),
                (
                    "core_slot_type",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("salesforce_record_type", models.CharField(max_length=32)),
                (
                    "salesforce_expected_prefix",
                    models.CharField(blank=True, max_length=16),
                ),
                ("evidence_profile", models.CharField(max_length=64)),
                ("costing_profile", models.CharField(max_length=64)),
                ("support_objective", models.CharField(blank=True, max_length=64)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("override_reason_required", models.BooleanField(default=True)),
                ("created_by", models.CharField(blank=True, max_length=30, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "activity_catalogue_item",
                "ordering": ["display_name", "stable_code"],
                "indexes": [
                    models.Index(
                        fields=["status", "effective_from", "effective_to"],
                        name="activity_ca_status_a31f58_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "delivery_method"],
                        name="activity_ca_activit_3f9cca_idx",
                    ),
                    models.Index(
                        fields=["workflow_kind"], name="activity_ca_workflo_a676ff_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_from__isnull", True),
                            ("effective_to__gte", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="activity_catalogue_effective_range_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "active"), _negated=True),
                            models.Q(
                                models.Q(("evidence_profile", ""), _negated=True),
                                models.Q(("salesforce_record_type", ""), _negated=True),
                                models.Q(("costing_profile", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="active_catalogue_profiles_required",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityCatalogueAlias",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("normalized_alias", models.CharField(max_length=255, unique=True)),
                ("source_alias", models.CharField(max_length=255)),
                (
                    "catalogue_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aliases",
                        to="activity_catalogue.activitycatalogueitem",
                    ),
                ),
            ],
            options={
                "db_table": "activity_catalogue_alias",
            },
        ),
        migrations.CreateModel(
            name="ActivityCatalogueReviewQueue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("review_kind", models.CharField(max_length=64)),
                ("source_model", models.CharField(max_length=128)),
                ("source_record_id", models.CharField(max_length=64)),
                ("source_value", models.TextField()),
                (
                    "candidate_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=96),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("status", models.CharField(default="needs_review", max_length=24)),
                ("resolution_note", models.TextField(blank=True)),
                ("resolved_by", models.CharField(blank=True, max_length=30, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "activity_catalogue_review_queue",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("review_kind", "source_model", "source_record_id"),
                        name="uniq_catalogue_review_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityEligibilityRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "eligible_school_levels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "eligible_school_categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "eligible_support_tiers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "allowed_target_audiences",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("core_school_only", models.BooleanField(default=False)),
                ("client_school_only", models.BooleanField(default=False)),
                ("requires_project_membership", models.BooleanField(default=False)),
                ("requires_cluster_membership", models.BooleanField(default=False)),
                (
                    "maximum_frequency_per_fy",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("cooldown_days", models.PositiveIntegerField(blank=True, null=True)),
                ("counts_toward_entitlement", models.BooleanField(default=False)),
                (
                    "catalogue_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_rule",
                        to="activity_catalogue.activitycatalogueitem",
                    ),
                ),
            ],
            options={
                "db_table": "activity_eligibility_rule",
            },
        ),
        migrations.CreateModel(
            name="ActivityCatalogueVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                ("change_reason", models.TextField()),
                ("created_by", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "catalogue_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="activity_catalogue.activitycatalogueitem",
                    ),
                ),
            ],
            options={
                "db_table": "activity_catalogue_version",
                "ordering": ["catalogue_item", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("catalogue_item", "version"),
                        name="uniq_activity_catalogue_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityInterventionMapping",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "intervention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("christlike_behaviour", "Christlike Behaviour"),
                            ("exposure_to_word_of_god", "Exposure to the Word of God"),
                            ("financial_health", "Financial Health"),
                            ("leadership", "Leadership"),
                            ("government_requirement", "Government Requirements"),
                            ("learning_environment", "Learning Environment"),
                            ("teaching_environment", "Teacher's Environment"),
                            ("enrolment", "Enrolment"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "mapping_mode",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("multiple_allowed", "Multiple allowed"),
                            (
                                "inherit_from_source_activity",
                                "Inherit from source activity",
                            ),
                            (
                                "ssa_completion_prerequisite",
                                "SSA completion prerequisite",
                            ),
                            ("administrative", "Administrative"),
                        ],
                        max_length=48,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                ("is_primary", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "catalogue_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intervention_mappings",
                        to="activity_catalogue.activitycatalogueitem",
                    ),
                ),
            ],
            options={
                "db_table": "activity_intervention_mapping",
                "ordering": ["priority", "catalogue_item__display_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("catalogue_item", "intervention", "mapping_mode"),
                        name="uniq_catalogue_intervention_mode",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("intervention__isnull", True),
                                (
                                    "mapping_mode__in",
                                    [
                                        "ssa_completion_prerequisite",
                                        "administrative",
                                        "inherit_from_source_activity",
                                    ],
                                ),
                            ),
                            models.Q(
                                ("intervention__isnull", False),
                                ("mapping_mode__in", ["fixed", "multiple_allowed"]),
                            ),
                            _connector="OR",
                        ),
                        name="catalogue_mapping_intervention_shape",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityProjectMapping",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "required_or_optional",
                    models.CharField(
                        choices=[("required", "Required"), ("optional", "Optional")],
                        default="optional",
                        max_length=16,
                    ),
                ),
                (
                    "eligible_school_levels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "eligible_school_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("staff_delivery_allowed", models.BooleanField(default=True)),
                ("partner_delivery_allowed", models.BooleanField(default=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "catalogue_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_mappings",
                        to="activity_catalogue.activitycatalogueitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_catalogue_activities",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "activity_project_mapping",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "catalogue_item"),
                        name="uniq_project_catalogue_item",
                    )
                ],
            },
        ),
    ]
