# Generated by Django 5.2.16 on 2026-07-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_catalogue', '0003_seed_known_project_activity_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycatalogueitem',
            name='ia_verification_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activitycatalogueitem',
            name='multi_day_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitycatalogueitem',
            name='non_school_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitycatalogueitem',
            name='programme_category',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='activitycatalogueitem',
            name='requires_participant_counts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitycatalogueitem',
            name='salesforce_id_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activitycatalogueitem',
            name='workflow_kind',
            field=models.CharField(choices=[('school_visit', 'School Visit'), ('follow_up_visit', 'Follow-up Visit'), ('coaching_visit', 'Coaching Visit'), ('in_school_support', 'In-school Support'), ('donor_visit', 'Donor Visit'), ('story_gathering_visit', 'Gathering Story'), ('school_invitation', 'School Invitation'), ('social_visit', 'Social Visit'), ('training_follow_up_visit', 'Training Follow-up Visit'), ('in_school_coaching_visit', 'In-school Coaching Visit'), ('training', 'Training'), ('in_school_training', 'In-school Training'), ('school_improvement_training', 'School Improvement Training'), ('cluster_meeting', 'Cluster Meeting'), ('cluster_training', 'Cluster Training'), ('ssa_activity', 'SSA Activity'), ('project_activity', 'Project Activity'), ('partner_activity', 'Partner Activity'), ('core_visit', 'Core Visit'), ('core_training', 'Core Training'), ('baseline_ssa_visit', 'SSA Visit'), ('school_visit_ssa_collection', 'School Visit + SSA Collection'), ('cluster_training_ssa_collection', 'Cluster Training + SSA Collection'), ('cluster_meeting_ssa_review', 'Cluster Meeting + SSA Review'), ('partner_ssa_collection', 'Partner SSA Collection'), ('core_assessment_visit', 'Core Assessment Visit'), ('programme_event', 'Programme Event')], max_length=48),
        ),
    ]
