# Generated by Django 5.2.17 on 2026-08-22 09:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_catalogue', '0009_alter_activitycatalogueitem_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='authored_by',
            field=models.CharField(choices=[('seed', 'Seed data'), ('import', 'Catalogue import'), ('reference', 'Reference data'), ('impact_assessment', 'Impact Assessment')], default='seed', max_length=32),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='country',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='eligibility_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='eligible_bands',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='expected_direction',
            field=models.CharField(choices=[('improve', 'Improve the score'), ('maintain_strong', 'Maintain a Strong score'), ('prevent_decline', 'Prevent decline'), ('close_compliance_gap', 'Close a compliance gap')], default='improve', max_length=32),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='follow_up_expected_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='follow_up_max_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='follow_up_min_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='fy',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='measurement_role',
            field=models.CharField(choices=[('eligibility_only', 'Eligibility only'), ('outcome_only', 'Outcome measurement only'), ('eligibility_and_outcome', 'Eligibility and outcome')], default='eligibility_and_outcome', max_length=32),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='min_meaningful_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='not_ssa_measured_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='relationship',
            field=models.CharField(choices=[('primary', 'Primary intervention'), ('secondary', 'Secondary intervention')], default='primary', max_length=16),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='activityinterventionmapping',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='activityinterventionmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('relationship', 'primary'), models.Q(('status', 'retired'), _negated=True)), fields=('catalogue_item',), name='uniq_primary_intervention_per_item'),
        ),
        migrations.AddConstraint(
            model_name='activityinterventionmapping',
            constraint=models.CheckConstraint(condition=models.Q(('follow_up_min_days__isnull', True), ('follow_up_max_days__isnull', True), ('follow_up_min_days__lte', models.F('follow_up_max_days')), _connector='OR'), name='mapping_follow_up_window_ordered'),
        ),
    ]
