# Generated by Django 5.2.17 on 2026-09-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_catalogue", "0013_costing_profiles_2026_09_06"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityinterventionmapping",
            name="change_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="activityinterventionmapping",
            name="review_basis",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="activityinterventionmapping",
            name="review_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="activityinterventionmapping",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activityinterventionmapping",
            name="reviewed_by",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="activityinterventionmapping",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activityinterventionmapping",
            name="submitted_by",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="activityinterventionmapping",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In review"),
                    ("published", "Published"),
                    ("superseded", "Superseded"),
                    ("retired", "Retired"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
