# Generated by Django 5.2.17 on 2026-10-06 11:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_catalogue", "0014_mapping_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitycatalogueitem",
            name="edited_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
