# Generated by Django 5.2.4 on 2026-06-26 23:00

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('fy', models.CharField(max_length=16)),
                ('owner_staff_id', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(default='draft', max_length=32)),
            ],
            options={
                'db_table': 'annual_plan',
                'constraints': [models.UniqueConstraint(fields=('fy', 'owner_staff_id'), name='uniq_annualplan_fy_owner')],
            },
        ),
        migrations.CreateModel(
            name='AnnualPlanActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('school_visit', 'School Visit'), ('follow_up_visit', 'Follow-up Visit'), ('coaching_visit', 'Coaching Visit'), ('in_school_support', 'In-school Support'), ('training', 'Training'), ('school_improvement_training', 'School Improvement Training'), ('cluster_meeting', 'Cluster Meeting'), ('cluster_training', 'Cluster Training'), ('ssa_activity', 'SSA Activity'), ('project_activity', 'Project Activity'), ('partner_activity', 'Partner Activity'), ('core_visit', 'Core Visit'), ('core_training', 'Core Training')], max_length=48)),
                ('school_id', models.CharField(blank=True, max_length=30, null=True)),
                ('cluster_id', models.CharField(blank=True, max_length=30, null=True)),
                ('quarter', models.CharField(max_length=8)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planning.annualplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('month_iso', models.CharField(max_length=16)),
                ('owner_staff_id', models.CharField(max_length=30)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country_id', models.CharField(default='Uganda', max_length=64)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_id', models.CharField(blank=True, max_length=30, null=True)),
                ('returned_reason', models.CharField(blank=True, max_length=512, null=True)),
                ('total_cost_cents', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'monthly_plan',
                'indexes': [models.Index(fields=['status'], name='monthly_pla_status_34ed38_idx'), models.Index(fields=['owner_staff_id'], name='monthly_pla_owner_s_d6d62c_idx')],
                'constraints': [models.UniqueConstraint(fields=('month_iso', 'owner_staff_id'), name='uniq_monthlyplan_month_owner')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPlanActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=48)),
                ('title', models.CharField(max_length=255)),
                ('week_of_month', models.IntegerField(default=1)),
                ('scheduled_date', models.CharField(blank=True, max_length=32, null=True)),
                ('school_id', models.CharField(blank=True, max_length=30, null=True)),
                ('assignee_id', models.CharField(blank=True, max_length=30, null=True)),
                ('est_cost_cents', models.IntegerField(default=0)),
                ('status', models.CharField(default='Planned', max_length=32)),
                ('intervention_area', models.CharField(blank=True, max_length=64, null=True)),
                ('delivery_type', models.CharField(blank=True, max_length=16, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planning.monthlyplan')),
            ],
            options={
                'db_table': 'monthly_plan_activity',
                'indexes': [models.Index(fields=['plan'], name='monthly_pla_plan_id_114a25_idx')],
            },
        ),
    ]
