# Generated by Django 5.2.16 on 2026-08-05 14:45

import apps.core.cuid
import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_alter_annualplanactivity_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('condition_key', models.CharField(db_index=True, max_length=255)),
                ('issue_type', models.CharField(max_length=64)),
                ('severity', models.CharField(default='critical', max_length=32)),
                ('school_id', models.CharField(db_index=True, max_length=30)),
                ('fy', models.CharField(db_index=True, max_length=16)),
                ('month_of_fy', models.IntegerField(blank=True, null=True)),
                ('related_activity_id', models.CharField(blank=True, max_length=30, null=True)),
                ('related_ssa_id', models.CharField(blank=True, max_length=30, null=True)),
                ('sender_id', models.CharField(db_index=True, max_length=30)),
                ('sender_role', models.CharField(max_length=64)),
                ('recipient_id', models.CharField(db_index=True, max_length=30)),
                ('recipient_role', models.CharField(max_length=64)),
                ('requested_action', models.CharField(max_length=255)),
                ('workflow_route', models.CharField(max_length=512)),
                ('message', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal')], default='urgent', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('overdue', 'Overdue'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('returned', 'Returned to sender'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=32)),
                ('detected_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_system', models.BooleanField(default=False)),
                ('manual_resolution_reason', models.TextField(blank=True, default='')),
                ('returned_reason', models.TextField(blank=True, default='')),
                ('reminder_count', models.IntegerField(default=0)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_to_id', models.CharField(blank=True, max_length=30, null=True)),
                ('supersedes_id', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'team_action',
                'indexes': [models.Index(fields=['condition_key', 'state'], name='idx_teamaction_cond_state'), models.Index(fields=['recipient_id', 'state'], name='idx_teamaction_recip_state'), models.Index(fields=['sender_id', 'state'], name='idx_teamaction_sender_state'), models.Index(fields=['state', 'due_date'], name='idx_teamaction_state_due')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state__in', ['open', 'acknowledged', 'in_progress', 'blocked', 'overdue', 'escalated'])), fields=('condition_key',), name='uniq_active_action_per_condition')],
            },
        ),
    ]
