# Generated by Django 5.2.16 on 2026-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0006_teamaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyplanactivity",
            name="est_cost_cents",
            field=models.BigIntegerField(default=0),
        ),
    ]
