# Generated by Django 5.2.17 on 2026-09-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_alter_annualplanactivity_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualplanactivity',
            name='annual_plan',
        ),
        migrations.DeleteModel(
            name='AnnualPlan',
        ),
        migrations.DeleteModel(
            name='AnnualPlanActivity',
        ),
    ]
