# Generated by Django 5.2.17 on 2026-09-15 19:25

import apps.core.cuid
import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0009_drop_annual_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalYearPlanningPolicy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country", models.CharField(default="Uganda", max_length=64)),
                ("fy", models.CharField(max_length=16)),
                ("planning_open_at", models.DateTimeField(blank=True, null=True)),
                ("execution_start", models.DateField()),
                ("execution_end", models.DateField()),
                (
                    "follow_up_visit_requires_prior_training",
                    models.BooleanField(default=True),
                ),
                ("opened_by", models.CharField(blank=True, default="", max_length=30)),
                ("updated_by", models.CharField(blank=True, default="", max_length=30)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "fiscal_year_planning_policy",
                "ordering": ["country", "fy"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "fy"), name="uniq_fy_planning_policy"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("execution_end__gte", models.F("execution_start"))
                        ),
                        name="fy_policy_execution_window_ordered",
                    ),
                ],
            },
        ),
    ]
