# Generated by Django 5.2.17 on 2026-09-28 15:06

import apps.core.cuid
import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0011_open_fy2026_fy2027_policies"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningOversightFollowUp",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fy", models.CharField(db_index=True, max_length=16)),
                ("period_type", models.CharField(default="fy", max_length=16)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "period_label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("country", models.CharField(blank=True, default="", max_length=64)),
                ("region_id", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "region_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "program_lead_staff_id",
                    models.CharField(db_index=True, max_length=30),
                ),
                (
                    "program_lead_user_id",
                    models.CharField(db_index=True, max_length=30),
                ),
                (
                    "program_lead_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "cceo_staff_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("cceo_name", models.CharField(blank=True, default="", max_length=255)),
                ("school_id", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "school_name",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("condition_key", models.CharField(db_index=True, max_length=255)),
                ("issue_type", models.CharField(max_length=48)),
                ("metric_key", models.CharField(max_length=64)),
                ("required_value", models.IntegerField(default=0)),
                ("planned_value", models.IntegerField(default=0)),
                ("remaining_value", models.IntegerField(default=0)),
                ("affected_school_ids", models.JSONField(blank=True, default=list)),
                ("affected_count", models.IntegerField(default=0)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "resolution_rule",
                    models.CharField(default="metric_zero", max_length=32),
                ),
                ("live_remaining", models.IntegerField(blank=True, null=True)),
                ("live_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("attention", "Attention"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        max_length=16,
                    ),
                ),
                ("instruction", models.TextField()),
                ("instruction_history", models.JSONField(blank=True, default=list)),
                ("assigned_by_id", models.CharField(max_length=30)),
                (
                    "assigned_by_role",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "assigned_by_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("assigned_at", models.DateTimeField()),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent_to_pl", "Sent to PL"),
                            ("acknowledged", "Acknowledged"),
                            ("action_linked", "Action Linked"),
                            ("waiting_for_resolution", "Waiting for Resolution"),
                            ("resolved_automatically", "Resolved Automatically"),
                            ("closed_by_cd", "Closed by CD with Reason"),
                            (
                                "returned_for_clarification",
                                "Returned for Clarification",
                            ),
                            ("cancelled", "Canceled"),
                        ],
                        db_index=True,
                        default="sent_to_pl",
                        max_length=32,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("action_linked_at", models.DateTimeField(blank=True, null=True)),
                ("linked_team_action_ids", models.JSONField(blank=True, default=list)),
                ("linked_note", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by_system", models.BooleanField(default=False)),
                ("resolution_note", models.TextField(blank=True, default="")),
                (
                    "closed_by_id",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("returned_reason", models.TextField(blank=True, default="")),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_count", models.IntegerField(default=0)),
                ("last_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("history", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "planning_oversight_follow_up",
                "ordering": ["-assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["program_lead_user_id", "status"],
                        name="idx_cpofu_lead_status",
                    ),
                    models.Index(fields=["fy", "status"], name="idx_cpofu_fy_status"),
                    models.Index(
                        fields=["status", "due_date"], name="idx_cpofu_status_due"
                    ),
                    models.Index(
                        fields=["cceo_staff_id", "status"], name="idx_cpofu_cceo_status"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "sent_to_pl",
                                    "acknowledged",
                                    "action_linked",
                                    "waiting_for_resolution",
                                    "returned_for_clarification",
                                ],
                            )
                        ),
                        fields=("condition_key",),
                        name="uniq_open_cpo_followup_per_condition",
                    )
                ],
            },
        ),
    ]
