# Generated by Django 5.2.17 on 2026-09-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0012_planning_oversight_follow_up"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="planningoversightfollowup",
            name="uniq_open_cpo_followup_per_condition",
        ),
        migrations.AddField(
            model_name="planningoversightfollowup",
            name="activity_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="planningoversightfollowup",
            name="activity_label",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="planningoversightfollowup",
            name="blocker_owner",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="planningoversightfollowup",
            name="days_overdue",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planningoversightfollowup",
            name="module",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("execution", "Execution & Completion"),
                ],
                db_index=True,
                default="planning",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="planningoversightfollowup",
            name="partner_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="planningoversightfollowup",
            name="partner_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="planningoversightfollowup",
            name="stage",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="planningoversightfollowup",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent_to_pl", "Sent to PL"),
                    ("acknowledged", "Acknowledged"),
                    ("action_linked", "Action Linked"),
                    ("waiting_for_resolution", "Waiting for Resolution"),
                    ("resolved_automatically", "Resolved Automatically"),
                    ("closed_by_cd", "Closed by CD with Reason"),
                    ("returned_for_clarification", "Returned for Clarification"),
                    ("cancelled", "Canceled"),
                    ("waiting_for_team_member", "Waiting for Team Member"),
                    ("waiting_for_partner", "Waiting for Partner"),
                    ("waiting_for_external", "Waiting for External Dependency"),
                    ("escalated", "Escalated"),
                ],
                db_index=True,
                default="sent_to_pl",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="planningoversightfollowup",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "sent_to_pl",
                            "acknowledged",
                            "action_linked",
                            "waiting_for_resolution",
                            "returned_for_clarification",
                            "waiting_for_team_member",
                            "waiting_for_partner",
                            "waiting_for_external",
                            "escalated",
                        ],
                    )
                ),
                fields=("condition_key",),
                name="uniq_open_cpo_followup_per_condition",
            ),
        ),
    ]
