# Generated by Django 5.2.17 on 2026-09-28 21:17

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0013_execution_follow_ups"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionPeriodSnapshot",
            fields=[
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("fy", models.CharField(max_length=10)),
                ("period_type", models.CharField(max_length=10)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("period_label", models.CharField(max_length=80)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[("original", "Original"), ("revision", "Revision")],
                        default="original",
                        max_length=12,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("as_of", models.DateField()),
                ("taken_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "taken_by_id",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "taken_by_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "stage_policy",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("figures", models.JSONField(default=dict)),
                ("channels", models.JSONField(default=dict)),
                ("hierarchy", models.JSONField(default=list)),
                ("follow_ups", models.JSONField(default=list)),
                (
                    "revises",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="planning.executionperiodsnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "execution_period_snapshot",
                "ordering": ["-period_start", "period_type", "-version"],
                "indexes": [
                    models.Index(
                        fields=["country", "period_type", "period_start"],
                        name="idx_exec_snapshot_period",
                    ),
                    models.Index(fields=["taken_at"], name="idx_exec_snapshot_taken"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "period_type", "period_start", "version"),
                        name="uniq_execution_snapshot_version",
                    )
                ],
            },
        ),
    ]
