# Generated by Django 5.2.17 on 2026-10-06 11:20

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0037_user_admin_is_never_cceo"),
        ("activity_catalogue", "0014_mapping_review"),
        ("planning", "0014_execution_period_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingCeiling",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fy", models.CharField(max_length=16)),
                ("ceiling", models.PositiveIntegerField()),
                ("set_by", models.CharField(blank=True, default="", max_length=30)),
                (
                    "set_by_role",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("note", models.CharField(blank=True, default="", max_length=512)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_ceilings",
                        to="accounts.staffprofile",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_ceilings",
                        to="activity_catalogue.activitycatalogueitem",
                    ),
                ),
            ],
            options={
                "db_table": "training_ceiling",
                "indexes": [
                    models.Index(
                        fields=["fy", "staff"], name="training_ce_fy_926b0f_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "training", "fy"),
                        name="uniq_training_ceiling_staff_training_fy",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ceiling__gte", 1)),
                        name="training_ceiling_at_least_one",
                    ),
                ],
            },
        ),
    ]
