# Generated by Django 5.2.17 on 2026-10-06 14:31

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_catalogue", "0016_item_universal_training"),
        ("planning", "0015_training_ceiling"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingCountryCeiling",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fy", models.CharField(max_length=16)),
                ("country", models.CharField(blank=True, default="", max_length=64)),
                ("ceiling", models.PositiveIntegerField()),
                ("set_by", models.CharField(blank=True, default="", max_length=30)),
                (
                    "set_by_role",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("note", models.CharField(blank=True, default="", max_length=512)),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="country_training_ceilings",
                        to="activity_catalogue.activitycatalogueitem",
                    ),
                ),
            ],
            options={
                "db_table": "training_country_ceiling",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("training", "fy", "country"),
                        name="uniq_training_country_ceiling",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ceiling__gte", 1)),
                        name="training_country_ceiling_at_least_one",
                    ),
                ],
            },
        ),
    ]
