# Generated by Django 5.2.4 on 2026-06-27 14:09

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activityschedulecostline_catalogue_id_and_more'),
        ('fund_requests', '0002_alter_fundrequest_accounted_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('responsible_user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fy', models.CharField(max_length=16)),
                ('quarter', models.CharField(max_length=8)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('planned_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('draft_from_schedule', 'Draft (from schedule)'), ('pending_responsible_confirmation', 'Pending responsible confirmation'), ('confirmed_for_advance', 'Confirmed for advance'), ('self_funded_pending_reimbursement', 'Self-funded (pending reimbursement)'), ('not_requested', 'Not requested'), ('submitted_to_accountant', 'Submitted to accountant'), ('disbursed', 'Disbursed'), ('accountability_pending', 'Accountability pending'), ('accounted', 'Accounted'), ('reimbursement_submitted', 'Reimbursement submitted'), ('reimbursed', 'Reimbursed'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending_responsible_confirmation', max_length=40)),
                ('advance_type', models.CharField(choices=[('advance', 'Request Advance'), ('self_funded', 'Use Own Funds (claim reimbursement later)'), ('not_requested', 'Do Not Request Funds Yet')], default='advance', max_length=16)),
                ('disbursed_amount', models.BigIntegerField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_by_user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('disburse_method', models.CharField(blank=True, max_length=64, null=True)),
                ('disburse_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('accounted_amount', models.BigIntegerField(blank=True, null=True)),
                ('returned_amount', models.BigIntegerField(blank=True, null=True)),
                ('accountability_netsuite_id', models.CharField(blank=True, max_length=128, null=True)),
                ('accountability_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('accountability_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_note', models.CharField(blank=True, max_length=512, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_requests', to='activities.activity')),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_requests', to='activities.activityschedulecostline')),
            ],
            options={
                'db_table': 'advance_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='advance_req_status_c044e0_idx'), models.Index(fields=['responsible_user_id'], name='advance_req_respons_f97908_idx'), models.Index(fields=['fy', 'month'], name='advance_req_fy_480aae_idx')],
                'constraints': [models.UniqueConstraint(fields=('budget_line',), name='uniq_advance_per_budget_line')],
            },
        ),
    ]
