# Generated by Django 5.2.4 on 2026-07-08 22:26

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budget", "0004_costcatalogue_required_school_visits_per_day"),
        ("geography", "0002_secondarydistrictgroup_district_district_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyVisitBatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("responsible_user", models.CharField(max_length=30)),
                ("visit_date", models.DateField()),
                (
                    "district_type",
                    models.CharField(
                        choices=[("primary", "Primary"), ("secondary", "Secondary")],
                        max_length=16,
                    ),
                ),
                ("catalogue_version", models.IntegerField(blank=True, null=True)),
                ("rate_snapshot", models.JSONField(default=dict)),
                ("daily_pool_amount", models.BigIntegerField(default=0)),
                ("school_count", models.IntegerField(default=0)),
                ("per_school_amount", models.BigIntegerField(default=0)),
                (
                    "required_target_snapshot",
                    models.IntegerField(blank=True, null=True),
                ),
                ("reason", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "cost_catalogue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_visit_batches",
                        to="budget.costcatalogue",
                    ),
                ),
                (
                    "secondary_district_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to="geography.secondarydistrictgroup",
                    ),
                ),
            ],
            options={
                "db_table": "daily_visit_batch",
                "indexes": [
                    models.Index(
                        fields=["visit_date"], name="daily_visit_visit_d_d5e8e4_idx"
                    ),
                    models.Index(
                        fields=["district_type"], name="daily_visit_distric_a08744_idx"
                    ),
                    models.Index(
                        fields=["responsible_user"],
                        name="daily_visit_respons_9b5063_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("responsible_user", "visit_date"),
                        name="uniq_daily_visit_batch_user_date",
                    )
                ],
            },
        ),
    ]
