# Generated by Django 5.2.16 on 2026-08-19 07:03

import apps.core.cuid
import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daily_visit_batches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyvisitbatch",
            name="actual_field_cost_per_school",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyvisitbatch",
            name="planned_field_cost_per_school",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyvisitbatch",
            name="school_visit_allocation",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyvisitbatch",
            name="workload_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ActivityWorkloadWeight",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("activity_type", models.CharField(db_index=True, max_length=64)),
                ("weight_hundredths", models.PositiveIntegerField(default=100)),
                ("version", models.PositiveIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                (
                    "changed_by_user_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "db_table": "activity_workload_weight",
                "indexes": [
                    models.Index(
                        fields=["activity_type", "active"],
                        name="activity_wo_activit_1dac67_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("activity_type", "version"),
                        name="uniq_workload_weight_type_version",
                    )
                ],
            },
        ),
    ]
