# Generated by Django 5.2.4 on 2026-07-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_alter_auditlog_actor_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="seq",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
