# Generated by Django 5.2.16 on 2026-08-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_unique_seq"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditChainCheckpoint",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="audit-chain-checkpoint",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("verified_through_seq", models.BigIntegerField(blank=True, null=True)),
                (
                    "verified_hash",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("broken_at_seq", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "audit_chain_checkpoint",
            },
        ),
    ]
