# Generated by Django 5.2.17 on 2026-09-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0007_auditlog_actor_role_regional_programme_lead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domaineventlog",
            name="aggregate_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
