# Generated by Django 5.2.4 on 2026-06-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clusters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="environment",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("staging", "Staging"),
                    ("production", "Production"),
                ],
                db_index=True,
                default="production",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual_upload", "Manual Upload"),
                    ("admin_created", "Admin Created"),
                    ("api_import", "API Import"),
                    ("local_test_upload", "Local Test Upload"),
                    ("production_upload", "Production Upload"),
                ],
                db_index=True,
                default="manual_upload",
                max_length=32,
            ),
        ),
    ]
