# Generated by Django 5.2.17 on 2026-09-15 18:41

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clusters", "0004_backfill_cluster_portfolio_owners"),
        ("geography", "0006_region_country"),
        ("schools", "0021_school_uniq_school_salesforce_account_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterServiceDistrict",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary district"),
                            ("neighbouring", "Approved neighbouring district"),
                        ],
                        default="primary",
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_by", models.CharField(blank=True, default="", max_length=30)),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("ended_by", models.CharField(blank=True, default="", max_length=30)),
                ("ended_reason", models.TextField(blank=True, default="")),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_districts",
                        to="clusters.cluster",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="cluster_catchments",
                        to="geography.district",
                    ),
                ),
            ],
            options={
                "db_table": "cluster_service_district",
                "ordering": ["relationship_type", "effective_from"],
            },
        ),
        migrations.CreateModel(
            name="SchoolClusterMembership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("started_by", models.CharField(blank=True, default="", max_length=30)),
                (
                    "started_by_role",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("ended_by", models.CharField(blank=True, default="", max_length=30)),
                ("start_reason", models.TextField(blank=True, default="")),
                ("end_reason", models.TextField(blank=True, default="")),
                (
                    "relationship_type",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "correlation_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "catchment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships",
                        to="clusters.clusterservicedistrict",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_history",
                        to="clusters.cluster",
                    ),
                ),
                (
                    "cluster_district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="geography.district",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_membership_history",
                        to="schools.school",
                    ),
                ),
                (
                    "school_district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="geography.district",
                    ),
                ),
            ],
            options={
                "db_table": "school_cluster_membership",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="clusterservicedistrict",
            index=models.Index(
                fields=["district", "active"], name="cluster_ser_distric_fe03f9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clusterservicedistrict",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("cluster", "district"),
                name="uniq_active_cluster_service_district",
            ),
        ),
        migrations.AddConstraint(
            model_name="clusterservicedistrict",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True), ("relationship_type", "primary")),
                fields=("cluster",),
                name="uniq_active_primary_cluster_district",
            ),
        ),
        migrations.AddConstraint(
            model_name="clusterservicedistrict",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="cluster_catchment_dates_ordered",
            ),
        ),
        migrations.AddIndex(
            model_name="schoolclustermembership",
            index=models.Index(
                fields=["cluster", "ended_at"], name="school_clus_cluster_74fde2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclustermembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("school",),
                name="uniq_open_school_cluster_membership",
            ),
        ),
    ]
