# Generated by Django 5.2.17 on 2026-10-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clusters", "0006_backfill_catchments_and_membership_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="facilitating_partner_id",
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="cluster",
            name="facilitator_assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cluster",
            name="facilitator_assigned_by",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
