# Generated by Django 5.2.17 on 2026-10-08 20:19

import apps.core.cuid
import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clusters", "0007_cluster_facilitating_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterScoreSetting",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("health_weights", models.JSONField(blank=True, default=dict)),
                ("impact_weights", models.JSONField(blank=True, default=dict)),
                ("teacher_weights", models.JSONField(blank=True, default=dict)),
                ("leader_weights", models.JSONField(blank=True, default=dict)),
                ("maturity_rules", models.JSONField(blank=True, default=dict)),
                ("set_by", models.CharField(blank=True, default="", max_length=30)),
                ("note", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "cluster_score_setting",
                "ordering": ["-created_at"],
            },
        ),
    ]
