# Generated by Django 5.2.4 on 2026-06-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0004_school_directory_filter_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="account_owner_status",
            field=models.CharField(
                choices=[
                    ("matched", "Matched"),
                    ("unmatched", "Unmatched"),
                    ("ambiguous", "Ambiguous"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
