# Generated by Django 5.2.4 on 2026-07-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_alter_uploadbatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='data_quality_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='school',
            name='data_quality_status',
            field=models.CharField(default='Clean', max_length=64),
        ),
        migrations.AlterField(
            model_name='school',
            name='planning_readiness',
            field=models.CharField(choices=[('requires_cluster', 'Requires Cluster'), ('ready_for_baseline_ssa', 'Ready for Baseline SSA'), ('ready_for_support_planning', 'Ready for Support Planning'), ('ready_for_partner_assignment', 'Ready for Partner Assignment'), ('scheduled', 'Scheduled'), ('in_my_plan', 'In My Plan'), ('awaiting_evidence', 'Awaiting Evidence'), ('awaiting_ia', 'Awaiting IA'), ('finance_pending', 'Finance Pending'), ('closed', 'Closed'), ('data_cleanup_required', 'Data Cleanup Required'), ('cost_catalogue_required', 'Cost Catalogue Required'), ('locked', 'Locked'), ('limited', 'Limited'), ('ready', 'Ready')], default='locked', max_length=32),
        ),
    ]
