# Generated by Django 5.2.4 on 2026-07-02 15:30

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_school_data_quality_score_school_data_quality_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolImportBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=512)),
                ('uploaded_by', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('imported', 'Imported'), ('cancelled', 'Cancelled')], default='staged', max_length=32)),
                ('total_rows', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'school_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SSAImportBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=512)),
                ('uploaded_by', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('imported', 'Imported'), ('cancelled', 'Cancelled')], default='staged', max_length=32)),
                ('total_rows', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ssa_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnmatchedSSARecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('school_id', models.CharField(max_length=64)),
                ('school_name_raw', models.CharField(blank=True, max_length=512, null=True)),
                ('district_raw', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_ssa', models.CharField(blank=True, max_length=64, null=True)),
                ('scores', models.JSONField(blank=True, default=dict, null=True)),
                ('reason', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('ignored', 'Ignored')], default='pending', max_length=32)),
            ],
            options={
                'db_table': 'unmatched_ssa_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('field_name', models.CharField(blank=True, max_length=64, null=True)),
                ('current_value', models.TextField(blank=True, null=True)),
                ('suggested_fix', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('assigned_to', models.CharField(blank=True, max_length=30, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_issues', to='schools.school')),
            ],
            options={
                'db_table': 'data_quality_issue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolChangeLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=64)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_by', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='schools.school')),
            ],
            options={
                'db_table': 'school_change_log',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolImportRow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('school_id', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('school_type', models.CharField(blank=True, max_length=64, null=True)),
                ('district_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_county_name', models.CharField(blank=True, max_length=255, null=True)),
                ('enrollment', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('director_name', models.CharField(blank=True, max_length=255, null=True)),
                ('headteacher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('account_owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ready', 'Ready to Import'), ('update', 'Will Update'), ('review', 'Needs Review'), ('duplicate', 'Duplicate Risk'), ('blocked', 'Blocked')], default='ready', max_length=32)),
                ('validation_errors', models.JSONField(blank=True, default=list, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='schools.schoolimportbatch')),
            ],
            options={
                'db_table': 'school_import_row',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='SSAImportRow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('school_id', models.CharField(blank=True, max_length=64, null=True)),
                ('date_of_ssa', models.CharField(blank=True, max_length=64, null=True)),
                ('scores', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('unmatched', 'Unmatched School ID'), ('blocked', 'Blocked')], default='ready', max_length=32)),
                ('validation_errors', models.JSONField(blank=True, default=list, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='schools.ssaimportbatch')),
            ],
            options={
                'db_table': 'ssa_import_row',
                'ordering': ['row_number'],
            },
        ),
    ]
