# Generated by Django 5.2.4 on 2026-07-14 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0011_alter_school_planning_readiness"),
    ]

    operations = [
        migrations.AddField(
            model_name="unmatchedssarecord",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unmatched_records",
                to="schools.ssaimportbatch",
            ),
        ),
        migrations.AddField(
            model_name="unmatchedssarecord",
            name="match_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unmatchedssarecord",
            name="suggested_school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="schools.school",
            ),
        ),
        migrations.AddIndex(
            model_name="unmatchedssarecord",
            index=models.Index(fields=["status"], name="unmatched_s_status_6a85ae_idx"),
        ),
        migrations.AddIndex(
            model_name="unmatchedssarecord",
            index=models.Index(fields=["batch"], name="unmatched_s_batch_i_8ef85c_idx"),
        ),
        migrations.AddIndex(
            model_name="unmatchedssarecord",
            index=models.Index(
                fields=["district_raw"], name="unmatched_s_distric_429bac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unmatchedssarecord",
            index=models.Index(
                fields=["school_id"], name="unmatched_s_school__2447b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unmatchedssarecord",
            index=models.Index(
                fields=["match_confidence"], name="unmatched_s_match_c_076005_idx"
            ),
        ),
    ]
