# Generated by Django 5.2.4 on 2026-07-14 04:34

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0002_secondarydistrictgroup_district_district_type_and_more"),
        ("schools", "0013_enable_pg_trgm"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="school",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="school_name_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
