# Generated by Django 5.2.16 on 2026-07-30 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0003_populate_sub_regions"),
        ("schools", "0015_normalize_planning_readiness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="schools",
                to="geography.district",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="schools",
                to="geography.region",
            ),
        ),
    ]
