# Generated by Django 5.2.16 on 2026-07-30 16:45

from django.db import migrations, models


def migrate_legacy_partner_types(apps, schema_editor):
    School = apps.get_model("schools", "School")
    replacements = {
        "potential_core": "core_trained",
        "potential_champion": "champion",
        "other": "client",
    }
    for old_value, new_value in replacements.items():
        School.objects.filter(school_type=old_value).update(school_type=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_allow_incomplete_school_geography'),
    ]

    operations = [
        migrations.RunPython(
            migrate_legacy_partner_types,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('champion', 'Champion'), ('client', 'Client'), ('core', 'Core'), ('core_graduate', 'Core Graduate'), ('core_trained', 'Core Trained')], default='client', max_length=32),
        ),
    ]
