# Generated by Django 5.2.16 on 2026-08-07 07:58

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0018_relink_school_geography"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="closure_effective_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="operational_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("temporarily_closed", "Temporarily closed"),
                    ("permanently_closed", "Permanently closed"),
                    ("reopened", "Reopened"),
                ],
                default="active",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="reopened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SchoolClosure",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "closure_type",
                    models.CharField(
                        choices=[
                            ("temporary", "Temporarily closed"),
                            ("permanent", "Permanently closed"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("owner_decision", "Owner decision"),
                            ("financial", "Financial difficulties"),
                            ("low_enrolment", "Low enrolment"),
                            ("licensing", "Licence or registration issue"),
                            ("government_closure", "Government closure"),
                            ("merged", "Merged with another school"),
                            ("relocated", "Relocated outside Edify scope"),
                            ("facility", "Building or facility problem"),
                            ("security", "Security or access problem"),
                            ("disaster", "Natural disaster or emergency"),
                            ("management", "School management breakdown"),
                            (
                                "temporary_suspension",
                                "Temporary suspension of operations",
                            ),
                            (
                                "duplicate_record",
                                "Duplicate or incorrect school record",
                            ),
                            ("unconfirmed", "Unable to confirm continued operation"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField()),
                ("effective_date", models.DateField()),
                ("closed_by", models.CharField(max_length=30)),
                ("closed_by_role", models.CharField(blank=True, max_length=48)),
                ("enrollment_at_closure", models.IntegerField(blank=True, null=True)),
                ("enrollment_source", models.CharField(blank=True, max_length=64)),
                ("enrollment_record_date", models.DateField(blank=True, null=True)),
                (
                    "cluster_at_closure",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "cluster_name_at_closure",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "owner_at_closure",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("owner_name_at_closure", models.CharField(blank=True, max_length=255)),
                ("activities_cancelled", models.IntegerField(default=0)),
                ("partner_assignments_withdrawn", models.IntegerField(default=0)),
                ("budget_released", models.BigIntegerField(default=0)),
                ("locked_activities_for_review", models.IntegerField(default=0)),
                ("reopened_at", models.DateTimeField(blank=True, null=True)),
                ("reopened_by", models.CharField(blank=True, max_length=30, null=True)),
                ("reopening_reason", models.TextField(blank=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closures",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "school_closure",
                "ordering": ["-effective_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "reopened_at"],
                        name="school_clos_school__09ada6_idx",
                    ),
                    models.Index(
                        fields=["effective_date"], name="school_clos_effecti_140be5_idx"
                    ),
                    models.Index(
                        fields=["reason_category"],
                        name="school_clos_reason__1bb15a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("reopened_at__isnull", True)),
                        fields=("school",),
                        name="one_open_closure_per_school",
                    )
                ],
            },
        ),
    ]
