# Generated by Django 5.2.16 on 2026-08-15 13:13
"""condition_key gives every quality issue a stable identity (the TeamAction
pattern) so regeneration reconciles in place instead of delete-and-recreate.

The backfill stamps existing rows with school:<school_id>|dq:<issue_type>;
because the old regeneration deleted every open row before recreating, at
most one open row per key should exist — but the dedupe pass runs anyway
(keeping the newest, resolving the rest) so the partial unique constraint
can never fail against historical data.
"""

from django.db import migrations, models
from django.utils import timezone


def backfill_condition_keys(apps, schema_editor):
    DataQualityIssue = apps.get_model("schools", "DataQualityIssue")
    batch = []
    for issue in DataQualityIssue.objects.filter(condition_key__isnull=True).iterator(
        chunk_size=2000
    ):
        issue.condition_key = f"school:{issue.school_id}|dq:{issue.issue_type}"
        batch.append(issue)
        if len(batch) >= 2000:
            DataQualityIssue.objects.bulk_update(batch, ["condition_key"])
            batch = []
    if batch:
        DataQualityIssue.objects.bulk_update(batch, ["condition_key"])

    # Dedupe open rows per key: keep the newest, resolve the rest.
    seen = set()
    to_resolve = []
    now = timezone.now()
    for issue in (
        DataQualityIssue.objects.filter(status="open")
        .order_by("-created_at")
        .iterator(chunk_size=2000)
    ):
        if issue.condition_key in seen:
            issue.status = "resolved"
            issue.resolved_at = now
            to_resolve.append(issue)
        else:
            seen.add(issue.condition_key)
    if to_resolve:
        DataQualityIssue.objects.bulk_update(to_resolve, ["status", "resolved_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0019_school_closed_at_school_closure_effective_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataqualityissue",
            name="condition_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=191, null=True
            ),
        ),
        migrations.RunPython(backfill_condition_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="dataqualityissue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("condition_key",),
                name="uniq_open_dq_condition",
            ),
        ),
    ]
