# Generated by Django 5.2.17 on 2026-09-16 03:07

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0029_presence_activity"),
        ("geography", "0006_region_country"),
        ("schools", "0021_school_uniq_school_salesforce_account_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictPortfolioTransfer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "open_activity_decision",
                    models.CharField(
                        choices=[
                            ("keep", "Keep open activities with their current owner"),
                            (
                                "transfer",
                                "Transfer eligible open activities to the new owner",
                            ),
                        ],
                        default="keep",
                        max_length=16,
                    ),
                ),
                ("school_count", models.PositiveIntegerField(default=0)),
                ("activities_transferred", models.PositiveIntegerField(default=0)),
                ("actor_id", models.CharField(blank=True, default="", max_length=30)),
                ("actor_role", models.CharField(blank=True, default="", max_length=64)),
                (
                    "correlation_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "target_reconciliation_status",
                    models.CharField(
                        choices=[
                            (
                                "not_required",
                                "No approved target depends on this portfolio",
                            ),
                            ("required", "Target reconciliation required"),
                            ("resolved", "Target reconciliation resolved"),
                        ],
                        default="not_required",
                        max_length=16,
                    ),
                ),
                ("preview", models.JSONField(blank=True, default=dict)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_transfers",
                        to="geography.district",
                    ),
                ),
                (
                    "from_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="district_portfolios_given",
                        to="accounts.staffprofile",
                    ),
                ),
                (
                    "to_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="district_portfolios_taken",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "district_portfolio_transfer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolOwnershipTransfer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "open_activity_decision",
                    models.CharField(
                        choices=[
                            ("keep", "Keep open activities with their current owner"),
                            (
                                "transfer",
                                "Transfer eligible open activities to the new owner",
                            ),
                        ],
                        default="keep",
                        max_length=16,
                    ),
                ),
                (
                    "transferred_activity_ids",
                    models.JSONField(blank=True, default=list),
                ),
                ("kept_activity_ids", models.JSONField(blank=True, default=list)),
                ("actor_id", models.CharField(blank=True, default="", max_length=30)),
                ("actor_role", models.CharField(blank=True, default="", max_length=64)),
                (
                    "correlation_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "target_reconciliation_status",
                    models.CharField(
                        choices=[
                            (
                                "not_required",
                                "No approved target depends on this portfolio",
                            ),
                            ("required", "Target reconciliation required"),
                            ("resolved", "Target reconciliation resolved"),
                        ],
                        default="not_required",
                        max_length=16,
                    ),
                ),
                (
                    "target_reconciliation_note",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "target_reconciliation_resolved_by",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "target_reconciliation_resolved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_transfers",
                        to="schools.districtportfoliotransfer",
                    ),
                ),
                (
                    "from_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schools_given",
                        to="accounts.staffprofile",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_transfers",
                        to="schools.school",
                    ),
                ),
                (
                    "to_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schools_taken",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "school_ownership_transfer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="districtportfoliotransfer",
            index=models.Index(
                fields=["district", "-created_at"],
                name="district_po_distric_9df39e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="schoolownershiptransfer",
            index=models.Index(
                fields=["school", "-created_at"], name="school_owne_school__154c6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolownershiptransfer",
            index=models.Index(
                fields=["target_reconciliation_status"],
                name="school_owne_target__eb3c69_idx",
            ),
        ),
    ]
