/* Which content-visibility:auto sections are drawn or skipped once a page has settled, and how tall they are. */
const { chromium } = require('@playwright/test'); const fs = require('node:fs'); const path = require('node:path');
const B = 'http://127.0.0.1:8376'; const OLD = process.env.OLD === '1';
(async () => { const browser = await chromium.launch(); const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, serviceWorkers: 'block' });
  if (OLD) { await context.route((u) => /\/static\/build\/css\/.+\.css$/.test(u.pathname), (route) => { const p = new URL(route.request().url()).pathname; const m = p.match(/\/static\/build\/css\/(.+?)\.[0-9a-f]{12}\.css$/) || p.match(/\/static\/build\/css\/(.+?)\.css$/); route.fulfill({ status: 200, contentType: 'text/css', body: fs.readFileSync(path.join(process.env.CSS_OLD, m[1] + '.css')) }); });
    for (const [needle, file] of Object.entries(JSON.parse(process.env.OVERRIDES))) await context.route((u) => u.pathname.includes('/static/') && u.pathname.includes(needle), (route) => route.fulfill({ status: 200, contentType: file.endsWith('.css') ? 'text/css' : 'application/javascript', body: fs.readFileSync(file) })); }
  const page = await context.newPage(); await page.goto(B + '/login'); await page.fill('input[name=email]', process.env.EMAIL); await page.fill('input[name=password]', 'edify'); await Promise.all([page.waitForNavigation(), page.press('input[name=password]', 'Enter')]);
  if (OLD && process.env.STRIP !== '0') await page.route((u) => u.origin === B && !u.pathname.startsWith('/static/'), async (route) => { if (route.request().resourceType() !== 'document') return route.continue(); const response = await route.fetch(); const body = (await response.text()).replace(/(<script\b[^>]*?) blocking="render"/g, '$1').replace(/<link rel="expect"[^>]*>/, ''); await route.fulfill({ response, body }); });
  await page.goto(B + process.env.PATHNAME, { waitUntil: 'load' }); await page.waitForTimeout(6000);
  const r = await page.evaluate(() => ({ height: document.documentElement.scrollHeight, sections: Array.from(document.querySelectorAll('main *')).filter((e) => getComputedStyle(e).contentVisibility === 'auto').map((e) => ({ el: e.tagName.toLowerCase() + '.' + Array.from(e.classList).slice(0, 2).join('.'), top: Math.round(e.getBoundingClientRect().top + scrollY), h: Math.round(e.getBoundingClientRect().height), drawn: e.firstElementChild ? e.firstElementChild.checkVisibility({ contentVisibilityAuto: true }) : null, intrinsic: getComputedStyle(e).containIntrinsicSize })) }));
  const shown = await page.evaluate(async () => { const card = document.querySelector('main .sp-matrix-card'); if (!card) return null; const before = Math.round(card.getBoundingClientRect().height); card.scrollIntoView(); await new Promise((r) => setTimeout(r, 1500)); return { rememberedWhileSkipped: before, heightWhenScrolledTo: Math.round(card.getBoundingClientRect().height) }; });
  if (shown) console.log((OLD ? 'original' : 'final   ') + ' matrix card ' + JSON.stringify(shown));
  console.log((OLD ? 'original' : 'final   ') + ' page height ' + r.height + '; content-visibility:auto sections: ' + r.sections.length); for (const s of r.sections) console.log('   ' + JSON.stringify(s));
  await browser.close(); })().catch((e) => { console.error(e); process.exit(1); });
