# Generated by Django 5.2.16 on 2026-07-24 22:56

import apps.core.cuid
import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_internal_report_delivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolVisitAnalysisSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scope_role", models.CharField(max_length=64)),
                ("scope_user_id", models.CharField(max_length=30)),
                ("methodology_version", models.CharField(max_length=32)),
                ("baseline_fy", models.CharField(max_length=16)),
                ("followup_fy", models.CharField(max_length=16)),
                ("included_schools", models.IntegerField(default=0)),
                ("excluded_summary", models.JSONField(default=dict)),
                ("visit_count", models.IntegerField(default=0)),
                ("data_confidence", models.CharField(default="none", max_length=24)),
                ("version", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("current", "Current"), ("superseded", "Superseded")],
                        default="current",
                        max_length=16,
                    ),
                ),
                ("results", models.JSONField(default=dict)),
                ("generated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "school_visit_analysis_snapshot",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["scope_user_id", "status"],
                        name="school_visi_scope_u_5b48ce_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "scope_role",
                            "scope_user_id",
                            "methodology_version",
                            "version",
                        ),
                        name="uniq_visit_analysis_scope_version",
                    )
                ],
            },
        ),
    ]
