# Generated by Django 5.2.16 on 2026-08-15 13:01

import apps.core.cuid
import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InteractionDay",
            fields=[
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(max_length=30)),
                ("role", models.CharField(max_length=64)),
                ("day", models.DateField(db_index=True)),
                ("active_seconds", models.PositiveIntegerField(default=0)),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("write_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "interaction_day",
                "indexes": [
                    models.Index(
                        fields=["role", "day"], name="idx_interaction_role_day"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "day"), name="uniq_interaction_user_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InteractionEvent",
            fields=[
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=30)),
                ("role", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("method", models.CharField(max_length=8)),
                ("route", models.CharField(max_length=255)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "interaction_event",
                "indexes": [
                    models.Index(
                        fields=["user_id", "occurred_at"],
                        name="idx_interaction_user_time",
                    )
                ],
            },
        ),
    ]
