# Generated by Django 5.2.16 on 2026-08-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactionday",
            name="execution_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="interactionday",
            name="planning_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
