# Generated by Django 5.2.17 on 2026-09-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0002_interactionday_execution_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactionevent",
            name="db_ms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="interactionevent",
            name="query_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="interactionevent",
            name="queue_ms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="interactionevent",
            name="status_code",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
