# Generated by Django 5.2.17 on 2026-09-13 04:46

import apps.core.cuid
import apps.core.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activities", "0053_activity_ssa_alignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionalCceReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author_id", models.CharField(db_index=True, max_length=30)),
                ("period", models.DateField()),
                ("fy", models.CharField(db_index=True, max_length=16)),
                (
                    "countries",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("acknowledged", "Acknowledged"),
                            ("returned", "Returned for revision"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("executive_summary", models.TextField(blank=True, default="")),
                ("training_programmes", models.TextField(blank=True, default="")),
                ("cce_impact", models.TextField(blank=True, default="")),
                ("curriculum_development", models.TextField(blank=True, default="")),
                ("programme_initiatives", models.TextField(blank=True, default="")),
                ("partnerships", models.TextField(blank=True, default="")),
                ("support_needed", models.TextField(blank=True, default="")),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "cce_regional_report",
                "ordering": ["-period", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "period"], name="idx_cce_report_status"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("author_id", "period"),
                        name="uniq_cce_report_author_month",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RegionalEngagement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author_id", models.CharField(db_index=True, max_length=30)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pl_coaching", "Programme Lead coaching"),
                            ("training_observation", "Training observation"),
                            (
                                "cd_quarterly_review",
                                "Quarterly review with a Country Director",
                            ),
                            (
                                "cd_annual_planning",
                                "Annual programming and budget input",
                            ),
                            ("vp_cce_checkin", "Check-in with the VP of CCE"),
                            (
                                "regional_leads_meeting",
                                "Regional Leads and VP of CCE meeting",
                            ),
                            ("rvp_meeting", "Meeting with the RVP"),
                            (
                                "cross_region_convening",
                                "Cross-region Programme Lead convening",
                            ),
                            ("site_visit", "School site visit"),
                            (
                                "partner_network",
                                "Training partner or school network meeting",
                            ),
                            ("prayer_event", "Prayer event"),
                        ],
                        max_length=32,
                    ),
                ),
                ("held_on", models.DateField()),
                ("fy", models.CharField(db_index=True, max_length=16)),
                ("country", models.CharField(blank=True, default="", max_length=64)),
                (
                    "program_lead_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("agreed_actions", models.TextField(blank=True, default="")),
                ("follow_up_due", models.DateField(blank=True, null=True)),
                (
                    "rating_biblical_integration",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "rating_need_alignment",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "rating_facilitation",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "rating_participation",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "rating_application",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("continue", "Continue as delivered"),
                            ("strengthen", "Strengthen with the training partner"),
                            ("replace", "Replace the training"),
                            ("economize", "Economize the delivery"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("feedback", models.TextField(blank=True, default="")),
                ("feedback_shared_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("lead_response", models.TextField(blank=True, default="")),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cce_observations",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "cce_regional_engagement",
                "ordering": ["-held_on", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["author_id", "kind", "held_on"],
                        name="idx_cce_engagement_author",
                    ),
                    models.Index(
                        fields=["country", "kind", "held_on"],
                        name="idx_cce_engagement_country",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("rating_biblical_integration__isnull", True),
                                ("rating_biblical_integration__range", (1, 4)),
                                _connector="OR",
                            ),
                            models.Q(
                                ("rating_need_alignment__isnull", True),
                                ("rating_need_alignment__range", (1, 4)),
                                _connector="OR",
                            ),
                            models.Q(
                                ("rating_facilitation__isnull", True),
                                ("rating_facilitation__range", (1, 4)),
                                _connector="OR",
                            ),
                            models.Q(
                                ("rating_participation__isnull", True),
                                ("rating_participation__range", (1, 4)),
                                _connector="OR",
                            ),
                            models.Q(
                                ("rating_application__isnull", True),
                                ("rating_application__range", (1, 4)),
                                _connector="OR",
                            ),
                        ),
                        name="cce_engagement_ratings_one_to_four",
                    )
                ],
            },
        ),
    ]
