# Generated by Django 5.2.17 on 2026-09-13 09:38

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0053_activity_ssa_alignment"),
        ("cce_leadership", "0001_initial"),
        ("debriefs", "0008_alter_dailydebrief_recommended_next_activity_type"),
        ("hr", "0020_compliance_status_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamGuidance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author_id", models.CharField(db_index=True, max_length=30)),
                ("fy", models.CharField(db_index=True, max_length=16)),
                ("country", models.CharField(blank=True, default="", max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("instruction", models.TextField()),
                ("expected_change", models.TextField(blank=True, default="")),
                ("review_on", models.DateField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_guidance",
                        to="hr.prioritymilestone",
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_guidance",
                        to="hr.strategicpriority",
                    ),
                ),
            ],
            options={
                "db_table": "cce_team_guidance",
                "ordering": ["-issued_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamGuidanceReceipt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_staff_id", models.CharField(db_index=True, max_length=30)),
                ("recipient_user_id", models.CharField(db_index=True, max_length=30)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("response", models.TextField(blank=True, default="")),
                (
                    "guidance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="cce_leadership.teamguidance",
                    ),
                ),
            ],
            options={
                "db_table": "cce_team_guidance_receipt",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CceoCoaching",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author_id", models.CharField(db_index=True, max_length=30)),
                ("cceo_staff_id", models.CharField(db_index=True, max_length=30)),
                ("cceo_user_id", models.CharField(db_index=True, max_length=30)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("one_to_one", "Monthly one-to-one"),
                            ("field_observation", "School visit observation"),
                            ("training_observation", "Training observation"),
                            ("performance_checkin", "Performance check-in"),
                            ("debrief_feedback", "Field debrief feedback"),
                            ("recognition", "Recognition"),
                            ("regional_feedback", "Regional Lead feedback passed on"),
                        ],
                        max_length=32,
                    ),
                ),
                ("held_on", models.DateField()),
                ("fy", models.CharField(db_index=True, max_length=16)),
                ("country", models.CharField(blank=True, default="", max_length=64)),
                ("subject", models.CharField(max_length=255)),
                ("strengths", models.TextField(blank=True, default="")),
                ("growth_areas", models.TextField(blank=True, default="")),
                ("agreed_actions", models.TextField(blank=True, default="")),
                ("follow_up_due", models.DateField(blank=True, null=True)),
                (
                    "rating_biblical_integration",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "rating_need_alignment",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "rating_facilitation",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "rating_participation",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "rating_application",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("shared_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("cceo_response", models.TextField(blank=True, default="")),
                ("follow_up_done_at", models.DateTimeField(blank=True, null=True)),
                ("follow_up_note", models.TextField(blank=True, default="")),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cceo_coaching",
                        to="activities.activity",
                    ),
                ),
                (
                    "debrief",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coaching",
                        to="debriefs.dailydebrief",
                    ),
                ),
                (
                    "source_engagement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="passed_to_cceos",
                        to="cce_leadership.regionalengagement",
                    ),
                ),
            ],
            options={
                "db_table": "cce_cceo_coaching",
                "ordering": ["-held_on", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["author_id", "held_on"], name="idx_cceo_coaching_author"
                    ),
                    models.Index(
                        fields=["cceo_staff_id", "held_on"],
                        name="idx_cceo_coaching_cceo",
                    ),
                    models.Index(
                        fields=["country", "held_on"], name="idx_cceo_coaching_country"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("rating_biblical_integration__isnull", True),
                                ("rating_biblical_integration__range", (1, 4)),
                                _connector="OR",
                            ),
                            models.Q(
                                ("rating_need_alignment__isnull", True),
                                ("rating_need_alignment__range", (1, 4)),
                                _connector="OR",
                            ),
                            models.Q(
                                ("rating_facilitation__isnull", True),
                                ("rating_facilitation__range", (1, 4)),
                                _connector="OR",
                            ),
                            models.Q(
                                ("rating_participation__isnull", True),
                                ("rating_participation__range", (1, 4)),
                                _connector="OR",
                            ),
                            models.Q(
                                ("rating_application__isnull", True),
                                ("rating_application__range", (1, 4)),
                                _connector="OR",
                            ),
                        ),
                        name="cceo_coaching_ratings_one_to_four",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="teamguidance",
            index=models.Index(
                fields=["author_id", "issued_at"], name="idx_team_guidance_author"
            ),
        ),
        migrations.AddConstraint(
            model_name="teamguidancereceipt",
            constraint=models.UniqueConstraint(
                fields=("guidance", "recipient_staff_id"),
                name="uniq_team_guidance_recipient",
            ),
        ),
    ]
