# Generated by Django 5.2.4 on 2026-06-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_environment_activity_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedulecostline',
            name='catalogue_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='activityschedulecostline',
            name='catalogue_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityschedulecostline',
            name='currency',
            field=models.CharField(default='UGX', max_length=8),
        ),
        migrations.AddField(
            model_name='activityschedulecostline',
            name='line_item_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
