# Generated by Django 5.2.4 on 2026-06-29 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0003_activityschedulecostline_catalogue_id_and_more"),
        ("clusters", "0002_cluster_environment_cluster_source"),
        ("partners", "0002_partner_environment_partner_source"),
        ("projects", "0002_project_environment_project_source"),
        ("schools", "0006_alter_uploadbatch_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="fiscal_year",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="planned_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="week_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="week_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activityschedulecostline",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clusters.cluster",
            ),
        ),
        migrations.AddField(
            model_name="activityschedulecostline",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="activityschedulecostline",
            name="fiscal_year",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="activityschedulecostline",
            name="month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activityschedulecostline",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="partners.partner",
            ),
        ),
        migrations.AddField(
            model_name="activityschedulecostline",
            name="planned_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activityschedulecostline",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="activityschedulecostline",
            name="quarter",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="activityschedulecostline",
            name="responsible_role",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="activityschedulecostline",
            name="responsible_user",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="activityschedulecostline",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="activityschedulecostline",
            name="total_cost",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activityschedulecostline",
            name="week_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activityschedulecostline",
            name="week_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
