# Generated by Django 5.2.4 on 2026-07-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_activity_purpose_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='support_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='training_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='visit_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
