# Generated by Django 5.2.4 on 2026-07-02 13:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0006_activity_support_type_activity_training_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="attended_school_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=30),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
