# Generated by Django 5.2.4 on 2026-07-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ssa_collection_expected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='ssa_not_collected_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
