# Generated by Django 5.2.4 on 2026-07-03 00:57

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0009_activity_ssa_collection_expected_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_planned", "Not Planned"),
                    ("planned", "Planned"),
                    ("scheduled", "Scheduled"),
                    ("assigned_to_partner", "Assigned to Partner"),
                    ("partner_scheduled", "Partner Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completion_started", "Completion Started"),
                    ("evidence_uploaded", "Evidence Uploaded"),
                    ("evidence_accepted", "Evidence Accepted"),
                    ("salesforce_id_required", "Salesforce ID Required"),
                    ("submitted_to_pl", "Submitted to PL"),
                    ("returned_by_pl", "Returned by PL"),
                    ("awaiting_ia_verification", "Awaiting IA Verification"),
                    ("ia_verified", "IA Verified"),
                    ("accountant_confirmed", "Accountant Confirmed"),
                    ("completed", "Completed"),
                    ("returned", "Returned"),
                    ("returned_by_ia", "Returned by IA"),
                    ("closed", "Closed"),
                    ("rejected", "Rejected"),
                    ("rescheduled", "Rescheduled"),
                    ("cancelled", "Cancelled"),
                    ("deferred", "Deferred"),
                ],
                default="not_planned",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="DuplicateActivity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="potential", max_length=32)),
                ("reason", models.CharField(max_length=255)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_flags",
                        to="activities.activity",
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_sources",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "ia_duplicate_activity",
            },
        ),
        migrations.CreateModel(
            name="IAVerification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("verified_by", models.CharField(blank=True, max_length=30, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("returned", "Returned"),
                            ("flagged", "Flagged"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ia_verification",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "ia_verification",
            },
        ),
        migrations.CreateModel(
            name="ReturnedReason",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(max_length=128)),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returned_reasons",
                        to="activities.iaverification",
                    ),
                ),
            ],
            options={
                "db_table": "ia_returned_reason",
            },
        ),
        migrations.CreateModel(
            name="VerificationChecklist",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("evidence_exists", models.BooleanField(default=False)),
                ("attendance_valid", models.BooleanField(default=False)),
                ("ssa_uploaded", models.BooleanField(default=False)),
                ("correct_school", models.BooleanField(default=False)),
                ("correct_cluster", models.BooleanField(default=False)),
                ("correct_intervention", models.BooleanField(default=False)),
                ("sf_id_entered", models.BooleanField(default=False)),
                ("duplicate_check_passed", models.BooleanField(default=False)),
                ("analytics_ready", models.BooleanField(default=False)),
                (
                    "verification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist",
                        to="activities.iaverification",
                    ),
                ),
            ],
            options={
                "db_table": "ia_verification_checklist",
            },
        ),
        migrations.CreateModel(
            name="VerificationComment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.TextField()),
                ("created_by", models.CharField(max_length=30)),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="activities.iaverification",
                    ),
                ),
            ],
            options={
                "db_table": "ia_verification_comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationDecision",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("decision", models.CharField(max_length=16)),
                ("decided_by", models.CharField(max_length=30)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="activities.iaverification",
                    ),
                ),
            ],
            options={
                "db_table": "ia_verification_decision",
                "ordering": ["-decided_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("verified_by", models.CharField(max_length=30)),
                ("verified_at", models.DateTimeField()),
                ("analytics_included", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_history",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "ia_verification_history",
            },
        ),
    ]
