# Generated by Django 5.2.4 on 2026-07-03 01:40

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_alter_activity_status_duplicateactivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityClosure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.CharField(default='system', max_length=30)),
                ('status', models.CharField(default='closure_not_ready', max_length=32)),
                ('notes', models.TextField(blank=True, null=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure_details', to='activities.activity')),
            ],
            options={
                'db_table': 'activity_closure',
            },
        ),
        migrations.CreateModel(
            name='ActivityReopenRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('reopened_by', models.CharField(max_length=30)),
                ('reason', models.TextField()),
                ('category', models.CharField(max_length=64)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reopen_requests', to='activities.activity')),
            ],
            options={
                'db_table': 'activity_reopen_request',
            },
        ),
        migrations.CreateModel(
            name='ActivityTimelineEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=128)),
                ('actor_id', models.CharField(default='system', max_length=30)),
                ('actor_role', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='activities.activity')),
            ],
            options={
                'db_table': 'activity_timeline_event',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsPublishRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_publish_record', to='activities.activity')),
            ],
            options={
                'db_table': 'analytics_publish_record',
            },
        ),
        migrations.CreateModel(
            name='ClosureBlocker',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('blocking_reason', models.CharField(max_length=255)),
                ('responsible_role', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_blockers', to='activities.activity')),
            ],
            options={
                'db_table': 'closure_blocker',
            },
        ),
        migrations.CreateModel(
            name='ClosureChecklist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('activity_executed', models.BooleanField(default=False)),
                ('evidence_uploaded', models.BooleanField(default=False)),
                ('salesforce_id_entered', models.BooleanField(default=False)),
                ('ia_verified', models.BooleanField(default=False)),
                ('finance_required', models.BooleanField(default=False)),
                ('accounts_cleared', models.BooleanField(default=False)),
                ('netsuite_id_entered', models.BooleanField(default=False)),
                ('analytics_published', models.BooleanField(default=False)),
                ('audit_trail_saved', models.BooleanField(default=False)),
                ('last_evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure_checklist', to='activities.activity')),
            ],
            options={
                'db_table': 'closure_checklist',
            },
        ),
        migrations.CreateModel(
            name='CompletedActivitySnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('final_budget_amount', models.BigIntegerField(default=0)),
                ('disbursed_amount', models.BigIntegerField(default=0)),
                ('actual_spend_amount', models.BigIntegerField(default=0)),
                ('netsuite_expense_id', models.CharField(blank=True, max_length=128, null=True)),
                ('evidence_count', models.IntegerField(default=0)),
                ('snapshot_taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completed_snapshot', to='activities.activity')),
            ],
            options={
                'db_table': 'completed_activity_snapshot',
            },
        ),
    ]
