# Generated by Django 5.2.4 on 2026-07-08 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0014_alter_activity_focus_intervention_and_more"),
        ("clusters", "0002_cluster_environment_cluster_source"),
        ("daily_visit_batches", "0001_initial"),
        ("schools", "0011_alter_school_planning_readiness"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="daily_visit_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="daily_visit_batches.dailyvisitbatch",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["daily_visit_batch"], name="activity_daily_v_693c20_idx"
            ),
        ),
    ]
