# Generated by Django 5.2.4 on 2026-07-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0016_alter_activity_payment_status"),
        ("clusters", "0002_cluster_environment_cluster_source"),
        ("daily_visit_batches", "0001_initial"),
        ("schools", "0011_alter_school_planning_readiness"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["responsible_staff_id", "fy", "activity_type"],
                name="activity_respons_9b2972_idx",
            ),
        ),
    ]
