# Generated by Django 5.2.4 on 2026-07-15 15:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_alter_activity_focus_intervention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='focus_intervention',
            field=models.CharField(blank=True, choices=[('christlike_behaviour', 'Christlike Behaviour'), ('exposure_to_word_of_god', 'Exposure to the Word of God'), ('financial_health', 'Financial Health'), ('leadership', 'Leadership'), ('government_requirement', 'Government Requirements'), ('learning_environment', 'Learning Environment'), ('teaching_environment', "Teacher's Environment"), ('enrolment', 'Enrolment')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='purpose_intervention',
            field=models.CharField(blank=True, choices=[('christlike_behaviour', 'Christlike Behaviour'), ('exposure_to_word_of_god', 'Exposure to the Word of God'), ('financial_health', 'Financial Health'), ('leadership', 'Leadership'), ('government_requirement', 'Government Requirements'), ('learning_environment', 'Learning Environment'), ('teaching_environment', "Teacher's Environment"), ('enrolment', 'Enrolment')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='secondary_focus_interventions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('christlike_behaviour', 'Christlike Behaviour'), ('exposure_to_word_of_god', 'Exposure to the Word of God'), ('financial_health', 'Financial Health'), ('leadership', 'Leadership'), ('government_requirement', 'Government Requirements'), ('learning_environment', 'Learning Environment'), ('teaching_environment', "Teacher's Environment"), ('enrolment', 'Enrolment')], max_length=64), blank=True, default=list, size=None),
        ),
    ]
