# Generated by Django 5.2.4 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0021_activitysalesforcereference"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="expected_participants",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
