# Generated by Django 5.2.4 on 2026-07-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0023_alter_activity_activity_type"),
        ("clusters", "0003_repair_canonical_school_cluster_membership"),
        ("daily_visit_batches", "0001_initial"),
        ("schools", "0015_normalize_planning_readiness"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("salesforce_activity_id__isnull", False),
                    models.Q(("salesforce_activity_id", ""), _negated=True),
                    ("deleted_at__isnull", True),
                ),
                fields=("salesforce_activity_id",),
                name="uniq_activity_salesforce_id",
            ),
        ),
    ]
