# Generated by Django 5.2.16 on 2026-07-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0026_remove_activity_closed_activity_must_have_sf_id'),
        ('activity_catalogue', '0001_initial'),
        ('clusters', '0003_repair_canonical_school_cluster_membership'),
        ('daily_visit_batches', '0001_initial'),
        ('schools', '0015_normalize_planning_readiness'),
        ('ssa', '0006_alter_ssascore_intervention'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'closed'), _negated=True), ('salesforce_record_type_snapshot__in', ['NONE', 'SSA_DATA_GATHERING']), models.Q(('salesforce_activity_id__isnull', False), models.Q(('salesforce_activity_id', ''), _negated=True)), _connector='OR'), name='closed_activity_must_have_sf_id'),
        ),
    ]
