# Generated by Django 5.2.16 on 2026-07-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0027_activity_closed_activity_must_have_sf_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityschedulecostline",
            name="activity_catalogue_item_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="activityschedulecostline",
            name="activity_catalogue_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activityschedulecostline",
            name="costing_profile",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
