# Generated by Django 5.2.16 on 2026-07-30 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "activities",
            "0030_remove_activityschedulecostline_uniq_cost_component_per_activity_and_more",
        ),
        ("geography", "0003_populate_sub_regions"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="activity_context_type",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="activity",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="event_district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programme_activities",
                to="geography.district",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="planning_source",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="activity",
            name="support_rationale",
            field=models.CharField(blank=True, default="", max_length=48),
        ),
        migrations.AddField(
            model_name="activity",
            name="venue",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("school_visit", "School Visit"),
                    ("follow_up_visit", "Follow-up Visit"),
                    ("coaching_visit", "Coaching Visit"),
                    ("in_school_support", "In-school Support"),
                    ("donor_visit", "Donor Visit"),
                    ("story_gathering_visit", "Gathering Story"),
                    ("school_invitation", "School Invitation"),
                    ("social_visit", "Social Visit"),
                    ("training_follow_up_visit", "Training Follow-up Visit"),
                    ("in_school_coaching_visit", "In-school Coaching Visit"),
                    ("training", "Training"),
                    ("in_school_training", "In-school Training"),
                    ("school_improvement_training", "School Improvement Training"),
                    ("cluster_meeting", "Cluster Meeting"),
                    ("cluster_training", "Cluster Training"),
                    ("ssa_activity", "SSA Activity"),
                    ("project_activity", "Project Activity"),
                    ("partner_activity", "Partner Activity"),
                    ("core_visit", "Core Visit"),
                    ("core_training", "Core Training"),
                    ("baseline_ssa_visit", "SSA Visit"),
                    ("school_visit_ssa_collection", "School Visit + SSA Collection"),
                    (
                        "cluster_training_ssa_collection",
                        "Cluster Training + SSA Collection",
                    ),
                    ("cluster_meeting_ssa_review", "Cluster Meeting + SSA Review"),
                    ("partner_ssa_collection", "Partner SSA Collection"),
                    ("core_assessment_visit", "Core Assessment Visit"),
                    ("programme_event", "Programme Event"),
                ],
                max_length=48,
            ),
        ),
    ]
