# Generated by Django 5.2.16 on 2026-08-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0034_expand_programme_budget_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="cluster_school_count_snapshot",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="participants_per_school",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
