# Generated by Django 5.2.16 on 2026-08-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0037_backfill_executor_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="schools_invited",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
