# Generated by Django 5.2.16 on 2026-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0039_cluster_participant_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="est_cost_cents",
            field=models.BigIntegerField(default=0),
        ),
    ]
