# Generated by Django 5.2.16 on 2026-08-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0040_alter_activity_est_cost_cents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("school_visit", "School Visit"),
                    ("follow_up_visit", "Follow-up Visit"),
                    ("coaching_visit", "Coaching Visit"),
                    ("in_school_support", "In-school Support"),
                    ("donor_visit", "Donor Visit"),
                    ("story_gathering_visit", "Gathering Story"),
                    ("school_invitation", "School Invitation"),
                    ("social_visit", "Social Visit"),
                    ("training_follow_up_visit", "Training Follow-up Visit"),
                    ("in_school_coaching_visit", "In-school Coaching Visit"),
                    ("training", "Training"),
                    ("in_school_training", "In-school Training"),
                    ("school_improvement_training", "School Improvement Training"),
                    ("cluster_meeting", "Cluster Meeting"),
                    ("cluster_training", "Cluster Training"),
                    ("ssa_activity", "SSA Activity"),
                    ("project_activity", "Project Activity"),
                    ("partner_activity", "Partner Activity"),
                    ("core_visit", "Core Visit"),
                    ("core_training", "Core Training"),
                    ("baseline_ssa_visit", "SSA Visit"),
                    ("school_visit_ssa_collection", "School Visit + SSA Collection"),
                    (
                        "cluster_training_ssa_collection",
                        "Cluster Training + SSA Collection",
                    ),
                    ("cluster_meeting_ssa_review", "Cluster Meeting + SSA Review"),
                    ("partner_ssa_collection", "Partner SSA Collection"),
                    ("core_assessment_visit", "Core Assessment Visit"),
                    ("programme_event", "Programme Event"),
                    ("field_event", "Field Event"),
                ],
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="programme_activity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("edtech_for_schools", "EdTech for Schools"),
                    ("school_leadership_training", "School Leadership Training"),
                    ("student_activities", "Student Activities"),
                    ("teacher_training", "Teacher Training"),
                    ("alumni", "Alumni"),
                    ("training", "Training"),
                    ("school_visit", "School Visit"),
                    ("field_event", "Field Event"),
                    ("youth_camp", "Youth Camp"),
                    ("admin", "Admin"),
                    ("programme_event", "Programme Event"),
                ],
                max_length=48,
                null=True,
            ),
        ),
    ]
