# Generated by Django 5.2.16 on 2026-08-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0041_alter_activity_activity_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityschedulecostline",
            name="vendor_paid",
            field=models.BooleanField(default=False),
        ),
    ]
