# Generated by Django 5.2.16 on 2026-08-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0042_activityschedulecostline_vendor_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="actual_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="actual_observations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="actual_outcome",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="execution_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="follow_up_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
