# Generated by Django 5.2.17 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0045_activity_ssa_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="delivery_contact_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
