# Generated by Django 5.2.17 on 2026-09-07 18:40

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0051_verification_sample"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolVisitFeedback",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("finding", models.TextField()),
                ("improvements", models.JSONField(default=list)),
                ("recorded_by", models.CharField(max_length=30)),
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="school_visit_feedback",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "school_visit_feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
