# Generated by Django 5.2.17 on 2026-09-13 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0053_activity_ssa_alignment"),
        ("ssa", "0008_ssarecommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationsample",
            name="method",
            field=models.CharField(
                choices=[
                    ("desk", "Desk re-check of the record"),
                    ("field", "Field back-check visit"),
                ],
                default="desk",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="verificationsample",
            name="ssa_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_samples",
                to="ssa.ssarecord",
            ),
        ),
        migrations.AddField(
            model_name="verificationsample",
            name="subject_type",
            field=models.CharField(
                choices=[
                    ("activity", "Verified activity"),
                    ("ssa_record", "Confirmed SSA"),
                ],
                default="activity",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="verificationsample",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_samples",
                to="activities.activity",
            ),
        ),
    ]
