# Generated by Django 5.2.17 on 2026-09-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0054_verification_sample_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="ssa_deviation_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="activity",
            name="ssa_alignment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("priority", "Targets an SSA priority"),
                    (
                        "off_priority",
                        "Targets an intervention the SSA does not prioritise",
                    ),
                    ("no_focus", "Names no SSA intervention"),
                    ("no_ssa", "No verified SSA to inform it"),
                    ("stale_ssa", "The verified SSA is out of date"),
                    ("ssa_collection", "Collects the SSA"),
                    ("not_applicable", "Not school-improvement work"),
                ],
                default="",
                max_length=24,
            ),
        ),
    ]
