# Generated by Django 5.2.17 on 2026-09-28 19:49

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0061_move_in_school_training_cost_to_visit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityScheduleChange",
            fields=[
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("rescheduled", "Rescheduled"),
                            ("cancelled", "Cancelled"),
                            ("restored", "Restored"),
                        ],
                        max_length=16,
                    ),
                ),
                ("from_day", models.DateField(blank=True, null=True)),
                ("to_day", models.DateField(blank=True, null=True)),
                (
                    "from_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("to_status", models.CharField(blank=True, default="", max_length=32)),
                ("reason", models.CharField(blank=True, default="", max_length=512)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_changes",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "db_table": "activity_schedule_change",
                "indexes": [
                    models.Index(
                        fields=["activity", "changed_at"],
                        name="idx_sched_change_activity",
                    ),
                    models.Index(fields=["changed_at"], name="idx_sched_change_at"),
                    models.Index(fields=["from_day"], name="idx_sched_change_from"),
                    models.Index(fields=["to_day"], name="idx_sched_change_to"),
                ],
            },
        ),
    ]
