# Generated by Django 5.2.17 on 2026-10-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0063_link_training_interventions"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="partner_date_set_by",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
    ]
