# Generated by Django 5.2.17 on 2026-10-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0064_partner_date_set_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="meeting_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("training", "Training"),
                    ("only_meeting", "Only Meeting"),
                    ("cluster_leaders", "Cluster Leaders Meeting"),
                ],
                default="",
                max_length=24,
            ),
        ),
    ]
