# Generated by Django 5.2.4 on 2026-06-26 23:03

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreCandidateVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('school_id', models.CharField(max_length=64, unique=True)),
                ('ssa_record_id', models.CharField(max_length=30)),
                ('verification_id', models.CharField(max_length=64)),
                ('verified_by_id', models.CharField(max_length=30)),
                ('verified_by_name', models.CharField(max_length=255)),
                ('verified_at', models.DateTimeField()),
                ('status', models.CharField(max_length=64)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_candidate_verification',
            },
        ),
        migrations.CreateModel(
            name='CorePlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('school_id', models.CharField(max_length=64, unique=True)),
                ('fy', models.CharField(max_length=16)),
                ('status', models.CharField(default='Active', max_length=32)),
                ('visits_target', models.IntegerField(default=4)),
                ('trainings_target', models.IntegerField(default=4)),
                ('visits_completed', models.IntegerField(default=0)),
                ('trainings_completed', models.IntegerField(default=0)),
                ('baseline_average', models.FloatField(blank=True, null=True)),
                ('follow_up_average', models.FloatField(blank=True, null=True)),
                ('baseline_ssa_record_id', models.CharField(blank=True, max_length=30, null=True)),
                ('follow_up_ssa_record_id', models.CharField(blank=True, max_length=30, null=True)),
                ('follow_up_scheduled_for', models.CharField(blank=True, max_length=32, null=True)),
                ('follow_up_assignee', models.CharField(blank=True, max_length=30, null=True)),
                ('interventions', models.JSONField(blank=True, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'core_plan',
                'indexes': [models.Index(fields=['status'], name='core_plan_status_75d34d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoreSchoolOnboarding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('school_id', models.CharField(max_length=64, unique=True)),
                ('fy', models.CharField(max_length=16)),
                ('previous_school_type', models.CharField(max_length=32)),
                ('baseline_ssa_record_id', models.CharField(max_length=30)),
                ('baseline_average_score', models.FloatField()),
                ('onboarded_by_id', models.CharField(max_length=30)),
                ('onboarded_by_name', models.CharField(max_length=255)),
                ('onboarded_at', models.DateTimeField()),
                ('onboarding_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Onboarded', max_length=32)),
                ('core_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='core_schools.coreplan')),
            ],
            options={
                'db_table': 'core_school_onboarding',
            },
        ),
        migrations.CreateModel(
            name='CoreSchoolProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('school_id', models.CharField(max_length=64, unique=True)),
                ('core_start_fy', models.CharField(max_length=16)),
                ('champion_status', models.CharField(default='Not Eligible', max_length=32)),
                ('status', models.CharField(default='Active', max_length=32)),
                ('core_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core_schools.coreplan')),
            ],
            options={
                'db_table': 'core_school_profile',
            },
        ),
        migrations.CreateModel(
            name='CoreActivitySlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('school_id', models.CharField(max_length=64)),
                ('intervention', models.CharField(max_length=64)),
                ('activity_type', models.CharField(max_length=16)),
                ('sequence_number', models.IntegerField()),
                ('status', models.CharField(default='Planned', max_length=32)),
                ('owner', models.CharField(default='unassigned', max_length=16)),
                ('assigned_staff_id', models.CharField(blank=True, max_length=30, null=True)),
                ('assigned_staff_name', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_partner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('assigned_partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_month', models.CharField(blank=True, max_length=16, null=True)),
                ('scheduled_week', models.IntegerField(blank=True, null=True)),
                ('scheduled_for', models.CharField(blank=True, max_length=32, null=True)),
                ('salesforce_id', models.CharField(blank=True, max_length=128, null=True)),
                ('activity_id', models.CharField(blank=True, max_length=30, null=True)),
                ('evidence_uri', models.CharField(blank=True, max_length=512, null=True)),
                ('evidence_notes', models.TextField(blank=True, null=True)),
                ('pl_verification_status', models.CharField(blank=True, max_length=16, null=True)),
                ('ia_verification_status', models.CharField(blank=True, max_length=16, null=True)),
                ('accountant_status', models.CharField(blank=True, max_length=16, null=True)),
                ('teachers', models.IntegerField(blank=True, null=True)),
                ('leaders', models.IntegerField(blank=True, null=True)),
                ('participants', models.IntegerField(blank=True, null=True)),
                ('returned_reason', models.CharField(blank=True, max_length=512, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('core_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core_schools.coreplan')),
            ],
            options={
                'db_table': 'core_activity_slot',
                'indexes': [models.Index(fields=['core_plan'], name='core_activi_core_pl_e3f0db_idx'), models.Index(fields=['school_id'], name='core_activi_school__1014ee_idx')],
            },
        ),
    ]
