"use client";

import { Calendar, MapPin } from "lucide-react";
import { PageHeader, type PageHeaderFilter } from "@/components/ui/PageHeader";
import { directorHeader } from "@/lib/director-mock";

// Shared page header for director / leadership surfaces (RVP country
// summary, leaderboard, weekly debrief reports).
//
// Now a thin adapter around the canonical <PageHeader>: title,
// subtitle, the three Director filter pills (Financial Year · Month ·
// Country/Region), and the global search. Breadcrumbs are auto-
// generated by PageHeader from the URL, so callers no longer pass a
// `breadcrumb` array — pass `breadcrumbTrailingLabel` if the final
// crumb needs a richer label (e.g. a specific report name).
//
// Bell + avatar + ⌘K trigger all come for free from PageHeader.
export function ExecutiveHeader({
  title = directorHeader.title,
  subtitle = directorHeader.subtitle,
  breadcrumbTrailingLabel,
  breadcrumb: _legacyBreadcrumb,
}: {
  title?:    string;
  subtitle?: string;
  /** Final breadcrumb override — set when the trailing crumb should
   *  read as the entity name rather than the generic route label. */
  breadcrumbTrailingLabel?: string;
  /** @deprecated — breadcrumbs are now auto-generated by PageHeader
   *  from the URL via the route-titles map. Pass `breadcrumbTrailingLabel`
   *  instead. Kept on the type to avoid breaking existing callers
   *  during the migration. */
  breadcrumb?: readonly string[];
} = {}) {
  void _legacyBreadcrumb;
  const filters: PageHeaderFilter[] = [
    { Icon: Calendar, label: directorHeader.filters.financialYear },
    { Icon: Calendar, label: directorHeader.filters.month },
    { Icon: MapPin,   label: directorHeader.filters.countryRegion },
  ];

  return (
    <PageHeader
      title={title}
      subtitle={subtitle}
      filters={filters}
      searchPlaceholder={directorHeader.searchPlaceholder}
      breadcrumbTrailingLabel={breadcrumbTrailingLabel}
    />
  );
}
