# Generated by Django 5.2.4 on 2026-06-26 21:50

import apps.core.cuid
import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostSetting",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=128, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("unit_cost", models.FloatField()),
                ("fy", models.CharField(blank=True, max_length=16, null=True)),
                ("version", models.IntegerField(default=1)),
                ("created_by", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "cost_setting",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyFundRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fy", models.CharField(max_length=16)),
                ("month", models.IntegerField()),
                ("staff_id", models.CharField(blank=True, max_length=30, null=True)),
                ("amount", models.FloatField()),
                ("status", models.CharField(default="submitted", max_length=32)),
            ],
            options={
                "db_table": "monthly_fund_request",
            },
        ),
        migrations.CreateModel(
            name="CostSettingHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("label", models.CharField(max_length=255)),
                ("old_unit_cost", models.FloatField(blank=True, null=True)),
                ("new_unit_cost", models.FloatField()),
                ("version", models.IntegerField()),
                ("fy", models.CharField(blank=True, max_length=16, null=True)),
                ("changed_by_user_id", models.CharField(max_length=30)),
                ("reason", models.CharField(blank=True, max_length=512, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cost_setting_history",
                "indexes": [
                    models.Index(fields=["key"], name="cost_settin_key_466339_idx"),
                    models.Index(
                        fields=["changed_at"], name="cost_settin_changed_5b0814_idx"
                    ),
                ],
            },
        ),
    ]
