# Generated by Django 5.2.4 on 2026-07-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0003_costcatalogue_costsetting_catalogue"),
    ]

    operations = [
        migrations.AddField(
            model_name="costcatalogue",
            name="required_school_visits_per_day",
            field=models.IntegerField(default=5),
        ),
    ]
