# Generated by Django 5.2.4 on 2026-07-17 09:17

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_activitysalesforcereference'),
        ('budget', '0005_seed_daily_visit_batch_cost_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAmendment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', apps.core.models.CuidField(default=apps.core.cuid.cuid, max_length=30, primary_key=True, serialize=False)),
                ('original_date', models.DateField(blank=True, null=True)),
                ('new_date', models.DateField()),
                ('original_amount', models.BigIntegerField(default=0)),
                ('original_fy', models.CharField(blank=True, max_length=16, null=True)),
                ('original_quarter', models.CharField(blank=True, max_length=8, null=True)),
                ('new_fy', models.CharField(blank=True, max_length=16, null=True)),
                ('new_quarter', models.CharField(blank=True, max_length=8, null=True)),
                ('reason', models.TextField()),
                ('requested_by', models.CharField(max_length=30)),
                ('reviewed_by', models.CharField(blank=True, max_length=30, null=True)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('returned', 'Returned'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='submitted', max_length=16)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_amendments', to='activities.activity')),
            ],
            options={
                'db_table': 'budget_amendment',
                'ordering': ['-created_at'],
            },
        ),
    ]
