# Generated by Django 5.2.17 on 2026-08-27 16:27

import apps.core.cuid
import apps.core.models
import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def classify_existing_costs(apps, schema_editor):
    """Preserve legacy money as operational history; never invent reference rates."""
    CostCatalogue = apps.get_model("budget", "CostCatalogue")
    ActivityCostSnapshot = apps.get_model("budget", "ActivityCostSnapshot")
    Activity = apps.get_model("activities", "Activity")
    ActivityScheduleCostLine = apps.get_model("activities", "ActivityScheduleCostLine")

    CostCatalogue.objects.all().update(
        kind="operational",
        status="published",
        currency="UGX",
        published_at=timezone.now(),
    )
    for country, fy in CostCatalogue.objects.values_list("country", "fy").distinct():
        CostCatalogue.objects.get_or_create(
            country=country,
            fy=fy,
            kind="reference",
            version=0,
            defaults={
                "status": "draft",
                "is_active": False,
                "currency": "UGX",
                "label": "Internal Reference Rate Card — Configuration Required",
                "notes": "Reference rates were not present in the legacy system and were not fabricated during migration.",
            },
        )

    line_rows = (
        ActivityScheduleCostLine.objects.values("activity_id", "catalogue_id")
        .annotate(total=models.Sum("amount"))
        .order_by()
    )
    totals = {}
    cards = {}
    for row in line_rows.iterator():
        activity_id = row["activity_id"]
        totals[activity_id] = totals.get(activity_id, 0) + int(row["total"] or 0)
        if row["catalogue_id"]:
            cards.setdefault(activity_id, row["catalogue_id"])

    known_cards = {
        str(card.id): card for card in CostCatalogue.objects.filter(kind="operational")
    }
    snapshots = []
    for activity in Activity.objects.all().iterator():
        operational_cost = totals.get(activity.id, int(activity.est_cost_cents or 0))
        if operational_cost == 0 and activity.id not in totals:
            continue
        planned_date = activity.planned_date
        snapshots.append(
            ActivityCostSnapshot(
                activity_id=activity.id,
                sequence=1,
                is_current=True,
                activity_catalogue_item_id=activity.catalogue_item_id,
                activity_catalogue_version=activity.catalogue_version,
                costing_profile_version=activity.costing_profile_snapshot,
                operational_rate_card=known_cards.get(str(cards.get(activity.id))),
                reference_rate_card=None,
                reference_cost=None,
                operational_cost=operational_cost,
                calculation_inputs={
                    "source": "legacy_operational_cost_backfill",
                    "activityType": activity.activity_type,
                    "deliveryType": activity.delivery_type,
                    "plannedDate": planned_date.isoformat() if planned_date else None,
                    "expectedParticipants": activity.expected_participants,
                    "schoolsInvited": activity.schools_invited,
                },
                reference_breakdown=[],
                operational_breakdown=[],
                warnings=["Historical reference cost unavailable."],
                missing_configuration={"reference": ["historical_rate_card"]},
                calculated_at=activity.created_at or timezone.now(),
                recalculation_reason="Legacy operational cost preserved during dual-rate-card migration.",
            )
        )
    ActivityCostSnapshot.objects.bulk_create(snapshots, batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0049_activity_training_course_and_paired_visit"),
        (
            "budget",
            "0009_budgetamendment_budget_amendment_original_amount_non_negative_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityCostReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("route_conditions_changed", "Route conditions changed"),
                            ("transport_rate_changed", "Transport rate changed"),
                            ("accommodation_needed", "Accommodation became necessary"),
                            ("participant_count_changed", "Participant count changed"),
                            ("venue_cost_changed", "Venue cost changed"),
                            (
                                "school_location_inaccurate",
                                "School location is inaccurate",
                            ),
                            (
                                "cost_component_missing",
                                "Required cost component is missing",
                            ),
                            ("other", "Other"),
                        ],
                        max_length=48,
                    ),
                ),
                ("explanation", models.TextField()),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("proposed_inputs", models.JSONField(blank=True, default=dict)),
                ("current_operational_cost", models.BigIntegerField(default=0)),
                (
                    "proposed_operational_cost",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("status", models.CharField(default="submitted", max_length=24)),
                ("requested_by", models.CharField(max_length=30)),
                ("reviewed_by", models.CharField(blank=True, max_length=30, null=True)),
                ("review_note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "activity_cost_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityCostSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "activity_catalogue_item_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "activity_catalogue_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "costing_profile_version",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("reference_cost", models.BigIntegerField(blank=True, null=True)),
                ("operational_cost", models.BigIntegerField(default=0)),
                (
                    "approved_operating_limit",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("amount_disbursed", models.BigIntegerField(default=0)),
                ("actual_accounted_spend", models.BigIntegerField(default=0)),
                ("unused_balance", models.BigIntegerField(default=0)),
                ("reimbursement_amount", models.BigIntegerField(default=0)),
                ("calculation_inputs", models.JSONField(default=dict)),
                ("reference_breakdown", models.JSONField(default=list)),
                ("operational_breakdown", models.JSONField(default=list)),
                ("warnings", models.JSONField(default=list)),
                ("missing_configuration", models.JSONField(default=list)),
                ("calculated_at", models.DateTimeField()),
                (
                    "calculated_by",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "recalculation_reason",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("approved_by", models.CharField(blank=True, max_length=30, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cost_status",
                    models.CharField(
                        choices=[
                            ("estimated", "Estimated Operational Cost"),
                            ("approved", "Approved Operating Limit"),
                            ("amendment_required", "Cost Amendment Required"),
                            ("disbursed", "Disbursed"),
                            ("accounted", "Accounted"),
                            ("closed", "Closed"),
                        ],
                        default="estimated",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "db_table": "activity_cost_snapshot",
                "ordering": ["-sequence"],
            },
        ),
        migrations.CreateModel(
            name="CountryStrategicActivityReserve",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country", models.CharField(default="Uganda", max_length=64)),
                ("fy", models.CharField(max_length=16)),
                ("period_key", models.CharField(blank=True, default="", max_length=16)),
                ("opening_reserve", models.BigIntegerField(default=0)),
                ("approved_additions", models.BigIntegerField(default=0)),
                ("cleared_savings_transferred", models.BigIntegerField(default=0)),
                ("amount_committed", models.BigIntegerField(default=0)),
                ("amount_disbursed", models.BigIntegerField(default=0)),
                ("amount_returned", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("approved_by", models.CharField(blank=True, max_length=30, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "country_strategic_activity_reserve",
            },
        ),
        migrations.CreateModel(
            name="StrategicReserveActivation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason_normal_funding_insufficient", models.TextField()),
                ("operational_cost", models.BigIntegerField(default=0)),
                ("requested_amount", models.BigIntegerField()),
                ("expected_outcome", models.TextField()),
                ("required_implementation_date", models.DateField()),
                ("alternative_considered", models.TextField()),
                ("balance_before", models.BigIntegerField(default=0)),
                ("balance_after", models.BigIntegerField(default=0)),
                ("requested_by", models.CharField(max_length=30)),
                (
                    "cd_approved_by",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "rvp_approved_by",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("awaiting_cd", "Awaiting CD Review"),
                            ("awaiting_rvp", "Awaiting RVP Approval"),
                            ("approved", "Approved"),
                            ("disbursement_pending", "Disbursement Pending"),
                            ("disbursed", "Disbursed"),
                            ("accounted", "Accounted"),
                            ("returned", "Returned"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Canceled"),
                        ],
                        default="suggested",
                        max_length=24,
                    ),
                ),
            ],
            options={
                "db_table": "strategic_reserve_activation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="costcatalogue",
            name="uniq_active_catalogue_per_country_fy",
        ),
        migrations.RemoveConstraint(
            model_name="costcatalogue",
            name="uniq_catalogue_country_fy_version",
        ),
        migrations.AddField(
            model_name="costcatalogue",
            name="approved_by",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="costcatalogue",
            name="created_by",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="costcatalogue",
            name="currency",
            field=models.CharField(default="UGX", max_length=8),
        ),
        migrations.AddField(
            model_name="costcatalogue",
            name="effective_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="costcatalogue",
            name="effective_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="costcatalogue",
            name="is_provisional",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="costcatalogue",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reference", "Internal Reference"),
                    ("operational", "Country Approved Operational"),
                ],
                default="operational",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="costcatalogue",
            name="material_difference_threshold_bps",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Approved warning threshold in basis points; null means not configured.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costcatalogue",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="costcatalogue",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="costcatalogue",
            name="reviewed_by",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="costcatalogue",
            name="source_note",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="costcatalogue",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("under_review", "Under Review"),
                    ("published", "Published"),
                    ("superseded", "Superseded"),
                    ("retired", "Retired"),
                ],
                default="published",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="costcatalogue",
            name="superseded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="costsetting",
            name="approved_minimum",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="costsetting",
            name="costing_profile_scope",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="costsetting",
            name="geographic_scope",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="costsetting",
            name="unit",
            field=models.CharField(default="unit", max_length=64),
        ),
        migrations.AlterField(
            model_name="costsetting",
            name="key",
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name="costcatalogue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("country", "fy", "kind", "is_active"),
                name="uniq_active_catalogue_per_country_fy",
            ),
        ),
        migrations.AddConstraint(
            model_name="costcatalogue",
            constraint=models.UniqueConstraint(
                fields=("country", "fy", "kind", "version"),
                name="uniq_catalogue_country_fy_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="costcatalogue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_from__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="rate_card_effective_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="costcatalogue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("country", "Uganda"), _negated=True),
                    ("currency", "UGX"),
                    _connector="OR",
                ),
                name="uganda_rate_card_currency_ugx",
            ),
        ),
        migrations.AddConstraint(
            model_name="costsetting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_minimum__isnull", True),
                    ("approved_minimum__gte", 0),
                    _connector="OR",
                ),
                name="cost_setting_approved_minimum_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="costsetting",
            constraint=models.UniqueConstraint(
                fields=("catalogue", "key"), name="uniq_rate_card_component"
            ),
        ),
        migrations.AddField(
            model_name="activitycostreview",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_reviews",
                to="activities.activity",
            ),
        ),
        migrations.AddField(
            model_name="activitycostsnapshot",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_snapshots",
                to="activities.activity",
            ),
        ),
        migrations.AddField(
            model_name="activitycostsnapshot",
            name="operational_rate_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operational_activity_snapshots",
                to="budget.costcatalogue",
            ),
        ),
        migrations.AddField(
            model_name="activitycostsnapshot",
            name="reference_rate_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reference_activity_snapshots",
                to="budget.costcatalogue",
            ),
        ),
        migrations.AddField(
            model_name="activitycostsnapshot",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="budget.activitycostsnapshot",
            ),
        ),
        migrations.AddField(
            model_name="activitycostreview",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="budget.activitycostsnapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="countrystrategicactivityreserve",
            constraint=models.UniqueConstraint(
                fields=("country", "fy", "period_key"),
                name="uniq_country_strategic_reserve_period",
            ),
        ),
        migrations.AddField(
            model_name="strategicreserveactivation",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reserve_activations",
                to="activities.activity",
            ),
        ),
        migrations.AddField(
            model_name="strategicreserveactivation",
            name="reserve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activations",
                to="budget.countrystrategicactivityreserve",
            ),
        ),
        migrations.RunPython(classify_existing_costs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="activitycostsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("activity",),
                name="uniq_current_activity_cost_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitycostsnapshot",
            constraint=models.UniqueConstraint(
                fields=("activity", "sequence"),
                name="uniq_activity_cost_snapshot_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitycostsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reference_cost__isnull", True),
                    ("reference_cost__gte", 0),
                    _connector="OR",
                ),
                name="activity_reference_cost_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitycostsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("operational_cost__gte", 0)),
                name="activity_operational_cost_non_negative",
            ),
        ),
    ]
