# Generated by Django 5.2.17 on 2026-08-27 16:57

from django.db import migrations, models
from django.db.models import Sum


def backfill_snapshot_finance_state(apps, schema_editor):
    """Project the existing advance ledger without changing its source rows."""
    Snapshot = apps.get_model("budget", "ActivityCostSnapshot")
    Advance = apps.get_model("fund_requests", "AdvanceRequest")
    updates = []
    for snapshot in Snapshot.objects.filter(is_current=True).iterator(chunk_size=500):
        advances = Advance.objects.filter(activity_id=snapshot.activity_id)
        totals = advances.aggregate(
            disbursed=Sum("disbursed_amount"),
            actual=Sum("accounted_amount"),
            reimbursed=Sum("reimbursed_amount"),
        )
        disbursed = int(totals["disbursed"] or 0)
        actual = int(totals["actual"] or 0)
        snapshot.amount_disbursed = disbursed
        snapshot.actual_accounted_spend = actual
        snapshot.unused_balance = max(0, disbursed - actual)
        snapshot.reimbursement_amount = int(totals["reimbursed"] or 0)
        if actual:
            snapshot.cost_status = "accounted"
        elif disbursed:
            snapshot.cost_status = "disbursed"
        elif advances.exclude(confirmed_at__isnull=True).exists():
            snapshot.approved_operating_limit = snapshot.operational_cost
            snapshot.cost_status = "approved"
        updates.append(snapshot)
    if updates:
        Snapshot.objects.bulk_update(
            updates,
            [
                "amount_disbursed",
                "actual_accounted_spend",
                "unused_balance",
                "reimbursement_amount",
                "approved_operating_limit",
                "cost_status",
            ],
            batch_size=500,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0049_activity_training_course_and_paired_visit"),
        ("budget", "0010_activitycostreview_activitycostsnapshot_and_more"),
        (
            "fund_requests",
            "0016_advancerequest_advance_request_amount_non_negative_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            backfill_snapshot_finance_state, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="activitycostreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_operational_cost__gte", 0)),
                name="cost_review_current_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitycostreview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("proposed_operational_cost__isnull", True),
                    ("proposed_operational_cost__gte", 0),
                    _connector="OR",
                ),
                name="cost_review_proposed_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitycostsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_operating_limit__isnull", True),
                    ("approved_operating_limit__gte", 0),
                    _connector="OR",
                ),
                name="activity_approved_limit_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitycostsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount_disbursed__gte", 0),
                    ("actual_accounted_spend__gte", 0),
                    ("unused_balance__gte", 0),
                    ("reimbursement_amount__gte", 0),
                ),
                name="activity_cost_ledger_amounts_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="countrystrategicactivityreserve",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("opening_reserve__gte", 0),
                    ("approved_additions__gte", 0),
                    ("cleared_savings_transferred__gte", 0),
                    ("amount_committed__gte", 0),
                    ("amount_disbursed__gte", 0),
                    ("amount_returned__gte", 0),
                ),
                name="strategic_reserve_amounts_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="strategicreserveactivation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("operational_cost__gte", 0),
                    ("requested_amount__gt", 0),
                    ("balance_before__gte", 0),
                    ("balance_after__gte", 0),
                ),
                name="reserve_activation_amounts_valid",
            ),
        ),
    ]
