# Generated by Django 5.2.17 on 2026-08-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "budget",
            "0011_activitycostreview_cost_review_current_amount_non_negative_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="costcatalogue",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reference", "Regional Standard Funding"),
                    ("operational", "Country Operational"),
                ],
                default="operational",
                max_length=16,
            ),
        ),
    ]
