# Generated by Django 5.2.4 on 2026-07-13 23:18

import apps.core.cuid
import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduledJobLock",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_name",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, default="", max_length=128)),
            ],
            options={
                "db_table": "scheduled_job_lock",
            },
        ),
        migrations.CreateModel(
            name="ScheduledJobExecution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    apps.core.models.CuidField(
                        default=apps.core.cuid.cuid,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_name", models.CharField(db_index=True, max_length=64)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("records_processed", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("runner", models.CharField(blank=True, default="", max_length=128)),
            ],
            options={
                "db_table": "scheduled_job_execution",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["job_name", "-started_at"],
                        name="scheduled_j_job_nam_0e490c_idx",
                    ),
                    models.Index(
                        fields=["status", "-started_at"],
                        name="scheduled_j_status_44326d_idx",
                    ),
                ],
            },
        ),
    ]
