import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { MonthlyWorkPlanBudgetStatus } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import { AuditService } from '../../common/audit/audit.service';
import { AuthUser } from '../../common/auth/auth-user';
import { ScopeService } from '../../common/scope/scope.service';

// ─────────────────── Monthly Work Plan Budget service ────────────────────
//
// CD-facing CRUD on the monthly envelope generated by the 25th cron:
//
//   • list / getOne          — CD dashboard reads
//   • addAdminLine           — CD adds rent, airtime, internet, etc.
//   • removeAdminLine        — CD revisions (status flips to "revised")
//   • submitToRvp            — locks the envelope, notifies RVP
//   • rvpReview              — RVP approves / returns
//   • markSentToAccountant   — CD releases an RVP-approved envelope
//
// All transitions are guarded so the workflow can't move backwards (e.g.
// can't add admin lines after submission, can't disburse before approval).

const ADMIN_CATEGORIES = new Set([
  'rent', 'airtime', 'internet', 'utilities', 'printing', 'stationery',
  'office_supplies', 'communication', 'bank_charges', 'other',
]);

@Injectable()
export class MonthlyWorkPlanService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService,
    private readonly scope: ScopeService,
  ) {}

  async list(user: AuthUser, opts: { fy?: string } = {}) {
    const sc = await this.scope.resolveUserScope(user);
    if (!sc.countryScope && !sc.canViewSummaryOnly) {
      throw new ForbiddenException('Monthly Work Plan Budget is country-scope (CD/RVP/Accountant).');
    }
    return this.prisma.monthlyWorkPlanBudget.findMany({
      where: opts.fy ? { fy: opts.fy } : {},
      orderBy: { monthKey: 'desc' }, take: 24,
      include: { _count: { select: { programItems: true, adminLines: true } } },
    });
  }

  async getOne(user: AuthUser, id: string) {
    const sc = await this.scope.resolveUserScope(user);
    if (!sc.countryScope && !sc.canViewSummaryOnly) throw new ForbiddenException();
    const row = await this.prisma.monthlyWorkPlanBudget.findUnique({
      where: { id },
      include: {
        programItems: { take: 500 },
        adminLines: { where: { status: 'active' } },
      },
    });
    if (!row) throw new NotFoundException();
    return row;
  }

  async addAdminLine(user: AuthUser, id: string, dto: {
    costCategory: string; description: string; quantity?: number; unitCost: number; justification?: string;
  }) {
    if (!ADMIN_CATEGORIES.has(dto.costCategory)) {
      throw new BadRequestException(`Unknown admin category: ${dto.costCategory}`);
    }
    if (!dto.description?.trim()) throw new BadRequestException('Description is required.');
    if (!Number.isFinite(dto.unitCost) || dto.unitCost <= 0) {
      throw new BadRequestException('unitCost must be > 0.');
    }
    const envelope = await this.assertEnvelopeMutable(id);
    const qty = dto.quantity ?? 1;
    const total = qty * dto.unitCost;
    const line = await this.prisma.adminBudgetLine.create({
      data: {
        monthlyBudgetId: id,
        costCategory: dto.costCategory,
        description: dto.description.trim(),
        quantity: qty,
        unitCost: dto.unitCost,
        totalCost: total,
        justification: dto.justification?.trim() || null,
        createdByUserId: user.userId,
      },
    });
    await this.recomputeTotals(id);
    // Mark transition: any draft envelope flips to "admin_plan_added" once
    // the first admin line is appended so the CD dashboard can show that
    // step in the flow.
    if (envelope.status === MonthlyWorkPlanBudgetStatus.draft_generated || envelope.status === MonthlyWorkPlanBudgetStatus.cd_review) {
      await this.prisma.monthlyWorkPlanBudget.update({
        where: { id }, data: { status: MonthlyWorkPlanBudgetStatus.admin_plan_added },
      });
    }
    await this.audit.log({
      action: 'monthlyWorkPlanBudget.addAdminLine',
      subjectKind: 'MonthlyWorkPlanBudget', subjectId: id,
      actorId: user.userId, actorRole: user.activeRole,
      payload: { lineId: line.id, category: line.costCategory, totalCost: total },
    });
    return line;
  }

  async removeAdminLine(user: AuthUser, id: string, lineId: string) {
    await this.assertEnvelopeMutable(id);
    const existing = await this.prisma.adminBudgetLine.findUnique({ where: { id: lineId } });
    if (!existing || existing.monthlyBudgetId !== id) throw new NotFoundException();
    await this.prisma.adminBudgetLine.update({
      where: { id: lineId },
      data: { status: 'cancelled' },
    });
    await this.recomputeTotals(id);
    await this.audit.log({
      action: 'monthlyWorkPlanBudget.removeAdminLine',
      subjectKind: 'MonthlyWorkPlanBudget', subjectId: id,
      actorId: user.userId, actorRole: user.activeRole,
      payload: { lineId },
    });
  }

  async submitToRvp(user: AuthUser, id: string) {
    const envelope = await this.assertEnvelopeMutable(id);
    // Pre-flight: must have at least one program item OR at least one admin
    // line. An empty envelope is by definition invalid.
    if (envelope.activityCount === 0 && envelope.adminTotal === 0) {
      throw new BadRequestException('Cannot submit an empty monthly budget — no program items and no admin plan.');
    }
    const updated = await this.prisma.monthlyWorkPlanBudget.update({
      where: { id },
      data: {
        status: MonthlyWorkPlanBudgetStatus.submitted_to_rvp,
        submittedAt: new Date(),
        submittedByUserId: user.userId,
      },
    });
    await this.audit.log({
      action: 'monthlyWorkPlanBudget.submitToRvp',
      subjectKind: 'MonthlyWorkPlanBudget', subjectId: id,
      actorId: user.userId, actorRole: user.activeRole,
      payload: { totalAmount: updated.totalAmount },
    });
    return updated;
  }

  async rvpReview(user: AuthUser, id: string, decision: 'approve' | 'return', note?: string) {
    const envelope = await this.prisma.monthlyWorkPlanBudget.findUnique({ where: { id } });
    if (!envelope) throw new NotFoundException();
    if (envelope.status !== MonthlyWorkPlanBudgetStatus.submitted_to_rvp) {
      throw new BadRequestException('Monthly budget is not in RVP review.');
    }
    const status = decision === 'approve'
      ? MonthlyWorkPlanBudgetStatus.approved_by_rvp
      : MonthlyWorkPlanBudgetStatus.returned_by_rvp;
    const updated = await this.prisma.monthlyWorkPlanBudget.update({
      where: { id },
      data: {
        status,
        rvpReviewedAt: new Date(),
        rvpReviewedByUserId: user.userId,
        rvpReviewNote: note?.trim() || null,
      },
    });
    await this.audit.log({
      action: `monthlyWorkPlanBudget.${decision}`,
      subjectKind: 'MonthlyWorkPlanBudget', subjectId: id,
      actorId: user.userId, actorRole: user.activeRole,
      payload: { note: note?.trim() ?? null },
    });
    return updated;
  }

  async markSentToAccountant(user: AuthUser, id: string) {
    const envelope = await this.prisma.monthlyWorkPlanBudget.findUnique({ where: { id } });
    if (!envelope) throw new NotFoundException();
    if (envelope.status !== MonthlyWorkPlanBudgetStatus.approved_by_rvp) {
      throw new BadRequestException('Only an RVP-approved monthly budget can be released to Accountant.');
    }
    const updated = await this.prisma.monthlyWorkPlanBudget.update({
      where: { id },
      data: {
        status: MonthlyWorkPlanBudgetStatus.sent_to_accountant,
        sentToAccountantAt: new Date(),
      },
    });
    await this.audit.log({
      action: 'monthlyWorkPlanBudget.sentToAccountant',
      subjectKind: 'MonthlyWorkPlanBudget', subjectId: id,
      actorId: user.userId, actorRole: user.activeRole,
    });
    return updated;
  }

  // ── Internals ─────────────────────────────────────────────────────────

  /** Throws if the envelope is in a status where mutations would silently
   *  edit an already-approved monthly budget. The Friday job and the admin
   *  line endpoints all gate on this. */
  private async assertEnvelopeMutable(id: string) {
    const envelope = await this.prisma.monthlyWorkPlanBudget.findUnique({ where: { id } });
    if (!envelope) throw new NotFoundException();
    const frozen: MonthlyWorkPlanBudgetStatus[] = [
      MonthlyWorkPlanBudgetStatus.submitted_to_rvp,
      MonthlyWorkPlanBudgetStatus.approved_by_rvp,
      MonthlyWorkPlanBudgetStatus.sent_to_accountant,
      MonthlyWorkPlanBudgetStatus.disbursed,
      MonthlyWorkPlanBudgetStatus.closed,
    ];
    if (frozen.includes(envelope.status)) {
      throw new BadRequestException(`Cannot mutate a ${envelope.status} envelope — create a budget revision instead.`);
    }
    return envelope;
  }

  /** Sum admin (active only) + program — keep envelope totals authoritative.
   *  Called after every admin-line add/remove and during the cron refresh. */
  private async recomputeTotals(id: string) {
    const admin = await this.prisma.adminBudgetLine.aggregate({
      where: { monthlyBudgetId: id, status: 'active' },
      _sum: { totalCost: true },
    });
    const program = await this.prisma.monthlyWorkPlanItem.aggregate({
      where: { monthlyBudgetId: id },
      _sum: { amount: true },
    });
    const programTotal = program._sum.amount ?? 0;
    const adminTotal = admin._sum.totalCost ?? 0;
    await this.prisma.monthlyWorkPlanBudget.update({
      where: { id },
      data: { programTotal, adminTotal, totalAmount: programTotal + adminTotal },
    });
  }
}
