# Generated by Django 5.2.4 on 2026-07-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(db_index=True, default="general", max_length=64),
        ),
    ]
