"""Uganda Master Priority Plan — normalized source data (FY2027).

Source: "Priorities.docx" (July Plan) — the confirmed Uganda contribution to
the FY2027 regional direction. Each row becomes a COUNTRY-level milestone
under the country translation of its regional priority group.

Normalization decisions are visible, never silent: every composite value that
was split, every unclear metric, and every FY-ambiguous date carries
``confirm`` — a needs-confirmation note the CD resolves in-app before the
master can publish (§14 steps 2–4, §15).

Field notes
- ``measurement``: count / percentage / date / manual_assessment. Percentages
  that logically cannot exceed 100 (coverage) set ``cap_100``.
- ``method``: how the target reaches owners (§5) — field_cascade, specialist,
  country_owned, non_scoreable.
- ``metric``: which canonical metric definition the milestone binds to —
  activity | school | core_school | coverage | participants | manual.
- ``catalogue``: (stable_code, rule overrides) pairs → MilestoneActivityRule.
  Unmapped source activities are queued for catalogue review, same as the
  regional seed.
"""

SOURCE_DOCUMENT = "Priorities.docx (Uganda July Plan)"

FIELD = "field_cascade"
SPECIALIST = "specialist"
COUNTRY = "country_owned"
NON_SCOREABLE = "non_scoreable"

UGANDA_MASTER = {
    "PROGRAM_GROWTH_AND_EXPANSION": [
        {
            "code": "NEW_SCHOOLS",
            "title": "New School Orientation — 1,000 schools",
            "source_text": "New Schools in operational countries — Uganda confirmed 1,000",
            "measurement": "count",
            "target": 1000,
            "unit": "schools",
            "method": FIELD,
            "metric": "school",
            "role": "CCEO",
            "catalogue": [("NEW_SCHOOL_ORIENTATION", {})],
            "basis": "UNIQUE_SCHOOLS_SUPPORTED",
        },
        {
            "code": "SCHOOLS_WITH_DCS",
            "title": "Schools with DCs — 60% of portfolio",
            "source_text": "#Schools with DCs — 60%",
            "measurement": "percentage",
            "target": 60,
            "unit": "percent",
            "cap_100": True,
            "method": FIELD,
            "metric": "coverage",
            "role": "CCEO",
            "catalogue": [("DISCIPLESHIP_DYNAMICS", {})],
            "basis": "PERCENT_OF_ELIGIBLE_SCHOOLS",
        },
        {
            "code": "NEW_CORE_SCHOOLS",
            "title": "New Core Schools — 500",
            "source_text": "New Core Schools — Uganda confirmed 500",
            "measurement": "count",
            "target": 500,
            "unit": "schools",
            "method": FIELD,
            "metric": "core_school",
            "role": "CCEO",
        },
        {
            "code": "ACTIVE_SOCIAL_MEDIA",
            "title": "Active social media and internal marketing — 24 posts",
            "source_text": "Keep active social media — 2 posts per month",
            "measurement": "count",
            "target": 24,
            "unit": "posts",
            "method": COUNTRY,
            "metric": "manual",
            "role": "CountryDirector",
            "confirm": "Source says 2 posts per month; annualized to 24 — confirm.",
        },
        {
            "code": "CONNECT_MOVEMENT",
            "title": "Operationalise Connect movement — 5",
            "source_text": "Operationalise Connect movement and document progress — 5",
            "measurement": "count",
            "target": 5,
            "unit": "count",
            "method": COUNTRY,
            "metric": "manual",
            "role": "CountryDirector",
        },
    ],
    "PROGRAM_QUALITY": [
        {
            "code": "CLIENT_VISIT_COVERAGE",
            "title": "Client school visit coverage — 90%",
            "source_text": "School visits: Client schools — 90%",
            "measurement": "percentage",
            "target": 90,
            "unit": "percent",
            "cap_100": True,
            "method": FIELD,
            "metric": "coverage",
            "role": "CCEO",
            "catalogue": [
                ("CLIENT_SCHOOL_FOLLOWUP_VISIT", {"school_type": "client"}),
                ("STANDARD_SCHOOL_VISIT", {"school_type": "client"}),
            ],
            "basis": "PERCENT_OF_ELIGIBLE_SCHOOLS",
        },
        {
            "code": "CLIENT_VISITS_STAFF",
            "title": "Client school visits/meetings (staff) — 12,212",
            "source_text": "Client School Visits/Meetings — Staff — 12,212",
            "measurement": "count",
            "target": 12212,
            "unit": "visits",
            "method": FIELD,
            "metric": "activity",
            "role": "CCEO",
            "catalogue": [
                ("CLIENT_SCHOOL_FOLLOWUP_VISIT", {"executor": "staff"}),
                ("STANDARD_SCHOOL_VISIT", {"executor": "staff"}),
            ],
            "basis": "VERIFIED_ACTIVITIES",
        },
        {
            "code": "CLIENT_VISITS_PARTNER",
            "title": "Client school visits/meetings (partner) — 11,260",
            "source_text": "Client School Visits/Meetings — Partner — 11,260",
            "measurement": "count",
            "target": 11260,
            "unit": "visits",
            "method": SPECIALIST,
            "metric": "activity",
            "role": "Program Lead",
            "catalogue": [
                ("CLIENT_SCHOOL_FOLLOWUP_VISIT", {"executor": "partner"}),
                ("STANDARD_SCHOOL_VISIT", {"executor": "partner"}),
            ],
            "basis": "VERIFIED_ACTIVITIES",
            "note": "Partner-delivered; monitored through the partner channel — "
            "never CCEO credit.",
        },
        {
            "code": "CORE_VISITS_STAFF",
            "title": "Core school visits/meetings (staff) — 3,200",
            "source_text": "Core — 400% [23,472]; Staff — 3,200",
            "measurement": "count",
            "target": 3200,
            "unit": "visits",
            "method": FIELD,
            "metric": "activity",
            "role": "CCEO",
            "confirm": "Confirm '400%' means four visits per Core school and that "
            "the staff share of the 23,472 total is 3,200.",
            "catalogue": [
                ("CORE_SCHOOL_FOLLOWUP_VISIT", {"executor": "staff"}),
            ],
            "basis": "VERIFIED_ACTIVITIES",
        },
        {
            "code": "CORE_VISITS_PARTNER",
            "title": "Core school visits/meetings (partner) — 3,200",
            "source_text": "Core School Visits/Meetings — Partner — 3,200",
            "measurement": "count",
            "target": 3200,
            "unit": "visits",
            "method": SPECIALIST,
            "metric": "activity",
            "role": "Program Lead",
            "catalogue": [
                ("CORE_SCHOOL_FOLLOWUP_VISIT", {"executor": "partner"}),
            ],
            "basis": "VERIFIED_ACTIVITIES",
            "note": "Partner-delivered; never CCEO credit.",
        },
        {
            "code": "DATA_METRICS",
            "title": "Data metrics complete (Enrolment, DCs, EdTech, Exam Scores) — 100%",
            "source_text": "Data Metrics (Enrolment, DCs, EdTech data, Exam Scores) — 100%",
            "measurement": "percentage",
            "target": 100,
            "unit": "percent",
            "cap_100": True,
            "method": FIELD,
            "metric": "coverage",
            "role": "CCEO",
            "basis": "PERCENT_OF_ELIGIBLE_SCHOOLS",
        },
        {
            "code": "CORE_SSA_COVERAGE",
            "title": "SSA: Core schools — 100%",
            "source_text": "SSA: Core schools — 100%",
            "measurement": "percentage",
            "target": 100,
            "unit": "percent",
            "cap_100": True,
            "method": FIELD,
            "metric": "coverage",
            "role": "CCEO",
            "catalogue": [
                ("ASA_SSA_DATA_GATHERING", {"school_type": "core"}),
                ("STANDARD_SCHOOL_VISIT_SSA_COLLECTION", {"school_type": "core"}),
            ],
            "basis": "PERCENT_OF_ELIGIBLE_SCHOOLS",
        },
        {
            "code": "CLIENT_SSA_COVERAGE",
            "title": "SSA: Client schools — 90%",
            "source_text": "SSA: Client schools — 90%",
            "measurement": "percentage",
            "target": 90,
            "unit": "percent",
            "cap_100": True,
            "method": FIELD,
            "metric": "coverage",
            "role": "CCEO",
            "catalogue": [
                ("ASA_SSA_DATA_GATHERING", {"school_type": "client"}),
                ("STANDARD_SCHOOL_VISIT_SSA_COLLECTION", {"school_type": "client"}),
            ],
            "basis": "PERCENT_OF_ELIGIBLE_SCHOOLS",
        },
        {
            "code": "ONE_TEST_DATA",
            "title": "Data gathering — one test — 1,129 schools",
            "source_text": "Data Gathering - One test — 1,129",
            "measurement": "count",
            "target": 1129,
            "unit": "schools",
            "method": FIELD,
            "metric": "activity",
            "role": "CCEO",
            "basis": "UNIQUE_SCHOOLS_SUPPORTED",
        },
        {
            "code": "CLUSTER_COVERAGE",
            "title": "Schools in clusters — 90%",
            "source_text": "Clusters: 90% of schools in clusters",
            "measurement": "percentage",
            "target": 90,
            "unit": "percent",
            "cap_100": True,
            "method": FIELD,
            "metric": "coverage",
            "role": "CCEO",
            "catalogue": [("STANDARD_CLUSTER_MEETING", {})],
            "basis": "PERCENT_OF_ELIGIBLE_SCHOOLS",
        },
        {
            "code": "CORE_TRAINING_COMPLIANCE",
            "title": "Core schools receive 4 trainings — 100%",
            "source_text": "Training: Core schools — 4 training — 100%",
            "measurement": "percentage",
            "target": 100,
            "unit": "percent",
            "cap_100": True,
            "method": FIELD,
            "metric": "coverage",
            "role": "CCEO",
            "catalogue": [("STANDARD_IN_SCHOOL_TRAINING", {"school_type": "core"})],
            "basis": "PERCENT_OF_ELIGIBLE_SCHOOLS",
        },
        {
            "code": "CLIENT_TRAINING_COMPLIANCE",
            "title": "Client schools receive 1 training — 90%",
            "source_text": "Training: Client — 1 — 90%",
            "measurement": "percentage",
            "target": 90,
            "unit": "percent",
            "cap_100": True,
            "method": FIELD,
            "metric": "coverage",
            "role": "CCEO",
            "catalogue": [
                ("STANDARD_IN_SCHOOL_TRAINING", {"school_type": "client"}),
                ("STANDARD_CLUSTER_TRAINING", {"school_type": "client"}),
            ],
            "basis": "PERCENT_OF_ELIGIBLE_SCHOOLS",
        },
        {
            "code": "ONLINE_TRAINING_SHARE",
            "title": "Online training share — 10%",
            "source_text": "Training: Online — 10%",
            "measurement": "percentage",
            "target": 10,
            "unit": "percent",
            "cap_100": True,
            "method": COUNTRY,
            "metric": "manual",
            "role": "ImpactAssessment",
        },
        {
            "code": "DC_TRAINING",
            "title": "DC Training (Discipleship Dynamics) — 4,157 schools",
            "source_text": "DC Training — Discipleship Dynamics — 4,157 (Core 520, Client 3,637)",
            "measurement": "count",
            "target": 4157,
            "unit": "schools",
            "core": 520,
            "client": 3637,
            "pps": 1,
            "method": FIELD,
            "metric": "activity",
            "role": "CCEO",
            "catalogue": [("DISCIPLESHIP_DYNAMICS", {})],
            "basis": "UNIQUE_SCHOOLS_TRAINED",
        },
        {
            "code": "CLA_TRAINING",
            "title": "Schools trained on CLA — 4,119",
            "source_text": "Christ-like Character Training - CLA — 4,119 (Core 482, Client 3,637)",
            "measurement": "count",
            "target": 4119,
            "unit": "schools",
            "core": 482,
            "client": 3637,
            "pps": 1,
            "method": FIELD,
            "metric": "activity",
            "role": "CCEO",
            "catalogue": [("CLA_CHARACTER_DEVELOPMENT", {})],
            "basis": "UNIQUE_SCHOOLS_TRAINED",
        },
        {
            "code": "SEL_TRAINING",
            "title": "Schools trained on SEL — 650",
            "source_text": "Christ-like Character Training - CC-SEL — 650 (Core 269, Client 381)",
            "measurement": "count",
            "target": 650,
            "unit": "schools",
            "core": 269,
            "client": 381,
            "pps": 6,
            "method": FIELD,
            "metric": "activity",
            "role": "CCEO",
            "catalogue": [("CC_SEL", {})],
            "basis": "UNIQUE_SCHOOLS_TRAINED",
        },
        {
            "code": "LITERACY_TRAINING",
            "title": "Schools trained in Literacy — 7,000",
            "source_text": "Schools trained in Literacy by September 2026 — 7,000 (Core 1,600, Client 5,400)",
            "measurement": "count",
            "target": 7000,
            "unit": "schools",
            "core": 1600,
            "client": 5400,
            "pps": 2,
            "method": FIELD,
            "metric": "activity",
            "role": "CCEO",
            "confirm": "Source says 'by September 2026' — confirm whether this "
            "belongs to FY2026 or carries into FY2027.",
            "catalogue": [("LITERACY_NUMERACY_PROJECT", {})],
            "basis": "UNIQUE_SCHOOLS_TRAINED",
        },
        {
            "code": "ECD_TEACHERS",
            "title": "Teachers trained on ECD — 2,000",
            "source_text": "Teachers trained on ECD, IDE by September 2026 — 2000, 200",
            "measurement": "count",
            "target": 2000,
            "unit": "participants",
            "method": FIELD,
            "metric": "participants",
            "role": "CCEO",
            "confirm": "Split from composite '2000, 200' (ECD, IDE) — confirm the "
            "split and the FY.",
            "catalogue": [("EARLY_CHILDHOOD_EDUCATION_PROJECT", {})],
            "basis": "TEACHERS_TRAINED",
        },
        {
            "code": "IDE_TEACHERS",
            "title": "Teachers trained on IDE — 200",
            "source_text": "Teachers trained on ECD, IDE by September 2026 — 2000, 200",
            "measurement": "count",
            "target": 200,
            "unit": "participants",
            "method": FIELD,
            "metric": "participants",
            "role": "CCEO",
            "confirm": "Split from composite '2000, 200' (ECD, IDE) — confirm the "
            "split, the FY and the IDE activity mapping.",
            "basis": "TEACHERS_TRAINED",
        },
        {
            "code": "TEACHER_PEDAGOGY",
            "title": "Teacher Pedagogy/Professionalism — 5,825 schools",
            "source_text": "Teacher Pedagogy/Professionalism — 5,825 (Core 1,600, Client 4,225)",
            "measurement": "count",
            "target": 5825,
            "unit": "schools",
            "core": 1600,
            "client": 4225,
            "pps": 4,
            "method": FIELD,
            "metric": "activity",
            "role": "CCEO",
            "catalogue": [("TEACHER_PEDAGOGY_PROFESSIONALISM", {})],
            "basis": "UNIQUE_SCHOOLS_TRAINED",
        },
        {
            "code": "STUDENT_LEADER_CONFERENCES",
            "title": "Student Leaders' conferences — 5",
            "source_text": "Student Leaders' conferences (4 Regional & Family experience) — 5",
            "measurement": "count",
            "target": 5,
            "unit": "events",
            "method": SPECIALIST,
            "metric": "activity",
            "role": "ProjectCoordinator",
            "catalogue": [("STUDENT_LEADERSHIP_CAMPS", {})],
            "basis": "VERIFIED_ACTIVITIES",
        },
        {
            "code": "CCSEL_CONFERENCE",
            "title": "CC-SEL Conference — 1",
            "source_text": "CC-SEL Conference — Teacher Leadership Conference/Camp/Retreat — 1",
            "measurement": "count",
            "target": 1,
            "unit": "events",
            "method": SPECIALIST,
            "metric": "activity",
            "role": "ProjectCoordinator",
            "confirm": "Confirm the conference-activity mapping (source maps it "
            "to Teacher Leadership Conference/Camp/Retreat).",
            "catalogue": [("TEACHER_LEADERSHIP_CONFERENCE", {})],
            "basis": "VERIFIED_ACTIVITIES",
        },
        {
            "code": "EDTECH_CONFERENCES",
            "title": "EdTech Conferences — 4",
            "source_text": "EdTech Conferences - 4 — Student Conference/Camps — 4",
            "measurement": "count",
            "target": 4,
            "unit": "events",
            "method": SPECIALIST,
            "metric": "activity",
            "role": "ProjectCoordinator",
            "confirm": "Confirm the mapping — the source routes EdTech "
            "conferences through Student Conference/Camps.",
            "catalogue": [("STUDENT_CONFERENCE_CAMPS", {})],
            "basis": "VERIFIED_ACTIVITIES",
        },
        {
            "code": "BIBLICAL_INTEGRATION",
            "title": "Biblical Integration — 613 schools",
            "source_text": "Biblical Integration - Core-4 — 613",
            "measurement": "count",
            "target": 613,
            "unit": "schools",
            "method": FIELD,
            "metric": "activity",
            "role": "CCEO",
            "catalogue": [("BIBLICAL_INTEGRATION", {})],
            "basis": "UNIQUE_SCHOOLS_TRAINED",
        },
        {
            "code": "TAM_TRAINING",
            "title": "Schools trained on TAM — 1,000",
            "source_text": "1000 schools trained on TAM by September 2026",
            "measurement": "count",
            "target": 1000,
            "unit": "schools",
            "method": FIELD,
            "metric": "activity",
            "role": "CCEO",
            "confirm": "Source says 'by September 2026' — confirm the FY.",
            "catalogue": [("TAM_I", {}), ("TAM_II", {})],
            "basis": "UNIQUE_SCHOOLS_TRAINED",
        },
        {
            "code": "SIP_LEADERS",
            "title": "Leaders trained — SIP — 18,500",
            "source_text": "Leaders Trained - SIP — Leadership — 18,500",
            "measurement": "count",
            "target": 18500,
            "unit": "participants",
            "method": FIELD,
            "metric": "participants",
            "role": "CCEO",
            "catalogue": [("SCHOOL_LEADERSHIP", {})],
            "basis": "SCHOOL_LEADERS_TRAINED",
        },
        {
            "code": "TOT_TRAININGS",
            "title": "TOT trainings",
            "source_text": "TOT trainings — no confirmed target",
            "measurement": "count",
            "target": None,
            "unit": "count",
            "method": NON_SCOREABLE,
            "metric": None,
            "role": "",
            "confirm": "No confirmed target in the source document.",
        },
        {
            "code": "TOT_MEALS",
            "title": "TOT trainings — Meals",
            "source_text": "TOT trainings - Meals — no confirmed target",
            "measurement": "count",
            "target": None,
            "unit": "count",
            "method": NON_SCOREABLE,
            "metric": None,
            "role": "",
            "confirm": "No confirmed target in the source document.",
        },
        {
            "code": "PROPRIETOR_CONFERENCE",
            "title": "Proprietor Conference",
            "source_text": "Proprietor Conference — Proprietor Training — no confirmed target",
            "measurement": "count",
            "target": None,
            "unit": "events",
            "method": NON_SCOREABLE,
            "metric": None,
            "role": "",
            "confirm": "No confirmed target in the source document.",
        },
        {
            "code": "TEACHERS_TRAINED_TOTAL",
            "title": "Teachers trained (all programmes) — 37,000",
            "source_text": "Teachers trained — 37,000",
            "measurement": "count",
            "target": 37000,
            "unit": "participants",
            "method": NON_SCOREABLE,
            "metric": None,
            "role": "",
            "confirm": "Umbrella figure overlapping the named trainings — "
            "excluded from scoring to avoid double counting until the CD "
            "defines its scope.",
        },
        {
            "code": "SSA_TRANSFORMATION_CORE",
            "title": "Transformation based on SSA — Core",
            "source_text": "Transformation based on SSA: 2% on core — 50%",
            "measurement": "percentage",
            "target": 50,
            "unit": "percent",
            "cap_100": True,
            "method": NON_SCOREABLE,
            "metric": None,
            "role": "",
            "confirm": "Metric definition unclear (source shows '2% on core' "
            "with a 50% target) — pending definition.",
        },
        {
            "code": "SSA_TRANSFORMATION_CLIENT",
            "title": "Transformation based on SSA — Client",
            "source_text": "Transformation based on SSA: 1% on client — 25%",
            "measurement": "percentage",
            "target": 25,
            "unit": "percent",
            "cap_100": True,
            "method": NON_SCOREABLE,
            "metric": None,
            "role": "",
            "confirm": "Metric definition unclear (source shows '1% on client' "
            "with a 25% target) — pending definition.",
        },
        {
            "code": "MSC_STORIES",
            "title": "MSC — exceed IAO targets — 100",
            "source_text": "MSC - exceed IAO targets — 100",
            "measurement": "count",
            "target": 100,
            "unit": "count",
            "method": COUNTRY,
            "metric": "manual",
            "role": "ImpactAssessment",
            "confirm": "Confirm the owner and measurement source.",
        },
        {
            "code": "CORE_GRADUATION_RATE",
            "title": "Core school graduation rate — 50%",
            "source_text": "Increase core school graduation rate — 50%",
            "measurement": "percentage",
            "target": 50,
            "unit": "percent",
            "cap_100": True,
            "method": COUNTRY,
            "metric": "manual",
            "role": "CountryDirector",
            "confirm": "Confirm the measurement source.",
        },
        {
            "code": "SSA_ROI_ANALYSIS",
            "title": "Country SSA/support correlation analysis",
            "source_text": "Analysis at country level of Client and Core SSA scores "
            "and correlation to training/visits to improve return on investment",
            "measurement": "manual_assessment",
            "target": None,
            "unit": "qualitative",
            "method": COUNTRY,
            "metric": None,
            "role": "ImpactAssessment",
        },
        {
            "code": "PARENT_SURVEY",
            "title": "Parent survey tested with Core schools — 25%",
            "source_text": "Ensure Parent survey is tested with Core schools — 25%",
            "measurement": "percentage",
            "target": 25,
            "unit": "percent",
            "cap_100": True,
            "method": SPECIALIST,
            "metric": "manual",
            "role": "ImpactAssessment",
        },
        {
            "code": "STUDENT_IMPACT_THINKING",
            "title": "Contribute to Impact-on-Students measurement thinking",
            "source_text": "Read reports and attend events to capture feedback and "
            "take next steps",
            "measurement": "manual_assessment",
            "target": None,
            "unit": "qualitative",
            "method": COUNTRY,
            "metric": None,
            "role": "CountryDirector",
        },
        {
            "code": "STUDENT_ALUMNI",
            "title": "Support student Alumni program — 10%",
            "source_text": "Support student Alumni program in all countries — 10%",
            "measurement": "percentage",
            "target": 10,
            "unit": "percent",
            "cap_100": True,
            "method": COUNTRY,
            "metric": "manual",
            "role": "CountryDirector",
            "confirm": "Confirm the measurement source.",
        },
    ],
    "BUSINESS_TRANSFORMATION": [
        {
            "code": "LOANS",
            "title": "Loans — 300",
            "source_text": "# Loans - 300 — 300: 200, 100",
            "measurement": "count",
            "target": 300,
            "unit": "loans",
            "method": SPECIALIST,
            "metric": "manual",
            "role": "Accountant",
            "confirm": "Composite '300: 200, 100' — confirm what the 200/100 "
            "split means before distribution.",
        },
        {
            "code": "EDTECH_LOANS",
            "title": "EdTech loans — 100",
            "source_text": "50% Ed Tech Loans — 100",
            "measurement": "count",
            "target": 100,
            "unit": "loans",
            "method": SPECIALIST,
            "metric": "manual",
            "role": "Accountant",
        },
        {
            "code": "MFI_MENTORSHIP",
            "title": "Monthly MFI mentorship sessions — 100%",
            "source_text": "Monthly MFI mentorship sessions — 100%",
            "measurement": "percentage",
            "target": 100,
            "unit": "percent",
            "cap_100": True,
            "method": SPECIALIST,
            "metric": "manual",
            "role": "Accountant",
        },
        {
            "code": "CREATIVE_VIDEOS",
            "title": "Creative videos — 1",
            "source_text": "Creative Videos: 2 — confirmed 1",
            "measurement": "count",
            "target": 1,
            "unit": "count",
            "method": COUNTRY,
            "metric": "manual",
            "role": "CountryDirector",
            "confirm": "Milestone says 2, confirmed Uganda number is 1 — confirm.",
        },
        {
            "code": "MFI_MEETINGS",
            "title": "Monthly MFI meetings — 10",
            "source_text": "Monthly MFI meetings — 10",
            "measurement": "count",
            "target": 10,
            "unit": "meetings",
            "method": SPECIALIST,
            "metric": "manual",
            "role": "Accountant",
        },
        {
            "code": "ACCOUNTANTS_TRAINING",
            "title": "Accountants training — 1,800 schools",
            "source_text": "Accountants training: 10% of schools — 1,800",
            "measurement": "count",
            "target": 1800,
            "unit": "schools",
            "method": SPECIALIST,
            "metric": "activity",
            "role": "Accountant",
            "confirm": "Confirm whether this is specialist-run or field-cascaded "
            "to CCEOs.",
            "catalogue": [("ACCOUNTING_FINANCIAL_MANAGEMENT", {})],
            "basis": "UNIQUE_SCHOOLS_TRAINED",
        },
        {
            "code": "LOAN_USE_VERIFICATION",
            "title": "Verification of loan use — 70%",
            "source_text": "Verification of loan use: 90% of the loans — 70%",
            "measurement": "percentage",
            "target": 70,
            "unit": "percent",
            "cap_100": True,
            "method": SPECIALIST,
            "metric": "manual",
            "role": "Accountant",
        },
    ],
    "EDUCATION_TECHNOLOGY": [
        {
            "code": "EDTECH_PIPELINE",
            "title": "EdTech pipeline — 1,000 schools",
            "source_text": "Pipeline - 2000 schools — Other EdTech — 1,000 (Client 1,000)",
            "measurement": "count",
            "target": 1000,
            "unit": "schools",
            "core": 0,
            "client": 1000,
            "method": SPECIALIST,
            "metric": "manual",
            "role": "ProjectCoordinator",
        },
        {
            "code": "EDTECH_FOUNDATIONS",
            "title": "EdTech Foundations — 2,000 schools",
            "source_text": "Foundation - 2400 schools — 2,000 (Core 1,400, Client 600)",
            "measurement": "count",
            "target": 2000,
            "unit": "schools",
            "core": 1400,
            "client": 600,
            "method": SPECIALIST,
            "metric": "activity",
            "role": "ProjectCoordinator",
            "catalogue": [("EDTECH_FOUNDATIONS", {})],
            "basis": "UNIQUE_SCHOOLS_TRAINED",
        },
        {
            "code": "EDTECH_ACCESS",
            "title": "EdTech Access — 300 schools",
            "source_text": "Access - 345 schools — Other EdTech — 300 (Core 100, Client 200)",
            "measurement": "count",
            "target": 300,
            "unit": "schools",
            "core": 100,
            "client": 200,
            "method": SPECIALIST,
            "metric": "manual",
            "role": "ProjectCoordinator",
        },
        {
            "code": "EDTECH_INTEGRATION",
            "title": "EdTech Integration — 300 schools",
            "source_text": "Integration - 310 schools — 300 (Client 300)",
            "measurement": "count",
            "target": 300,
            "unit": "schools",
            "core": 0,
            "client": 300,
            "method": SPECIALIST,
            "metric": "activity",
            "role": "ProjectCoordinator",
            "catalogue": [("EDTECH_INTEGRATION", {})],
            "basis": "UNIQUE_SCHOOLS_TRAINED",
        },
        {
            "code": "EDTECH_SKILLING",
            "title": "EdTech Skilling — 150 schools",
            "source_text": "Skilling - 225 schools — 150 (Client 150)",
            "measurement": "count",
            "target": 150,
            "unit": "schools",
            "core": 0,
            "client": 150,
            "method": SPECIALIST,
            "metric": "activity",
            "role": "ProjectCoordinator",
            "catalogue": [("TECH_SKILLS_EMPLOYABLE_FUTURE", {})],
            "basis": "UNIQUE_SCHOOLS_TRAINED",
        },
        {
            "code": "EDTECH_CONFERENCE",
            "title": "EdTech conference — 1 per country",
            "source_text": "Conference - 1 per country — no confirmed Uganda number",
            "measurement": "count",
            "target": None,
            "unit": "events",
            "method": NON_SCOREABLE,
            "metric": None,
            "role": "",
            "confirm": "No confirmed Uganda number in the source document.",
        },
        {
            "code": "LEARNING_PLATFORM",
            "title": "Operational learning platform — 150 schools",
            "source_text": "Operational Learning Platform with country specific "
            "content - 225 schools — 150 (Client 150)",
            "measurement": "count",
            "target": 150,
            "unit": "schools",
            "core": 0,
            "client": 150,
            "method": SPECIALIST,
            "metric": "activity",
            "role": "ProjectCoordinator",
            "catalogue": [("LEARNER_CENTERED_APPROACHES", {})],
            "basis": "UNIQUE_SCHOOLS_TRAINED",
        },
        {
            "code": "VENDOR_LENDING",
            "title": "Vendor lending for EdTech access — 50",
            "source_text": "Explore lending to vendors to increase Ed Tech Access — 50 (Client 50)",
            "measurement": "count",
            "target": 50,
            "unit": "loans",
            "core": 0,
            "client": 50,
            "method": SPECIALIST,
            "metric": "manual",
            "role": "Accountant",
        },
    ],
    "GOVERNANCE_AND_PEOPLE_MANAGEMENT": [
        {
            "code": "ANNUAL_PLAN_BUDGETS",
            "title": "Annual plan and budgets — by August",
            "source_text": "Complete annual plan and budgets by September — August",
            "measurement": "date",
            "target": None,
            "unit": "date",
            "method": COUNTRY,
            "metric": None,
            "role": "CountryDirector",
        },
        {
            "code": "PTO_USAGE",
            "title": "PTO usage — 80%",
            "source_text": "PTO - 90% usage for myself and for the team members — 80%",
            "measurement": "percentage",
            "target": 80,
            "unit": "percent",
            "cap_100": True,
            "method": COUNTRY,
            "metric": "manual",
            "role": "HumanResources",
        },
        {
            "code": "PDF_USAGE",
            "title": "Professional Development Fund usage — 90%",
            "source_text": "PDF - 90% usage (at least 8 people per quarter) — 90%",
            "measurement": "percentage",
            "target": 90,
            "unit": "percent",
            "cap_100": True,
            "method": COUNTRY,
            "metric": "manual",
            "role": "HumanResources",
        },
        {
            "code": "ONE_ON_ONES",
            "title": "One-on-ones with supervisor and reports — 4",
            "source_text": "One-on-Ones: once a month minimum — 4",
            "measurement": "count",
            "target": 4,
            "unit": "count",
            "method": COUNTRY,
            "metric": "manual",
            "role": "CountryDirector",
            "confirm": "Source target reads '4' against a monthly commitment — "
            "confirm 4 per quarter vs 12 per year.",
        },
        {
            "code": "NEW_PARTNERSHIPS",
            "title": "New partnerships — 10",
            "source_text": "#New Partnerships, #Church, #Partner review meetings — 10, 4, 4",
            "measurement": "count",
            "target": 10,
            "unit": "count",
            "method": COUNTRY,
            "metric": "manual",
            "role": "CountryDirector",
            "confirm": "Split from composite '10, 4, 4' — confirm.",
            "catalogue": [("PARTNER_MEETINGS_ADMIN", {})],
            "basis": "VERIFIED_ACTIVITIES",
        },
        {
            "code": "CHURCH_PARTNERSHIPS",
            "title": "Church partnerships — 4",
            "source_text": "#New Partnerships, #Church, #Partner review meetings — 10, 4, 4",
            "measurement": "count",
            "target": 4,
            "unit": "count",
            "method": COUNTRY,
            "metric": "manual",
            "role": "CountryDirector",
            "confirm": "Split from composite '10, 4, 4' — confirm.",
        },
        {
            "code": "PARTNER_REVIEW_MEETINGS",
            "title": "Partner review meetings — 4",
            "source_text": "#New Partnerships, #Church, #Partner review meetings — 10, 4, 4",
            "measurement": "count",
            "target": 4,
            "unit": "meetings",
            "method": COUNTRY,
            "metric": "manual",
            "role": "CountryDirector",
            "confirm": "Split from composite '10, 4, 4' — confirm.",
            "catalogue": [("PARTNER_MEETINGS_ADMIN", {})],
            "basis": "VERIFIED_ACTIVITIES",
        },
        {
            "code": "PARTNER_MOUS_SAFEGUARDING",
            "title": "All partners: MOUs + safeguarding — by March",
            "source_text": "All partners sign MOUs and complete safeguarding training — by March",
            "measurement": "date",
            "target": None,
            "unit": "date",
            "method": COUNTRY,
            "metric": None,
            "role": "CountryDirector",
        },
        {
            "code": "BOARD_MEETINGS",
            "title": "Quarterly board meetings — 4",
            "source_text": "Quarterly board meetings - Uganda — 4",
            "measurement": "count",
            "target": 4,
            "unit": "meetings",
            "method": COUNTRY,
            "metric": "manual",
            "role": "CountryDirector",
        },
        {
            "code": "STAFF_MENTORING",
            "title": "Mentoring staff for higher roles — 2",
            "source_text": "Mentoring two staff for higher roles — 2",
            "measurement": "count",
            "target": 2,
            "unit": "count",
            "method": COUNTRY,
            "metric": "manual",
            "role": "CountryDirector",
        },
        {
            "code": "COUNTRY_VISITS",
            "title": "Visit each operation and associate country twice",
            "source_text": "Visit each operation and associate country at least twice — NA",
            "measurement": "manual_assessment",
            "target": None,
            "unit": "qualitative",
            "method": NON_SCOREABLE,
            "metric": None,
            "role": "",
            "confirm": "Marked NA for Uganda in the source document.",
        },
        {
            "code": "STAKEHOLDER_REVIEWS",
            "title": "Stakeholder planning and review meetings — 2",
            "source_text": "Involving stakeholders in planning and reviews — 2 review meetings",
            "measurement": "count",
            "target": 2,
            "unit": "meetings",
            "method": COUNTRY,
            "metric": "manual",
            "role": "CountryDirector",
        },
        {
            "code": "GOVERNMENT_COMPLIANCE",
            "title": "Government reporting and compliance — 100%",
            "source_text": "Government Reporting and Compliance — 100%",
            "measurement": "percentage",
            "target": 100,
            "unit": "percent",
            "cap_100": True,
            "method": COUNTRY,
            "metric": "manual",
            "role": "CountryDirector",
            "catalogue": [("GOVERNMENT_STATUTORY_REQUIREMENTS", {})],
            "basis": "VERIFIED_ACTIVITIES",
        },
        {
            "code": "GOVERNANCE_SCHOOL_VISITS",
            "title": "School visits (governance)",
            "source_text": "School visits — NA",
            "measurement": "manual_assessment",
            "target": None,
            "unit": "qualitative",
            "method": NON_SCOREABLE,
            "metric": None,
            "role": "",
            "confirm": "Marked NA in the source document.",
        },
        {
            "code": "COUNTRY_TEAM_PERFORMANCE",
            "title": "High-performing country team — 80% on priorities",
            "source_text": "Form a fully functional high performing country team — "
            "80% performance on everyone's priorities, measured quarterly",
            "measurement": "percentage",
            "target": 80,
            "unit": "percent",
            "cap_100": True,
            "method": COUNTRY,
            "metric": "manual",
            "role": "CountryDirector",
        },
        {
            "code": "REGIONAL_INITIATIVES",
            "title": "Support regional initiatives — 90% response rate",
            "source_text": "Support Regional Initiatives — 90% Response rate",
            "measurement": "percentage",
            "target": 90,
            "unit": "percent",
            "cap_100": True,
            "method": COUNTRY,
            "metric": "manual",
            "role": "CountryDirector",
        },
    ],
}

assert set(UGANDA_MASTER) == {
    "PROGRAM_GROWTH_AND_EXPANSION",
    "PROGRAM_QUALITY",
    "BUSINESS_TRANSFORMATION",
    "EDUCATION_TECHNOLOGY",
    "GOVERNANCE_AND_PEOPLE_MANAGEMENT",
}
